### DISCUSSION TITLE
Health check for Applications with multiple sources

### DISCUSSION THREAD

**Discussion by daftping** [akuity/kargo#1398] [Q&A] [answered]
Seems like the health check for Applications with multiple sources is not supported right now.
https://github.com/akuity/kargo/blob/8b6f58a4ddfc81e004bb782de69a45a575d29a44/internal/controller/stages/health.go#L98-L100
Does anybody know what Argo CD issue this TODO is referring to?

```yaml
  health:
    status: Unknown
    issues:
      - bugs in Argo CD currently prevent a comprehensive assessment of the
        health of multi-source Application "test-app-helm" in
        namespace "argo-cd"
```
