### DISCUSSION TITLE
Kargo auto promotion not working from warehouse to first stage

### DISCUSSION THREAD

**Discussion by MPritsch** [akuity/kargo#1646] [Q&A] [answered]
Hello, not sure if we use kargo wrong or if the mechanics are broken.
We enabled the "enableAutoPromotion" field on the project for our stage "develop". There is only one stage. My expectations are that whenever there is a new Freight added, that it should be automatically promoted to the stage. That does not happen.

The only logs I see in the kargo-controller, when I manually trigger the Freight to promote. No mention when a new freight is detected.

I use kargo version 0.4.2 on an on-premise kubernetes cluster.

Here is my configuration. Is there anything wrong with the promotion mechanic?:
```yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-my-project
spec:
  promotionPolicies:
    - stage: develop
      enableAutoPromotion: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: my-project
  namespace: kargo-my-project
spec:
  subscriptions:
    - git:
        repoURL: https://my.git.repo/url/my-project.git
        allowTags: '^my-tag-regex$'
        commitSelectionStrategy: NewestTag
    - image:
        allowTags: '^my-tag-regex$'
        repoURL: my.docker.repo/url/my-project
        imageSelectionStrategy: NewestBuild
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: develop
  namespace: kargo-my-project
spec:
  subscriptions:
    warehouse: my-project
  promotionMechanisms:
    argoCDAppUpdates:
      - appName: develop-my-project
        appNamespace: kube-system
        sourceUpdates:
          - repoURL: https://my.git.repo/url/my-project.git
            updateTargetRevision: true
          - repoURL: https://my.git.repo/url/my-project.git
            kustomize:
              images:
                - image: my.docker.repo/url/my-project
                  useDigest: true
```

If you need mor information, do not hesitate to ask. Best Regards
