### DISCUSSION TITLE
gitRepoUpdates Loop

### DISCUSSION THREAD

**Discussion by wmiller112** [akuity/kargo#1985] [General]
In setting up my first pipelines, I seem to be running into a loop error that I'm not clear how to work around. I've configured a warehouse with image and git subscriptions. The first stage has a `gitRepoUpdates` promotion mechanism. I then have a number of stages that I'd like to subscribe to that first stage with a `argoCDAppUpdates` promotion mechanism so they are updated whenever the image gets updated by first stage, OR when manifests change. I havent seen any discussion about it, but I imagine we want the auto sync mechanism in ArgoCD turned off if we want things to be synced via `argoCDAppUpdates` promotion. If that is the case, and we cant create freight with the image repo and manifests where the image gets updated, how can we auto apply manifest updates?

I track the images in kustomization files in a specific directory, and have the git subscription configured with `includePaths` that don't include the image directory, but the `gitRepoUpdates` still error that the commit would cause a loop (hitting [this](https://github.com/akuity/kargo/blob/main/internal/controller/promotion/git.go#L260))
Since stages can only subscribe to a single warehouse or multiple stage, it almost seems like I'd need to either 
1. split the pipeline, having one that subscribes to a warehouse with image subscription and updates git, and a separate pipeline with all the stages subscribed to a warehouse with git subscription that refreshes and syncs the argo apps? But that cant be right as in that case there doesn't seem to be any point in replacing image updater.
2. Move the image definition kustomizations out to a separate repo

**Comment by wmiller112** [comment]
This actually falls into https://github.com/akuity/kargo/issues/835.

**Comment by krancour** [comment]
I'm not _completely_ clear on what you're trying to do. I can outline what the common case looks like as well as an alternative that seems it _may_ be close to what you're describing...

Commonly, a Warehouse subscribes to an image repo and a git repo. The former for images, obviously, and the latter for manifests (or something that _renders_ as manifests, like a Helm chart or some manifests + Kustomize overlays). A new piece of Freight is created when _either_ of those subscriptions detects something new.

Since you're using Kustomize, I will focus on that. Typically a Stage subscribed directly to a Warehouse (or indirectly, via upstream Stages) is going to (essentially) check out the desired commit, run `kargo edit set image <image-url=desired-tag>` in some specified path, take the _entire_ contents of that branch, and _completely overwrite_ the contents of some other, Stage-specific branch. (Which you can think of simply as storage. It may as well be an S3 bucket.)

So imagining your Warehouse found commit X and image Y, those are "mashed together" _at each Stage_ and written to someplace Stage-specific.

This is the common pattern.

Again, I am not entirely sure I've understood what you're trying to do, but it seems you are perhaps shooting for a slightly different pattern that essentially involves _two_ pipelines, with one being very short:

Pipeline 1:

Subscribe _only_ to new images. When one is detected, "promote it" with a Stage that _only_ does the "kustomize edit set image" bit and writes it back to `main` (for instance) in the git repo (to which it is not subscribed, btw).

Pipeline 2:

Subscribe _only_ to git repo changes. When one is detected, promoted it using whatever promotion mechanisms are desired, but _without_ worrying at all about the `kustomize edit set image ...` bit, which has already been handled by the _other_ pipeline.

Does this sound like what you're trying to do?

I believe this is already achievable like so:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: example
spec:
  promotionPolicies:
  - stage: image-promoter
    autoPromotionEnabled: true
  - stage: test
    autoPromotionEnabled: true
  # More promotion policies ...
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: image
  namespace: example
spec:
  subscriptions:
  - image:
      repoURL: nginx # Watch for new versions of this image
      semverConstraint: ^1.24.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: image-promoter
  namespace: example
spec:
  subscriptions:
    warehouse: image
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/example/examples.git
      readBranch: main
      writeBranch: main # Forms no loop because the Warehouse doesn't also
      kustomize:        # subscribe to this
        images:
        - image: nginx
          path: base # Run kustomize edit set image on this path
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: manifests
  namespace: example
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/example/examples.git
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: example
spec:
  subscriptions:
    warehouse: manifests
  promotionMechanisms:
    # Whatever you want to do here, such as force a particular Argo CD
    # Application to refresh/sync ...
---
# More Stages downstream from test ...
```

The one caveat to this is that the UI isn't great about Projects containing multiple Warehouses yet, although we hope to have that addressed in the upcoming v0.7.0 release. If that is a problem, a possible workaround is creating these two pipelines in separate Projects.

Please let me know if this helps at all or if I have completely missed the mark.
