### DISCUSSION TITLE
kargo configuration for okta sso

### DISCUSSION THREAD

**Discussion by L0rdWyd3r** [akuity/kargo#2364] [Q&A]
Hi everyone,

I am new here and starting my adventure with Kargo.
I am generally at the stage of implementing Kargo and SSO with OKTA on my EKS cluster.

My configuration (SSO OKTA) for Kargo is almost identical to the one I did for ArgoCD and works very well, but for ArgoCD not for Kargo.

Unfortunately I am not able to configure the same for Kargo.

I have pasted below the anonymised contents of the values.yaml file, maybe one of you will be able to point out to me what I have misconfigured in this file.

```
global:
  env: []
  envFrom: []
  nodeSelector: {}

  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}

  tolerations: []
  affinity: {}
  securityContext: {}

image:
  repository: ghcr.io/akuity/kargo
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

rbac:
  installClusterRoles: true
  installClusterRoleBindings: true

crds:
  install: true
  keep: true

kubeconfigSecrets: {}

api:
  enabled: true
  replicas: 1
  host: kargo.mydomain.net
  logLevel: DEBUG

  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext: {}
  env: []
  envFrom: []

  probes:
    enabled: true

  tls:
    enabled: true
    selfSignedCert: true

  enablePermissiveCORSPolicy: true

  ingress:
    enabled: true
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-1:111111111111:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    ingressClassName: alb
    tls:
      enabled: true
      selfSignedCert: false
    pathType: Prefix

  service:
    type: ClusterIP
    annotations: {}

  secret:
    name: "kargo-admin"

  adminAccount:
    enabled: true
    passwordHash: ""
    tokenSigningKey: ""
    tokenTTL: 24h

  oidc:
    enabled: true
    issuerURL:
    clientID:
    cliClientID:

    admins:
      subs: []
      emails: []
      groups: []

    viewers:
      subs: []
      emails: []
      groups: []

    globalServiceAccounts:
      namespaces: []

    dex:
      enabled: true

      image:
        repository: ghcr.io/dexidp/dex
        tag: v2.37.0
        pullPolicy: IfNotPresent
        pullSecrets: []

      env: []
      envFrom: []

      volumes: []

      volumeMounts:

      probes:
        enabled: true

      tls:
        selfSignedCert: true
      skipApprovalScreen: false
      connectors:
        - type: saml
          id: okta
          name: Okta
          config:
            ssoURL: https://mydomain.okta.com/app/mydomain_kargoapp_1/exkLps17kyiG587l3EJ3/sso/saml
            caData: "base64 encoded cert"
            usernameAttr: name
            emailAttr: email
            groupsAttr: groups
            allowedGroups:
              - Admins-Kargo
            redirectURI: https://kargo.mydomain.net/dex/callback

      resources: {}
      nodeSelector: {}
      tolerations: []
      affinity: {}
      annotations: {}
      securityContext: {}

  argocd:
    urls:

  rollouts:
    integrationEnabled: true

controller:
  enabled: true

  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}

  serviceAccount:
    iamRole: ""

  globalCredentials:
    namespaces: []

  gitClient:
    name: "Kargo Render"
    email: "kargo-render@akuity.io"

    signingKeySecret:
      name: ""
      type: ""

  securityContext: {}

  argocd:
    integrationEnabled: true
    namespace: argocd
    watchArgocdNamespaceOnly: false

  rollouts:
    integrationEnabled: true
    controllerInstanceID: ""

  logLevel: INFO

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env: []
  envFrom: []

managementController:
  enabled: true

  logLevel: INFO

  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}

  securityContext: {}

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env: []
  envFrom: []

webhooks:
  register: true

webhooksServer:
  enabled: true
  replicas: 1
  logLevel: INFO

  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}

  tls:
    selfSignedCert: true
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext: {}
  env: []
  envFrom: []

garbageCollector:
  enabled: true
  schedule: "0 * * * *"
  workers: 3
  maxRetainedPromotions: 20
  maxRetainedFreight: 20
  logLevel: INFO

  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}

  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext: {}
  env: []
  envFrom: []
```

Thank you very much in advance for any help.
