### DISCUSSION TITLE
Kargo creates git branch that does not checkout `main`

### DISCUSSION THREAD

**Discussion by pww217** [akuity/kargo#2692] [General]
I noticed that when I used a configuration like this for a stage:

```yaml
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/org/repo.git
      writeBranch: stage/repo-dev # Write to stage-specific branch
      helm:
        images:
        - image: ecr:::someimage:tag
          valuesFilePath: infra/values/version.yaml
          key: image.tag
          value: Tag
    argoCDAppUpdates:
    - appName: some-app-dev
```

That it will do two things:

1. Write the commit to the values file and key specified above
2. Sync `some-app-dev` with that new image

This is great an exactly what I want, but there's one interesting caveat:

We typically store these values files in the app repo alongside the codebase. When Kargo creates the branch `stage/repo-dev` it does not check out `main` or track it in any way. I think this is intended, but the result is that it ends up for instance `1 commit ahead, 5300 behind`. Basically, it's first commit is the entire repo.

But I suspect more than this being a mistake or a bug, I'm misunderstand how the pattern _should_ be. Is it that we should create a **new** repository that basically has no traditional `main` branch, or at least not one that's ever written to, and simply as a place for all of these `stage/` branches to live and be accounted for?

How do other people set this up? Because I intended for my developers to use the UI primarily, this is probably not a huge issue anyway. It's just an interesting behavior I didn't expect, I guess.

**Comment by krancour** [comment]
Hey @pww217. Great question. Nuanced answer...

Historically, Kargo has leaned heavily into the idea of Stage-specific branches and rendered branches, too. I know that these patterns have, at times, been in-fashion and, at other times, fallen out of favor, which I blame on a prior lack of good tooling for managing so many branches. Of course, we think Kargo is that missing tool.

With the particular promotion process you're using here, Kargo is updating your `values.yaml` file and then writing _everything_ it had checked out + that tiny update to a Stage-specific branch. This means save for that tiny update, it's identical to what you started with. It is a little odd, in a way, because so much of what gets copied over simply isn't relevant...

But drilling down farther into the question of not having common history with the `main` branch, that's because Kargo creates the new, Stage-specific branch as an orphan, deliberately having no common history with main, because there is no intention of what's in that branch ever being merged back into `main`. We've encouraged people to think of these Stage-specific branches as _storage_ and not so much like feature branches, which you might care for over time like a pet. For all intents and purposes, they may as well be S3 buckets.

So that's the low-down on how this was all supposed to work. i.e. The behavior you're seeing is/was normal.

Now, having said that, we've found over time that some of these opinionated promotion mechanisms we've built don't really suit everyone. There's no shortage of differing opinions on the "right way" to coordinate Promotions...

So it was just _today_, in fact, that we finally released, in v0.9.0, what we've been working on for some time, which are far more granular, more GitHub Actions-like promotion "steps," wherein you have far more flexibility to define your promotion processes as you see fit.

See updated docs [here](https://docs.kargo.io/concepts#promotion-templates) and [here](https://docs.kargo.io/references/promotion-steps) for more details.

The step equivalent of what you currently have looks something like this:

```yaml
promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/krancour/kargo-demo-gitops-2.git
          checkout:
          - fromFreight: true
            path: ./src
          - branch: stage/test
            create: true
            path: ./out
      - uses: git-clear
        config:
          path: ./out
      - uses: helm-update-image
        as: update-image
        config:
          path: ./src/charts/kargo-demo/values.yaml
          images:
          - image: public.ecr.aws/nginx/nginx
            key: image.name
            value: ImageAndTag
      - uses: helm-template
        config:
          path: ./src/charts/kargo-demo
          releaseName: kargo-demo
          valuesFiles:
          - ./src/charts/kargo-demo/stages/test/values.yaml
          outPath: ./out
      - uses: git-commit
        as: commit
        config:
          path: ./out
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: ./out
          targetBranch: stage/test
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-test
            sources:
            - repoURL: https://github.com/krancour/kargo-demo-gitops-2.git
              desiredCommitFromStep: commit
```

This is a bit more verbose, and it does still utilize orphaned branches, but your stage-specific branches are going to end up quite a bit tidier _and_ if there is some aspect of this process that doesn't suit you, you have far more latitude here to modify it to your liking.

I hope this helps and I'm happy to answer any follow-up questions, as this is quite a large and recent pivot.
