### DISCUSSION TITLE
OIDC scopes groups not working

### DISCUSSION THREAD

**Discussion by creeram** [akuity/kargo#3008] [General]
I'm trying to use groups for the admin permissions.

```

api:
  enabled: true
  replicas: 1
  host: kargo.example.com
  tls:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
      enabled: false

  adminAccount:
    enabled: false
  oidc:
    enabled: true
    issuerURL: https://keycloak.example/realms/{realmname}
    clientID: kargo
    additionalScopes: []
    admins:
      claims:
        email:
        - user@example.com
        groups:
        - kargo-admin
```

the api.oidc.claims.email works as an admin user. But the groups are not working.

kargo-admin is a i tried creating groups on Keycloak and Google Group with users added in the group for testing but could not get the admin permissions.

am I doing something wrong here?
