### DISCUSSION TITLE
yaml-update step syntax for conditionally selecting objects from arrays

### DISCUSSION THREAD

**Discussion by danielloader** [akuity/kargo#3080] [Q&A]
Quick question hopefully around how to use the yaml-update on selectors more complex than simple dot notation for objects.

Has anyone worked out the syntax for selecting a key in an object which is in an array? 

I can select and replace it using yq on the terminal but using a yq path with a select component doesn't seem to work.

Given this example file:

```yaml
example:
  nested:
    - id: a
      something: value
    - id: b
      something: value
```

How do I set the `something` value if `id` == `a`? 
Here's the example using the yq CLI to achieve an update on a key in this way.

```shell
yq '(.example.nested[] | select(.id == "a") | .something) = "abc"' test.yaml
example:
  nested:
    - id: a
      something: abc
    - id: b
      something: value
```
