### DISCUSSION TITLE
kargo Slack Posting messages not received

### DISCUSSION THREAD

**Discussion by creeram** [akuity/kargo#3165] [General]
I'm trying to post messages to Slack. The promotion is successful, but I don't receive any notifications or messages in the channel.

The Slack credentials are valid and tested with the curl command, and I can see the messages in the Slack channel.

Kargo Verision: 
```
Client Version: v1.1.1
Server Version: v1.1.1
```

Screenshot of Stage promotion successful run.

<img width="762" alt="Screenshot 2024-12-20 at 08 15 13" src="https://github.com/user-attachments/assets/88c2c68d-dc68-4cd9-adb5-9b2fd21f705a" />

There are not error logs in Kargo API and controller pods.

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: demo
  namespace: kargo-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
       - name: slackChannel
         value: xxxxxx 
      steps:
      - uses: git-clone
        config:
          repoURL: xxxxxxx
          checkout:
          - branch: main
            path: ./src
      - uses: helm-update-image
        as: update-chart-image
        config:
          path: ./src/apps/demo/e2e.yaml
          images:
          - image: xxxxxxxxxxxxx
            key: image.tag
            value: Tag
      - uses: git-commit
        as: commit
        config:
          path: ./src/apps
          messageFromSteps:
          - update-chart-image
      - uses: git-push
        config:
          path: ./src
          targetBranch: main

      - uses: http
        config:
          method: POST
          url: https://slack.com/api/chat.postMessage
          headers:
          - name: Authorization
            value: Bearer xoxb-xxxxxxx-xxxxxxx-xxxxxxx
          - name: Content-type
            value: application/json
          body: |
            ${{ quote({
              "channel": vars.slackChannel,
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Hi I am a bot that can post *_fancy_* messages to any public channel."
                  }
                }
                ]
            }) }}


```
