### DISCUSSION TITLE
Failure understand how to upgrade from kargo 1.0.x to 1.1.x - implicit configuration into explicit

### DISCUSSION THREAD

**Discussion by danielloader** [akuity/kargo#3197] [Q&A] [answered]
Anyone come across this? 

This was working in kargo 1.0.3 but since upgrading to 1.1.1 it's now failing - given it's meant to be a bool, and says it can be false or null and I've got it set to true, kinda confused where to go next

```
apps.0.sources.0.updateTargetRevision must be one of the following: false, null
```

Guessing it's because I don't have an `apps.0.sources.0.desiredRevision` value, trying to work out which template I need to inject to get the prior behaviour now.

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: app-frontend
spec:
  promotionTemplate:
    spec:
      steps:
       - uses: argocd-update
         config:
          apps:
          - name: frontend-uat
            namespace: argocd
            sources:
            - repoURL: https://github.com/example/platform-applications
              updateTargetRevision: true
              desiredRevision: <WHAT GOES HERE NOW?>
              kustomize:
                images:
                  - repoURL: ghcr.io/example/frontend
                    newName: 12345678910.dkr.ecr.eu-west-2.amazonaws.com/ghcr.io/example/frontend
                    useDigest: false
  requestedFreight:
    - origin:
        kind: Warehouse
        name: frontend
      sources:
        direct: true
```

**Comment by krancour** [comment]
Can I see your Warehouse to get an idea of what artifacts are included in each piece of Freight?

**Reply by danielloader** [reply]
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: frontend
  namespace: app-frontend
spec:
  freightCreationPolicy: Automatic
  interval: 3m0s
  subscriptions:
    - image:
        allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
        discoveryLimit: 20
        imageSelectionStrategy: SemVer
        repoURL: ghcr.io/example/frontend
    - git:
        branch: main
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 20
        includePaths:
          - manifests/frontend
          - bootstrap/applications/kargo-apps/frontend
        repoURL: https://github.com/example/platform-applications

```

**Reply by krancour** [reply, marked as answer]
Thanks. So, if your intention is to update the target revision to whatever commit from https://github.com/example/platform-applications was contained within the Freight, then your desiredRevision would be `${{ commitFrom('https://github.com/example/platform-applications').ID }}`

**Reply by danielloader** [reply]
Perfect, worked!

Thanks for the help.

**Reply by danielloader** [reply]
@krancour only had partial success.

Now I have an warehouse with 2 sources:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: openfga
  namespace: service-openfga
spec:
  freightCreationPolicy: Automatic
  interval: 1m0s
  subscriptions:
    - chart:
        name: openfga
        repoURL: https://openfga.github.io/helm-charts
        discoveryLimit: 5
    - git:
        branch: main
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 5
        includePaths:
          - values/services/openfga
          - charts/defaults/openfga
        repoURL: https://github.com/example/platform-services

```

Stage in question:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: service-openfga
spec:
  promotionTemplate:
    spec:
      steps:
       - uses: argocd-update
         retry:
          errorThreshold: 1
          timeout: 60s
         config:
          apps:
          - name: openfga-uat
            namespace: argocd
            sources:
            - repoURL: https://openfga.github.io/helm-charts
              updateTargetRevision: true
              desiredRevision: ${{ chartFrom('https://openfga.github.io/helm-charts', 'openfga').Version }}
              chart: openfga
            - repoURL: https://github.com/example/platform-services
              updateTargetRevision: true
              desiredRevision: ${{ commitFrom('https://github.com/example/platform-services').ID }}
  requestedFreight:
    - origin:
        kind: Warehouse
        name: openfga
      sources:
        direct: true

```

The argocd application has 3 sources as shown via its manifest (as sourced from argocd web UI):

```yaml
project: addons
destination:
  namespace: openfga
  name: uat
syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
sources:
  - repoURL: https://github.com/example/platform-services
    targetRevision: 87b4cdb7e9310b4663a7eb14c2623b14205b17ac
    ref: values
  - repoURL: https://openfga.github.io/helm-charts
    targetRevision: 0.2.19
    helm:
      valueFiles:
        - $values/values/services/openfga/values.yaml
        - $values/values/services/openfga/uat.yaml
      releaseName: openfga
    chart: openfga
  - repoURL: https://github.com/example/platform-services
    path: charts/defaults/openfga/resources/stages/uat
    targetRevision: d8f37d7d21c6b5ef1a823d14219cdb2902b587b2
    kustomize:
      namespace: openfga

```

The first source is just being used as an alias to referencing values files outside of the chart directory in the same repo. Second source is the helm chart, third are some extra resources I'd like to bundle into the application state and sync process.

Kargo 1.x.x seemingly bumped both sources to the correct revision since they matched, this time around I'm experiencing a partial failure state where only one of the sources for https://github.com/example/platform-services is matching the correct and tracked commit id - I'd like to make sure both are updated in lockstep in this scenario.

Any ideas?
