### DISCUSSION TITLE
step execution failed: step 6 timeout of 10m0s has elapsed

### DISCUSSION THREAD

**Discussion by creeram** [akuity/kargo#3223] [General]
I have the code snippet below in the Kargo stage steps, which performs an HTTP GET to check whether the new version is deployed.

The URL endpoint health check output is:

`{"status":"Healthy","version":"v0.1.0"}`

```
- uses: http
  as: healthcheck-endpoint
  retry:
    errorThreshold: 5
    timeout: 10m
  config:
    method: GET
    url: https://demo.example.com/healthcheck
    successExpression: response.body.version == "${{ imageFrom(vars.imageURL).Tag }}"
    failureExpression: response.status == 404
    outputs:
      - name: client_version
        fromExpression: response.body.version
```

When the promotion is done, it triggers the deployment in Kubernetes. After the new version is deployed, this step should pass. It typically takes a maximum of 4-5 minutes for the changes to be reconciled in the Kubernetes cluster. However, with the above configuration, it shows as failed even though the new version is already deployed and the endpoint is healthy.

How can I configure it to redo the health check every 30 or 60 seconds to verify if the new version is deployed? It should only fail if the timeout is reached. In my case, it does not take 10 minutes to deploy a new version.
