### DISCUSSION TITLE
What is the correct way to configure cross-cluster communication and analysisRuns?

### DISCUSSION THREAD

**Discussion by pww217** [akuity/kargo#3239] [Q&A] [answered]
There are a few issues and discussions around this but there's no clear answer that I can see.

My end goal is to run analysisRuns on the remote clusters where workloads actually run, not the mgmt cluster that the main Kargo controller runs on.

I gathered from other threads and docs that the ArgoCD model of basically putting a [KubeConfig in a secret](https://github.com/akuity/kargo/blob/main/charts/kargo/values.yaml#L63-L87) and calling across clusters in that fashion is frowned up.

But the alternative or best practice config is not really documented as far as I can tell. It seems to be something like: set up a Kargo controller on each cluster with one as the primary, then use some sort of communication/webhooks between them to run remote AnalysisRuns and do other operations on a remote cluster.

Basically Kargo <--> Kargo communication instead of authing with a cluster directly, if I understand right.

That sounds great to me but I really can't find how to set it up much of anywhere. Looking through the docs, issues, discussions, and helm chart documentation it's really not very clear to me what the best practice is to do this.

It's important to me because it's really the final thing I need to prove that Kargo is capable of internally in order to sort of begin actually using it more widely. If we want to replace GHA we need to bring the ability to run arbitrary code in between promotions (unit, E2E, integration testing) and it seems that Kargo is perfectly capable of this, it's just a bit hard to figure out how to do it in remote clusters.

I think this will be a common use case going forward as being able to run analysisTemplates in the same cluster/namespace as the actual workload of course makes for more accurate, reliable, and simple (less complex networking and such) testing.

So any guidance, docs, issues, or anything else folks could point me to would help a lot! A helm example in particular would be most valuable.

**Comment by krancour** [comment, marked as answer]
This isn't documented yet, but it's basically this:

1. When installing a distributed (i.e. sharded) Kargo controller somewhere besides the cluster that actually hosts the Kargo control plane, provide a cluster-specific value for `controller.rollouts.controllerInstanceID` during the helm install.  

1. Run a Rollouts controller "next to" each of your distributed Kargo controllers. Following process quite similar to how you must have already configured the distributed Kargo controllers, configure it like so:
    1. Create a Secret with kubeconfig for connecting back to the Kargo control plane's cluster.
    1. Mount that Secret somewhere in the controller's container. Assuming you install with Helm, use `controller.volumes` and `controller.volumeMounts` for this.
    1. Point the controller at the kubeconfig using the `--kubeconfig` flag. Assuming you install with Helm, use `controller.extraArgs` for this.
    1. Also start the controller with `--instance-id` set to the cluster-specific value mentioned in the first step. Assuming you install with Helm, use `controller.extraArgs` for this as well.

What you'll end up with is:

* Both the distributed Kargo controller and its nearby Rollouts contoller connected to the Kargo control plane.
* That controller will create AnalysisTemplates and Analysis runs in the Kargo control plane and apply an Rollouts instance ID label to all of them.
* The rollouts controller will watch/reconcile Rollouts resources in the Kargo control plane, but only those labeled with a certain instance ID.

**Reply by krancour** [reply]
Note this will not conflict with any _other_ Rollouts controller that might happen to be running in that cluster.

**Reply by krancour** [reply]
I forgot to mention the most important part. I'm pretty sure you knew this anyway, but for the benefit of anyone else who reads this thread in the future, any _Jobs_ will run where the Rollouts controller is running. 😄

**Comment by pww217** [comment]
Appreciate the quick and detailed response as always!

I modified an existing diagram I have to try to visualizing this architecture. I have a lot of trouble with this stuff without diagramming it out, and maybe it'll also help future lurkers.

I don't think it's perfectly accurate but I tried to make all the connections as I understand them. Is this basically accurate or what would you change? It's a bit simplified/has generic names but hopefully it drives home the key ideas.

![Kargo drawio](https://github.com/user-attachments/assets/bad0707a-25b9-40ca-820e-aca2c6ea94ec)

**Reply by pww217** [reply]
I think one thing about this diagram is that ideally the rollout/job would run in the app's namespace itself in ideal conditions, to match the runtime environment as closely as possible. Traditionally we've mirrored this as best as we can with cross-cluster GHA runners and similar but obviously it's simpler, more reliable, and more accurate to run verifications alongside the real workload (or as close as feasible). Interested in any thoughts on that, too.

**Reply by krancour** [reply]
This looks close. I'd say your understanding is fairly good.

I'd put boxes in the clusters on the righthand side to depict the rollouts controllers.

I gather you have one Argo CD control plane in your tooling cluster and it's managing Apps in both of the other clusters. People _do_ do this, but just a heads up that this is generally thought of to be less secure than having an Argo CD control plane _per cluster_.

The reason is that your one Argo CD control plane has highly privileged credentials for multiple clusters. It becomes a very high value target. Kargo avoided this by distributing the controllers to the different clusters and having them "phone home" to the control plane.

**Reply by pww217** [reply]
Yep we do a hub and spoke, and yeah I agree it's not the most secure. We've been running Argo since the earliest days so a lot of our architectural methods could probably be better. I should see if there's a way to do a deployment per cluster while maintaining a single UI/URL for actually managing workloads, as we grant developers access to their own stacks and try to keep things simple. Something to discuss with my team.

Anyway that's a whole rabbit hole. I do have another question - you said the rollout controlling won't interfere with any existing ones on the remote cluster. Is it possible to just re-use the controller already there (it's used for Argo/Canary rollouts) or does it need to run a second Rollouts controller? My diagram refers to an existing namespace where the Rollouts controller exists - I should have been more clear.

**Reply by krancour** [reply]
It needs to be a dedicated rollouts controller since it's configured pretty specifically.

Re: control plane per cluster while maintaining a single pane of glass. Argo CD still doesn't do that to this day. It's a tricky thing. So much so that we built a company around managed Argo CD control planes with distributed agents. 😉

**Comment by liron-smarsh** [comment]
Hi @krancour , that did the work and now AnalisysysRun's works from the remote clusters thank you so much for that much needed explanation! 
I"m hitting another issue here, the issue is that on on Kargo UI I"m no longer able to view AnalisysysRun's output anymore it just stopped responding even though it can tell that it was successful (via the UI) there is no verification presentation ( I was able to verify that the analysis run gets created in to control plane cluster)
referring to this window that is **expected to work** if I was not clear enough:
![image](https://github.com/user-attachments/assets/757efc19-a3ca-4f27-a4f2-cba372ae0d9a)
Also getting this console error when clicking the Analysis run:
![image](https://github.com/user-attachments/assets/7638f2bd-a12c-473e-b664-9446325b2b76)

**Reply by krancour** [reply]
It looks like it's choking on a response body that was supposed to be JSON but wasn't. Presumably, that's the response that should have contained the logs you're looking for. Would you be able to use the browser's developer tools to find the response in question? It's possible that the response you're receiving isn't from the API server, but is an error response of some kind from a proxy between you and the API server. That's the most likely reason I can think of that the response would not be JSON as expected.

**Reply by krancour** [reply]
Or... perhaps that error isn't occurring in the UI. This might have been an error experienced by the API server and propagated to the UI....

Because I am questioning, give the topology we've discussed in this thread, _how_ the API server could possibly be getting logs from a Job on another cluster, when (by design) it doesn't communicate directly with any cluster other than its own.

**Reply by pww217** [reply]
@liron-smarsh can you share a bit more about how you configured the values of your primary control plane and the remote/secondary controllers, assuming you're using the [official helm chart?](https://github.com/akuity/kargo/tree/main/charts/kargo)

It may save me some trial and error (and others in the future) and maybe we can improve upon the chart's documentation, too.

**Reply by liron-smarsh** [reply]
Hi @pww217,
What @krancour  mentioned about the changes for the rollouts chart are the correct changes
here is my final spec that just differ from oem chart:
``` 
spec:
  containers:
  - args:
    - --instance-id=remote-controller
    - --kubeconfig=/kube/kubeconfig
    env:
    - name: ARGO_ROLLOUTS_ANALYSIS_JOB_KUBECONFIG
      value: /jobkube/kubeconfig
    volumeMounts:
    - mountPath: /kube
      name: kubeconfig
      readOnly: true
    - mountPath: /jobkube
      name: jobkubeconfig
      readOnly: true
  volumes:
  - name: kubeconfig
    secret:
      defaultMode: 420
      secretName: kubeconfig
  - name: jobkubeconfig
    secret:
      defaultMode: 420
      secretName: jobkubeconfig
```      
      jobkubeconfig => local-cluster kubeconfig (where your apps are at).
      kubeconfig     => Kargo control-plane cluster.

**Comment by liron-smarsh** [comment]
Thank for your response dear @krancour ,
Seems like this was caused by a none json formatted response  (it was raw HTML/TEXT response) when using the web provider, when the response is a proper json Kargo is able to display the AnlysisRun result window (not sure if that's a bug since the web provider and Kargo do declare success on the outcome but Kargo is unable to display).
Also one more thing I believe worth mentioning that this setup should work with all providers besides jobs, jobs (pods) are created on the control plane cluster which makes them kind of ineffective for this scenario in a way, the solution i used to overcome this is presented here:
 https://github.com/argoproj/argo-rollouts/pull/3350

**Comment by krancour** [comment]
> Also one more thing I believe worth mentioning that this setup should work with all providers besides jobs, jobs (pods) are created on the control plane cluster

Ya... I'd been thinking this was your scenario and part of your problem. I missed that this _wasn't_ using the job provider.

Until we work out how to do make this work for jobs that executed on another cluster (I'll look at rollouts#3350), I think we can probably disable the link if it's a job provider and the stage is labeled for a shard.

**Reply by pww217** [reply]
Ah yeah that's going to be a problem for me and I'm sure others too. As cool as it is to pull in metrics and such, for a CD tool like Kargo a critical functionality is the running of arbitrary code (in a one-time `job`) via Rollouts for purposes such as automated/integration/UI testing as well as custom logic between promotions. 

For me this is largely about replacing the CD components of Github Actions and what makes so many of our workflows absolute spaghetti code is that we're often forced to basically bash or python script in the workflow itself. It's neither modular nor maintainable.

My dream is to contain these tests and workflows as distinct artifacts in the form of `analysisTemplates` (and after 1.2.0 `promotionTemplates` too I hope). This way we can take a workload, create a quick pipeline, and plug in the templates we require. From a platform/dev enablement POV this makes automation/testing something that's modular/reusable, mix-and-matchable, consistent/versioned/maintainable, better security supply chain security/compliance, and more benefits I won't list here but the long and short is: artifacts instead of duplicative/spaghetti code.

On a related note, I've actually built a Helm chart called `kargo-pipelines` that I'd like to contribute upstream. At the moment it feels too opinionated due to the complexity of `promotionTemplates` so it's Helm/ECR/Github focused. Once those are a CRD it'll be easier to make more agnostic so that others can make better use of it.

But the basic format for a pipeline is as follows:

```yaml
owner: my-team

# Will override the naming conventions that are by default based on .Release.Name
nameOverride:

# Services definition including both warehouses and stages.
# This is designed only for Github, Helm, and Amazon ECR at the moment.

# Below are two examples. The first nginx one shows the most explicit configuration with multiple source images, previous stages, etc.
# The httpd one shows the bare minimum configuration possible.
services:
  nginx:
    gitRepoURL: https://github.com/nginx-app.git
    sourceImages:
      - imageURL: docker.io/library/nginx
        imageSelectionStrategy: NewestBuild
        tagFilter: Regex expression to sort for specific tag patterns
        valuesFilePath: infra/values # Path to values file(s) from repo root
        imageValueFile: version.yaml # The yaml file that actually contains the image and/or tag versionKey(s)
        versionKeys: # The helm key that the image is defined at in the values file.
          - image.tag

    stages:
      dev:
        autoPromotionEnabled: true
        sources:
          - direct # Pulls from the Warehouse
        argoCDAppName: nginx-dev
        analysisTemplates: []
      staging1:
        autoPromotionEnabled: true
        sources:
          - dev # Pulls from a single upstream stage
        argoCDAppName: nginx-staging
        analysisTemplates:
          - integration-test
      staging2:
        autoPromotionEnabled: true
        sources:
          - dev
        argoCDAppName: nginx-staging
        analysisTemplates:
          - integration-test
      prod:
        autoPromotionEnabled: false
        sources: # Pulls from one or more upstream stages that will promote to this stage
         - staging1
         - staging2
        argoCDAppName: nginx-prod
        analysisTemplates:
          - prometheus-canary

  httpd:
    gitRepoURL: https://github.com/httpd-app.git
    sourceImages:
      - imageURL: docker.io/library/httpd
        valuesFilePath: infra/values
        imageValueFile: version.yaml
        versionKeys:
          - image.tag

    stages:
      dev:
        autoPromotionEnabled: true
        sources:
        - direct # Pulls from the Warehouse
        argoCDAppName: httpd-dev
        analysisTemplates: []
        
		...more services and stages in any combination
```

I went through some effort to make sure you could define the values in a service-oriented way, and populate the CRs appropriately. Also the ability to add multiple previous stages, multiple warehouses, etc. etc. Basically I want to make this more agnostic and flexibility with the hope that eventually it can be modular enough to cover any use case or pipeline configuration. A bit of a tall order as of 1.1.2 but lots of potential.
