### DISCUSSION TITLE
How to read yaml file in promotion steps

### DISCUSSION THREAD

**Discussion by tangkhaiphuong** [akuity/kargo#3511] [General]
Hi, I applied Kargo as Continuos Deployment for our project. The problem I faced is how to read YAML file and get value base from path as input for `yaml-update`

For example:
```yaml
spec:
      steps:
        - config:
            checkout:
              - fromFreight: true
                path: ${{ vars.srcPath }}
              - branch: ${{ vars.branch }}
                path: ${{ vars.outPath }}
            repoURL: ${{ vars.gitRepo }}
          uses: git-clone
        - as: update-target-revision
          config:
            path: ${{ vars.outPath }}/demo.yaml
            updates:
              - key: spec.source.targetRevision
                value:  ???  # How to read yaml from: ${{ vars.srcPath }}/input.yaml with path: a.c.d 
          uses: yaml-update
```
