### DISCUSSION TITLE
Updating helm-update-image to yaml-update

### DISCUSSION THREAD

**Discussion by creeram** [akuity/kargo#3673] [General]
I saw with the new version of kargo `helm-update-image` is deprecated.

We have this config for that:

```
      - uses: helm-update-image
        as: update-chart-image
        config:
          path: ./src/apps/dev/deployment.yaml
          images:
          - image: registry.example.com/demo/images/nginx
            key: spec.values.override_app_image
            value: ImageAndTag

```

Now how can I achieve the same thing for `ImageAndTag` with `yaml-update`?

**Comment by hiddeco** [comment]
```yaml
- uses: yaml-update
  as: update-chart-image
  config:
    path: ./src/apps/dev/deployment.yaml
    updates:
    - key: spec.values.override_app_image
      value: registry.example.com/demo/images/nginx:${{ imageFrom("registry.example.com/demo/images/nginx").Tag }}
```

or

```yaml
- uses: yaml-update
  as: update-chart-image
  config:
    path: ./src/apps/dev/deployment.yaml
    updates:
    - key: spec.values.override_app_image
      value: ${{ imageFrom("registry.example.com/demo/images/nginx").RepoURL }}:${{ imageFrom("registry.example.com/demo/images/nginx").Tag }}
```

should make this work for you.

Refer also to the [expression language reference](https://docs.kargo.io/user-guide/reference-docs/expressions) to get a better grasp on how this works, as it is of growing importance to describe (complex) promotion steps.
