### DISCUSSION TITLE
base64 encoded bcrypt-hashed password is multiline

### DISCUSSION THREAD

**Discussion by shezaan-hashgraph** [akuity/kargo#3749] [Q&A]
I'm trying to set up Kargo and one of the first steps is to create a secret for the admin account. I am following this https://docs.kargo.io/operator-guide/security/secure-configuration/#securing-the-admin-account but have realized that the base64 encoded bcrypt-hashed password is a multiline password. That script does not put the password onto a single line. My question is that in the secret object does the password need to be on a single line as shown by this
I'm not using this so please nobody freak out but this is a sample output of the script from step # 1 on that link

```
Password: Ya1llbB8uBEHKc6yciu4QbZpYLVEdpZr
Password Hash: $2y$10$oGfFZJuAm1X3KqvVHiQBZeu.tnZWVNZbJaHyg9i5Rj.35980WtqJq
Encoded Password Hash: JDJ5JDEwJG9HZkZaSnVBbTFYM0txdlZIaVFCWmV1LnRuWldWTlpiSmFIeWc5aTVSai4zNTk4
MFd0cUpx -------> Notice this is a multiline Password Hash
Encoded Signing Key: NENsTGFvTUJESkhOU0R5MUI2YThsMkdSc0x0SGRxU1Y=
```

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: <secret name>
  namespace: <kargo namespace>
data:
  ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: <base64 encoded signing key>
  ADMIN_ACCOUNT_PASSWORD_HASH: <base64 encoded bcrypt-hashed password> ----> Single line only?
```
