### DISCUSSION TITLE
How to get output from PromotionTask as args to AnalysisTemplate

### DISCUSSION THREAD

**Discussion by tangkhaiphuong** [akuity/kargo#3806] [Q&A]
Assuming I have manifest like that
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/description: NL1
  finalizers:
    - kargo.akuity.io/finalizer
  name: nl1
  namespace: test
spec:
  promotionTemplate:
    spec:
      steps:
        - task:
            name: standard-promotion-task
          as: standard_promotion_task
  verification:
    analysisTemplates:
      - name: healthy-verification
    args:
      - name: is_success
        value: # How to get output of task inside standard_promotion_task
```
