### DISCUSSION TITLE
OIDC with Keycloak: only `groups` claim works ?

### DISCUSSION THREAD

**Discussion by pmkr04241** [akuity/kargo#3816] [Q&A] [answered]
👋 Hello,

I'm trying to enable OIDC authentication in Kargo using Keycloak as the identity provider.  
I followed the documentation here: https://docs.kargo.io/operator-guide/security/openid-connect#configuring-kargo

Here's the configuration I used (based on the docs):

```yaml
oidc:
  enabled: true
  issuerURL: https://<my-keycloak-url>/realms/<my-realm>
  clientID: kargo
  additionalScopes:
    - roles
  admins:
    claims:
      roles:
        - TEAM_ADMIN
 ```
However, this doesn't work — I can't authenticate.

But when I change `additionalScopes ` from `roles ` to `groups`, like this:

```yaml
oidc:
  enabled: true
  issuerURL: https://<my-keycloak-url>/realms/<my-realm>
  clientID: kargo
  additionalScopes:
    - groups
  admins:
    claims:
      groups:
        - TEAM_ADMIN
```
Then everything works as expected.

It seems like Kargo is hardcoded to only use the `groups `claim, and I can't use custom claims like `roles`, even though the documentation suggests it should be possible.

**Questions**
- Is it possible to use another claim than `groups`, like `roles`, in the admins.claims configuration?
- If not, could the documentation be updated to make this clearer?
- Is my initial configuration wrong or unsupported?

Thanks in advance!

**Comment by krancour** [comment]
> It seems like Kargo is hardcoded to only use the groups claim

This is not the case.

Because the Kargo UI and CLI both use PKCE, the OIDC authorization code flow takes place between the client and the IDP (KeyCloak in this case) directly, without the Kargo API server acting as an sort of a middle-man. To enable this, the Kargo API server has a "public configuration" endpoint that clients (like the Kargo UI or CLI) can query to learn the details of where they can find the IDP and how they should interact with it. These details include things like the issuer URL, but also, importantly for your case, they contain a list of scopes the client should request. This is is the list you are configuring with `api.oidc.additionalScopes`. It's not anything more than telling the API server to tell clients to ask for certain scopes when talking directly to the IDP. It isn't hard coded.

Chances are very high that your issue lies in your KeyCloak configuration. I don't have more than a passing familiarity with KeyCloak, but it seems highly probable to me that either `roles` is not a valid scope _or_ it isn't a scope that (on the KeyCloak end) the `kargo` client ID is configured to be able to use.

**Reply by gregoryboue** [reply]
> > It seems like Kargo is hardcoded to only use the groups claim
> 
> This is not the case.
> 

Are you sure ? Because on [this line](https://github.com/akuity/kargo/blob/main/ui/src/pages/user.tsx#L52) i can see ` Object.hasOwn(JWTInfo, 'groups')` so it means that if keycloak client doesn't add scope which explicit names 'groups', it can't be working.

Generally it's possible to configure clients scope name which contains groups for permission management.

**Reply by krancour** [reply, marked as answer]
I'm quite sure. What you're looking at there is code that displays user details in the UI. It's checking whether there _is_ a groups claim and if there is, it's displaying its values.

That probably shouldn't have been hard coded to look for specific claims and should just be dumping _all_ of the user's claims to the page, and I will open a separate issue for that, but code plays no role at all in the actual authentication process.

**Reply by gregoryboue** [reply]
Hi,

I can confirm that is functionnal with additionalScope : my-groups-attribute and then : 

```yaml
  admins:
    claims:
      my-groups-attribute:
        - TEAM_ADMIN
```

It just would be great if there is a way to configure `my-groups-attribute` to be treated as `groups` in kargo GUI.
