### DISCUSSION TITLE
The order of analysis run in verification

### DISCUSSION THREAD

**Discussion by tangkhaiphuong** [akuity/kargo#3929] [Q&A]
From document: https://docs.kargo.io/user-guide/how-to-guides/verification#configuring-verification
We can define many AnalysisTemplate:

```yaml

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: guestbook
spec:
  # ...
  verification:
    analysisTemplates:
      - name: health-check
      - name: integration-test
      - name: query-metric
      - name: query-log
```

Assuming there are 4 `AnalysisTemplate` and I expect that they should run in sequential with 4 `AnalysysRun` separately. But in-practical all of them run parallel under one `AnalysisRun`.

Is is the design of Kargo do that? So, is there any way to keep each `AnalysisRun` executes in sequential order? 

The scenario that I want `health-check` run first. Then `integration-test` and follow with `query-metric` and `query-log`
