### DISCUSSION TITLE
ClusterPromotionTask templating to support arbitrary set of images on multiple projects

### DISCUSSION THREAD

**Discussion by Brightside56** [akuity/kargo#3988] [General]
I have multiple projects with 2-3-5 images using "Grouped services", what means I have multiple container images which are promoted from single warehouse through stages. I'm considering to standardize promotion pipelines by utilizing ClusterPromotionTask resource. My initial idea was to have 4-5 straightforward ClusterPromotionTask CRs which would fully describe promotion template and could be referenced from any pipeline with quite standard set of variables.

First what comes to mind: it would great to pass array of container image repos to stage variables, then add task steps for stages referencing ClusterPromotionTask with defined logic of iteration over image repos and substitute them to manifest using yaml-update or kustomize-set-image steps". But wait, Kargo EL doesn't support iterators like for loop

Is there a recommended approach to handle my case?
How can I have relatively simple global promotion task templates which can be used for different set of images per project?

**Comment by david-curran-90** [comment]
Could you create one generic task that could be run multiple times?

I.e your task takes an image and does the `yaml-update` step and then build your stage manifest dynamically with something that does support conditionals

some ytt pseudo code:

```yaml
#@ for image in image_list:
- task:
     name: image-updater
     kind: ClusterPromotionTask
  as: #@ image
  vars:
    - name: image
      value: #@ image
#@ end
```

task manifest
```yaml
spec:
  vars:
  - name: image
  steps:
  - uses: update-yaml
     config:
       path: file.yaml
       updates:
       - key: path.to.image
         value: ${{ vars.image }}
```
