### DISCUSSION TITLE
Nested repos (directory as a helm chart)

### DISCUSSION THREAD

**Discussion by esn89** [akuity/kargo#4029] [Q&A]
I have a "nested helm chart" like so:

```
📁  my-nested-chart
├── 📁  apps
│   ├── 📁  templates
│   │   ├── 📄  demo-app.yaml
│   ├── 📄  Chart.yaml
│   ├── 📄  values.yaml
├── 📁  templates
│   └── 📄  cluster-root.yaml
├── 📄  Chart.yaml
└── 📄  values.yaml
```

Trying to use argocd-update to reference `apps/template` folder but no luck:

```        - uses: argocd-update
          config:
            apps:
            - name: demo-app
              sources:
              - repoURL: https://mycompany.com/my-nested-chart.git
                chart: apps
                desiredRevision: develop
 ```
 
 In my Application that is deployed, it looks like this:
 
 ```
 apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "80"
    kargo.akuity.io/authorized-stage: demo-app:dev
  name: demo-app
  namespace: argocd
  ```
  
  The error I am getting is this:
  
  
  ```
  step execution failed: step 4 met error threshold of 0: failed to run step "argocd-update": error building desired sources for Argo CD Application "demo-app" in namespace "argocd": no source of Argo CD Application "demo-app" in namespace "argocd" matched update for source with repoURL https://mycompany.com/my-nested-chart.git
  ```
  
  Are these types of nested repos not supported? Or am I doing something obviously wrong?
