### DISCUSSION TITLE
github commit metadata enrichment in Freight?

### DISCUSSION THREAD

**Discussion by voidlily** [akuity/kargo#4321] [Q&A]
I would like to be able to get more information about a Github commit from a git commit in a Freight, such as for example the github username.

Right now I notice the Freight has git commit authorship information

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
alias: ...
commits:
- author: Lily <voidlily@users.noreply.github.com>
  committer: Lily <voidlily@users.noreply.github.com>
  id: ...
  message: ...
  repoURL: ...
...
```

I could use the github API to get the commit information like so: https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#get-a-commit

However, doing this as a github app may be harder with the `http` promotion step because I'd need to generate a jwt somewhere, but all I have available is the equivalent of curl and no additional steps: https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-json-web-token-jwt-for-a-github-app#generating-a-json-web-token-jwt

Is there a way to enrich the metadata like I want, or is this more suited to a feature request?
