### DISCUSSION TITLE
How to use Argo like template creds in Kargo?

### DISCUSSION THREAD

**Discussion by Kavinraja-G** [akuity/kargo#4466] [Q&A]
I was looking to implement the templated creds for Kargo similar to what Argo [did](https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-repo-creds-yaml/).

So what we're doing in Argo is to have the
```yaml
─❯ k get secrets -n argocd github -oyaml
apiVersion: v1
data:
  githubAppID: *****
  githubAppPrivateKey: *****
  url: https://github.com
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repo-creds # Template creds
  name: github
  namespace: argocd
type: Opaque
```

&& project specific GH App creds which includes only the App installation ID like this
```yaml
╰─❯ k get secrets -n argocd xyz-project-main-repository -oyaml
apiVersion: v1
data:
  githubAppInstallationID: ******
  url: <xyz-repo-url>
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository # Repo cred
  name: xyz-project-main-repository
  namespace: argocd
type: Opaque
```
I want to look for similar approach in Kargo. Any workarounds here?

**Comment by krancour** [comment]
For better or worse, we took a lot of queues from Argo CD on how we handled credentials, so the approach that works is similar, but not the same.

Notes:

* We didn't feel `repo-creds` (as compared to `repository`) clearly communicated "this is a template," so this is one area where we did things a little differently.

* Our Projects also work differently.

To give all Projects access to credentials ("templates" or otherwise), put the Secret in one of your "global" credentials namespaces: https://docs.kargo.io/operator-guide/security/managing-credentials#global-credentials

To make the credentials work for a broad range of repositories, use a regular expression as the value of the `repoURL` key in the Secret's data map _and_ use the _string_ `"true"` as the value of the `repoURLIsRegex` key: https://docs.kargo.io/operator-guide/security/managing-credentials#repository-credentials-as-secret-resources

Example:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: <name>
  namespace: <namespace>
  labels:
    kargo.akuity.io/cred-type: <type>
stringData:
  repoURL: <regular expression>
  repoURLIsRegex: "true"
  # Other fields ...
```

**Reply by Kavinraja-G** [reply]
Yeah I looked into that Global credentials earlier. But the main use-case I can see of adopting template creds in Argo:

We only need to set the `githubAppID, githubAppPrivateKey` once in the template and users only need to set the `repoURL` and `githubAppInstallationID` In our setup we're using a single app, so this was much cleaner approach for us.

But it sounds like we can't do similar thing with Kargo yet?

**Reply by krancour** [reply]
Here's a full example of what you're asking about:

https://docs.kargo.io/user-guide/security/managing-credentials#github-app-authentication

Is there a reason this doesn't work for you?

**Reply by Kavinraja-G** [reply]
No it does, that's what I currently did. 

My point is I can't split out `githubAppID & githubAppPrivateKey` to be templated like we do in Argo. So, that our Kargo users don't need to worry about those secret keys (you can consider they are only managed by the "operator"), "user" only need to create a secret with `repoURL & githubAppInstallationID` for their project and good to go. (Since we have a single GH App here)

**Reply by krancour** [reply]
Why are you wishing for "Kargo users" (presumably Project-level admins) to maintain any aspect of this when the entirety of what you're asking about can be centralized and managed by the Kargo admin?

**Reply by Kavinraja-G** [reply]
Why we need to centralise every "Kargo user" projects secrets to be global? 

Here, we only have the `githubAppID & githubAppPrivateKey` are common and considered to be global. And the users they themself install the common GH app to their org and deploy the secret for any repos.

I can give you an overview on how I'm thinking this, once a "user" needs to onboard Kargo:

**Kargo User**:
1. Install the common GH App
2. Get the installation ID
3. Send it to a self-service catalog

**Kargo Operator** (Manages the self-service catalog)
1. Already manages the global credential namespace where we have the pullSecrets etc., (now I just want to template out the GH privateKeys and appID, which we do currently in Argo) 
1. Provisions the "Kargo User"'s Project
2. With all RBAC
3. From here, it's the "Kargo User" who can take control of all the project specific repo secrets etc.,

**Reply by krancour** [reply]
> install the common GH app to their org and deploy the secret for any repos

Maybe I'm confused, because this seems somewhat unconventional (to me). I would ordinarily expect that _org_ is common across many/most projects and that a GitHub App is installed into that org by some highly privileged user of that org.

By way of example, let's call the org `example`. The App would be installed into the `example` org, resulting in a single installation ID, and the Secret would be configured with something like `repoURL: ^https://github.com/example/.*$` and `repoURLIsRegex: "true"`. This would then work for _all_ Projects requiring access to repos belonging to the `example` org.

It seems, however, you have an App that is installed into many orgs, which means many installation IDs.

(Aside: It seems odd that you would do this. Doesn't making an App available for installation into multiple orgs require you to make the App publicly available for installation to _all_ GitHub repos/orgs?)

Anyway, what stops you from doing this, which would allow you to have the single App installed into multiple orgs (as you're doing), without requiring anything additional on the part of each Project?

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-creds
  namespace: my-global-creds-ns
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: ^https://github.com/example/.*$
  repoURLIsRegex: "true"
  # Other fields ...
  githubAppInstallationID: <installation ID here>
---
apiVersion: v1
kind: Secret
metadata:
  name: example-skunkworks-creds
  namespace: my-global-creds-ns
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: ^https://github.com/example-skunkworks/.*$
  repoURLIsRegex: "true"
  # Other fields ...
  githubAppInstallationID: <installation ID here>
```
