### DISCUSSION TITLE
Issues with authenticating to azure container registry

### DISCUSSION THREAD

**Discussion by akselleirv** [akuity/kargo#953] [Q&A] [answered]
I'm trying to subscribe to a container changes in ACR and I have the following secret:

```
apiVersion: v1
kind: Secret
metadata:
  name: acr-pull
  namespace: kargo-my-project
  labels:
    kargo.akuity.io/secret-type: repo-creds
stringData:
  password: <repository-token>
  type: image
  url: <my-registry>.azurecr.io
  username: <token-name>
```

But it's failing with the following logs:
```
time="2023-10-13T11:08:46Z" level=debug msg="reconciling Stage" namespace=kargo-my-project stage=my-app-dev
time="2023-10-13T11:08:46Z" level=debug msg="found Stage" namespace=kargo-my-project stage=my-app-dev 
time="2023-10-13T11:08:46Z" level=debug msg="obtained credentials for image repo" namespace=kargo-my-project repo=my-registry.azurecr.io/my-app stage=my-app-dev
time="2023-10-13T11:08:47Z" level=error msg="error syncing Stage: error syncing image repo subscriptions: error getting latest suitable tag for image \"my-registry.azurecr.io/my-app\": error fetching tags for image \"my-registry.azurecr.io/my-app\": errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.\n" namespace=kargo-my-project stage=my-app-dev
time="2023-10-13T11:08:47Z" level=debug msg="done reconciling Stage" namespace=kargo-my-project stage=my-app-dev
```

I have tested locally with curl that the token is valid:
```
curl -v -u "<token-name>:<repository-token>" "https://my-registry.azurecr.io/oauth2/token?service=my-registry.azurecr.io&scope=repository:my-app:metadata_read"

# Which returns: {"access_token":"<access_token>"}

curl -H "Authorization: <access_token>" https://my-registry.azurecr.io/v2/my-app/tags/list

# Which returns: {"name":"my-app","tags":["0.1.0"]}
```

Any ideas what could be wrong?
