### DISCUSSION TITLE
Flow control stage not showing Freight ID

### DISCUSSION THREAD

**Discussion by tal-hason** [akuity/kargo#981] [General]
When creating a flow control stage, that just subscribes to the upstream stages, when this stage gets promoted in the UI no freight ID is shown:

```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-ready
  namespace: gotham-kargo
  annotations:
    kargo.akuity.io/color: fuchsia
spec:
  subscriptions:
    upstreamStages:
    - name: code-testing
    - name: security-testing
```

in the UI it Looks like that:
![image](https://github.com/akuity/kargo/assets/97454240/3243f302-a83d-4be2-b792-7f4715ebd819)

you can see that the stage doesn't have a freight id and the image on the right side does not update the color for the current stage.

this is very confusing
