### ISSUE TITLE
Helm option to disable creation of secret

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1016]
# Proposed Feature

I agree with, and understand the rationale for https://github.com/akuity/kargo/pull/829, which forgoes a default password hash and token signing key.

However, in my case, I don't want kargo to manage the secret, because I want to create the secret myself through an ExternalSecret.

# Motivation

Right now I am forced to workaround the issue by create dummy values for admin password hash, and then use kustomize to remove the secret, and add the External Secret 

# Suggested Implementation

Many charts have a `create: true` option for secrets. I am proposing we add one ourselves:

```yaml
api:
  secret:
    # creates the `kargo-api` secret. Set to false if the `kargo-api` Secret is created by some other means
    create: true
```
