### ISSUE TITLE
error creating Freight: cannot set blockOwnerDeletion

### ISSUE THREAD

**Issue by christianknell** [akuity/kargo#1046]
# Description

I tried to reproduce the kargo-demo from the Quickstart guide using the latest kargo Helm Chart v0.1.1-rc.2. I had to change the stage test to use a warehouse. But the creation of a Freight object fails with the following error message in the controller Pod:

```bash
error syncing Warehouse: error creating Freight \"47b33c0c92b54439e5eb7fb80ecc83f8626fe390\" in namespace \"kargo-demo\": freights.kargo.akuity.io \"47b33c0c92b54439e5eb7fb80ecc83f8626fe390\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on
```

# Steps to Reproduce

### values.yaml

```yaml
kargo:
  api:
    adminAccount:
      password: <REMOVED>
      tokenSigningKey: <REMOVED>
    host: <REMOVED>
    ingress:
      enabled: true
      annotations:
        route.openshift.io/termination: "edge"
      tls:
        enabled: false
    tls:
      enabled: false
  controller:
    argocd:
      namespace: openshift-gitops
      watchArgocdNamespaceOnly: true
```

### Installation

```bash
helm install kargo -n openshift-gitops -f values.yaml oci://ghcr.io/akuity/kargo-charts/kargo --version 0.1.1-rc.2
```

## Namespaces

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-test
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-uat
---
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo-prod
```

## ArgoCD Applications

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:test
  name: kargo-demo-test
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/akuity/kargo-demo.git
    targetRevision: main
    path: stages/test
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-test
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:uat
  name: kargo-demo-uat
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/akuity/kargo-demo.git
    targetRevision: main
    path: stages/uat
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-uat
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kargo.akuity.io/authorized-stage: kargo-demo:prod
  name: kargo-demo-prod
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/akuity/kargo-demo.git
    targetRevision: main
    path: stages/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo-demo-prod
```

## Kargo Project

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kargo.akuity.io/project: "true"
  name: kargo-demo
```

## Kargo Warehouse

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    - image:
        repoURL: nginx
        semverConstraint: ^1.24.0
```

## Kargo Stages

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    warehouse: test
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/akuity/kargo-demo.git
        writeBranch: stage/test
        kustomize:
          images:
            - image: nginx
              path: stages/test
    argoCDAppUpdates:
      - appName: kargo-demo-test
        appNamespace: openshift-gitops
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
      - name: test
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/akuity/kargo-demo.git
        writeBranch: stage/uat
        kustomize:
          images:
            - image: nginx
              path: stages/uat
    argoCDAppUpdates:
      - appName: kargo-demo-uat
        appNamespace: openshift-gitops
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  subscriptions:
    upstreamStages:
      - name: uat
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/akuity/kargo-demo.git
        writeBranch: stage/prod
        kustomize:
          images:
            - image: nginx
              path: stages/prod
    argoCDAppUpdates:
      - appName: kargo-demo-prod
        appNamespace: openshift-gitops


```

# Version

```
Client Version: v0.1.0
Server Version: v0.1.1-rc.2
```

# Workaround

It works if I add a new ClusterRole and ClusterRoleBinding to the ServiceAccount used to start the controller Pod:

## ClusterRole

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-controller-admin
rules:
  - apiGroups:
      - kargo.akuity.io
    resources:
      - "*"
    verbs:
      - "*"
```

## ClusterRoleBinding

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-controller-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-controller-admin
subjects:
  - kind: ServiceAccount
    name: kargo-controller
    namespace: openshift-gitops
```

## Result

![grafik](https://github.com/akuity/kargo/assets/12433010/9cfd63ac-61c1-4303-8861-68288b0e838b)

**Comment by krancour** [comment]
> I tried to reproduce the kargo-demo from the Quickstart guide using the latest kargo Helm Chart v0.1.1-rc.2.

Sorry about this. The quickstart is compatible only with the latest official release.

> But the creation of a Freight object fails with the following error message...

You're on OpenShift, right? I think I recall running into this before with OpenShift and the Promotion type.

I'm fairly certain this can be rectified by adding only `path` and `update` verbs for the `warehouses/finalizers` type. 

Thanks for reporting this @christianknell!

**Comment by krancour** [comment]
See #811/#834

**Comment by christianknell** [comment]
Thanks @krancour for the quick reply. This worked:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-controller-admin
rules:
  - apiGroups:
      - kargo.akuity.io
    resources:
      - warehouses/finalizers
    verbs:
      - patch
      - update
```
