### ISSUE TITLE
SSO OIDC mapping to ServiceAccount for Auth-N

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1102]
# Proposed Feature

Today we have incomplete SSO support and anyone who logs in is a kargo admin. Kargo needs a way to scope the privileges of what the current user can do.

# Motivation

This is table stakes.

# Suggested Implementation

Discussed with @krancour , @devholic , @gdsoumya. We will use a similar technique that used in [argo-workflows](https://argoproj.github.io/argo-workflows/argo-server-sso/#sso-rbac).

1. The `kargo-api` Role will be given the following additional privileges:
* list/get/watch ServiceAccounts in all namespaces
* the ability to perform `SubjectAccessReviews` or `LocalSubjectAccessReview` (not sure if we can use Local)

2. A kargo project owner, who has permissions to his/her own namespace, will be able to annotate ServiceAccounts with a mapping to OIDC users and groups. Something like:

```yaml
kind: ServiceAccount
metadata:
  annotations:
    kargo.akuity.io/rbac.groups: devops,prod-admins
    kargo.akuity.io/rbac.sub: jesse@akuity.io,kent@akuity.io
  name: devops
```

3. When authorizing a request, the `kargo-api` server will:
* Iterate all ServiceAccounts in the project namespace in question
* For each ServiceAccount in project namespace
    * Check if ServiceAccount has an OIDC group/user associated with it
        * If yes perform a SubjectAccessReview to see if the ServiceAccount has permission to perform the request
            * If yes, allow the request to occur (using `kargo-api`'s permission)

4. If the project level ServiceAccounts had no ability to perform the request, kargo-api should fall back to **_globally_** configured ServiceAccounts that a kargo administrator defined in the `kargo` namespace. This will allow a kargo admin to configure some global defaults (e.g. permit everyone who is able to login, to have a `viewer` Role)

NOTE: unlike argo-workflows, the above approach has the benefit of *aggregating* the permissions of multiple ServiceAccounts, due to the fact that we iterate multiple ServiceAccounts and perform multiple `SubjectAccessReview`s.

# Open Issues

We agreed to have a simple CSV mapping:

```yaml
  annotations:
    kargo.akuity.io/rbac.groups: devops,prod-admins
    kargo.akuity.io/rbac.sub: jesse@akuity.io,kent@akuity.io
```

But for a global configuration, we would need the ability to support something like wildcard globs:

```yaml
  annotations:
    kargo.akuity.io/rbac.sub: *
```
