### ISSUE TITLE
bug: Invalid Repository Name when using default Harbor project

### ISSUE THREAD

**Issue by kjvellajr** [akuity/kargo#1106]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When using Harbor as the image registry, Kargo can not find any image tags under the default (`library`) project. It looks like this is related to the `argocd-image-updater` code being used here: https://github.com/akuity/kargo/blob/1e8b1e142bbf3012b67fac4154ea6e6cc8f6cf5a/internal/images/images.go#L83

Working: `harbor.example.com/homelab/foo:latest`
Not working: `harbor.example.com/library/foo:latest` (see logs section below)

I noticed that the `/library` portion of the URL is missing during API calls to Harbor when listing image tags:  `GET /v2/foo/tags/list HTTP/1.1" 400 98 "-" "Go-http-client/1.1" 0.003 0.004 .`. When using a non-default project in Harbor I see the following logs `"GET /v2/homelab/foo/tags/list HTTP/1.1" 200 57 "-" "Go-http-client/1.1" 0.003 0.002 .`

# Screenshots

![2023-11-14_12-36](https://github.com/akuity/kargo/assets/5348122/510b4ddf-c36a-422e-83ab-f2b33c515e3a)

# Steps to Reproduce

Create Kargo Namespace, Stage, and Kargo Secret for Harbor registry
```
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Namespace
metadata:
  name: foo
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: homelab
  namespace: foo
spec:
  subscriptions:
    repos:
      images:
      - repoURL: harbor.exaple.com/library/foo
---
apiVersion: v1
kind: Secret
metadata:
  name: kargo-harbor
  namespace: foo
  labels:
    kargo.akuity.io/secret-type: repo-creds
stringData:
  type: image
  url: harbor.example.com
  username: robot$kargo
  password: supersecretpassword
EOF
```

Observe error in kargo-controller.

# Version

```
Client Version: v0.1.0
Server Version: v0.1.0
```

# Logs

`
level=error msg="error syncing Stage: error syncing image repo subscriptions: error getting latest suitable tag for image \"harbor.example.com/library/foo\": error fetching tags for image \"harbor.example.com/library/foo\": unknown: bad request: invalid repository name: foo" namespace=foo stage=homelab
`
