### ISSUE TITLE
Warehouse image updateStrategy: NewestBuild not pulling the Tags curretly

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#1149]
# Checklist

* [v] I've searched the issue queue to verify this is not a duplicate bug report.
* [v] I've included steps to reproduce the bug.
* [v] I've pasted the output of `kargo version`.
* [v] I've pasted logs, if applicable.

# Description

When creating a warehouse with an image subscription with the updateStrategy = NewestBuild

the image tags that are arriving from the registry are not updated.

# Screenshots

the image list from the registry:
![image](https://github.com/akuity/kargo/assets/97454240/10deede6-73c9-4557-880e-aca687a87bf6)

The image that the warehouse received:
![image](https://github.com/akuity/kargo/assets/97454240/8dd559cd-1737-4ca2-b592-09a8d9e99451)

# Steps to Reproduce

Create a warehouse with a subscription:

```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gotham
spec:
  subscriptions:
      - image:
          repoURL: quay.io/gotham/batman
          updateStrategy: NewestBuild
      - image:
          repoURL: quay.io/gotham/joker
          updateStrategy: NewestBuild
      - image:      
          repoURL: quay.io/gotham/robin
          updateStrategy: NewestBuild
      - git:
          repoURL: https://github.com/gotham-demo/gotham-cd.git
          branch: main
```

# Version

```
V0.2.1
```

# Logs

```
Controller log:
[kargo-controller-798f754644-f4nn4-controller.log](https://github.com/akuity/kargo/files/13412135/kargo-controller-798f754644-f4nn4-controller.log)

```

**Comment by krancour** [comment]
@tal-hason I presume this to be an Image Updater bug, and more specifically, I suspect it has something to do with the way they cache things, which seems to me that it may be incorrect in some cases.

#1058 will move us off of image updater entirely.

If you don't mind helping me out a bit here, there are two things that would be useful data points:

1. If you restart the controller, does it then find the right image? This would prove it is related to Image Updater's cache.

2. I did a custom build of main + #1058 and pushed it to `krancour/kargo:for-tal`. Would you be willing to try that image and tell me if it solves your problem?

These datapoints would be useful for further justifying the transition away from Image Updater.

**Comment by tal-hason** [comment]
> If you restart the controller, does it then find the right image? This would prove it is related to Image Updater's cache.

Yes, I tried it many times but without any success :-(

> I did a custom build of main + https://github.com/akuity/kargo/pull/1058 and pushed it to krancour/kargo:for-tal. Would you be willing to try that image and tell me if it solves your problem?

NP I will try it later on and update you

**Comment by krancour** [comment]
> Yes, I tried it many times but without any success :-(

Still possible it is an image-updater bug we don't know about.

> NP I will try it later on and update you

I appreciate this very much!

**Comment by tal-hason** [comment]
@krancour ,

I get:

> Failed to pull image "ghcr.io/krancour/kargo:for-tal": rpc error: code = Unknown desc = Requesting bearer token: invalid status code from registry 403 (Forbidden)

**Comment by krancour** [comment]
@tal-hason, `krancour/kargo:for-tal` is on Docker Hub; not `ghcr.io`.

**Comment by tal-hason** [comment]
@krancour,

now change with the custom image

here is the log file of the controller:

[kargo-controller-f5c4b67c4-bw6rz-controller.log](https://github.com/akuity/kargo/files/13419800/kargo-controller-f5c4b67c4-bw6rz-controller.log)

**Comment by krancour** [comment]
Thanks for trying that @tal-hason. @christianh814 confirms the same issue both with `main` and the custom build.

**Comment by krancour** [comment]
@tal-hason @christianh814 I've gotten to the bottom of this:

Kargo and Image Updater disagree on the constants used to represent the different strategies and have all along:

This is from v0.1.0:

https://github.com/akuity/kargo/blob/v0.1.0/internal/images/images.go#L15-L42

Image Updater defaults to semver if it cannot parse the provided strategy.

This continues to be the case, all the way up to and including `main`.

We never noticed up until now because all of our examples have used semver and we assumed existing Image Updater code just works -- and mostly it does. It was just the failed parsing throwing everything off.

My PR #1058 that completely replaces Image Updater (for reasons entirely unrelated to this) happens to solve the issue just because it eliminates the disagreement over what constants represent each strategy.

(If my custom build didn't appear to solve the issue for you, I am questioning whether I was possibly sitting on the wrong branch when I built it.)

If #1058 isn't merged soon, I will open a separate fix for this.

**Comment by tal-hason** [comment]
@krancour , here are soylent-green logs thanks 

[kargo-controller-74bdd7d5c5-cczs5-controller.log](https://github.com/akuity/kargo/files/13421971/kargo-controller-74bdd7d5c5-cczs5-controller.log)

**Comment by krancour** [comment]
@tal-hason @christianh814 I just remembered that #1058 (soylent-green) has breaking changes to the CRDs.

`updateStrategy` has changed to `tagSelectionStrategy`.

Your old data adhering to the schema for the old CRD is _missing_ `tagSelectionStrategy` and so we're once again defaulting to semver.

🤦 

i.e. Can't test #1058/soylent-green custom image without also taking the new CRDs.

**Comment by tal-hason** [comment]
@krancour ,
LOL, np.

So just changing the warehouse as follows

updateStrategy -> tagSelectionStrategy

If not share a sample 😁

**Comment by krancour** [comment]
> So just changing the warehouse as follows

> updateStrategy -> tagSelectionStrategy

Yep. That's it. As long as you've upgraded the CRDs.

**Comment by tal-hason** [comment]
> > So just changing the warehouse as follows
> 
> > updateStrategy -> tagSelectionStrategy
> 
> Yep. That's it. As long as you've upgraded the CRDs.
@krancour, here is the update:

Updated the CRD like this:
![image](https://github.com/akuity/kargo/assets/97454240/d844d67c-79d3-4667-9ab4-005f85bbad64)

the warehouse YAML:
```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: gotham
  namespace: gotham-kargo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  subscriptions:
      - image:
          repoURL: quay.io/gotham/batman
          tagSelectionStrategy: NewestBuild
      - image:
          repoURL: quay.io/gotham/joker
          tagSelectionStrategy: NewestBuild
      - image:      
          repoURL: quay.io/gotham/robin
          tagSelectionStrategy: NewestBuild
      - git:
          repoURL: https://github.com/gotham-demo/gotham-cd.git
          branch: main
```

now it seems to work:
![image](https://github.com/akuity/kargo/assets/97454240/fa822f2b-5f95-4fe7-aba4-da2ef26936bd)

but the auto-promotion is taking a long time to start.

here is the controller LOG:
[kargo-controller-74bdd7d5c5-d54v9-controller.log](https://github.com/akuity/kargo/files/13423352/kargo-controller-74bdd7d5c5-d54v9-controller.log)

I will build some new images and test how it repsonds

**Comment by krancour** [comment]
> but the auto-promotion is taking a long time to start.

Known, but probably undocumented, issue and unrelated to #1058.

We are lacking an event handler to make a warehouse's subscribers reconcile immediately after new freight is created.

If you open an issue, we can probably fix that quickly.

**Comment by tal-hason** [comment]
For now, i will keep on running with:

```YAML
image:
  ## @param image.repository Image repository of Kargo
  repository: docker.io/krancour/kargo
  # repository: ghcr.io/akuity/kargo
  ## @param image.tag Overrides the image tag. The default tag is the value of `.Chart.AppVersion`
  tag: soylent-green
```
