### ISSUE TITLE
Image Selection appears too flexible

### ISSUE THREAD

**Issue by phclark** [akuity/kargo#1153]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

When running through the quickstart with 0.2.0, I modified the Warehouse semverConstraint to include more than one images from the image repository. I would expect that I would only be able to "pull" Freight currently in use by the upstream stage, but I was able to select any piece of Freight in the freighline. For example, I clicked the pull button in the `uat` stage, and was able to `d9a3e3e` when the `test` stage used `3104320`. 

Additionally, when "pushing", I would expect my only option would be to push the current freight. However, when I select the push button on the `uat` stage, I'm able to push `47b33c0` when I would expect to only be able to push the current freight, `d9a3e3e`.

Note that I have gone through the 
# Screenshots

<img width="1051" alt="image" src="https://github.com/akuity/kargo/assets/35117115/572be628-23d3-420f-8f20-1f5aa28021c0">

<img width="1047" alt="image" src="https://github.com/akuity/kargo/assets/35117115/2a629887-2d2f-42ed-80c3-2174c7cac9ac">

# Steps to Reproduce

1. Follow the Quickstart for version 0.2.0, https://kargo.akuity.io/quickstart
2. Edit the `kargo-demo` Warehouse's `semverConstraint` to match multiple images:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
    - image:
        repoURL: nginx
        semverConstraint: ~1.25.0
        updateStrategy: SemVer
```

# Version

```
Client Version: v0.2.1
Server Version: v0.2.1
```

# Logs

```
Paste any relevant application logs here.
```
