### ISSUE TITLE
Flow Control Stages are Auto promoted even if a PromotionPolicy is defined "false"

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#1166]
# Checklist

* [v] I've searched the issue queue to verify this is not a duplicate bug report.
* [v] I've included steps to reproduce the bug.
* [v] I've pasted the output of `kargo version`.
* [v] I've pasted logs, if applicable.

# Description

When having a flow control stage( a stage without any promotionMechanisms) when promoting to a stage that flow-control stage is subscribed to it automatically gets promoted.

i this flow control stage:
```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod-ready
  namespace: gotham-kargo
  annotations:
    kargo.akuity.io/color: fuchsia
    argocd.argoproj.io/sync-wave: "5"
spec:
  subscriptions:
    upstreamStages:
    - name: code-testing
    - name: security-testing
```

and for testing created the following promote Policy:
```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: prod-ready-policy
stage: prod-ready
enableAutoPromotion: false
```

when promoting images to code-testing & security-testing once one of those stages reports healthy from argoCD it starts promoting the the subscribed prod stages of the prod-ready stage.

# Version

0.2.1

# Logs

[kargo-controller-74bdd7d5c5-8t2nv-controller.log](https://github.com/akuity/kargo/files/13439233/kargo-controller-74bdd7d5c5-8t2nv-controller.log)
