### ISSUE TITLE
Patch promotions

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#1183]
# Proposed Feature

An ability to detect and prompt arbitrary patches in Git repository. Kargo should be able to monitor specific changes in YAML/JSON files and propagate these changes between environments.

# Motivation

To my knowledge today, most Argo CD users store configurations of all environments in different folders of a single branch. The promotions between environments are replications of small patches in different directories. Examples:

* image tag in `env/test/kustomization.yaml`, `env/stage/kustomization.yaml`, `env/prod/kustomization.yaml`
* `image.tag` parameter `values-test.yaml`, `values-stage.yaml`, `values-prod.yaml`
* dependant chart version in `env/test/Chart.yaml`, `env/stage/Chart.yaml`, `env/prod/Chart.yaml`

Often these promotions are automated using CI, so it is the perfect use case for Kargo.

# Suggested Implementation

Introduce patches in subscriptions and promotions settings:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/jessesuen/guestbook-deploy.git
      branch: main
      patches:
      # image tag in kustomization.yaml
      - path: env/test/kustomization.yaml
        jsonPaths:
          path: $.images.*.newTag
      # image.tag in values.yaml
      - path: values-qa.yaml
        jsonPaths:
          path: $.image.tag
```

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
spec:
  subscriptions:
    warehouse: guestbook
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/jessesuen/guestbook-deploy.git
        patches:
          path: env/test/kustomization.yaml
          jsonPaths:
            path: $.images.*.newTag
    argoCDAppUpdates:
      - appName: guestbook-dev
```
