### ISSUE TITLE
Kargo should emit Kubernetes Events on interesting events

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1231]
# Proposed Feature

When interesting events happen, we should emit Kubernetes events.

Some events we should handle:
* User initiated a promotion
* User approved a Freight for promotion
* Promotion Succeeded/Failed/Error
* Freight became verified in a Stage

These events should then be shown in the UI in an Events tab.

# Motivation

These Events can then be persisted and shown alongside other interesting things

# Suggested Implementation

Kubernetes has an eventing library that API server and controller would use to emit events. However, its default behavior is to deduplicate multiple or reoccurring events into a single event and increase a counter of occurrences in the Event object. We need to make sure that we disable that when it makes sense since we want individual records of events. The deduplication behavior loses individual timestamps of each event and instead records first and last occurrence.

```[tasklist]
### Tasks
- [ ] https://github.com/akuity/kargo/issues/1818
- [x] Backend
```

**Comment by jessesuen** [comment]
From discord:
> What about DORA metrics? Kargo knows when commit was made (commit which is related to warehouse artifacts) and when it reached production 

The above question got me thinking...

Since the Kargo API/controller has full context on Freight, Stages, Users, Promotions etc..., we should ensure that the events that we omit are enriched with useful information that could be mined later. For example, to address the above use case, we could pass along metadata around (as annotations to the Event) so that the Events can be associated together.

Here are some ideas on annotations that we would want to preserve:

```yaml
metadata:
  annotations:
    meta.kargo.akuity.io/initiator: jesse@akuity.io
    meta.kargo.akuity.io/freight: abc123
    meta.kargo.akuity.io/stage: prod
    meta.kargo.akuity.io/promotionName: prod.01hgjfdt6d22wcq1h6neez0enr.abc123
    meta.kargo.akuity.io/promotionCreationTime: 2023-12-05T12:00:00
    meta.kargo.akuity.io/promotionCompletionTime: 2023-12-05T12:01:00
    meta.kargo.akuity.io/stageVerificationTime: 2023-12-05T12:05:00
```
