### ISSUE TITLE
Consult `rbac.kargo.akuity.io/email` as a scope

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1278]
# Proposed Feature

In v0.3.0, we will support mapping of `sub` and `groups` OIDC fields:

```yaml
metadata:
  annotations:
    rbac.kargo.akuity.io/sub: jessesuen
    rbac.kargo.akuity.io/groups: myorg:kargoadmin
```

But we should also support `email`, which is a standard OIDC scope.

# Motivation

`sub` is often an opaque user ID. But emails are not. In order to improve the UX of giving individuals access, we need to support the `email` scope.

# Suggested Implementation

Similar implementation as sub:

https://github.com/akuity/kargo/blob/4e28102659e94c151c751ad86344a9f40f829882/internal/kubeclient/indexer.go#L307-L330
