### ISSUE TITLE
support time-based windows on warehouses and stages

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1328]
For Warehouses, allow specifying time periods where new Freight can/cannot be produced.

For Stages, allow specifying time periods where Promotions may/may not occur.

__Edit:__ It might be better to include these features in `ProjectSpec`.

**Comment by lknite** [comment]
This came in as a requirement for us, or something similar, we need to be able to do a "freeze" such as a winter holiday freeze, or "no changes around earnings" freeze, or similar.  The ability to perform some sort of check like a Job before a promotion is allowed would work as well.

**Comment by lknite** [comment]
I received clarification on the use cases:

- "I'm thinking more of a scenario where we have an incident happening in production and we want to halt all changes into that environment. This would be more of an emergency button to stop all deployments."

- "We need this when we do patching, DR exercises, or when there's an incident"

If there was the ability to run a Job before a promotion, that would work also cause I could have it check for an on/off switch that we could turn off.  I could make sure its added to all stages.  Of course, something at more of a top-level would be much simpler.

**Comment by krancour** [comment]
@lknite there was a separate issue for a "stop the line button." It might have gone stale and been closed. I'll find it and re-open that.

**Comment by krancour** [comment]
@lknite I re-opened #1422

**Comment by gmauleon** [comment]
That would work well for "maintenance windows" where depending on the cluster you deploy on, you have specific time frames when promotion are allowed.

**Comment by george-e-shaw-iv** [comment]
Just commenting in support of this feature. While we could probably get away with sync windows in ArgoCD, I'd rather manage this at the promotion orchestration level.

**Comment by ThomasSteinbach** [comment]
That would be great to promote Renovate changes in a repo during "working days".

ref: Discussion [Promotion at "time of day" and "day of week". #4987](https://github.com/akuity/kargo/discussions/4987)

**Comment by jonwinton** [comment]
Adding a comment in support for this feature. My team discussed using ArgoCD sync windows but determined it had other drawbacks for our configuration and we'd prefer to manage this at the Kargo layer

**Comment by andrewmc201** [comment]
My company has regular windows during certain days of the week where code should not be promoted to our production stage in particular. If we had the ability to time-limit when we could promote freight to that production stage, it'd be pretty helpful for us.

**Comment by jfgrea27** [comment]
+1 from our team as well. cc @krancour

We'd like to use auto-promotion on production stages but restrict it to business-hours change windows (e.g. Mon–Fri 09:00–17:00 UTC). Today the only workaround is scripting `kubectl patch` against `ProjectConfig` from an external cron job, which is brittle and pushes scheduling concerns outside of Kargo.

For what it's worth, the API shape we had in mind looks something like this on `ProjectConfig`:

```yaml
spec:
  promotionPolicies:
  - stage: prod
    autoPromotionEnabled: true
    autoPromotionWindows:
    - days: ["Mon", "Tue", "Wed", "Thu", "Fri"]
      startTime: "09:00"
      endTime: "17:00"
      timezone: "Europe/London"
```

Key points from our side:

- **Optional** — if `autoPromotionWindows` is omitted, auto-promotion behaves as today (always on).
- **Timezone-aware** — IANA tz strings avoid ambiguity across teams in different regions.
- **Multiple windows** — allows expressing different schedules (e.g. weekday daytime + Saturday morning maintenance slot).

Happy to help test or provide further input as the design evolves.

**Comment by jfgrea27** [comment]
Hi @krancour, any thoughts on the above?

**Comment by nikolay-te** [comment]
The way I'm solving this is by calling an external service with the `http` step, and this service decides if the promotion can proceed or not.

**Comment by LittaKake** [comment]
A project currently is managed by a projectconfig. The projectconfig currently is quite minimal, where it mostly decides if promotions will happen automatically for certain stages. This promotion policy seems thightly knitted with time-based windows, and I therefore imagine this kind of configuration be set on the projectconfig resource.

## Problem statement

Organizations and teams often require development of their services and products to halt during critical hours. For example, an organization might want to freeze all production code during christmas to avoid incidents. Or a team wants to disallow pushing code during weekends.

## Policies

As kargo administrators we should be able to enforce certain policies company wide. One should be able to handle, without developer interaction, add/modify/remove a time window for promotions for all projects. If the organization decides that all production pipelines are to be halted during holiday a kargo admin should be able to change a configuration from one location to do so.

A team should also be able to decide on their own time windows. Not all teams work in the same timezone, have the same workflow, or working procedure.

## ClusterPromotionWindow and PromotionWindow

To allow for administration, we could introduce a new CRD `ClusterPromotionWindow`. This CRD would define time windows for all matching stages, warehouses, etc. in which the window should apply.

Example `ClusterPromotionWindow` CRD:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionWindow
metadata:
  name: allow-weekend
spec:
  - kind: "allow"
    schedule: "0 0 * * 1-5"
    duration: "24h"
    timeZone: "Europe/xxx"
    projectSelector:
      matchLabels:
        env: dev
    stageSelector:
      matchLabels:
        env: dev
    warehouseSelector:
      matchLabels:
        env: dev
  - kind: "deny"
     ...
```

The `ClusterPromotionWindow` CRD above is inspired from [ArgoCD sync windows](https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/).  It sets a specific time window in which promotion is allowed or denied. A kargo admin in this case would easily be able to select projects, stages and warehouses which should be affected by the time window. The selection of stages and warehouses should only be selected from those that match the projectSelector labels.

In the `ProjectConfig` we could also allow for teams to define their own time windows. For example

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: my-project
  namespace: my-project
spec:
  promotionPolicies:
  - stageSelector:
      name: automation-window-test
    autoPromotionEnabled: true
    promotionWindows:
    # option 1, define the config of the windows directly
    - kind: "allow"
      schedule: "0 0 * * 1-5"
      duration: "24h"
      timeZone: "Europe/xxx"
    # options 2, for ease of both readability and reuse of clusterpromotionwindows, we reference CRDs.
    # Maybe allow for referencing ClusterPromotionWindow, even though the projectSelector does not include the project?
    - kind: ClusterPromotionWindow
      name: allow-weekend
   - kind: PromotionWindow
     name: deny-holidays
```

## Edit

@krancour I closed my PR, as I see this is now `maintainer-only`.

I added some of my thoughts on the matter this evening. Bit tired, so hopefully this will still make sense the next time I read it.

Anyways, this is just for getting some discussion going 👍
