### ISSUE TITLE
Controller is crashing with: "Error starting rollouts manager"

### ISSUE THREAD

**Issue by Brightside56** [akuity/kargo#1334]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

kargo-controller pod is crashloopbackoff-ing shortly after start

# Steps to Reproduce

Just install Kargo 0.3.0 using Helm without installed Argo Rollouts and wait a bit (most probably)

# Version

```
{
  "Version": "v0.3.0",
  "BuildDate": "2023-12-22T22:31:02Z",
  "GitCommit": "882617be74f0d6c09647e276ca52d545824c5ac8",
  "GitTreeDirty": false,
  "GoVersion": "go1.21.5",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```
# Logs

```
time="2023-12-25T00:45:32Z" level=error msg="error starting rollouts manager: failed to wait for analysisrun caches to sync: timed out waiting for cache to be synced"
```

**Comment by geowalrus4gh** [comment]
+1 for this issue

**Comment by moensch** [comment]
For those looking for a workaround, here's how you can apply the Rollouts CRDs and the Kargo helm chart in one go:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-rollouts///manifests/crds?ref=v1.6.4

helmCharts:
- name: kargo
  includeCRDs: true
  valuesInline:
    api:
      adminAccount:
        password: foo
        tokenSigningKey: bar
  releaseName: kargo
  version: 0.3.0
  repo: oci://ghcr.io/akuity/kargo-charts
```

And then run with `kustomize build --enable-helm`
