### ISSUE TITLE
Support of path filtering/monorepos when rendering

### ISSUE THREAD

**Issue by Brightside56** [akuity/kargo#1335]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature

I would like to see a monorepo support (which could be implemented via possibility to perform path filtering when rendering to env. branches)

# Motivation

I would like to have a monorepo with multiple microservices, like
```
svc-1
svc-2
svc-3
```
and those microservices are supposed to be separate pipelines in Kargo and promoted using rendering to env. branches. Currently Kargo is able to invoke kargo-render which is rendering contents of whole branch according definition in `kargo-render.yaml`. Kargo-render.yaml contains definition for rendering of all microservices in a repo, therefore in case of svc-1 promotion kargo-render will render manifests also for svc-2 or vice versa. Possibility to filter/specify and pass to kargo-render path (of source manifests) for rendering will make possible work with multiple services in single repository

# Suggested Implementation

1. kargo-render.yaml spec has fields like `configManagement.path` or `appConfig.<name>` which could be utilized. Kargo could pass application name to kargo-render and kargo-render could thus determine the path for rendering
2. This can be configurable as part of `gitRepoUpdates.render`

**Comment by krancour** [comment]
@Brightside56 you may need to take a closer look at Kargo Render, because there is already adequate flexibility in the `kargo-render.yaml` file to enable what you're asking for.

Here's an example:

```
configVersion: v1alpha1
branchConfigs:
- pattern: svc-1/stage/(\w+)
  appConfigs:
    svc-1:
      configManagement:
        kustomize:
          path: svc-1/stage/${1}
      outputPath: svc-1
- pattern: svc-2/stage/(\w+)
  appConfigs:
    svc-2:
      configManagement:
        kustomize:
          path: svc-2/stage/${1}
      outputPath: svc-2
```

**Comment by Brightside56** [comment]
@krancour flexibility from my point of view is something what allows user to decide how to organize his/her gitops-repo. Example above is more like workaround, which assumes that I need to have a branch prefix for each service for each stage and prescribes me how things should be organized. I wouldn't like to have hundreds of branches in my monorepo. If kargo-render spec contains appConfigs including path in repo, why just not use it and let user decide how to organize his/her repo? I would like to have branch per stage with multiple services for this stage and not branch per service/stage

**Comment by krancour** [comment]
@Brightside56 I again invite you to take a closer look because there is nothing opinionated about how your repo is organized. Organize it however you like.

Kargo Render's config allows you to spell out the rules for how to construct each branch, either using the branch's explicit name or by matching it to a pattern.

I'm not sure if my use of pattern matching is what's throwing you off here?

The following is equally valid:

```
configVersion: v1alpha1
branchConfigs:
- name: my-weird-branch
  appConfigs:
    svc-1:
      configManagement:
        kustomize:
          path: any/path/i/want
      outputPath: any/path
...
```

**Comment by Brightside56** [comment]
@krancour I'm trying to have following config
```
configVersion: v1alpha1
branchConfigs:
- name: my-weird-branch
  appConfigs:
    svc-1:
      configManagement:
        kustomize:
          path: svc-1
      outputPath: svc-1
    svc-2:
      configManagement:
        kustomize:
          path: svc-2
      outputPath: svc-2
...
```
where `svc-1` and `svc-2` are my apps with respective Kargo pipelines and `my-weird-branch` is stage for those pipelines. I would like to have a possibility to render svc-1 independently from svc-2, but if svc-1 and svc-2 are in same branch, kargo-render can only render whole branch, therefore any render of `svc-1` will lead to render of `svc-2`
```
/ $ kargo-render render --help
Render environment-specific manifests into an environment-specific branch of the remote gitops repo

Usage:
  kargo-render render [flags]

Flags:
      --allow-empty             allow the rendered manifests to be empty; if false this is disallowed as a safeguard against scenarios where a bug of any kind might otherwise cause Kargo Render to wipe out the contents of the target branch in error
  -m, --commit-message string   specify a custom message to be used for the commit to the target branch
  -d, --debug                   display debug output
  -h, --help                    help for render
  -i, --image stringArray       specify a new image to apply to the final result (this flag may be used more than once)
  -o, --output string           specify a format for command output (json or yaml)
  -R, --ref string              specify a branch or a precise commit to render from; if this is not provided, Kargo Render renders from the head of the default branch
  -r, --repo string             the URL of a remote gitops repo (required)
  -p, --repo-password string    password or token for reading from and writing to the remote gitops repo (required; can also be set using the KARGO_RENDER_REPO_PASSWORD environment variable)
  -u, --repo-username string    username for reading from and writing to the remote gitops repo (required; can also be set using the KARGO_RENDER_REPO_USERNAME environment variable)
  -t, --target-branch string    the environment-specific branch to render manifests into (required)
```
