### ISSUE TITLE
UI issue when multiple subscriptions

### ISSUE THREAD

**Issue by geowalrus4gh** [akuity/kargo#1337]
# Description

When I use multiple subscriptions, the UI has an overflow issue. Please see screenshot below

The warehouse sample as follows.
 ```
  kind: Warehouse
  metadata:
    name: kargo-demo
    namespace: kargo-demo
  spec:
    subscriptions:
    - image:
        repoURL: xyz/kargo-demo-app
        semverConstraint: ^0
    - image:
        repoURL: xyz/kargo-show-app
        semverConstraint: ^0
    - git:
        repoURL: https://github.com/xyz/kargo-demo-deploy.git
```

# Screenshots

![image](https://github.com/akuity/kargo/assets/33422391/2ac52d9d-c594-40c8-a618-0ed1749df7aa)

# Version

```
0.3.0
```

# Logs

```
No logs
```
