### ISSUE TITLE
Support sync option Replace=true

### ISSUE THREAD

**Issue by zbialik** [akuity/kargo#1338]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I have a kargo stage/warehouse setup such that whenever a new chart version is published to a helm repo, kargo will update the chart version defined for a dependent chart in a GitOps repo. The helm chart I am playing with just creates a `ConfigMap` object that used the chart version as part of it's name, which warrants the `Replace=true` `syncOption` for the argocd `Application`.

Upon publishing the new chart version in my helm repo, Kargo successfully updated the chart version in my GitOps repo and performed the sync of the `Application`. However, it did not perform the sync with `Replace=true`. 

I think Kargo should respect the `Replace=true` `syncOption` defined on the ArgoCD `Application`.

**NOTE**:
- I think this maybe was supposed to be fixed in #873 but I just experienced this with `v0.3.0`.

# Screenshots
<img width="1328" alt="Screenshot 2023-12-27 at 1 42 46 PM" src="https://github.com/akuity/kargo/assets/42648195/971c8fb2-3d30-42db-9c33-4abdb7a731c0">

# Steps to Reproduce

1. create ArgoCD `Application` like so:
    ```
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      annotations:
        kargo.akuity.io/authorized-stage: kargo-homelab:test-kargo-promotion-dev
      name: test-kargo-promotion
      namespace: argocd
    spec:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: ${GITOPS_REPO_URL}
        path: path/to/chart
        targetRevision: HEAD
      syncPolicy:
        syncOptions:
          - Replace=true
    ```
1. In the GitOps repo, define a `Chart.yaml` at `path/to/chart` with the following contents:
    ```
    apiVersion: v2
    name: test-kargo-promotion
    type: application
    version: 0.1.0
    dependencies:
      - name: "test-kargo-promotion"
        version: 0.1.1 # this chart version should already be available
        repository: ${HELM_REPO_URL}
    ```
1. Define the following kargo manifests:
    ```
    apiVersion: kargo.akuity.io/v1alpha1
    kind: PromotionPolicy
    metadata:
      name: test-kargo-promotion-dev
    stage: test-kargo-promotion-dev
    enableAutoPromotion: true
    ---
    apiVersion: kargo.akuity.io/v1alpha1
    kind: Stage
    metadata:
      name: test-kargo-promotion-dev
    spec:
      subscriptions:
        warehouse: test-kargo-promotion
      promotionMechanisms:
        gitRepoUpdates:
        - repoURL: ${GITOPS_REPO_URL}
          readBranch: main
          writeBranch: main
          helm:
            charts:
            - chartPath: path/to/chart
              name: test-kargo-promotion
              registryURL: ${HELM_REPO_URL}
        argoCDAppUpdates:
        - appName: test-kargo-promotion
          appNamespace: argocd
    ---
    apiVersion: kargo.akuity.io/v1alpha1
    kind: Warehouse
    metadata:
      name: test-kargo-promotion
    spec:
      subscriptions:
      - chart:
          name: test-kargo-promotion
          registryURL: ${HELM_REPO_URL}
          semverConstraint: ^0
    ```
1. publish a new upgraded chart version (0.1.2 will suffice)
1. wait for Kargo to update GitOps repo's Chart.yaml with new dependency chart version set.
1. confirm ArgoCD application stuck Out of Sync because sync was performed without `Replace=true`.

# Version

```
v0.3.0
```

# Logs

```
time="2023-12-27T21:30:46Z" level=info msg="began promotion" freight=5937b48b3b989a02038150cef0a1e8ab7e5328e3 namespace=kargo-homelab promotion=test-kargo-promotion-dev.01hjpjzs3ajkpvqxgrhn2yr50z.5937b48 stage=test-kargo-promotion-dev
time="2023-12-27T21:30:50Z" level=info msg="promotion Succeeded" freight=5937b48b3b989a02038150cef0a1e8ab7e5328e3 namespace=kargo-homelab promotion=test-kargo-promotion-dev.01hjpjzs3ajkpvqxgrhn2yr50z.5937b48 stage=test-kargo-promotion-dev
```
