### ISSUE TITLE
Support of rendering to another repository

### ISSUE THREAD

**Issue by dan1el-k** [akuity/kargo#1354]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Rendering to a another repository. (Service Repo concept)

# Motivation

As of version `0.3.0` kargo, just supports rendering in branches of the same repository as the source `helm` or `kustomize` files exists.

This is fine and supported for:
- Single application repos: containing manifests of one application
- Mono application repos: containing manifests of multiple application within the same repository. Those could be rendered in to a Stage branch in multiple subfolder

What I would like to have is the support of:
- Service repos: repo for the Business service, containing all the kargo deployment objects for this project, and which is used as `Rendered Target` and furthermore as deployment source for ArgoCD. 
To bundle multiple application rendered manifests in one repo, however having the original manifests still in separate repos.

With that, this `Service repo`could be a pure pipeline/infrastructure repo with no manual changes need after setup, and the `application repos`(multiple, one for each microservice) are used as a source and working repo for the team/engineers.

# Suggested Implementation

Support of following new parameters

- `readRepoURL`: currently `repoURL`, mandatory
- `readBranch`: optional as of now
- `writeBranch`: optional as of now
- `writeRepoURL`: **optional, new**

Full example
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-demo-service
spec:
  subscriptions:
    warehouse: demo-kustomize
  promotionMechanisms:
    gitRepoUpdates:
    - readRepoURL: https://gh-enterprise.com/my-org/kargo-demo-kustomize
      readBranch: main
      writeRepoURL: https://gh-enterprise.com/my-org/kargo-demo-service
      writeBranch: stage/dev
      render:
        images:
        - image: artifacts.my-comp/docker/my-org/cortex-template-kustomize-application/nginx
```
