### ISSUE TITLE
Predefined ServiceAccounts to improve SSO/RBAC UX

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1368]
# Proposed Feature

One of the first things people should do with their Kargo instance is to configure SSO and stop using the built-in admin user. It will be common for orgs to have SSO user(s) that is equivalent to the admin user. Today, this process is:

1. GLOBAL_SERVICE_ACCOUNT_NAMESPACES: kargo
2. create a `kargo-admin` ServiceAccount
3. create `kargo-admin` ClusterRoleBinding to `kargo-api` ClusterRole
4. annotate kargo-admin ServiceAccount with a SSO annotations

I feel that Kargo Helm chart should have a convenience option to do 1-3 out of the box to reduce the upfront steps and have a standard ServiceAccount that we could refer to in docs.

In addition, we could introduce a `kargo-viewer` built-in ServiceAccount and ClusterRole/ClusterRoleBinding, that is ready to be annotated for giving readonly access to SSO users.

# Motivation

Getting started will be easier.

# Suggested Implementation

Simply vend these resources in our Helm chart, with a helm values option for additional annotations.

**Comment by jessesuen** [comment]
This is what the convenience option would do:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-api
  namespace: kargo
data:
  GLOBAL_SERVICE_ACCOUNT_NAMESPACES: kargo

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    rbac.kargo.akuity.io/groups: mydevopsgroup
  name: kargo-admin
  namespace: kargo

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-api
subjects:
- kind: ServiceAccount
  name: kargo-admin
  namespace: kargo
```
