### ISSUE TITLE
bug: Global Credentials require authorized-projects and argocd repo-type

### ISSUE THREAD

**Issue by moensch** [akuity/kargo#1373]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

In my testing I found that an image repo credential is only loaded from the global credentials namespace if **both** of the following are true:
* It has the `argocd.argoproj.io/secret-type: repo-creds` label
* The requesting project is in the `kargo.akuity.io/authorized-projects` annotation

# Screenshots

# Steps to Reproduce

Create a `Secret` in the `kargo` namespace like so:
```yaml
apiVersion: v1
stringData:
  name: foo
  password: bar
  type: image
  url: 1234567890.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
kind: Secret
type: Opaque
metadata:
  labels:
    kargo.akuity.io/secret-type: repo-creds
  name: ecr-image-registry-us-east-1
  namespace: kargo
```
Ensure `kargo-controller` ConfigMap has:
```
GLOBAL_CREDENTIALS_NAMESPACES":"kargo"
```

Restart controller

## Expected result
repo-creds should be loaded

## Actual Result
repo-creds are not loaded

# Workaround/fix
I **can** get this to work, but I must do the following:
* Add a matching `kargo.akuity.io/authorized-projects` annotation
* Add the `argocd.argoproj.io/secret-type: repo-creds` label (despite this secret not being borrowed from Argo CD)
* 
# Version

Running `0.3.0` - clean build

# Logs

```
level=debug msg="found no credentials for image repo" namespace=ssuter-test-service repo=1234567890.dkr.ecr.us-east-1.amazonaws.com/ssuter-test-service warehouse=ssuter-test-service
```
