### ISSUE TITLE
Support ROLLOUTS_INSTANCE_ID when creating AnalysisRuns

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1442]
# Proposed Feature

When creating AnalysisRuns, the kargo controller should have the option to label that AnalysisRun with the `controller-instance-id` label supported in Argo Rollouts. e.g.

```yaml
metadata:
  labels:
    argo-rollouts.argoproj.io/controller-instance-id: foo
```

# Motivation

There may be multiple argo rollouts controllers acting on a cluster for different purposes (e.g. shard). The instance-id option allows them to co-exist.

# Suggested Implementation

Introduce `ROLLOUTS_INSTANCE_ID` env var. When set, then the AnalysisRun `argo-rollouts.argoproj.io/controller-instance-id` label will be set with that value.
