### ISSUE TITLE
Stages with shared Warehouse subscription cause duplicated Warehouse and duplicated Warehouse Subscriptions pointing to one Stage.

### ISSUE THREAD

**Issue by JanGrosse** [akuity/kargo#1468]
# Checklist

* [ x] I've searched the issue queue to verify this is not a duplicate bug report.
* [ x] I've included steps to reproduce the bug.
* [ x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

Hello,

when trying to reuse the same Warehouse on multiple Stages it displays the same Warehouse twice (one attached on each Stage) but the Subscriptions for the Warehouse are also duplicated but only attached to a single Warehouse.

What I hoped to achieve was that both Stages point to the same single Warehouse & Subscription. 
Or maybe show the Warehouse duplicated attached to each Stage having its own Subsription.

# Screenshots

Here is a screenshot how this example looks like

![kargo-example](https://github.com/akuity/kargo/assets/25822756/1157a18e-fedb-4b31-b7bf-20d26d43e914)

And here a drawing how I would have hoped it to look like

![example-kargo drawio](https://github.com/akuity/kargo/assets/25822756/998a6020-df36-415e-81d1-453b7b2b91c0)

# Steps to Reproduce

1. Create a Warehouse
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: example-warehouse
spec:
  subscriptions:
  - git:
      repoURL: https://mygiturl
```

2. Add two Stages, both subscribing to the same Warehouse

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: example-1
spec:
  promotionMechanisms:
    gitRepoUpdates:
    - render: {}
      repoURL: https://mygiturl
      writeBranch: env/example1
  subscriptions:
    warehouse: example-warehouse
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: example-2
spec:
  promotionMechanisms:
    gitRepoUpdates:
    - render: {}
      repoURL: https://mygiturl
      writeBranch: env/example2
  subscriptions:
    warehouse: example-warehouse
``` 

# Version

```
0.3.2
```

# Logs

```
Paste any relevant application logs here.
```
