### ISSUE TITLE
`kustomize edit set image` should not set `newName`

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1476]
# Description

When Kargo sets an image in the kustomization.yaml as part of image promotion, it will add `newName`, even though the newName is the same as name. e.g.:

```yaml
images:
- name: ghcr.io/jessesuen/guestbook
  newName: ghcr.io/jessesuen/guestbook # << not desirable
  newTag: 0.2.0
```

This is because kargo runs:

```
kustomize edit set image ghcr.io/jessesuen/guestbook=ghcr.io/jessesuen/guestbook:0.2.0
```

Instead of that command, kargo should run the following:

```
kustomize edit set image ghcr.io/jessesuen/guestbook:0.2.0
```

Fix would go here:
https://github.com/akuity/kargo/blob/main/internal/kustomize/kustomize.go#L18-L28

# Version

0.3.0
