### ISSUE TITLE
Merge commit promotion strategy

### ISSUE THREAD

**Issue by theseanything** [akuity/kargo#1497]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.

# Proposed Feature

A promotion strategy for writing values back to git where a promotion branch is based off a target branch (e.g. main), changes committed to the promotions branch, then the promotion branch is merged into the target branch. 

This would follow a similar (if not the same) process that occurs for [PR based promotion](https://github.com/akuity/kargo/blob/14974eb211840196e1fe126bfbbe54ad83e2e0a5/internal/controller/promotion/pullrequest.go#L21), except instead of raising a PR, the commit is just directly merged.

An example of the logic can be found in [this script](https://github.com/alphagov/govuk-helm-charts/blob/main/charts/argo-services/scripts/update-image-tag.sh).

# Motivation

This would be helpful for the use case whereby, the gitops set up is a single branch (main) as the source truth and different helm values files are configured for each environment. 

Making commits directly on the same branch (e.g. main) isn't possible as there's no way to co-ordinate concurrent changes (e.g. from either multiple promotions occurring at the same time or someone committing to it externally). Failures occur as the branch can become out of sync in between checking out the branch and the committing the changes. Using a separate promotion branch and merging changes helps mitigate against contention.

# Suggested Implementation

This could be implemented as an option for PR based promotion. Instead of opening a PR, Kargo could merge the branch instead.

**Comment by krancour** [comment]
Hi @theseanything! Thanks for the request!

Without summarily ruling this out, I'll mention there are some difficulties with what you've proposed. The problem actually has less to do with the idea of merge commits and much more to do with some general problems that result from making all Applications read configuration from the same branch. It may work okay-ish for specific cases, but it doesn't generalize.

An example where it sort of works:

If you were using Kargo as a glorified [Image Updater](https://argocd-image-updater.readthedocs.io/en/stable/) (i.e. your Warehouse doesn't subscribe to a Git repo and _only_ subscribes to an image repo), then you could get away with something like this because, at each Stage, promotion would _only_ involve updating the tag or digest referenced by a Stage-specific values file. i.e. You're not updating anything that's _shared_ between Stages. For any given Stage, you could therefore flip back and forth all day long between image version A and image version B and never affect any other Stage in the process. Obviously, your Applications do still share the chart's templates and default values, but in this scenario, Kargo isn't tasked with coordinating changes to those. If this were your use case, I think you can actually use Kargo just as it is.

But as I said, it doesn't generalize well...

Using Kargo as a mere Image Updater replacement isn't the common case. The common case would have your warehouse subscribed not _only_ to an image repository, but also to your Git repository. i.e. In this case, Kargo is tasked with coordinating more than just images. It's tasked also with coordinating _all_ configuration changes...

So here's the rub: If your Stages are mutually dependent on the same chart templates and the same default chart values, and your Applications all point at the same branch, then it becomes impossible to promote a change affecting the templates or default values into one Stage without inadvertently affecting all the others.

We have for, some time, been promoting the branch-per-Stage model because isolating each Stage's configuration to its own branch provides a strong guarantee that changes to one Stage are likewise isolated to that Stage only. Models that use just a single branch as the source of truth cannot offer any such guarantee, except in the simplest case described earlier.

Admittedly, this is all difficult to wrap one's head around. (It's difficult to explain, also!) Happy to discuss further.

**Comment by theseanything** [comment]
Thanks for explaining @krancour, makes sense! The primary motivation for this feature is to solve contention between concurrent changes being made to a branch. Agree with the points you make about the branch-per-stage model, though for our setup having a single branch with config differences in separate files is working well for us.

Kargo’s feature set addresses the majority of our needs (e.g. verifications, manual promotions… etc), whereas I think Image Updater doesn’t extend beyond a single environment. Would be great to take advantage of Kargo even if the use case is slightly outside the assumed gitops model and I think this feature wouldn't impede on the branch-per-stage model.

Also, I do understand not wanting feature bloat. Noticed extensible promotion mechanisms is on [the roadmap](https://kargo.akuity.io/roadmap#v050), which could solve this. The reason I’d suggested this as an in-built promotion mechanism was due to the existing PR based promotions. My understanding is that a PR based promotion follows almost the same logic, except raises a PR instead of just merging the branch - so maybe could integrate with that(?).   

Thanks again for your reply! It’d be great if the project was open such a feature still, or this is one to wait for [user defined promotion mechanisms](https://github.com/akuity/kargo/issues/862).

**Comment by theseanything** [comment]
Ah - I think I don't quite understand how this model would work if Kargo was _just_ updating images tags. (i.e. warehouse only subscribed to an image repository).

If ArgoCD is using main branch as the targetRevision - it'll miss the updating image tags in the stage branches.
If ArgoCD is using a stage branch as the targetRevision, then config changes in main won't be applied.

(I assume Kargo won't automatically apply changes in main to the stage branch - because it's not subscribed to the git repository?)

So the only way I see this working, is if you have ArgoCD reading from main and have Kargo writing back to main.

Let me know if I've gotten the wrong end of the stick!

**Comment by krancour** [comment]
> I think I don't quite understand how this model would work if Kargo was just updating images tags.

I mentioned a few messages back:

> An example where it sort of works:

I think that example covers your case. The "sort of" part is simply that Kargo will only be capable of moving _images_ through the pipeline. Your config is just _always_ going to be what's at the head of main and Kargo won't ever progress or roll back those changes.

Here's how you'd define your warehouse and stages in this case:

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: demo
  namespace: demo
spec:
  subscriptions:
  - image:
      repoURL: some/image
      semverConstraint: ^1.0.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: demo
spec:
  subscriptions:
    warehouse: demo
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/some/repo.git
      readBranch: main
      writeBranch: main
      helm:
        images:
        - image: some/image
          valuesFilePath: charts/demo/values.test.yaml
          key: image.tag
          value: Tag
    argoCDAppUpdates:
    - appName: demo-test
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: demo
spec:
  subscriptions:
    upstreamStages:
    - name: test
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/some/repo.git
      readBranch: main
      writeBranch: main
      helm:
        images:
        - image: some/image
          valuesFilePath: charts/demo/values.uat.yaml
          key: image.tag
          value: Tag
    argoCDAppUpdates:
    - appName: demo-uat
---
# etc.
```

This says, at each stage, read what's at the head of `main`, update the value of `image.tag` in `charts/demo/values.<stage>.yaml` with the `some/image` from the Freight, write it back to `main`, and prompt the Argo CD `Application` to refresh and sync.
