### ISSUE TITLE
UI: Freight Image-Tags hardly readable after with long tag names

### ISSUE THREAD

**Issue by MPritsch** [akuity/kargo#1527]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.

# Description

When using longer image-tag names, the selectable freights do not display the image-tag name properly. I know that there has to be some kind of limitation to the size, but if the freight was configurable to scale with the tag-name it would help us a lot. I'm open to suggestions on how this could be mitigated.

Currently we fetch the versions of our maven pom.xml and add a release-candidate tag to iterate over it. That means we also get the typical `SNAPSHOT` suffix from maven. With this version we tag our images and karge watches for the tag structure. E.g. `0.6.1-SNAPSHOT-rc1`

With more time these names will get longer and be even harder to read in the small freight view. You could try with a `1234.5678.9123-SNAPSHOT-rc1234` Version and see what happens.

I'm not sure if this feature-requests already covers it? https://github.com/akuity/kargo/issues/1430

And I think this pull-request might already change the behaviour, although I know not much about frontends https://github.com/akuity/kargo/pull/1510

# Screenshots

Here are the boxes like they list the image-tags now. Currently there is no way to differentiate `0.6.1-SNAPSHOT-rc1` from `0.6.1-rc2` in the freight-view besides scrolling down on each box:
![kargo-tag-cut](https://github.com/akuity/kargo/assets/15358778/fa27b536-58ad-4dd0-8dc1-ec7abe8ea796)

When selecting a single freight it is a bit better, since the field is bigger, but still not great.
![kargo-tag-cut-selected](https://github.com/akuity/kargo/assets/15358778/a022bfbf-5243-4c29-9b65-810edf7880b5)

# Steps to Reproduce

Create a few freights with long tag names. E.g.
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
commits:
  - id: b61ad0a3b216bbe9efd66207d3274cfbfaee261d
    message: 'fix: commit message'
    repoURL: >-
      https://gitlab.com/path/to/my/repo
images:
  - digest: sha256:98ae8a8009441ade8b96bb6f9356430bd89ae142c4260988e5b925d35a9c18b3
    repoURL: >-
      https://gitlab.com/path/to/my/repo/image
    tag: 0.6.0-SNAPSHOT-rc1
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
commits:
  - id: b61ad0a3b216bbe9efd66207d3274cfbfaee261d
    message: 'fix: commit message'
    repoURL: >-
      https://gitlab.com/path/to/my/repo
images:
  - digest: sha256:98ae8a8009441ade8b96bb6f9356430bd89ae142c4260988e5b925d35a9c18b3
    repoURL: >-
      https://gitlab.com/path/to/my/repo/image
    tag: 0.6.0-SNAPSHOT-rc2
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Freight
commits:
  - id: b61ad0a3b216bbe9efd66207d3274cfbfaee261d
    message: 'fix: commit message'
    repoURL: >-
      https://gitlab.com/path/to/my/repo
images:
  - digest: sha256:98ae8a8009441ade8b96bb6f9356430bd89ae142c4260988e5b925d35a9c18b3
    repoURL: >-
      https://gitlab.com/path/to/my/repo/image
    tag: 0.6.1-SNAPSHOT-rc3
```

# Version
kargo is from the wolfi packages here: https://github.com/wolfi-dev/os/blob/df0bb04cb3c656d7181bbceb660cec5aa6d087f1/kargo.yaml
So the output of "kargo version" is just go build meta-information:
```
{
  "Version": "devel+07d91a1.dirty",
  "BuildDate": "1970-01-01T00:00:00Z",
  "GitCommit": "07d91a10f3d082ebcb22585f25dae16abd510709",
  "GitTreeDirty": true,
  "GoVersion": "go1.22.0",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

Just use version `0.4.0` from your own repository or install the wolfi version in a wolfi-base image via `apk update && apk add kargo-0.4.0-r0`
