### ISSUE TITLE
CLI for managing credentials

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1531]
# Proposed Feature

This is the CLI equivalent to https://github.com/akuity/kargo/issues/1444

# Motivation

For all the same reasons in https://github.com/akuity/kargo/issues/1444

Currently, inputting a credential is a bit painful. They can do this today, but it requires knowledge of the Secret format. e.g.:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: github-creds
  namespace: kargo-simple
  labels:
    kargo.akuity.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/akuity/kargo-simple.git
  username: username
  password: github_pat_REPLACEME
```

A convenience CLI option would be useful

```
kargo credentials add \
    --project my-project \
    --type repository \
    --url https://github.com/akuity/kargo-simple.git \
    --username jessesuen
```

It should then prompt from stdin, or accept pipes.
