### ISSUE TITLE
Unsynced ressources forever with ArgoCd

### ISSUE THREAD

**Issue by stephaneetje** [akuity/kargo#1549]
Since version 0.4.0 of the chart, argocd sees some changes that never can be made, and kargo remains OutOfSync forever.
Here is the screenshot with the concerned ressources 

<img width="1148" alt="Capture d’écran 2024-02-28 à 10 23 18" src="https://github.com/akuity/kargo/assets/73826402/15f833f7-3c58-4af4-86e8-e6495ed82d66">

**Comment by krancour** [comment]
@stephaneetje that's not a lot of information to go on. Do you have an error message?

**Comment by stephaneetje** [comment]
I don't have any error message, if i modify manually the ressources for the requested change with `name: kargo...` with kubectl , it saves successfuly but automaticaly delete the entry, so no error.

**Comment by stephaneetje** [comment]
With latest version, the problem is still here only for the 2 cluster roles :

<img width="1199" alt="Capture d’écran 2024-02-29 à 09 27 08" src="https://github.com/akuity/kargo/assets/73826402/99a43c30-95aa-4eab-bcd1-c6b462974788">

**Comment by krancour** [comment]
Backtracking here to make sure I am clear on the context... you are using Argo CD to manage the installation of Kargo. Is that correct?

> argocd sees some changes that never can be made

There is no explanation for why surfaced anywhere in the Argo CD UI?

**Comment by stephaneetje** [comment]
You perfectly understood! 
I see absolutly no error, it just syncs successfully, but remains outofsync, as if the change gets ignored by kubernetes.

<img width="1278" alt="Capture d’écran 2024-02-29 à 15 28 12" src="https://github.com/akuity/kargo/assets/73826402/7451aaa8-3963-42be-bf27-4d95b0df4edc">

**Comment by stephaneetje** [comment]
You perfectly understood!
I see absolutly no error, it just syncs successfully, but remains outofsync, as if the change gets ignored by kubernetes.

<img width="1207" alt="Capture d’écran 2024-02-29 à 15 30 33" src="https://github.com/akuity/kargo/assets/73826402/737f70fd-611b-4307-a05f-b5d75b5b5e13">

**Comment by krancour** [comment]
Your last sync was to commit b802577. Argo CD is aware of 1190e9f, but _hasn't_ synced to it because you have auto-sync disabled (which is fine). Your original screen shot is showing you what has changed between b802577 and 1190e9f.

All you need to do is click sync.

**Comment by stephaneetje** [comment]
The commit concerns another project on the same repo. I synced it many times, it doesn't change anything, it still wants to make those 3 changes, that get ignored apparently.
I have thousands of apps in argocd and im used to managing it.

**Comment by krancour** [comment]
cc @morey-tech I'm wondering if you might have any insight.

**Comment by morey-tech** [comment]
This is a strange one. 
- The fields trying to be added to the configMap are [expected](https://github.com/akuity/kargo/blob/ab40a6f5a281ea3fcf7b11626ba0431fca6e8fef/charts/kargo/templates/controller/configmap.yaml#L32-L33).
- The name on the rule in the ClusterRole is extra strange, it's not present in [the template](https://github.com/akuity/kargo/blob/ab40a6f5a281ea3fcf7b11626ba0431fca6e8fef/charts/kargo/templates/management-controller/cluster-roles.yaml#L27-L32).

@stephaneetje, can you share the Application manifest used to install Kargo? I'm looking for the exact chart version and values used to reproduce this issue.

**Comment by krancour** [comment]
> The name on the rule in the ClusterRole is extra strange, it's not present in [the template](https://github.com/akuity/kargo/blob/ab40a6f5a281ea3fcf7b11626ba0431fca6e8fef/charts/kargo/templates/management-controller/cluster-roles.yaml#L27-L32).

@morey-tech you just jogged my memory... It's not present in the template _in main_.

That line _is_ in v0.4.x, and it's a mistake... but I've only ever seen it produce a warning at install time... granted I've observed that on a direct `helm install` and not via Argo CD.

**Comment by stephaneetje** [comment]
No problem, here is my `values.yaml` (with some hidden) 

```
kargo:
    controller:
        argocd:
            integrationEnabled: true
    api:
        host: kargo.test.cc
        adminAccount:
            enabled: false
        tls:
            enabled: false
        oidc:
            enabled: true
            issuerURL: https://keycloak.test.cc/realms/argocd
            clientID: argocd-infra
            globalServiceAccounts:
                namespaces:
                    - kargo
            dex:
                enabled: true
                connectors:
                    - id: keycloak
                      name: keycloak
                      type: oidc
                      config:
                        clientID: argocd-infra
                        issuer: https://keycloak.test.cc/realms/argocd
                        clientSecret: xxxxxxxx-xxx-xxxx-xxxx-xxxxxxxxxxxx
                        redirectURI: https://kargo.test.cc/dex/callback
                        getUserInfo: true
                        insecureEnableGroups: true
                        scopes:
                            - openid
                            - profile
                            - email
                            - groups
        argocd:
            urls:
                "": https//argocd-infra.test.cc
        ingress:
            enabled: true
            ingressClassName: nginx
            tls:
                selfSignedCert: false
            annotations:
                cert-manager.io/cluster-issuer: letsencrypt-dns
                external-dns.alpha.kubernetes.io/hostname: kargo.test.cc
```

Here is the `chart.yaml` :

```
apiVersion: v2
name: kargo
version: 1.0.0
dependencies:
- name: kargo
  version: 0.4.2
  repository:  oci://ghcr.io/akuity/kargo-charts
```

**Comment by krancour** [comment]
@stephaneetje I think you're going to have better luck with v0.4.3 -- just released.

**Comment by stephaneetje** [comment]
Perfect, it is fixed for the cluster roles. It just remain the 3 empty entries in kargo-controller cm :

```
GLOBAL_CREDENTIALS_NAMESPACES: ''
ROLLOUTS_ANALYSIS_RUNS_NAMESPACE: ''
ROLLOUTS_CONTROLLER_INSTANCE_ID: ''
```

**Comment by krancour** [comment]
> I'm pretty sure the problem is that you aren't rendering the quotes

It's valid YAML without them and Kubernetes does not require them. I will research whether this is an idiosyncrasy of Argo CD.

**Comment by stephaneetje** [comment]
What i can say is that if i take the rendered yaml, add quotes, its all good.
I dont think it is specific to argocd, applying the yaml directly with kubectl has the same effect.

**Comment by krancour** [comment]
The following yields no errors or warnings:

```
helm template kargo \    
  oci://ghcr.io/akuity/kargo-charts/kargo \
  --namespace kargo \
  --create-namespace \
  --set api.adminAccount.password=admin \
  --set api.adminAccount.tokenSigningKey=iwishtowashmyirishwristwatch --include-crds | kubectl apply -f -
```

**Comment by krancour** [comment]
Ok... using the following, I _can_ reproduce your problem:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
spec:
  project: default
  sources:
  - chart: kargo
    helm:
      parameters:
      - name: api.adminAccount.password
        value: admin
      - name: api.adminAccount.tokenSigningKey
        value: iwishtowashmyirishwristwatch
    repoURL: ghcr.io/akuity/kargo-charts
    targetRevision: 0.4.3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kargo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
```

I have to say this looks like an Argo CD-specific issue.

I did discover, however, that you can force it to sync using the `Replace=true` syncOption.

@jessesuen do you know anything about why Argo CD would be giving any trouble over valid YAML that k8s has no issue with?
