### ISSUE TITLE
Default args not carried over from AnalysisTemplate when creating AnalysisRuns

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1573]
# Description

When Kargo creates an AnalysisRun from an AnalysisTemplate, if the Stage does not "pass" args, then the "default" args as defined in the template will not be used.

e.g., if this is my template:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: test
spec:
  args:
  - name: foo
    value: bar
  metrics:
  - name: test
    provider:
      job:
        spec:
```

And my Stage does not "pass" args, then the AnalysisRun that is created will not have args. e.g.:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  name: dev.01hr6e2hap3be7mfks5qy04jcj.9ed4919
spec:
  metrics:
  - name: test
    provider:
      job:
        spec:
```

In Argo Rollouts, the arg values in the AnalysisTemplate are supposed to act as a "default," and used if the caller does not supply them. See docs:

https://argo-rollouts.readthedocs.io/en/stable/features/analysis/#analysis-template-arguments

# Version

v0.4.1
