### ISSUE TITLE
helm chart error when trying to use using existing secret

### ISSUE THREAD

**Issue by hoopty** [akuity/kargo#1635]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When deploying kargo with helm, and specifying and existing secret in the values file, it is throwing an error.

# Steps to Reproduce

I ran:
```
$helm template ../charts/kargo-0.4.4.tgz -f kargo-values.yaml
Error: execution error at (kargo/templates/api/secret.yaml:14:8): A value MUST be provided for either api.adminAccount.passwordHash or api.adminAccount.password
```

Here's the values file:
```
$cat kargo-values.yaml 
# https://github.com/akuity/kargo/blob/main/charts/kargo/values.yaml
api:
  # adminAccount:
  #   password: test
  #   tokenSigningKey: test

  secret:
    name: "kargo-api"
```

Note: using image `ghcr.io/akuity/kargo-charts/kargo:0.4.4`
