### ISSUE TITLE
Kargo CLI should allow setting promotionpolicies when creating a Project

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#1698]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

I am able to create a project with `kargo create project kargo-demo` ...however  I still need to provide further configuration to get other settings.

Example being promotionPolices

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
spec:
  promotionPolicies:
  - stage: dev
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
```

Although declarative configuration is the preferred method, it would still be nice to be able to be able to do it imperatively.

# Motivation

Usually someone needs to create a Project before creating the credentials (chicken/egg), even if they will store the configurations declaratively 

# Suggested Implementation

Since `promotionPolices` can be tricky to write an intuitive CLI against...I would recommend looking at `kubectl create role` and `kubectl create clusterrole` as users would probably be used to that type of syntax

example (off the top of my head)

`kargo create promotionPolicy dev --auto-promote=true --project  kargo-demo`

Or, if we want to leave it in the `project` subcommand

`kargo create project  kargo-demo --promotion-policy=dev --promotion-autopromote=dev:true --promotion-policy=uat  --promotion-autopromote=uat:true`

Just ideas, I'm completely open to any implementation that makes sense.

**Comment by krancour** [comment]
I am somewhat opposed to this for a few reasons:

* Policies are almost guaranteed to grow in complexity over time. There are a number of open issues that are likely to be addressed through new policy fields -- for instance specifying, "freeze" or "blackout" windows where promotions do not occur. Projects are likely to eventually have more properties than just PromotionPolicies as well. It will be a burden to keep the CLI up to date with all those options, which segues into the next reason...

* Beyond a certain degree of complexity, doing things imperatively just does not make sense anymore. Your `kubectl create role` example may feel reasonable on some level, but only because `Role` resources are relatively simple. Look at `kubectl create deployment` and you will notice two things: The number of flags is absolutely dizzying and even with all of those options available, there are _still_ things you can only do declaratively. One wonders why they bothered with all those flags.

* > Usually someone needs to create a Project before creating the credentials (chicken/egg), even if they will store the configurations declaratively

  This isn't so much of a problem as you might think.
  
  Taking Kargo out of the equation and speaking about out-of-the-box Kubernetes resources, something similar goes on with namespaces. If you're declaring a namespace and a bunch of resources that _belong_ in that namespace, you have the following options, both of which are fairly well-established conventions that Kubernetes respects:

    * Put all the resources in a single file, with the namespace(s) preceding everything else.
    * When dealing with multiple files, use naming conventions (like prefixing certain files with `_`) to create an implied ordering, with namespaces first.
    
    In either case, Kubernetes will create resources in the desired order. These same strategies work with Projects, and in fact, we were quite careful to ensure that. I've observed 100% success rate with the following:
   
__`my-project.yaml`:__
   
  ```yaml
  apiVersion: kargo.akuity.io/v1alpha1
  kind: Project
  metadata:
    name: kargo-demo
  spec:
    promotionPolicies:
    # ...
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    namespace: kargo-demo
    # ...
  # ...
  ---
  apiVersion: kargo.akuity.io/v1alpha1
  kind: Warehouse
  metadata:
    namespace: kargo-demo
    # ...
  # ...
  ---
  apiVersion: kargo.akuity.io/v1alpha1
  kind: Stage
  metadata:
    namespace: kargo-demo
    # ...
  # ...
  ---
  # ...
  ```

  ```shell
  $ kargo create -f myproject.yaml
  ```

I'll leave the final decision up to @jessesuen, however.
