### ISSUE TITLE
Add more file path matching options in Warehouse Git Subscription includePaths/excludePaths filters

### ISSUE THREAD

**Issue by maksimstankevic** [akuity/kargo#1711]
Now only regexp matching is there, enabled by "regex:/regexp:" prefix in the filter string:

```
spec:
  subscriptions:
  - git:
      branch: helm
      commitSelectionStrategy: NewestFromBranch
      includePaths:
      - regex:.*
```

 in previous discussions we talked about the need for other matching strategies to be added, like bash glob or .gitignore format.

@krancour @hiddeco I would like to start working on this and, for now, add simple-bash-glob type backed by https://pkg.go.dev/path/filepath#Match, enabled by something like a "pattern:" prefix:

```
spec:
  subscriptions:
  - git:
      branch: helm
      commitSelectionStrategy: NewestFromBranch
      includePaths:
      - pattern:charts/chart-name/*
```

wdyt?
