### ISSUE TITLE
add project-level user & permission management

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1731]
Add to:

* API
* UI
* CLI

We need the ability to define Roles and RoleBindings and mappings of OIDC users to ServiceAccounts...

In thinking about how to make this a nice UX that is not complex, I think an abstraction could help, but I'd like some buy-in from @jessesuen on this...

Mapping OIDC users to SAs _is already a binding of sorts_. If a "Kargo role" were an abstraction over a 1:1:1 of SA:RoleBinding:Role it would only require users to define membership (based on OIDC claims) and permissions. Such an object would bind very cleanly to a UI form and eliminate the need to juggle many separate elements.

It would also make for a pleasant UX in the CLI. Examples:

* `kargo create role foo`
* `kargo grant --email kent@example.io --role foo`
* `kargo revoke --email kent@example.io --role foo`
* `kargo grant --group 12345 --role foo`
* `kargo revoke --group 12345 --role foo`
* `kargo grant --verb read --type stage --role foo`
* `kargo revoke --verb read --type stage --role foo`
* `kargo grant --verb promote --type stage --resource prod`
* `kargo revoke --verb promote --type stage --resource prod`

_All of this would reconcile as pure RBAC resources._

**Comment by jessesuen** [comment]
Is the proposal to introduce a CRD that is the abstraction over the 1:1:1 of SA:RoleBinding:Role? Or are you suggesting the API server provides the abstraction?

Given the two options, I hesitate to introduce a CRD to wrap existing objects. Instead, I propose presenting a unified concept at our API layer that makes RBAC easier to reason about and manage.

**Comment by krancour** [comment]
I had been thinking CRD, but the idea of doing it in the API server is another approach we could consider.

For me, the pro of doing it with the CRD was that even if not using the API server and doing everything with `kubectl` or with GitOps, the abstraction would still be available.

However we approach it, I'd like to be able to do _something_ like this (doesn't need to be _exactly_ this):

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Role
metadata:
  name: prod-promoter
  namespace: kargo-demo
users:
  groups:
  - some-oidc-group-claim
  - some-other-oidc-group-claim
rules:
- apiGroups:
  - kargo.akuity.io/v1alpha1
  resources:
  - stages
  resourceNames:
  - prod
  verbs:
  - promote
```

If I'm slinging YAML, having the above reconcile as the following is a significant convenience:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-promoter
  namespace: kargo-demo
  labels:
    rbac.kargo.akuity.io/groups: some-oidc-group-claim,some-other-oidc-group-claim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prod-promoter
  namespace: kargo-demo
rules:
- apiGroups:
  - kargo.akuity.io/v1alpha1
  resources:
  - stages
  resourceNames:
  - prod
  verbs:
  - promote
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prod-promoter
  namespace: akrgo-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prod-promoter
subjects:
- kind: ServiceAccount
  namespace: kargo-demo
  name: prod-promoter
```

And if I'm not slinging YAML directly, the proposed abstraction binds cleanly to a UI form, which negates the need for a much more complex UI for managing SAs, Roles, and RoleBindings as separate things.

Another option is that instead of being a new top-level CRD, this could be a new section of `ProjectSpec`.
