### ISSUE TITLE
Stage YAML editor fails: Object 'Kind' is missing in '{

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#1766]
# Description

See video. Saving a Stage update fails with:

```
parse manifest: error unmarshaling manifest: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{
```

Even after adding the following to the spec before saving,

```yaml
kind: Stage
apiVersion: kargo.akuity.io/v1alpha1
```

The following error happens:

```
admission webhook "stage.kargo.akuity.io" denied the request: json: cannot unmarshal string into Go struct field StageStatus.status.observedGeneration of type int64
```

# Screenshots

https://github.com/akuity/kargo/assets/12677113/d0370b91-f004-490b-9b50-070a0e965f07

# Version

```
v0.5.0
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
Regarding this error:

`admission webhook "stage.kargo.akuity.io" denied the request: json: cannot unmarshal string into Go struct field StageStatus.status.observedGeneration of type int64`

I don't feel like there will ever be a good reason for Kargo API server endpoint to update stage `.status` based on user input.

**Comment by jessesuen** [comment]
This probably can be a backend-only fix, since we could:
1. avoid patching status
2. not care if apiVersion/kind is specified

**Comment by hiddeco** [comment]
> 1. avoid patching status

We do not issue a patch for the status, and providing status data in the YAML would not cause any data to be written. What I think the actual issue is after inspecting the payload request, is that the frontend somehow injects status data with the wrong type:

```yaml
status:
  phase: NotApplicable
  history: []
  observedGeneration: "1" # Should be int
  message: ""
```

If you instead add this to the editor, it will succeed (but the change will not have an effect):

```yaml
status:
  phase: Promoting # Will not be updated
  history: []
  observedGeneration: 1 # Fixes the error
  message: ""
```

> 2. not care if apiVersion/kind is specified

As the edit functionality makes use of the generic `UpdateResource` endpoint, it needs to include GVK information as otherwise the endpoint does not know what resource it should update (see https://github.com/akuity/kargo/blob/release-0.5/internal/api/update_resource_v1alpha1.go#L44-L55).
