### ISSUE TITLE
preview modal for analysistemplates and analysis runs both fail

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#1783]
Both fail with errors similar to the following:

```
Uncaught Error: cannot encode field github.com.akuity.kargo.internal.controller.rollouts.api.v1alpha1.AnalysisRun.spec to JSON: cannot encode field github.com.akuity.kargo.internal.controller.rollouts.api.v1alpha1.AnalysisRunSpec.metrics to JSON: cannot encode field github.com.akuity.kargo.internal.controller.rollouts.api.v1alpha1.Metric.provider to JSON: cannot encode field github.com.akuity.kargo.internal.controller.rollouts.api.v1alpha1.MetricProvider.job to JSON: cannot encode field github.com.akuity.kargo.internal.controller.rollouts.api.v1alpha1.JobMetric.metadata to JSON: cannot encode field k8s.io.apimachinery.pkg.apis.meta.v1.ObjectMeta.creationTimestamp to JSON: invalid date
    writeMessage chunk-6HYTNFIP.js:1350
    toJson chunk-6HYTNFIP.js:149
    AnalysisRunModal analysis-run-modal.tsx:35
    React 18
    batchCalls notifyManager.ts:60
    notifyFn notifyManager.ts:17
    flush notifyManager.ts:72
    flush notifyManager.ts:71
    batchNotifyFn notifyManager.ts:20
    flush notifyManager.ts:70
    setTimeout handler*scheduleFn notifyManager.ts:22
    flush notifyManager.ts:69
    batch notifyManager.ts:36
    dispatch_fn query.ts:601
    setData query.ts:206
    onSuccess query.ts:483
    resolve retryer.ts:103
    promise callback*run retryer.ts:153
    createRetryer retryer.ts:204
    fetch query.ts:469
    executeFetch_fn queryObserver.ts:322
    onSubscribe queryObserver.ts:96
    subscribe subscribable.ts:14
    useBaseQuery useBaseQuery.ts:77
    React 16
    show modal-context.tsx:34
    show use-modal.ts:26
    onClick verifications.tsx:114
    React 
```

**Comment by krancour** [comment]
https://github.com/akuity/kargo/assets/1821014/a329ef95-7cac-4cab-a01a-7199ad07a885

**Comment by krancour** [comment]
Ok.... here's the problem (and why I can reproduce it and @rpelczar could not).

It has to do with my `AnalysisTemplate` -- which is perfectly valid, btw:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo
  namespace: kargo-demo-07
spec:
  metrics:
  - name: test
    provider:
      job:
        metadata:
          annotations:
            foo: bar # annotations defined here will be copied to the Job object
          labels:
            foo: bar # labels defined here will be copied to the Job object
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: alpine:latest
                command:
                - sleep
                - "20"
              restartPolicy: Never
```

The error _isn't_ about `metadata.creationTimestamp`. It's about `spec.metrics[0].provider.job.metadata.creationTimestamp`
