### ISSUE TITLE
Global Configuration in Helm chart

### ISSUE THREAD

**Issue by danielloader** [akuity/kargo#1813]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

A global configuration block akin to the argocd one: https://github.com/argoproj/argo-helm/blob/f42e0e1fd586d48459d99db69e65f2540a5cd209/charts/argo-cd/values.yaml#L38-L149

# Motivation

This is quite... a lot to set to have a global toleration on a node group.

```yaml
api:
  tolerations: 
    - key: "CriticalAddonsOnly"
      operator: "Exists"
  oidc:
    dex:
      tolerations: 
        - key: "CriticalAddonsOnly"
          operator: "Exists"
controller:
  tolerations: 
    - key: "CriticalAddonsOnly"
      operator: "Exists"
managementController:
  tolerations: 
    - key: "CriticalAddonsOnly"
      operator: "Exists"
webhooksServer:
  tolerations: 
    - key: "CriticalAddonsOnly"
      operator: "Exists"
garbageCollector:
  tolerations: 
    - key: "CriticalAddonsOnly"
      operator: "Exists"
```

# Suggested Implementation

Follow the ArgoCD chart and have some things that can be globally set on all pods.
