### ISSUE TITLE
`PromotionInfo` contains duplicate information about the involved Freight

### ISSUE THREAD

**Issue by hiddeco** [akuity/kargo#1929]
Due to #1748 adding the Status of the Promotion to the `PromotionInfo`, and #1721 adding the Freight itself. The `PromotionInfo` now contains a duplicate `FreightReference`, as the Status of the Promotion does _also_ include it.

```yaml
  lastPromotion:
    name: ab-test-a.01hww6gj8ez5zxvgat11g5rtrt.cb03f5a
    freight:
      # ...omitted for brevity
    status:
      phase: Succeeded
      freight:
        name: cb03f5ab8aa44d64fa8680e0ff35cb47d27e9fe6
       # ...omitted for brevity
```

This should be addressed, possibly by removing the Status in favor of copying specific fields of interest to present in the frontend (cc: @rbreeze).
