### ISSUE TITLE
List images fails for ECR

### ISSUE THREAD

**Issue by wmiller112** [akuity/kargo#1950]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description
I am attempting to set up credentials for a private ECR repo. Came across [this issue](https://github.com/akuity/kargo/issues/1885), and as suggested, created a cronjob that has ECR access to generate a secret for kargo to consume. I cannot seem to get the warehouse to successfully authenticate with the generated secret, getting `no basic auth credentials`. I thought probably best to make a separate issue, as I'm not sure if this is related to something I might be configuring incorrectly in my secret/warehous

# Steps to Reproduce
secret in the project namespace or in a namespace specified in `controller.globalCredentials.namespaces`
```
apiVersion: v1
kind: Secret
metadata:
  name: <app-name>-ecr
  annotations:
    kargo.akuity.io/cred-type: image
stringData:
  username: AWS
  password: <output of aws ecr get-login-password --region ${AWS_REGION}>
  repoURL: <accout-id>.dkr.ecr.us-west-2.amazonaws.com.*
  repoURLIsRegex=true
```
Note that I tried both in the project ns and globally specified ns, tried with a slash and escaped slash at the end of repoURL, as well as with the full repoURL with repoURLIsRegex not set (default false), username set to `AWS` and empty. The password can be successfully used locally to `docker login` to the repo.
warehouse.yaml
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: <app-name>
spec:
  subscriptions:
    - image:
        allowTags: ^${ARGOCD_ENV_IMAGE_PREFIX}-[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}-[0-9]{2}-[0-9]{2}Z-[0-9a-f]{40}$
        imageSelectionStrategy: Lexical
        repoURL: <account-id>.dkr.ecr.us-west-2.amazonaws.com/<repo>
```

# Version

```
Client Version: v0.5.2
Server Version: v0.5.2
```

# Logs

```
msg="error syncing Warehouse: error getting latest Freight from repositories: error syncing image repo subscriptions: error getting latest suitable image \"<account-id>.dkr.ecr.us-west-2.amazonaws.com/<repo>\": error fetching newest applicable image \"<account-id>.dkr.ecr.us-west-2.amazonaws.com/<repo>\": error listing tags: error retrieving tags from repository: Get \"https://<account-id>.dkr.ecr.us-west-2.amazonaws.com/v2/<repo>/tags/list\": no basic auth credentials" namespace=<repo> warehouse=<repo>
msg="Reconciler error" Warehouse="{<repo> <repo>}" controller=warehouse controllerGroup=kargo.akuity.io controllerKind=Warehouse error="error getting latest Freight from repositories: error syncing image repo subscriptions: error getting latest suitable image \"<account-id>.dkr.ecr.us-west-2.amazonaws.com/<repo>\": error fetching newest applicable image \"<account-id>.dkr.ecr.us-west-2.amazonaws.com/<repo>\": error listing tags: error retrieving tags from repository: Get \"https://<account-id>.dkr.ecr.us-west-2.amazonaws.com/v2/<repo>/tags/list\": no basic auth credentials" name=<repo> namespace=<repo> reconcileID="\"b8ee695e-bd68-44d7-91d1-76c5e312be91\""
```

**Comment by krancour** [comment]
Hi @wmiller112 it sounds like you've already tried all the things I would have suggested, save for one, so kudos on that!

My one remaining suggestion is to enable debug logging and look for a message indicating that no credentials were found for that repo, since that is likely what is going on.

Once we know that for sure, we can try to get to the bottom of _why_.

**Comment by wmiller112** [comment]
Ah ha, there it is
```
level=debug msg="found no credentials for image repo" namespace=<app-name> repo=<account-id>.dkr.ecr.us-west-2.amazonaws.com/<app-name> warehouse=<app-name>
```
So in this case it looks like its failing to find it in the given namespace, which makes sense because I currently have it in the `kargo` namespace with the following in helm values:
```
controller:
    globalCredentials:
      namespaces:
        - kargo
```
which I see populated properly in kargo-controller cm

```
k get cm -n kargo kargo-controller -o yaml | yq '.data.GLOBAL_CREDENTIALS_NAMESPACES'
kargo
```
