### ISSUE TITLE
Freightline height when dealing w/ 3 subscriptions

### ISSUE THREAD

**Issue by jamessthompson** [akuity/kargo#1982]
# Checklist

* [ x ] I've searched the issue queue to verify this is not a duplicate bug report.
* [ x ] I've included steps to reproduce the bug.
* [ x ] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

When defining 3 subscriptions in a warehouse, the frieghtline height UI is too short, causing the versions to be cut off in at least Chrome and Edge under MacOS.

# Screenshots

<img width="549" alt="image" src="https://github.com/akuity/kargo/assets/1183445/b5f3c375-624a-4645-bbd7-182b198b5422">

# Steps to Reproduce

Define a warehouse with three subscriptions

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: sample
  namespace: kargo-sample
spec:
  subscriptions:
  - chart:
      name: chart1
      repoURL: https://charts.example.com/stable
      semverConstraint: 6.5.0
  - chart:
      name: chart2
      repoURL: https://chartstwo.example.com/stable
      semverConstraint: 1.0.1
  - image:
      imageSelectionStrategy: SemVer
      repoURL: us-docker.pkg.dev/some/image
      semverConstraint: 4.6.3
```

# Version

```
╰─$ kargo version
Client Version: v0.5.2
Server Version: v0.6.0
```

# Logs

```
Paste any relevant application logs here.
```
