### ISSUE TITLE
bookkeeper-based promotion mechanism should allow enumerating images

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#204]
Here's an example of updating images in a git repo using Kustomize:

```yaml
gitRepoUpdates:
- repoURL: https://github.com/krancour/kargo-demo.git
  kustomize:
    images:
    - image: krancour/nginx
      path: base/foo
    - image: krancour/nginx
      path: base/bar```
```

One can see that images that need to be updated are listed along with the paths they should be applied to.

By contrast, configuration for the Bookkeeper-based promotion mechanism currently looks like this:

```yaml
gitRepoUpdates:
- repoURL: https://github.com/krancour/kargo-demo.git
  branch: env/test
  bookkeeper: {}
```

This mechanism passes _all_ image versions associated with the target Environment state to Bookkeeper. That's ok, but in some cases, that could add some irrelevant noise to branch-specific Bookkeeper metadata. To avoid this and promote parity with other promotion mechanisms, we should allow the Bookkeeper-based promotion mechanism to be configured with a list of images.

This should be done sooner rather than later because, behaviorally speaking, this is a breaking change.
