### ISSUE TITLE
Support for Gitlab MR's on Private instances

### ISSUE THREAD

**Issue by ig12** [akuity/kargo#2079]
# Proposed Feature

Support the PullRequest promotion Feature for custom Gitlab deployments.

# Motivation

A lot of enterprises are running their git instances. The Promotion with merge requests is a valuable feature, especially in enterprise use cases, where each change to a production environment has to be validated and approved. The Merge Request Process is often already implemented and can be reused but simplified thanks to Kargo.

# Suggested Implementation

I have no suggestion for the implementation of the logic itself, but in the Stage CR it could be implemented like this:

```
  promotionMechanisms:
    gitRepoUpdates:
    - pullRequest:
        gitlab:
          customUrl: gitlab.enterprise.com
      repoURL: https://gitlab.enterprise.com/playground/kargo-demo-app.git
      writeBranch: stage/prod
```
