### ISSUE TITLE
UI shows two subscriptions even though Warehouse has one

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2151]
# Description

UI shows two subscriptions even though Warehouse has one

# Screenshots

<img width="367" alt="image" src="https://github.com/akuity/kargo/assets/12677113/32c7ff5f-3f79-4d18-9e97-c7b0df3a4395">

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
...
spec:
  subscriptions:
    - image:
        allowTags: ^[0-9]+\.[0-9]+\.[0-9]+
        repoURL: us-docker.pkg.dev/xxx/yyyy
```

# Version

```
v0.7.0
```

# Logs

```
Paste any relevant application logs here.
```
