### ISSUE TITLE
promotion process unnecessarily clones repos repeatedly -- can encounter rate limit

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#2178]
I'll stop short of calling this a bug, because I know it's by design, but still presents a bit of a problem...

Consider a Stage employing the following promotion mechanisms:

```yaml
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/example/repo.git
      kustomize:
        images:
        - image: nginx
          path: stages/test
    argoCDAppUpdates:
    - appName: kargo-demo-test
```

When a Promotion is in a Running phase, it is periodically re-reconciled to follow up on the state of the the Application. In the course of those repeated reconciliations, the gitRepoUpdates are performed anew each time. They're idempotent, so this is ok, but not very efficient.

I know this to be by design, because it means an abruptly terminated reconciliation attempt (due to controller restart, perhaps) can recover.

The inefficiency of this becomes a bigger problem in the context of #2156 (for instance). When a repo is cloned several times in rapid succession using SSH, it seems we run the risk of bumping into what appears to be a rate limit on SSH connections to GitHub. The result is that a first reconciliation attempt generally succeeds, all the way through to forcing a the Argo CD App to refresh, meaning the promotion is, largely speaking, complete, _but will likely fail on a subsequent reconciliation attempt_.

I'm trying to think of a clean way to improve this...

@hiddeco what would you think about replacing the Running phase with two new phases -- Mutating and Waiting?

On successful completion of Git or Argo CD _updates_ we could transition from Mutating to Waiting. On subsequent reconciliations, parts of the promotion process could be skipped if the Promotion is found to be in a Waiting state.

Just one idea -- I am open to others.
