### ISSUE TITLE
Kargo updates helm timestamp every 5 minute with a new commit on GitHub pull request

### ISSUE THREAD

**Issue by akselleirv** [akuity/kargo#2226]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

Kargo will constantly add commits to a pull request when using Helm chart.

It updates the `Chart.lock` file with a need timestamp on the generated field every five minute:
`generated: "2024-07-01T07:01:59.944058789Z"`

# Steps to Reproduce

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: example
  namespace: kargo
spec:
  subscriptions:
    - chart:
        repoURL: oci://my-acr.azurecr.io/helm-charts/my-app
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo
spec:
  subscriptions:
    warehouse: example
  promotionMechanisms:
    gitRepoUpdates:
      - repoURL: https://github.com/akselleirv/fake-example.git
        writeBranch: main
        pullRequest:
          github: { }
        helm:
          charts:
            - chartPath: my-app-dir
              name: my-app
              repository: oci://my-acr.azurecr.io/helm-charts
```
# Version

```
v0.7.1
```

# Logs

```
Paste any relevant application logs here.
```
