### ISSUE TITLE
oidc server specified, certificate required to validate oidc server, where to specify certificate in helm chart?

### ISSUE THREAD

**Issue by lknite** [akuity/kargo#2271]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

- ability to specify certificate needed to verify oidc server via helm chart

# Motivation

- after specifying oidc server, client_id, client_secret, etc ... unable to login because certificate verification fails

# Suggested Implementation

implement two methods which may be used:
1. allow a ca-bundle to be provided via a secret:
    - api.oidc.caBundle.secretName
    - api.oidc.caBundle.key
2. allow a ca-bundle to be provided in-line
    - api.oidc.caBundle
- allow the ca-bundle to be one or more certificates

**Comment by krancour** [comment]
@lknite are you using Dex?

**Comment by lknite** [comment]
no, am using keycloak

**Comment by krancour** [comment]
And the failure is occurring right when the API server starts?

**Comment by lknite** [comment]
yes, the pod never becomes ready cause it detects the cert cannot be verified during startup

**Comment by krancour** [comment]
Ok. Got it. I am thinking back to when we first did the ODIC integration and trying to recall why I wouldn't have made provisions for a custom CA bundle right from the get go...

My vague recollection is that the possibility of identity providers _without_ a cert that is trusted by users' browsers didn't seem realistic. After all, if one doesn't trust the IDP's cert without using a custom CA bundle, neither does the other.

Are your users installing a custom CA bundle into their browsers? Or are they just clicking through the warnings?

I guess what it all boils down to was an assumption that, with the possible exception of the included Dex, IDPs being properly secured with widely-trusted certificates was a given.

I'm open to that assumption being challenged. Can you tell me more about your use case?

**Comment by lknite** [comment]
Vault is used via cert-manager to generate certificates within all clusters.  The ca-bundle root certificates and intermediate certificates are pushed out to client systems automatically so that clients can access trust applications running via kubernetes.

Tanzu is used to stand up kubernetes clusters, and there is a place to specify the vault ca-bundle so that it also reaches workernodes of kubernetes clusters.

However, applications running in kubernetes still need a ca-bundle mounted to /etc/ssl/certs or wherever is appropriate within a pod to get it to trust the oidc provider.  I've currently hacked together a solution to mount a configmap to /etc/ssl/certs using kyverno, but given that no one really knows ahead of time where the correct place to mount a ca-bundle is in any given container, I certainly always appreciate it when the option is available via a helm chart.  (I wouldn't expect everyone to have kyverno experience in order to be able to deploy kargo.  Even myself, I didn't have kyverno experience until last week when I first set it up, thank goodness so I could use it today.)

**Comment by lknite** [comment]
There is another way to "resolve" this that you might prefer, 'harbor' has an option to just disable the verification of a tls cerficate with its OIDC configuration (see the checkbox at the bottom of this configuration gui) ... obviously not ideal, but I could see it existing for development purposes:
![image](https://github.com/akuity/kargo/assets/92187614/0fca8b70-a2a6-4b34-a2c0-ecc6228d6410)

**Comment by krancour** [comment]
@lknite thanks for the details. I get how you're distributing CA bundles around to things _in Kubernetes_. But what happens with interactions between the user's browser and the IDP? There are basically three possibilities:

1. Your IDP uses a cert trusted by the browser's default CA bundle.
2. Your IDP uses a cert _not_ trusted by the browser's default CA bundle and users ignore the warnings their browser raises.
3. Your IDP uses a cert _not_ trusted by the browser's default CA bundle, but your users all install a CA bundle that trusts the IDP's cert.

If it were no.1, Kargo should trust the IDP as much as the browser does. (So I assume it's not no.1.) If it were no.2, it feels dangerous to ignore cert warnings on an IDP. This is what lead to the (possibly poor) assumption that people don't do this. For this case, I'd recommend using a more widely trusted certificate if that is an option or else falling back to no.3.

No.3 seems to be the intersection of secure + plausible and is why I'm willing to be convinced to make it easier to install CA bundles.

**Comment by krancour** [comment]
Ok. Makes sense! Consider me convinced that it's not only people who have thrown caution to the wind (case 2) who would benefit from this.

I'll put some thought into how best to approach this.

**Comment by lknite** [comment]
Is it in the 0.8.1 helm chart and I just don't see it?

**Comment by krancour** [comment]
@lknite no. This hasn't been assigned to any milestone yet. In light of current internal priorities, a community contribution might be the fastest path to getting this done.

**Comment by lknite** [comment]
I used kyverno to mount the needed certs into /etc/ssl/certs ... things seemed ok until I tried my first git-based promotion then I saw this in the logs:
```
[kargo-controller-7c8c67bfb9-ntdzm] time="2024-08-05T00:34:51Z" level=error msg="error executing Promotion" error="error executing Git-based promotion mechanisms: error executing Kustomize promotion mechanism: error cloning git repo \"https://gitlab.com/lknite/lido-managers-deploy.git\": error cloning repo \"https://gitlab.com/lknite/lido-managers-deploy.git\" into \"/tmp/repo-2409851590/repo\": error executing cmd [/usr/bin/git clone --no-tags https://gitlab.com/lknite/lido-managers-deploy.git /tmp/repo-2409851590/repo]: Cloning into '/tmp/repo-2409851590/repo'...\nfatal: unable to access 'https://gitlab.com/lknite/lido-managers-deploy.git/': error setting certificate file: /etc/ssl/certs/ca-certificates.crt\n" freight=b87f75a60e71b2b45aa0d897fa21a49ebcfb9909 namespace=kargo-lido-managers promotion=non-prod.01j4fzbp6hwp8pc21abrxzkvrm.b87f75a stage=non-prod
[kargo-controller-7c8c67bfb9-ntdzm] time="2024-08-05T00:34:51Z" level=info msg=promotion freight=b87f75a60e71b2b45aa0d897fa21a49ebcfb9909 namespace=kargo-lido-managers phase="\"Errored\"" promotion=non-prod.01j4fzbp6hwp8pc21abrxzkvrm.b87f75a stage=non-prod
```

**Comment by lknite** [comment]
Maybe something like this, but with an 'emptydir' instead of a pvc:
```
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - name: ca-bundle
          mountPath: /tmp/source
        - name: pvc-ca-bundle
          mountPath: /tmp/target
      initContainers:
      - name: get-ca-bundle
        image: docker.io/alpine/curl:latest
        command:
        - "/bin/sh"
        - "-c"
        args:
        - |
          for FILE in /tmp/source/*; do awk 'BEGIN {c=0;} /BEGIN CERT/{c++} { print > "/usr/local/share/ca-certificates/cert." c ".crt"}' < $FILE; done
          /usr/sbin/update-ca-certificates
          rm -rf /tmp/target/*
          cp -r /etc/ssl/certs/* /tmp/target/
        volumeMounts:
        - name: ca-bundle
          mountPath: /tmp/source
        - name: pvc-ca-bundle
          mountPath: /tmp/target
      volumes:
      - name: ca-bundle
        secret:
          secretName: ca-bundle
      - name: pvc-ca-bundle
        persistentVolumeClaim:
          claimName: ca-bundle
```
