### ISSUE TITLE
Stage verification.args[] are not available in the AnalysisRun (anymore)

### ISSUE THREAD

**Issue by WZBFLM** [akuity/kargo#2333]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description
In Kargo 0.7.1 the handover of stage verification.args[] to the actual analysis run stopped working. Tested this in 0.3.0 successfully but now when re-evaluating for productive use this feature seems to stopped working.

# Steps to Reproduce

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-demo-helm
spec:
...
...
  verification:
    analysisTemplates:
    - name: kargo-demo-helm
    analysisRunMetadata:
      labels:
        app: kargo-demo-helm
      annotations:
        bat: baz4
    args:
    - name: exit-code
      value: "0"    
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo-helm
  namespace: kargo-demo-helm
spec:
  metrics:
  - name: fail-or-pass
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:latest
                command: [sh, -c]
                args:
                - exit {{args.exit-code}}
              restartPolicy: Never
          backoffLimit: 1      
```

After trigger of promotion:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  annotations:
    bat: baz4
  creationTimestamp: "2024-07-23T11:06:42Z"
  generation: 2
  labels:
    app: kargo-demo-helm
    kargo.akuity.io/freight: 37903f475b44b5d801dbffa3e35c2dac9a363d27
    kargo.akuity.io/promotion: dev.01j3fmb8dh5pwhq2pc00epcxdq.37903f4
    kargo.akuity.io/stage: dev
...
...
status:
  message: 'Unable to resolve metric arguments: failed to resolve {{args.exit-code}}'
  phase: Error
  runSummary: {}
```

This test passed in 0.3.0 version

# Version

```
v0.7.1
```

# Logs

From rollouts-controller:
```
time="2024-07-23T11:06:42Z" level=warning msg="Unable to resolve metric arguments: failed to resolve {{args.exit-code}}" analysisrun=dev.01j3fmb9ng4qq33a2c314em3ts.37903f4 namespace=kargo-demo-helm
```

**Comment by hiddeco** [comment]
I wonder if this is somehow related to #1577, which was added in 0.5.0

**Comment by hiddeco** [comment]
The solution is to ensure the AnalysisTemplate contains the definition of the argument you are attempting to use:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: kargo-demo-helm
spec:
  args:
  - name: exit-code
  metrics:
  - name: fail-or-pass
    provider:
      job:
        spec:
          template:
            spec:
              containers:
              - name: sleep
                image: alpine:latest
                command: [sh, -c]
                args:
                - exit {{args.exit-code}}
              restartPolicy: Never
          backoffLimit: 1
```

This subtle change is required because the bug fix in #1577 now uses the arguments from the AnalysisTemplate as a (default) base to resolve #1573. This implicitly means that arguments must be defined within the AnalysisTemplate for values (overrides) from the Stage to be taken into account.
