### ISSUE TITLE
Multi source Argo CD applications fail when promotions are applied

### ISSUE THREAD

**Issue by danielloader** [akuity/kargo#2423]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I have been attempting to use Kargo with a multi-source Argo CD application last week that has a relatively simple use-case:
- One helm chart with an upstream application (OpenFGA)
- One kustomization manifest containing auxiliary manifests for this chart e.g. Cloudnative PG cluster, External Secrets, etc.

The screenshots show the pre-promotion state (the default state of the Application) and the post promotion state of the Application. In this scenario moving from 0.2.9 to 0.2.10 on OpenFGAs helm chart, and moving from the HEAD to a fixed commit on the main branch on the kustomization.

On promotion, the targetRevisions are being bumped correctly but the rest of the object is lost causing Argo CD to fail to sync (thankfully) due to nil pointer dereferences.

```
InvalidSpecError: spec.source.repoURL and either source.path, source.chart, or source.ref are required for source {https://github.com/example/platform-services e0b568919388ed0f514bc1ac18dbed344ecbba6c nil &ApplicationSourceKustomize{NamePrefix:,NameSuffix:,Images:[],CommonLabels:map[string]string{},Version:,CommonAnnotations:map[string]string{},ForceCommonLabels:false,ForceCommonAnnotations:false,Namespace:,CommonAnnotationsEnvsubst:false,Replicas:[]KustomizeReplica{},Patches:[]KustomizePatch{},Components:[],LabelWithoutSelector:false,} nil nil }
```

# Screenshots

![image](https://github.com/user-attachments/assets/64ee585b-8387-4ff0-b2c8-3b49efdc3411)
![image](https://github.com/user-attachments/assets/dfc5854f-8a0e-4502-8191-a66c4c0678fb)

# Steps to Reproduce

Here's the stage in question, I'm assuming the warehouse configuration is not pertinent as it's finding/selecting the correct versions for the sources.

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: service-openfga
spec:
  promotionMechanisms:
    argoCDAppUpdates:
      - appName: openfga-uat
        appNamespace: argocd
        origin:
          kind: Warehouse
          name: openfga
        sourceUpdates:
          - repoURL: https://openfga.github.io/helm-charts
            chart: openfga
            updateTargetRevision: true
          - repoURL: https://github.com/example/platform-services
            updateTargetRevision: true
  requestedFreight:
    - origin:
        kind: Warehouse
        name: openfga
      sources:
        direct: true
  subscriptions: {}
```

And the relevant ignore section on the ApplicationSet:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: service-openfga
  namespace: argocd
spec:
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.sources[].targetRevision
...
```

# Version

```
0.8.4
```

# Logs

```
Paste any relevant application logs here.
```
