### ISSUE TITLE
feature request: Customisable freight aliases

### ISSUE THREAD

**Issue by joaoestrela** [akuity/kargo#2426]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.

# Proposed Feature

Customisable freight aliases

# Motivation

With the introduction of Multi-Pipelines it would be nice to allow some customisation to freight aliases to better distinguish. It is possible to rename but generated recognisable aliases would be a great improvement.

# Suggested Implementation

1. Add a new string key to the Warehouse CRD that allows the addition of a prefix or suffix to the respective generated freights.
2. Add a boolean key to the Warehouse CRD that enables the prefixing or suffixing of the Warehouse name to the respective generated freights.

**Comment by krzwiatrzyk** [comment]
Fully agree, it would be awesome to automatically generate freights with an alias equal image version (from semver) like that:
![image](https://github.com/user-attachments/assets/37b1bfd2-c7af-49fc-94f9-30ec3af3fda7)

**Comment by krancour** [comment]
Bear in mind that a piece of Freight is a _collection_ of artifacts. A piece of Freight with just one artifact in it is the _simple_ case. It may seem intuitive in that case that the Freight alias would just match the tag of your Docker image, for instance, but that doesn't generalize well. The moment you have two or more artifacts in a piece of Freight (which is common, btw) that strategy falls apart. _Some kind_ of customization ability seems likely, eventually, but adopting a strategy of mirroring version information of a single artifact doesn't seem likely when it doesn't hold up for the common case.

**Comment by antoine-sncf** [comment]
Contributing to the use case

**Possible situations to identify** 
1. Single subscription: use the item tag (image/chart)
3. Single image & Single chart : option to chose the image or chart as tag source (shouldn't -image- be the more popular option?)
4. Multiple subscription ( <x> chart and/or <y> image). Option to select a specific freight item as tag source (same as 3 in fact but with full subscription name ? could be merged with only 4)
5. External info (http call to a custom service?)
6. External trigger ? In my case using git  mono repo & -trunk based- development : when the project tags the main repo, our CI creates the images with their own semver (possibly) or maybe the same as the tag. We want the freight to be created only when the CI is finished (because we don't want the auto-assembly to trigger while it's still building possibly "many" images). 
So the question here are: who is sending the tag information 
- inside the CI ? does it sends all freights or le the auto discover handle it ?)
- or withih kargo (gitlab/hub hook to trigger on tag and trigger the freight creation after watching <something> (the gitlabCI or something else finish).

_A quick braindump to help on refinement_

**Comment by krancour** [comment]
2 and 3 aren't viable. If you have an existing piece of Freight containing multiple artifacts and you use version information of _one_ of those as the alias, then a new version of the artifact you're _not_ using as the alias is discovered while the one you _are_ using as the alias has no new version, you will end up with a second piece of Freight with the same alias as the first. Aliases are supposed to be unique.

> External info (http call to a custom service?)

Can you elaborate on how that might be useful?

5 could be solved by #1069, but I'm not sure I understand what it's got to do with the Freight alias.

**Comment by antoine-sncf** [comment]
> 2 and 3 aren't viable. If you have an existing piece of Freight containing multiple artefacts and you use version information of _one_ of those as the alias, then a new version of the artifact you're _not_ using as the alias is discovered while the one you _are_ using as the alias has no new version, you will end up with a second piece of Freight with the same alias as the first. Aliases are supposed to be unique.

indeed or maybe add a suffix if it creates duplicate ? 1.2.3-rev123  ?

>> > External info (http call to a custom service?)
> 
> Can you elaborate on how that might be useful?

It's all about WHO decides of the semver increment. Could be infered with some Jira tracking or whatever systgemhaving a complex rule. That was a pure question without any anwser #BrainDump.

> 5 could be solved by #1069, but I'm not sure I understand what it's got to do with the Freight alias.
Delaying the freight assembly will not solve the freight alias, only reducing the amount of freight.

My use case is : my dev team is releasing by tagging our git with -1.2.3- (current deployment was 1.2.2) the CI will generate various artefacts with possibly their own semvers.
I want to trigger a freight assembly immediatly at the end of the CI and then name it as 1.2.3 because it was the name of tag chosen by the team

**Comment by MPV** [comment]
> Bear in mind that a piece of Freight is a _collection_ of artifacts. A piece of Freight with just one artifact in it is the _simple_ case. It may seem intuitive in that case that the Freight alias would just match the tag of your Docker image, for instance, but that doesn't generalize well. The moment you have two or more artifacts in a piece of Freight (which is common, btw) that strategy falls apart. _Some kind_ of customization ability seems likely, eventually, but adopting a strategy of mirroring version information of a single artifact doesn't seem likely when it doesn't hold up for the common case.

In our use case we're considering letting all hydration happen before Kargo. Meaning that we'd only have one subscription (for such a collection of manifests for a freight), and thus as we'd be going through some hoops to nail assembly and versioning _before_ Kargo, it would be nice if Kargo would allow that to show / propagate clearly into the UI. 

In my mind this would also align with how one would want it when OCI becomes supported: you'd subscribe to, and deploy an (already versioned) artifact.

**Comment by sennerholm** [comment]
I wonder if it's possible to write a kyverno policy that mutate the freight name. Anyone who have tried?

**Comment by pvickery-ParamountCommerce** [comment]
> I wonder if it's possible to write a kyverno policy that mutate the freight name. Anyone who have tried?

I was able to get this working using a kyverno mutation in a POC today. I use github actions to tag my main branch after merging PRs (ex `PR:<number>`) and monitor those tags with my Kargo Warehouse and mutate new Freights to set the alias as the tag value

**Comment by pvickery-ParamountCommerce** [comment]
I ran into a small problem with the freight alias mutation. I get an error when the warehouse refreshes and finds no new changes, it complains that the (latest) alias already exists. I am a bit surprised by this issue but I was able to work around it by prepending a small random string to each freight.

> Error creating Freight "97ad89dc6df4774cf714ff7ec17ddd84fc14527b" in namespace "hello-world": admission webhook "freight.kargo.akuity.io" denied the request: Freight.kargo.akuity.io "a4c4da8d42f4ade75b3267508718299be2874685" is invalid: alias: Invalid value: "38_bump-world": alias already used by another piece of Freight in namespace "hello-world"

**Comment by krancour** [comment]
If you do anything with `latest` or any other mutable tag, you're playing with 🔥

**Comment by pvickery-ParamountCommerce** [comment]
I keep finding myself drawn to the fire 😅 

I may have caused some confusion by saying 'latest'. I am not using the tag `latest` or overwriting any git tags and have setup branch rules to only allow the kargo app to create tags. I am using github actions to create a tag after a PR is merged, the tag is the `<PR number>_<PR title>` so the tags are always unique.

In my above error, I had successfully released `38_bump-world` to all stages and when the warehouse refreshed, it showed the error about the duplicate alias value as `38_bump-world` already exists (and is the most recent / latest freight alias).

**Comment by sennerholm** [comment]
Is it possible for you to share some skeleton code? Then I can see if I get same problem on my side?

**Comment by pvickery-ParamountCommerce** [comment]
For sure! Here is the mutation that I am using. It assumes that the git tags follow this format: `kargo_<application>_<PR number>_<PR title>` where application is either `helloWorld` or `helloUniverse` for my two test projects. helloWorld just watches for  commits but helloUniverse also watches for image updates. The mutation supports both and optionally includes the image tag if available. ex `38_bump-world` and `21_testing-universe_v1.25` are my most recent freights for helloWorld and helloUniverse respectively.

``` yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    policies.kyverno.io/description: Automatically sets kargo.akuity.io/alias label
      on Kargo Freight resources based on commit tag and image tag if present
    policies.kyverno.io/title: Kargo Freight Alias Mutation
  name: kargo-freight-alias-mutation-new
spec:
  admission: true
  background: false
  emitWarning: false
  rules:
  - context:
    - name: commitTag
      variable:
        # Assumes format kargo_<application>_<PR number>_<PR title>
        value: '{{ split(request.object.commits[0].tag, ''_'')[2] }}_{{ split(request.object.commits[0].tag,
          ''_'')[3] }}'
    - name: imageTag
      variable:
        value: '{{ request.object.images[0].tag || '''' }}'
    # Include the imageTag if available
    - name: aliasValue
      variable:
        # Switch commented value line to change behaviour
        value: '{{ trim(''{{ commitTag }}_{{ imageTag}}'', ''_'') }}'
        # value: '{{ trim(''{{ commitTag }}_{{ imageTag}}'', ''_'') }}-{{ random(''[a-z0-9]{4}'') }}'
    match:
      any:
      - resources:
          kinds:
          - kargo.akuity.io/v1alpha1/Freight
          namespaces:
          - hello-world
          - hello-universe
    mutate:
      patchStrategicMerge:
        alias: '{{ aliasValue }}'
        metadata:
          labels:
            kargo.akuity.io/alias: '{{ aliasValue }}'
    name: add-freight-alias-label
    preconditions:
      any:
      - key: '{{request.object.commits[0].tag}}'
        operator: NotEquals
        value: ""
    skipBackgroundRequests: true
  validationFailureAction: Audit
```

**Comment by pvickery-ParamountCommerce** [comment]
I tried to fiddle with the mutation some more to skip the policy if the alias is already used by another Freight but I still had the same issue 😕 

I realized I can just ignore the error and when a new commit/image is pushed, the warehouse works as expected. It's not ideal but it doesn't cause any blockers.

Here was the modification I tried to skip when the alias already existed.
``` yaml
...
spec:
...
  rules:
  - context:
        - apiCall:
            jmesPath: items
            method: GET
            urlPath: /apis/kargo.akuity.io/v1alpha1/freights
          name: allFreights
    preconditions:
        all:
          - key: "{{ length(allFreights[?spec.alias == '{{request.object.alias}}']) }}"  #This is incorrect
            operator: Equals
            value: "0"

```

**Comment by pvickery-ParamountCommerce** [comment]
I made some mistakes in the modifications and this mutation is working well so far 🙂 

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kargo-freight-alias-mutation

spec:
  rules:
    - name: add-freight-alias-label
      context:
        - name: commitTag
          variable:
            value: "{{ split(request.object.commits[0].tag, '_')[2] }}_{{
              split(request.object.commits[0].tag, '_')[3] }}"
        - name: imageTag
          variable:
            value: "{{ request.object.images[0].tag || '' }}"
        - name: aliasValue
          variable:
            value: "{{ trim('{{ commitTag }}_{{ imageTag}}', '_') }}"
        - apiCall:
            jmesPath: items
            method: GET
            urlPath: /apis/kargo.akuity.io/v1alpha1/namespaces/{{request.namespace}}/freights
          name: allFreights
      preconditions:
        all:
          - key: "{{request.object.commits[0].tag}}"
            operator: NotEquals
            value: ""
          - key: "{{ request.object.alias }}"
            operator: NotEquals
            value: "{{ aliasValue }}"
          - key: '{{ request.object.metadata.labels."kargo.akuity.io/alias" }}'
            operator: NotEquals
            value: "{{ aliasValue }}"
          - key: "{{ length(allFreights[?alias == '{{ aliasValue }}']) }}"
            operator: Equals
            value: "0"
      match:
        any:
          - resources:
              kinds:
                - kargo.akuity.io/v1alpha1/Freight
              namespaces:
                - hello-world
                - hello-universe
      mutate:
        patchStrategicMerge:
          alias: "{{ aliasValue }}"
          metadata:
            labels:
              kargo.akuity.io/alias: "{{ aliasValue }}"
      skipBackgroundRequests: true
  validationFailureAction: Audit
```
