### ISSUE TITLE
The semverContraint sometimes picks up short SHA from images

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#2438]
# Description

When tagging images with the short "sha" of a Git commit, Kargo will pick it up as valid semver (because it is)

Example

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/christianh814/kargo-demo-deploy
      branch: main
      commitSelectionStrategy: SemVer
      semverConstraint: '>= 1.2.3'
  - image:
      repoURL: ghcr.io/christianh814/kargo-demo-app
      imageSelectionStrategy: SemVer
      semverConstraint: '>= 1.2.3'
```

This picked up an image that was tagged as `ghcr.io/christianh814/kargo-demo-app:917005`

# Screenshots

![image](https://github.com/user-attachments/assets/78cb32d6-0132-4302-b82d-802e1357ecac)

# Steps to Reproduce

Set a `semverConstraint` of `'>= 1.2.3'` and then tag your image with random numbers

# Version

```
$ kargo version 
Client Version: v0.8.4
Server Version: v0.8.4
```
