### ISSUE TITLE
Missing git credentials pass-through for kustomize remotebases

### ISSUE THREAD

**Issue by dwkop** [akuity/kargo#2477]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When using `kustomize with a remoteBase targeting to a private repository` (in our case Github Enterprise), credentials are needed for authentication. With ArgoCD repoServer as well as with local kustomize client, credentials are passed through
.
"kargo-render" howerver, do not pass through the credentials properly so that it prompts *again* for git credentials, even though they are provided from a credential store.

This results simply in failed promotions via Kargo Controller and an error message in the logs (see below).
When running kargo-render locally within a container it fails as well when no credentials are provided, but would succeed if they are provided a 2nd time as a user-input.

I understood that kargo-renders future is unknown, and it might end up fully in Kargo 0.9+, Therefore I want to highlight this bug here to be directly covered in the potentially integration, since we are heavily relying in using kustomize remotebases

**Expected behavior:**

Kargo/Kargo-render handles git credentials similar like ArgoCD does in order to support kustomize remote bases targeting private repositories

# Screenshots

# Steps to Reproduce

Example:

kargo-render.yaml
```yaml
configVersion: v1alpha1
branchConfigs:
  - name: stage/kube1-dev
    appConfigs:
      mercury-argoevents: # source repo
        configManagement:
          path: applications/cortex-argoevents-manifest/stages/kube1-dev
        outputPath: mercury-argoevents
        combineManifests: true
```

kustomization
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://my-company/my-org/cortex-argoevents-manifest.git//deployment?ref=HEAD
#  - ../../base
#  - ../../tests
```

local command
```bash
docker run -it ghcr.io/akuity/kargo-render:v0.1.0-rc.40  --repo https://my-company/my-org/mercury-manifest  --repo-username yyy   --repo-password xxx  --target-branch stage/kube1-dev
```
prompts for:
```
Username for 'https://code.rbi.tech': 
```
and if not provided it fails with error

```
Error: error pre-rendering manifests: error generating manifests using Argo CD repo server: `kustomize build /tmp/repo-311868286/repo/applications/cortex-argoevents-manifest/stages/kube1-dev` failed exit status 1: Error: accumulating resources: accumulating resources from 'https://my-company/my-org/cortex-argoevents-manifest.git//deployment?ref=HEAD': MalformedYAMLError: yaml: line 184: mapping values are not allowed in this context in File: https://my-company/my-org/cortex-argoevents-manifest.git//deployment?ref=HEAD
```

# Version

```
version: 0.8.4
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by bcross** [comment]
I have a centralized Kustomize library repo that I was able to clone beside my IAC repo and that worked. Something like this:

```yaml
spec:
  steps:
    - uses: git-clone
      config:
        repoURL: https://github.com/mine/iac.git
        checkout:
          - fromFreight: true
            path: ./src
          - branch: env/dev
            path: ./out
            create: true
    - uses: git-clone
      config:
        repoURL: https://github.com/mine/kustomize-library.git
        checkout:
          - branch: main
            path: ./kustomize-library
    - uses: kustomize-build
        config:
          path: ./src/dev
          outPath: ./out
```

The `kustomization.yaml` in the dev folder of the iac repo looks something like this:

```yaml
resources:
- ../../kustomize-library/kustomize/api
```

**Comment by nikolay-te** [comment]
I see the `kustomize-build` step is actually executing `git`. I've tried setting up a `/home/nonroot/.gitconfig` file directly on the controller pod to see if I can redirect the git repo to a local path of an already `git-clone`-d repo via `insteadOf`, but this doesn't seem to work as the step seems to be executing in /tmp/kustomize-xxx chroot.
It seems like allowing to customize the .gitconfig or potentially setup the credential-helper might get this to work without big changes?

**Comment by krancour** [comment]
@hiddeco I assigned you, but no immediate action is required. At this point just looking for insight and some idea of whether this is reasonable to include in v1.5.0.

**Comment by jessesuen** [comment]
Wanted to share the approach we took with Argo CD which I think we should consider using here.

When we invoke the `kustomize build` subprocess, we would also set `GIT_ASKPASS` env var to a script/program that is responsible for returning credentials for a supplied repo that `git` will pass as an argument to the script. This will likely be the `kargo` binary itself, e.g. `GIT_ASKPASS="/usr/local/bin/kargo ask-pass"`.

Now, `kargo ask-pass` can't just dole out git credentials to anyone who asks it since the controller is multi-tenant. It should only supply credentials to projects that have acces to those credentials. So additionally, we would set a one-time nonce to go along with the `kustomize build` command. e.g.

```
KARGO_GIT_NONCE=abcd1234
GIT_ASKPASS="/usr/local/bin/kargo ask-pass"
kustomize build path/to/dir
```

This nonce would serve to allow the `git` process to identify the context of  the`kustomize build`, namely it lets us know which project is asking for the password (e.g. we would remember that nonce `abcd1234` is associated with project `foo`.

There is a RPC server/client aspect to this:
`/usr/local/bin/kargo ask-pass` is a client (over `/var/run/kargo-ask-pass.sock`) to `kargo-controller`

So the sequence of events would be:

1. `kargo-controller` is about to invoke a `kustomize-build` step for project `foo`
2. Before running `kustomize build`, it generates a NONCE, `abc123`, and remembers in-memory that it is associated with project `foo`
3. `kargo-controller` invokes `kustomize build` with the following env vars set:
```
KARGO_GIT_NONCE=abc123
GIT_ASKPASS="/usr/local/bin/kargo ask-pass"
```
4. `kargo ask-pass` makes an RPC call to kargo-controller (over `/var/run/kargo-ask-pass.sock`) and supplies the git repo and `KARGO_GIT_NONCE` as part of the request.
5. `kargo-controller` receives the request, understands that it is being requested by project `foo` and verifies the credential that is being requested is accessible to `foo`. If so returns it.
6. As soon as the nonce is used, `abc123` nonce is discarded. We could also ensure it's not usable after a certain time limit (e.g. 1m).


More details can be gleaned from the implementation here:
https://github.com/argoproj/argo-cd/blob/e4a8c9ee980b150167b37afa27385d6ae564f19d/util/askpass/server.go

**Comment by jessesuen** [comment]
A simpler, but less secure approach could have been, we generate a script at a random path on disk which is set as the GIT_ASKPASS script. e.g.:

```
GIT_ASKPASS=/tmp/abc123.sh
```

The `/tmp/abc123.sh` script would contain the git passwords of the project hard-coded into the script so that it could return them to the caller (git). After the `kustomize build` step finished, the  `/tmp/abc123.sh` would be deleted.

However, this approach is less secure since we don't have a good way of preventing other processes from reading the contents of `/tmp/abc123.sh`, but would eliminate the server-client piece to the first proposal.

**Comment by julianderks** [comment]
We are currently facing this exact issue in our organization: our GitOps repositories rely on Kustomize remote bases, and kargo-render fails to access these private remotes as described above.

Neither SSH nor HTTPS remote bases work with Kargo, even though the credentials are correctly configured and work with ArgoCD and local kustomize build. 

We are excited about Kargo, but this behavior is currently blocking further adoption in our organization, as we rely heavily on reusable Kustomize bases stored in private Git repositories.

**Comment by snuggie12** [comment]
We def need this feature since we have a lot of library like transformations.

If you want kustomize to work both on the laptop and in kargo, a slight spin on https://github.com/akuity/kargo/issues/2477#issuecomment-2513183677 would be to add a `hacks` directory at the kustomize root and copy it in before running `kustomize-build`.

For instance, the file with the remote base for us was `components/foo/kustomization.yaml` so I put a fixed copy into `hacks/components/foo/kustomization.yaml`. Then `kargo` does a `copy`.

**Comment by nikolay-te** [comment]
I've mentioned earlier our a little bit more elaborate setup to workaround this limitation for now. Here is what we did:

This kustomization is applied to the kargo controller manifests:
```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: gitconfig-volume
          secret:
            secretName: kargo-controller-dot-gitconfig
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: IGNORED
        namespace: IGNORED
      spec:
        template:
          spec:
            containers:
              - name: controller
                env:
                  - name: GIT_CONFIG_GLOBAL
                    value: /gitconfig/.gitconfig
                volumeMounts:
                  - name: gitconfig-volume
                    mountPath: /gitconfig
                    readOnly: true
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=controller,app.kubernetes.io/instance=kargo,app.kubernetes.io/name=kargo
```

This mounts a gitconfig file from a secret within the controller and sets the GIT_CONFIG_GLOBAL env var to point to it which the git process the controller spawns via the kustomize-build step properly recognizes and uses.


The contents of the secret is refreshed dynamically using the GithubAccessToken External Secrets Operator generator and provisioned like this:

```yaml
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kargo-controller-dot-gitconfig
  namespace: kargo
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: kargo-github-auth-token
  refreshInterval: 15m
  target:
    template:
      engineVersion: v2
      data:
        .gitconfig: |
          [url "https://x-access-token:{{ .token }}@github.com/myorg/"]
            insteadOf = "git@github.com:myorg/"

          [url "https://x-access-token:{{ .token }}@github.com/myorg/"]
            insteadOf = "https://github.com/myorg/"
    name: kargo-controller-dot-gitconfig
```

This both sets the tokens, and also makes sure git access happens over https only so we don't have to deal with ssh keys too.
