### ISSUE TITLE
Pass dynamic information to AnalysisRun

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2482]
# Proposed Feature

Today, we support hardwired arguments to an AnalysisRun:

```yaml
  verification:
    analysisTemplates:
    - name: cat-fact
    args:
    - name: foo
      value: bar
```

This is useful but somewhat limited. It would be more useful to be able to supply runtime information to the AnalysisRun, for example, information about the freight that it is running verification against.

# Motivation

The analysis may want to use the freight information for its query or test.

# Suggested Implementation

One approach is to introduce some variable feature, e.g.:

```yaml
  verification:
    analysisTemplates:
    - name: cat-fact
    args:
    - name: foo
      value: "${freight.image}"  
```

We are already thinking of variables as part of promotion directives, and this would likely need to come after that.

**Comment by krancour** [comment]
Our promotion directives will require some sort of EL as they continue to mature, so I think this is something we could deal with in tandem with that.

**Comment by lknite** [comment]
upvote

i was looking for this today; created a work around to pull the freight information but my work around creates a race condition, better if the values could be passed in ... as a default environment variable maybe?

**Comment by rcontreras-te** [comment]
Just curious if there's been any further thought or progress on this?  

Having the ability for an `AnalysisRun` to know what freight is under test (_e.g. images+tags, git repo commit hashes, etc..._) opens up the possibilities for what can be done by a verification step.  If this is known at runtime then that info could be used to check on additional external verification steps.  

For example, if we know what images+tags are in the deployed freight then we could create a verification step that could check to see if those images have successfully completed some external process. (_have those images been successfully scanned for vulnerabilities?  have their SBOM's been published to an external service as required by a business rule?  etc..._)

**Comment by rcontreras-te** [comment]
Another thought... although @jessesuen 's suggestion that we could essentially allow for templated values to be passed in as arguments to the `AnalysisTemplate` would certainly be useful,

```yaml
  verification:
    analysisTemplates:
    - name: cat-fact
    args:
    - name: foo
      value: "${freight.image}"  
```

It would seem to me that it could be _very beneficial_ to expose fundamental freight metadata to an `AnalysisTemplate` without requiring that it always be done explicitly.  I suppose this is similar to the request that @lknite is making.  I first thought this could be done via a standard set of injected environment variables (e.g. `KARGO_*`) but it could by some other method.  The overall goal being that any `AnalysisTemplate` can always expect certain freight metadata to be available without having to explicitly pass it in as an argument.
