### ISSUE TITLE
Promoting downstream from control-flow stage doesn't work

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2496]
# Description

When clicking the truck icon on a control-flow stage (one that doesn't have any promotion mechanisms), the UI doesn't highlight any Freight as promotable, so I am unable to promote to all the downstream stages with one click. I'm not sure if this is a UI problem or a backend problem.

The following video shows "Promote downstream" working for `staging`, but not for `prod`.

https://github.com/user-attachments/assets/4efacd6d-a763-4b9f-8482-35e1ce52f15d

Here is the live object of the `prod` Stage:

```yaml
metadata:
  name: prod
  namespace: kargo-advanced
spec:
  subscriptions: {}
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        direct: false
        stages:
          - ab-test-a
          - ab-test-b
status:
  phase: NotApplicable
  observedGeneration: "2"
  freightSummary: 0/1 Fulfilled
```

# Steps to Reproduce

Create the [kargo-advanced](https://github.com/akuity/kargo-advanced) example and try to promote downstream from prod stage.

# Version

```
v0.8.7
```
