### ISSUE TITLE
Allow Labels to be Added to Namespace through Kargo Project Manifest

### ISSUE THREAD

**Issue by BenjaminNeale-Heritage** [akuity/kargo#2525]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature
A Kubernetes namespace is automatically created when a Kargo project is created.  Please allow for labels to be defined in the Kargo project that will then be set on the namespace.

# Motivation
The Security Best Practices page for the External Secrets Operator (ESO) states that ClusterSecretStore resources should be configured to match conditions such as namespaces that have an expected label [1].  This prevents the ClusterSecretStore from being accessed from any namespace on the cluster.  The namespace created by the Kargo project is not labelled so that ESO can be used to create the credential secrets [2].  It is currently necessary to use Argo CD to do a server-side apply to add the label to the namespace.  It would be much easier if the Kargo project allowed for labels to be defined within the Project resource manifest that will then be added to the namespace when it is created.

[1] https://external-secrets.io/latest/guides/security-best-practices/#2-configure-clustersecretstore-match-conditions
[2] https://kargo.akuity.io/how-to-guides/managing-credentials

# Suggested Implementation
This capability could potentially be added by a "template" field within the Kargo Project resource.

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: kargo-awesome-service
spec:
  template:
    metadata:
      labels:
        eso.example.com.au: cluster-secret-store-alpha
```
