### ISSUE TITLE
Visualize historical freight in a Stage

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2530]
# Proposed Feature

For a given Stage, it would be useful to know what freight it was running previously in a historical/chronological view.

I'm proposing we add some timeline view after clicking on a Stage:

<img width="889" alt="image" src="https://github.com/user-attachments/assets/15c1b816-43e6-4417-a476-5f0576b1a88b">

That will show some timeline like:

<img width="1676" alt="image" src="https://github.com/user-attachments/assets/3aad4827-4044-4ee4-82f5-9bf1b8bf6376">

We could possibly re-using the existing freight timeline component (in a read only manner)

# Motivation

It is useful to see what a stage previously ran.

# Suggested Implementation

We already have the information there in the stage, so no new backend feature would be needed. This is only about visualizing it:

```yaml
  freightHistory:
    - items:
        Warehouse/guestbook:
          name: 28c0c29c967a950c20734fdb898b1e76744fb820
          images:
            - repoURL: guestbook
              tag: 1.0.1
              digest: sha256:39c5476e80433a0f119c8bfcaac5dbf12f028f160bb3c5177d6bd5838b0af147
          origin:
            kind: Warehouse
            name: guestbook
      id: 7844e215533c29b606ab0f72d7b9b092fcee5c66
    - items:
        Warehouse/guestbook:
          name: 9048ca52d6110c942236000cbc9fd1d007c91c88
          images:
            - repoURL: guestbook
              tag: 1.0.0
              digest: sha256:7db3dff75d6c34c1413a51531919e720a36b55afd270c3a65b737fee1dad9dad
          origin:
            kind: Warehouse
            name: guestbook
      id: 770771a789e5eb4fe00b884a3dfd08a5b5008e50
```
