### ISSUE TITLE
Don't show/list project to user if user doesn't have permissions in project

### ISSUE THREAD

**Issue by Brightside56** [akuity/kargo#2578]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature

I would like projects where user doesn't have permissions to be hidden from this user

# Motivation

1. It's possible to filter projects using input, but large list of irrelevant projects (20-30-40) on main page causes frustration among users who work with 2-3-4 projects
2. Principle of least privilege/security point of view/best practices

# Suggested Implementation

Additional checks and filtering project list on backend

**Comment by krancour** [comment]
Take Kargo out of this entirely for a moment. This is more of a general Kubernetes problem without a real solution.

If a user can list resources of a given type, their results when doing so are not constrained by what their permissions happen to be on individual resources _of_ that type. Since a pretty direct comparison could also be made between Projects and namespaces, it's also worth pointing out that if a user can list namespaces, their results when doing so are also not constrained by their permissions on resources _within_ each namespace.

I suppose there is some technical possibility of giving the Kargo API server's list Projects endpoint tricks that k8s itself doesn't have, but I would really hate having `kubectl get projects` and `kargo get projects` return different results. Even if that weren't a concern, there would still be a question of what the criteria are for deciding to include/exclude a given Project in the results. Even supposing there were a satisfactory answer for that, the next problem is that this could mean performing thousands of subject access reviews per Project list operation, which would slow that operation to a crawl and possibly even impact cluster performance.

All this being said, I agree that the UX could be better and wonder if the ability to star/favorite projects might not be a more viable improvment.

**Comment by Brightside56** [comment]
If we focus on the Kubernetes resource model, then absence of possibility to make list verb more granular also doesn't make me happy. I understand that overloading a project with features or workarounds to ensure paranoid security measures can negatively affect its functional part

> All this being said, I agree that the UX could be better and wonder if the ability to star/favorite projects might not be a more viable improvment.

In general it would be great improvement. In my edge case there is also a requirement to ensure least privilege on top, even if it's list privilege =/

Allright... I'll try to workaround it somehow, probably

**Comment by krancour** [comment]
> If we focus on the Kubernetes resource model, then absence of possibility to make list verb more granular also doesn't make me happy.

Indeed, I empathize.

We are, however, trying pretty hard to keep all RBAC as _pure_ k8s RBAC and not layer something on top of it for enforcement (the way Argo CD does with casbin, for instance). The inherent disadvantage of something like that is too many things are enforced when the API server is involved and aren't enforced at all when you use kubectl. 😦 

I'll carve out a separate issue in the morning for starring/favoriting. That should be non-controversial and easy to get done.

**Comment by krancour** [comment]
Closing in favor of #2689

**Comment by dan1el-k** [comment]
@krancour 
wouldn't it be possible to limit the `list` view based on `resourceNames`. 
According kubernetes docs, it should be possible to do so and would be a native feature, see: https://stackoverflow.com/questions/62274122/kubernetes-rbac-roles-with-resourcename-and-listing-objects 




That would be an example Role, which can be deployed in the kargo default namespace, which limits to one users project `my-demo` only and bounded to one user specific ServiceAccount.
```yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: kargo-my-demo-viewer
  namespace: kargo
  annotations:
    rbac.kargo.akuity.io/claim.groups: MY_DEMO_GROUP
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-my-demo-kargo-viewer
subjects:
  - kind: ServiceAccount
    name: kargo-my-demo-viewer
    namespace: kargo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-my-demo-projects-viewer
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-my-demo-projects-viewer
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - events
      - namespaces
      - serviceaccounts
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
  - verbs:
      - list
    apiGroups:
      - kargo.akuity.io
    resources:
      - projects
    resourceNames:
      - my-demo
```

The only thing required I guess, would be that the kargo as a client, needs to include the metadata.name` field selector in the list query, according this comment here: https://github.com/kubernetes/website/pull/29468/files#diff-b39dd9c0a047fe6b4d12eb238bc7d66137d6828df7c3a03801c5d3e375ad8a42R284

I think this would be somewhere in this file necessary:
https://github.com/akuity/kargo/blob/main/internal/api/list_projects_v1alpha1.go
