### ISSUE TITLE
Rollouts integration is disabled on this controller; cannot start verification

### ISSUE THREAD

**Issue by abo-abo** [akuity/kargo#2586]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate bug report.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `kargo version`.
* [X] I've pasted logs, if applicable.

# Description
Hi,

I'm trying out Kargo, and `kargo-demo` is working fine.

I've tried extending it by setting up an `AnalysisTemplate` just like in the docs.

However, after a few promotion requests, there's no `AnalysisTemplate` run. The freight simply promotes as before and is marked as healthy.

When I check `kubectl -n kargo-demo get stage test -o yaml`, I see:

```yaml
status:
  freightHistory:
  - id: 1948ea786cddf78d86f43b9f6f18122de6a1b70c
    items:
      Warehouse/kargo-demo:
        images:
        - digest: sha256:f28a6bcae1c32a35e45678de83099e91520eb8ad0777ed1864592269eca89156
          repoURL: docker.io/okrehel/minirepo
          tag: 2409.27.3
        name: 1424c04cccbf0b8a1364cd5fc7651bc989b52cdc
        origin:
          kind: Warehouse
          name: kargo-demo
    verificationHistory:
    - finishTime: "2024-09-27T17:34:56Z"
      id: 8d3c3841-2674-41dd-b124-313b51d187a9
      message: Rollouts integration is disabled on this controller; cannot start verification
      phase: Error
      startTime: "2024-09-27T17:34:56Z"
```

I did some searching and it seems like rollouts integration should be enabled by default unless explicitly disabled.

I did not explicitly disable it, nor do I know how to enable it.

Looking through the issues, #2075 might be related.

# Steps to Reproduce

- Run quickstart
- Add an AnalysisTemplate from https://kargo.akuity.io/concepts/
- Promote
- Check stage status: `verificationHistory` shows verification was not started

# Version

```
Client Version: v0.8.7
Server Version: v0.8.7
```

I run:
- Ubuntu 22.04
- Docker 27.3.1
- kind v0.23.0 go1.21.10 linux/amd64

# Logs

```
Paste any relevant application logs here.
```
