### ISSUE TITLE
bug(promotion): helm-update-image directive does not produce commitMessage when there is no update

### ISSUE THREAD

**Issue by CCOLLOT** [akuity/kargo#2699]
According to [the documentation](https://kargo.akuity.io/references/promotion-steps#helm-update-image-output), the `helm-update-image` step should produce a `commitMessage`

However, my git-commit action does not find any when looking up that step's outputs. I get the following error message even if the previous steps were successful: 
```bash
failed to run step "git-commit": error building commit message: no commit message found in output from step with alias "update-image"; cannot construct commit message
```
<img width="776" alt="image" src="https://github.com/user-attachments/assets/a5b56d8e-1351-4bd8-b57b-0387492e25d1">

Corresponding promotionTemplate (trying to update a single file on main):
```yaml
    steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/org/repo.git
          checkout:
            - branch: main
              path: ./src
      - uses: helm-update-image
        as: update-image
        config:
          path: ./src/path/to/values.yaml
          images:
            - image: repoURL/imageName
              key: image.tag
              value: Tag
      - uses: git-commit
        as: commit
        config:
          path: ./src
          messageFromSteps:
            - update-image
      - uses: git-push
        config:
          path: ./src
          targetBranch: main
```

Not sure if it's my promotionTemplate (and how I try to do the commit) that's wrong as I could not find an example for my use-case or if it's an actual bug
