### ISSUE TITLE
bug(git-commit): author name and email are not taken into account

### ISSUE THREAD

**Issue by CCOLLOT** [akuity/kargo#2700]
When using the following promotionTemplate, the produced commit is from the `"Kargo"` user. I would expect the commit to be from the `"foo"` user
Changing the value of `author.name` or `author.email` does not seem to change anything.

```yaml
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/mygitopsrepo.git
            checkout:
              - branch: main
                path: ./repo
        - uses: helm-update-image
          as: update-image
          config:
            path: ./path/to/values.yaml
            images:
              - image: myimagename
                fromOrigin:
                  kind: Warehouse
                  name: mywarehousename
                key: image.tag
                value: Tag
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            author:
              name: foo
              email: bar@guestbook.com
            messageFromSteps:
              - update-image
        - uses: git-push
          config:
            path: ./repo
            targetBranch: main
```

Besides, I fear that the environment variables provided to the controller via the `.Values.controller.gitClient` chart value are not honored anymore, so signing commits is no longer possible.
