### ISSUE TITLE
feat(helm-promotion): allow arbitrarily updating a key from a yaml file with the new helm chart version

### ISSUE THREAD

**Issue by CCOLLOT** [akuity/kargo#2701]
When promoting images, we can use the following directive:
```yaml
  - uses: helm-update-image
    as: update-image
    config:
      path: ./path/to/values.yaml # arbitrary filename
      images:
        - image: <image-name>
          fromOrigin:
            kind: Warehouse
            name: <warehouseName>
          key: image.Tag # arbitrary key
          value: Tag
```

I would like to be able to do the same thing with helm charts, without needing a Chart.yaml file.
I use an applicationSet to create ArgoCD applications pointing to helm repos based on the content of certain files (containing keys like .chartVersion, .repoURL and .chartName), using the ArgoCD ApplicationSet `git-generator`.

It could either be achieved by making the helm-update-image directive generic, or by extending the current helm-update-chart directive.

Something like that would do the trick:

### Option 1
Introduce a generic directive to update yaml keys based on the supported artifacts
```yaml
# generic directive
  - uses: helm-update-key # or yaml-update-key
    as: update-key
    config:
      path: ./path/to/file.yaml
      update:
        - type: helm # or image
          chartName: <chartName> # or image
          fromOrigin:
            kind: Warehouse
            name: <warehouseName>
          key: my.yaml.key
          value: Version # may be omitted 
```

### Option 2
Alternatively, we could extend the helm-update-chart directive
```yaml
# extending helm-update-chart
  - uses: helm-update-chart
    as: update-key
    config:
      path: ./path/to/file.yaml # if not a directory but a yaml file, do not look for Chart.yaml and expect a key to replace
      charts:
      - repository: https://example-chart-repo
         name: some-chart
         fromOrigin:
            kind: Warehouse
            name: <warehouseName>
        key: my.yaml.key # used only if config.path points to a yaml file and not a directory
        value: Version # may be omitted
    path: ./src/charts/my-chart

```

Option 2 seems like a minor change that would make the helm-update-chart as flexible as helm-update-image. I'm open to contributing if necessary
