### ISSUE TITLE
helm-update-chart - runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ggogel** [akuity/kargo#2726]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I'm trying to setup this simple one stage promotion for our argo-rollouts deployment.

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: my-project-argo-rollouts
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: argo-rollouts
spec:
  subscriptions:
  - chart:
      name: argo-rollouts
      repoURL: https://artifactory.example.services/artifactory/api/helm/helm-all
      discoveryLimit: 10
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: argo-rollouts
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://git.example.services/my-project/my-project-gitops.git
          checkout:
          - branch: master
            path: ./my-project-gitops
      - uses: helm-update-chart
        as: helm-update-chart
        config:
          path: ./my-project-gitops/apps/argo-rollouts/stages/dev
          charts:
          - name: argo-rollouts
            repository: https://artifactory.example.services/artifactory/api/helm/helm-all
      - uses: git-commit
        as: commit
        config:
          path: ./my-project-gitops
          messageFromSteps:
          - helm-update-chart
      - uses: git-push
        config:
          path: ./my-project-gitops
          targetBranch: master
      - uses: argocd-update
        config:
          apps:
          - name: my-project-dev-argo-rollouts
```

The step `git-clone` always fails with `runtime error: invalid memory address or nil pointer dereference`. We tried countless approaches: cloning a different repo, cloning a different branch, cloning from a tag etc. The error remains.

Based on the official demo project, we had set up a working POC with version `v0.7.x`. Now we're trying to implement Kargo for our GitOps Repository holding some basic services required for Continuous Deployment before we use it for applications we develop. Our GitOps Repo is single branch with stages in different folders.

When we enter the container `kargo-controller` with `kubectl exec`, we can see that it successfully cloned the repository under `/tmp/<promotion-id>/my-project-gitops`. I guess that the controller is not cleaning up these folders when it crashes with this null pointer exception. Even with the debug log turned on, we can't understand where and why this error happens.

# Steps to Reproduce

1. Deploy the above YAML.
2. Navigate to the Kargo UI.
3. Try to promote a new Helm Chart Release to the dev stage.

# Version

```
v0.9.1
```

# Logs

```
time="2024-10-11T12:32:03Z" level=debug msg="reconciling Promotion" namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c
time="2024-10-11T12:32:03Z" level=debug msg="promo added to priority queue" namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c
time="2024-10-11T12:32:03Z" level=debug msg="begin promo" namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c
time="2024-10-11T12:32:03Z" level=info msg="began promotion" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="found associated Stage" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="Stage is not awaiting Promotion" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="reconciling Stage" namespace=my-project-argo-rollouts stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="found Stage" namespace=my-project-argo-rollouts stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="Stage has a running Promotion" namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="checking for new terminated Promotions" namespace=my-project-argo-rollouts stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="reconciling Promotion" namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c
time="2024-10-11T12:32:03Z" level=debug msg="continuing Promotion" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="found associated Stage" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="Stage is not awaiting Promotion" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="reconciling Promotion" namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c
time="2024-10-11T12:32:03Z" level=debug msg="continuing Promotion" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="found associated Stage" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="Stage is not awaiting Promotion" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="Stage has no current Freight; no health checks or verification to perform" namespace=my-project-argo-rollouts stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="checking if auto-promotion is permitted..." namespace=my-project-argo-rollouts stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="found no PromotionPolicy associated with the Stage" namespace=my-project-argo-rollouts stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="auto-promotion is not permitted for the Stage" namespace=my-project-argo-rollouts stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="reconciling Promotion" namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c
time="2024-10-11T12:32:03Z" level=debug msg="continuing Promotion" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="found associated Stage" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:03Z" level=debug msg="done reconciling Stage" namespace=my-project-argo-rollouts stage=dev
time="2024-10-11T12:32:04Z" level=error msg="Promotion panic" error="runtime error: invalid memory address or nil pointer dereference" freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:04Z" level=info msg=promotion freight=464f55c2a8459348b6fb73243ef1c38faff59132 namespace=my-project-argo-rollouts phase="\"Errored\"" promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c stage=dev
time="2024-10-11T12:32:04Z" level=debug msg="concluded promo" namespace=my-project-argo-rollouts promotion=dev.01j9xs12c87gqxm48vm7zy1rme.464f55c
```
