### ISSUE TITLE
bug(ui) Support of Multi-Pipeline Freights with promotionTemplate steps not working

### ISSUE THREAD

**Issue by dan1el-k** [akuity/kargo#2734]
# Checklist

* [ ] I've searched the issue queue to verify this is not a duplicate bug report.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

The previously improved [Multi-Pipeline support in the UI](https://github.com/akuity/kargo/issues/2302) seems to not working.

I used 2 git subscriptions per Warehouse. 
- 1 containing base charts from manifest repo
- 1 containing stages values from values repo
I have 2 separate freights created, one per warehouse.

The UI however just show the latest Freight. The "next" buttons are missing, which were introduced in #2353

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: kube2-dev-common
  namespace: mercury-debug
  finalizers:
    - kargo.akuity.io/finalizer
spec:
  promotionTemplate:
    spec:
      steps:
        - config:
            checkout:
              - branch: main
                path: ./mm
              - branch: stage/kube2-dev-common
                create: true
                path: ./out
            repoURL: 'https://my-domain/my-org/mercury-manifest.git'
          uses: git-clone
        - config:
            checkout:
              - fromFreight: true
                fromOrigin:
                  kind: Warehouse
                  name: mercury-dex
                path: ./dex
            repoURL: 'https://my-domain/my-org/mercury-dex-manifest.git'
          uses: git-clone
        - config:
            checkout:
              - fromFreight: true
                fromOrigin:
                  kind: Warehouse
                  name: mercury-apptio-agent
                path: ./apptio-agent
            repoURL: 'https://my-domain/my-org/mercury-apptio-agent-manifest.git'
          uses: git-clone
        - config:
            inPath: ./mm/applications
            outPath: ./out
          uses: copy
        - config:
            inPath: ./dex/deployment
            outPath: ./out/mercury-dex/stages/kube2-dev/deployment
          uses: copy
        - config:
            inPath: ./apptio-agent/deployment
            outPath: ./out/mercury-apptio-agent/stages/kube2-dev/deployment
          uses: copy
        - config:
            message: Always pass on what you have learned.
            path: ./out
          uses: git-commit
        - config:
            path: ./out
            targetBranch: stage/kube2-dev-common
          uses: git-push
  requestedFreight:
    - origin:
        kind: Warehouse
        name: mercury-dex
      sources:
        direct: true
    - origin:
        kind: Warehouse
        name: mercury-apptio-agent
      sources:
        direct: true
```

# Screenshots

Project
![image](https://github.com/user-attachments/assets/1a203916-d948-4cb7-8801-d9d2eb5c825e)

Freigts
![image](https://github.com/user-attachments/assets/c68094d6-41fa-48e6-8da7-3ea442c0c136)

# Steps to Reproduce

# Version

```
0.9.0
```

# Logs

```
Paste any relevant application logs here.
```
