### ISSUE TITLE
Deep link to Argo CD application lost with Promotion Directives

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2746]
# Description

We lost the deep link feature to the Argo CD application in v0.9. The following link is no longer present on Stages using promotion directives (but still present on ones that use promotionMechanisms).

![image](https://github.com/user-attachments/assets/8d2b3dec-754d-49bd-bad2-79b7f437e131)

# Steps to Reproduce

Any stage that references an Argo CD app using promotionTemplate steps will not have the link.

I think the UI will need to iterate the promotion steps and construct the links based on `argocd-update` steps.

```yaml
        - uses: argocd-update
          config:
            apps:
              - name: guestbook
```

# Version

```
v0.9
```
