### ISSUE TITLE
Promotion Directives could populate metadata into status

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2752]
# Proposed Feature

We should provide a way for directives to produce metadata in a status field. For example, the `argocd-update` step could populate application names and/or URLs:

```yaml
status:
  metadata:
    argocd-update:
      applications:            # the structure under the directive name would be free to update
      - name: guestbook-a
         url: https://argocd.example.com/applications/argocd/guestbook
```

# Motivation

1. We wish to provide 3rd party directives equal footing to native directives (such as presenting information into the UI)
2. We recently lost the ability to use wildcards for `authorized-stages`. The reason was partly technical since application name references were no longer easily discoverable. But if we allowed directives to populate information into a well known status location, it would restore our ability to index on them.

# Suggested Implementation

The directive interface should have the ability to return stage metadata that we could store in the stage's status.
