### ISSUE TITLE
Stage sourced by multiple warehouses always result in error when promoting first time

### ISSUE THREAD

**Issue by kejne** [akuity/kargo#2757]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

When setting up multiple warehouses and promoting to a stage which needs to update multiple images, it is not possible to promote to the stage the first time, since it fails when running the update image step.
However, it will work to promote if promoting all of the required images - but there should be some kind of indication that the promotion didn't completely fail.

# Screenshots
![image](https://github.com/user-attachments/assets/9eb902e5-6a4b-4d24-849c-4cdb4d2e978f)

# Steps to Reproduce

1. Create multiple warehouses that pull in different images
2. Setup a promotionTemplate like so:
```yaml
promotionTemplate:
    spec:
      steps:
        - config:
            checkout:
              - branch: main
                path: ./src
              - branch: deploy/prod
                create: true
                path: ./out
            repoURL: https://github.com/myowner/myrepo.git
          uses: git-clone
        - config:
            path: ./out
          uses: git-clear
        - as: update-image
          config:
            images:
              - fromOrigin:
                  kind: Warehouse
                  name: canary
                image: mycanaryrepo
              - fromOrigin:
                  kind: Warehouse
                  name: tester
                image: mytesterimage
            path: ./src/infrastructure/overlays/prod
          uses: kustomize-set-image
        - config:
            outPath: ./out
            path: ./src/infrastructure/overlays/prod
          uses: kustomize-build
        - as: commit
          config:
            messageFromSteps:
              - update-image
            path: ./out
          uses: git-commit
        - config:
            path: ./out
          uses: git-push
        - config:
            apps:
              - name: drive-canary-prod
                sources:
                  - desiredCommitFromStep: commit
                    repoURL: https://github.com/myowner/myrepo.git
          uses: argocd-update
  requestedFreight:
    - origin:
        kind: Warehouse
        name: canary
      sources:
        stages:
          - stg
    - origin:
        kind: Warehouse
        name: tester
      sources:
        stages:
          - stg
```

# Version

```
0.9.1
```
