### ISSUE TITLE
Sharding not working properly

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#2791]
# Description

The following situation occurred because two controllers were reconciling the same Promotion

```yaml
status:
  phase: Succeeded
  message: 'failed to run step "argocd-update": Argo CD integration is disabled on
    this controller; cannot update Argo CD Application resources'
```

# Screenshots

<img width="653" alt="image" src="https://github.com/user-attachments/assets/cd3508f0-ee3d-4704-a3b6-2023468d5165">

# Steps to Reproduce

# Version

```
v1.0.0
```

# Logs

```
Paste any relevant application logs here.
```
