### ISSUE TITLE
git-open-pr : private gitlab server not working

### ISSUE THREAD

**Issue by flbla** [akuity/kargo#2792]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate bug report.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `kargo version`.
* [X] I've pasted logs, if applicable.

# Description

I have a stage with a git-open-pr step. 
I'm using a private gitlab server.

I'm getting this error when I try to promote : `failed to run step "git-open-pr": error creating git provider service: No registered providers with name "gitlab"`

Does private gitlab server are supported ?

# Steps to Reproduce

```
  promotionTemplate:
    spec:
      steps:
      # some steps
      # ...
        - as: push
          config:
            generateTargetBranch: true
            path: ./out
          uses: git-push
        - as: open-pr
          config:
            createTargetBranch: true
            insecureSkipTLSVerify: true
            provider: gitlab
            repoURL: https://privateGitlab.com/repo.git
            sourceBranchFromStep: push
            targetBranch: out
          uses: git-open-pr
```

I also try without the "provider".
The error was almost the same : `failed to run step "git-open-pr": error creating git provider service: No registered providers with name "https://privateGitlab.com/repo.git"`

# Version

```
/ $ kargo version
{
  "Version": "v1.0.0",
  "BuildDate": "2024-10-19T01:45:22Z",
  "GitCommit": "cf1278071ae31e2c79b4bf77dc125fb081c0aff3",
  "GitTreeDirty": false,
  "GoVersion": "go1.23.2",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

# Logs

```
time="2024-10-21T15:30:19Z" level=error msg="error executing Promotion" error="failed to run step \"git-open-pr\": error creating git provider service: No registered providers with name \"gitlab\""
```
