### ISSUE TITLE
The clusterRole `kargo-controller-read-secrets` appears to be missing an appropriate `clusterRoleBinding` when using `globalCredentials`.

### ISSUE THREAD

**Issue by pww217** [akuity/kargo#2796]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

The Controller's service account when setting the Helm values as globalCredentials below appears to be missing a required clusterRoleBinding for the clusterRole `kargo-controller-read-secrets`

Basically, can't access the global credentials secret in the same namespace `kargo`, as it's not allowed to `list`. See logs below.

I could fix this by manually apply in the binding. See the before-after here.

```
❯ kubectl auth can-i list secrets --as=system:serviceaccount:kargo:kargo-controller -n kargo

no
❯ cat crb.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-controller-read-secrets-binding
subjects:
- kind: ServiceAccount
  name: kargo-controller
  namespace: kargo
roleRef:
  kind: ClusterRole
  name: kargo-controller-read-secrets
  apiGroup: rbac.authorization.k8s.io

❯ kc apply -f crb.yaml
clusterrolebinding.rbac.authorization.k8s.io/kargo-controller-read-secrets-binding created
❯ kubectl auth can-i list secrets --as=system:serviceaccount:kargo:kargo-controller -n kargo

yes
```

And this fixed up the ECR auth pretty immediate in the UI too. I may be able to make this fix myself if someone doesn't beat me to it, but wanted to make you aware.

# Screenshots

# Steps to Reproduce

Using Kargo v1.0.0

Set the Helm values to use globalCredentials like so:

```
controller:
  globalCredentials:
    namespaces: 
      - kargo
```

My understanding is that without this, it'll only look for credentials in the `Project`'s namespace.

# Version

v1.0.0

```
{
  "Version": "v1.0.0",
  "BuildDate": "2024-10-19T01:45:22Z",
  "GitCommit": "cf1278071ae31e2c79b4bf77dc125fb081c0aff3",
  "GitTreeDirty": false,
  "GoVersion": "go1.23.2",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

# Logs

```
time="2024-10-21T17:11:28Z" level=error msg="error syncing Warehouse" error="error discovering artifacts: error discovering images: error obtaining credentials for image repo \"<awsAccountNumber>.dkr.ecr.us-east-1.amazonaws.com/some/image\": secrets is forbidden: User \"system:serviceaccount:kargo:kargo-controller\" cannot list resource \"secrets\" in API group \"\" in the namespace \"kargo\"" namespace=kargo-project warehouse=kargo-project-some-app-warehouse
time="2024-10-21T17:11:28Z" level=error msg="Reconciler error" Warehouse="{kargo-project-some-app-warehouse kargo-project}" controller=warehouse controllerGroup=kargo.akuity.io controllerKind=Warehouse error="error discovering artifacts: error discovering images: error obtaining credentials for image repo \"<awsAccountNumber>.dkr.ecr.us-east-1.amazonaws.com/some/image\": secrets is forbidden: User \"system:serviceaccount:kargo:kargo-controller\" cannot list resource \"secrets\" in API group \"\" in the namespace \"kargo\"" name=kargo-project-some-app-warehouse namespace=kargo-project reconcileID="\"0d96659b-133e-45bf-8d49-a4791ee1d4b5\
```

**Comment by pww217** [comment]
This seems like the PR that added the new clusterRole but without a binding.

https://github.com/akuity/kargo/commit/8ff3121e10923aee63fec4f1dde5f5d5d78d7d8c

**Comment by krancour** [comment]
🤦‍♂️ This change was deliberate. The true mistake is that we failed to acknowledge this as a breaking change in the release notes.

For reference:

https://github.com/akuity/kargo/blob/98a39396ac0d193d49a1e624086031c23dab8e9e/charts/kargo/values.yaml#L368-L378

I am updating the release notes as we speak.

**Comment by pww217** [comment]
Cool, well glad I could be some help. Thanks for the fast response. I suppose that makes sense. I guess I'd like to be able to scope it to just the main control plane Namespace `kargo` without giving it access to all others as well. 

But it seems like the only options are "cluster-wide read access for secrets" or "per Project namespace" only.

I wonder if it makes sense to use `globalCredentials.namespaces` as a source for role and roleBindings? As in, a secret-reading role that is scoped to only the globalCredentials namespace(s)? In my case I simply put this secret in the control-plane NS and use a GH App. That way maybe we can still have decent RBAC where we can use global credentials while not giving the control cluster-wide read access?

Or am I thinking about this all wrong?

**Comment by pww217** [comment]
Doh! If I had actually read your new release notes first I woulda seen that your suggested solution is a separate roleBinding.

I will do that for now to keep security a bit tighter but I do wonder what you think of my idea above, regardless.

**Comment by pww217** [comment]
Alright just to confirm, the (role)bindings worked fine. 

I applied the following for anyone who runs into this in the future:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kargo
  name: kargo-controller-read-global-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
```

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-controller-read-global-secrets-binding
  namespace: kargo
subjects:
- kind: ServiceAccount
  name: kargo-controller
  namespace: kargo
roleRef:
  kind: Role
  name: kargo-controller-read-global-secrets
  apiGroup: rbac.authorization.k8s.io
```
