### ISSUE TITLE
helm-update-image fails after upgrade to v1.0.x

### ISSUE THREAD

**Issue by ggogel-exxeta** [akuity/kargo#2809]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I've implemented a working promotion template using `helm-update-image` in v0.9.1. After upgrading to v1.0.0 and v1.0.1. The promotion is no longer working and fails with the following error:

```
failed to run step "helm-update-image": values file update failed: error updating image references in values file "./test-gitops-gitops/apps/test-gitops/stages/dev/values.yaml": error mutating bytes: error finding key frontend.image.tag: key path not found
```

The configuration:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: test-gitops
spec:
  subscriptions:
  - image:
      repoURL: artifactory.example.services:5308/test-gitops-frontend
      discoveryLimit: 10
      imageSelectionStrategy: NewestBuild
  - image:
      repoURL: artifactory.example.services:5308/test-gitops-backend
      discoveryLimit: 10
      imageSelectionStrategy: NewestBuild
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: test-gitops
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://git.example.services/releng/templates/gitops-repo-template.git
          checkout:
          - branch: test-gitops
            path: ./test-gitops-gitops
      - uses: helm-update-image
        as: helm-update-image
        config:
          path: ./test-gitops-gitops/apps/test-gitops/stages/dev/values.yaml
          images:
            - image: artifactory.example.services:5308/test-gitops-frontend
              key: frontend.image.tag
              value: Tag
            - image: artifactory.example.services:5308/test-gitops-backend
              key: backend.image.tag
              value: Tag
      - uses: git-commit
        as: commit
        config:
          path: ./test-gitops-gitops
          messageFromSteps:
          - helm-update-image
      - uses: git-push
        config:
          path: ./test-gitops-gitops
          targetBranch: test-gitops
      - uses: argocd-update
        config:
          apps:
          - name: test-gitops-dev
```

values.yaml:
```
fronted:
  replicaCount: 1
  image:
    repository: artifactory.example.services:5308/test-gitops-frontend
    tag: 0.0.1
backend:
  replicaCount: 1
  image:
    repository: artifactory.example.services:5308/test-gitops-backend
    tag: 0.0.2
```

# Steps to Reproduce

1. Use Kargo v0.9.1
2. Create a stage with a promotion using `helm-update-image`. The promotion works without errors.
3. Upgrade to Kargo v1.0.1
4. Try the promotion again. It fails with the above error.

# Version

```
v1.0.1
```
