### ISSUE TITLE
pipelines are rendered in random order

### ISSUE THREAD

**Issue by ddeath** [akuity/kargo#2861]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description
If you have multiple "pipelines" then order of this pipelines is "random" / changing over time.

If I have microservice-a and microservice-b then sometimes pipeline for microservice-a is first on top of the page, sometimes microservice-b pipeline is first. Imho the order should be always first

# Screenshots

<img width="904" alt="Screenshot 2024-10-28 at 12 39 41" src="https://github.com/user-attachments/assets/a8abe42a-3fd1-4ba4-a47f-066ec87f9f71">
<img width="915" alt="Screenshot 2024-10-28 at 12 42 16" src="https://github.com/user-attachments/assets/2e9186b0-4eb9-4267-8201-cc9bfac49a0e">

# Steps to Reproduce

Create multiple pipelines for microservice (microservice-a, microservice-b, microservice-c) and then go to project page and refresh it multiple times and observe that order is changing.

This is because from the code it looks like we do not "sort" the nodes in any way and those pipelines are rendered based on nodes order.

# Version

1.0.3

# Logs

-

My suggestion is to apply sorting of the node, the question would be based on what? For my example the first stage name would be sufficient. The goal is to have same order every time.
Additional question: Would it be ok to add "order" annotation? therefore we could specify our desired order. Maybe some service is used often then others or is more important so we would like to keep it on top. Question would be where to put such annotation since we dont have representation for pipeline 🤔 So maybe stage....

Actually:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: testing-playground
  namespace: kargo
spec:
  promotionPolicies:
   - stage: int-microservice-a
   - stage: int-microservice-b
   - stage: int-microservice-c
   - stage: int-microservice-d
   - stage: int-microservice-e
   - stage: int-microservice-f
```

We kind of have "order" in `Project` entity. How about we use order of those Stages? Not sure if that would work because multiple stages can be in same pipeline so we have some edge case so ordering will not be straightforward....
