### ISSUE TITLE
Argo CD Application "XXX" in namespace "argocd" does not permit mutation by Kargo Stage dev in namespace YYY

### ISSUE THREAD

**Issue by wqbbs911** [akuity/kargo#2876]
# Checklist

* [y ] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description
first , i am not sure this is bug , because i test in kargo-demo project ,it works.
maybe it cause by my incorrect configuration, but i don't know how to fix it now!

installed ApplicationSet in argocd with namespace ctms-schedule-provider-dev , and configure project  ctms-schedule-provider-kargo in kargo to trigger it ,but when i promot it ,it report like：
```
failed to run step "argocd-update": error getting Argo CD Application "ctms-schedule-provider-dev" in namespace "argocd": Argo CD Application "ctms-schedule-provider-dev" in namespace "argocd" does not permit mutation by Kargo Stage dev in namespace ctms-schedule-provider-kargo
```

# Screenshots
![image](https://github.com/user-attachments/assets/1a5a017b-b8ee-4535-9575-185d8335404e)

# Steps to Reproduce
argocd applicationset.yaml:
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ctms-schedule-provider
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://10.10.254.8
      - cluster: test
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'ctms-schedule-provider-{{.cluster}}'
    spec:
      project: default
      sources:
      - repoURL: 'https://registry.ops.eclincloud.net/chartrepo/ecc-helm-chart' # helm所在的git仓库地址(后面需要推送的git仓库)
        chart: ecc-service
        targetRevision: 0.1.1
        helm:
          valueFiles:
            - $values/base/{{.cluster}}/values.yaml
      - repoURL: 'https://git.ops.eclincloud.net/ops/devops/ctms-schedule-provider-demo.git'
        targetRevision: HEAD
        ref: values

      destination:
        server: '{{.url}}'
        namespace: 'ctms-schedule-provider-{{.cluster}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            factor: 2
            maxDuration: 1m
```

kargo-ctms.yaml:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: ctms-schedule-provider-kargo
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ctms-schedule-provider-repo
  namespace: ctms-schedule-provider-kargo
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://git.ops.eclincloud.net/ops/devops/ctms-schedule-provider-demo.git
  username: aaa
  password: glpat-abcdefg
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ctms-schedule-provider-docker
  namespace: ctms-schedule-provider-kargo
  labels:
    kargo.akuity.io/cred-type: image
stringData:
  repoURL: registry.ops.eclincloud.net/eclin-ctms/ctms-schedule-provider/ctms-schedule-provider
  username: aaa
  password: test123
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ctms-schedule-provider
  namespace: ctms-schedule-provider-kargo
spec:
  subscriptions:
  - image:
      imageSelectionStrategy: Lexical
      strictSemvers: false
      repoURL: registry.ops.eclincloud.net/eclin-ctms/ctms-schedule-provider/ctms-schedule-provider
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: ctms-schedule-provider-kargo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: ctms-schedule-provider
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://git.ops.eclincloud.net/ops/devops/ctms-schedule-provider-demo.git
          checkout:
          - branch: main
            path: ./src
      - uses: helm-update-image
        as: helm-update-image
        config:
          path: ./src/base/dev/values.yaml
          images:
          - image: registry.ops.eclincloud.net/eclin-ctms/ctms-schedule-provider/ctms-schedule-provider
            key: image.tag
            value: Tag
      - uses: git-commit
        as: commit
        config:
          path: ./src
          messageFromSteps:
          - helm-update-image
      - uses: git-push
        config:
          path: ./src
          targetBranch: main
      - uses: argocd-update
        config:
          apps:
          - name: ctms-schedule-provider-dev
```

# Version

```
v1.0.3
```

# Logs

kargo-controller pod logs:
```
time="2024-10-30T03:58:57Z" level=info msg="began promotion" freight=f549f1a14aa82037adb51f21cc379be0da1e248f namespace=ctms-schedule-provider-kargo promotion=dev.01jbds76xxt91ntthe2tdyc6dt.f549f1a stage=dev
time="2024-10-30T03:58:57Z" level=error msg="error executing Promotion" error="failed to run step \"argocd-update\": error getting Argo CD Application \"ctms-schedule-provider-dev\" in namespace \"argocd\": Argo CD Application \"ctms-schedule-provider-dev\" in namespace \"argocd\" does not permit mutation by Kargo Stage dev in namespace ctms-schedule-provider-kargo" freight=f549f1a14aa82037adb51f21cc379be0da1e248f namespace=ctms-schedule-provider-kargo promotion=dev.01jbds76xxt91ntthe2tdyc6dt.f549f1a stage=dev
time="2024-10-30T03:58:57Z" level=info msg=promotion freight=f549f1a14aa82037adb51f21cc379be0da1e248f namespace=ctms-schedule-provider-kargo phase="\"Errored\"" promotion=dev.01jbds76xxt91ntthe2tdyc6dt.f549f1a stage=dev
```
argocd-applicationset-controller pod logs:
```
root@CD-W00044:/mnt/d/ECC/apps/ecc_git# kubectl logs argocd-applicationset-controller-b8b4bc9d9-pg9ml -n argocd --tail=20
time="2024-10-30T04:06:34Z" level=debug msg="requeue: false caused by application kargo-demo-test\n" app=argocd/kargo-demo-test requeue=false
time="2024-10-30T04:06:34Z" level=debug msg="received update event from owning an application" app=argocd/ctms-schedule-provider-test
time="2024-10-30T04:06:34Z" level=debug msg="requeue: false caused by application ctms-schedule-provider-test\n" app=argocd/ctms-schedule-provider-test requeue=false
time="2024-10-30T04:06:34Z" level=debug msg="received update event from owning an application" app=argocd/dev-ctms-schedule-provider
time="2024-10-30T04:06:34Z" level=debug msg="requeue: false caused by application dev-ctms-schedule-provider\n" app=argocd/dev-ctms-schedule-provider requeue=false
time="2024-10-30T04:06:34Z" level=debug msg="received update event from owning an application" app=argocd/ctms-schedule-provider-dev
time="2024-10-30T04:06:34Z" level=debug msg="requeue: false caused by application ctms-schedule-provider-dev\n" app=argocd/ctms-schedule-provider-dev requeue=false
time="2024-10-30T04:07:02Z" level=info msg="Alloc=19071 TotalAlloc=10914814 Sys=97880 NumGC=8941 Goroutines=141"
time="2024-10-30T04:09:34Z" level=debug msg="received update event from owning an application" app=argocd/kargo-demo-prod
time="2024-10-30T04:09:34Z" level=debug msg="requeue: false caused by application kargo-demo-prod\n" app=argocd/kargo-demo-prod requeue=false
time="2024-10-30T04:09:34Z" level=debug msg="received update event from owning an application" app=argocd/ctms-schedule-provider-dev
time="2024-10-30T04:09:34Z" level=debug msg="requeue: false caused by application ctms-schedule-provider-dev\n" app=argocd/ctms-schedule-provider-dev requeue=false
time="2024-10-30T04:09:34Z" level=debug msg="received update event from owning an application" app=argocd/dev-ctms-schedule-provider
time="2024-10-30T04:09:34Z" level=debug msg="requeue: false caused by application dev-ctms-schedule-provider\n" app=argocd/dev-ctms-schedule-provider requeue=false
time="2024-10-30T04:09:35Z" level=debug msg="received update event from owning an application" app=argocd/kargo-demo-test
time="2024-10-30T04:09:35Z" level=debug msg="requeue: false caused by application kargo-demo-test\n" app=argocd/kargo-demo-test requeue=false
time="2024-10-30T04:09:35Z" level=debug msg="received update event from owning an application" app=argocd/kargo-demo-uat
time="2024-10-30T04:09:35Z" level=debug msg="requeue: false caused by application kargo-demo-uat\n" app=argocd/kargo-demo-uat requeue=false
time="2024-10-30T04:09:35Z" level=debug msg="received update event from owning an application" app=argocd/ctms-schedule-provider-test
time="2024-10-30T04:09:35Z" level=debug msg="requeue: false caused by application ctms-schedule-provider-test\n" app=argocd/ctms-schedule-provider-test requeue=false
``` 

any suggestions are appreciate, thanks very much!
