### ISSUE TITLE
helm-update-image doesn't do anything if value isn't in the values file, reports success

### ISSUE THREAD

**Issue by mmclane** [akuity/kargo#2900]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description
I have a kargo promotion workflow that includes the helm-update-image.  This works if the value to be updated exists in the values file.  If it doesn't, kargo reports that it has updated the value but it doesn't actually commit anything so nothing is updated.

# Screenshots
![image](https://github.com/user-attachments/assets/57aea011-db37-440e-b5ee-2136529a86dd)

# Steps to Reproduce

Set the promotionTemplate something like this:
```
promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          as: clone
          config:
            repoURL: https://github.com/docnetwork/k8s-configs.git
            checkout:
            - branch: main
              path: ./k8s-config
        - uses: helm-update-image
          as: update-values
          config:
            path: ./k8s-config/helm-values/dev/mclaneinator.yaml
            images:
              - image: repos.doc.network/m3test/m3test
                key: job.image.tag
                value: Tag
              - image: repos.doc.network/microfrontends/imms-reg
                key: mfe.image.tag
                value: Tag
        - uses: git-commit
          as: commit
          config:
            path: ./k8s-config
            messageFromSteps:
            - update-values
        - uses: git-push
          as: push
          config:
            path: ./k8s-config

        - uses: argocd-update
          as: sync
          config:
            apps:
            - name:  dev-mclaneinator
              sources:
              - chart: m3test
                updateTargetRevision: True
                repoURL:  repos.doc.network/helm-charts
```
but do not include mfe.image.tag in the values file that is being updated.  Kargo will not add the value nor will it indicate that it hasn't updated that value.

# Version

![image](https://github.com/user-attachments/assets/fda6a746-cf37-48d2-ba31-f9d57b95f2aa)

# Logs

```
time="2024-11-05T16:40:22Z" level=info msg="began promotion" freight=8bb36ec2bd37396d7cba741fe4438febe4f56ac3 namespace=imms-reg promotion=dev.01jbyk5qk9j1a1h1r2xx8mb48x.8bb36ec stage=dev
time="2024-11-05T16:40:35Z" level=info msg=promotion freight=8bb36ec2bd37396d7cba741fe4438febe4f56ac3 namespace=imms-reg phase="\"Succeeded\"" promotion=dev.01jbyk5qk9j1a1h1r2xx8mb48x.8bb36ec stage=dev
time="2024-11-05T16:47:59Z" level=info msg="began promotion" freight=8bb36ec2bd37396d7cba741fe4438febe4f56ac3 namespace=imms-reg promotion=dev.01jbykknrx0x21tyhr811qn329.8bb36ec stage=dev
time="2024-11-05T16:48:01Z" level=info msg=promotion freight=8bb36ec2bd37396d7cba741fe4438febe4f56ac3 namespace=imms-reg phase="\"Succeeded\"" promotion=dev.01jbykknrx0x21tyhr811qn329.8bb36ec stage=dev
time="2024-11-05T16:50:06Z" level=info msg="began promotion" freight=47377799a33d59d2c0f850ce1ece1206c0e01418 namespace=mclaneinator promotion=qa.01jbykqhmq712axmsrh7ak8484.4737779 stage=qa
time="2024-11-05T16:50:12Z" level=info msg=promotion freight=47377799a33d59d2c0f850ce1ece1206c0e01418 namespace=mclaneinator phase="\"Succeeded\"" promotion=qa.01jbykqhmq712axmsrh7ak8484.4737779 stage=qa

```
