### ISSUE TITLE
Select Stage Dependencies with Selectors

### ISSUE THREAD

**Issue by Bourne-ID** [akuity/kargo#2922]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate feature request.
* [X] I've pasted the output of `kargo version`, if applicable.
* [X] I've pasted logs, if applicable.

# Proposed Feature

Allow Stage dependencies (`spec.requestedFreight[].sources.stages`) to be selected by selector (labels or something similar) allowing for dynamic stage dependency mapping. 

# Motivation

I aim to replace my usage of AppSet Progressive Syncs with Kargo to manage and maintain our cluster addons. To achieve this simplistically, each cluster is either marked as dev, stage or prod. These clusters are automatically generated as a Kargo Stages through an AppSet with Cluster generator (pending #339). My clusters are dynamic and may change, but I want to enforce my stage dependencies automatically. 

Right now my stage dependencies are set manually as this is a static list of known stages. 

# Suggested Implementation

Being able to use a labelSelector (or similar) allows me to label stages with the environment and have them automatically map the dependencies. Whilst #339 states dependency mappings, I feel this is a smaller change and something that could provide value whilst the full StageSet implementation is designed out.

**Comment by Bourne-ID** [comment]
cc @jessesuen in relation to our chat at Kubecon - thank you for your time!

**Comment by jessesuen** [comment]
Today, we support explicit references:

```yaml
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        direct: false
        stages:
          - ab-test-a
          - ab-test-b
```

The proposal is to support something like:

```yaml
  requestedFreight:
    - origin:
        kind: Warehouse
        name: guestbook
      sources:
        direct: false
        selector:
          matchLabels:
            env: preprod
```
