### ISSUE TITLE
feat(Warehouse): Subscribe to Git tags

### ISSUE THREAD

**Issue by asolanki-mgni** [akuity/kargo#2955]
# Proposed Feature

I would like to have the ability to have a Warehouse subscribe to git tags within a repo. When a new git tag is created I would like Kargo to create a freight so I can progress the freight to the different stages. 

A promotionMechanism should also be created so I can update a values file with the newly created tag.

# Motivation

We currently follow the apps of apps pattern in ArgoCD. We have helm-<team>-parent which sources multiple child apps. In the child apps, the devs can make the needed code changes (helm or image) and when changes are ready they will commit, merge and finally tag.

In the helm-<team>-parent repo, we manage the clusters that the child apps are deployed to with their specific version tags in different values files.

I would like to subscribe to a repo's git tags and when a new tag is created be able to have a promotionMechanism to update a values file with the new tag value.

# Suggested Implementation

Warehouse:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: git-tag-warehouse
spec:
  subscriptions:
  - git:
      repoURL: <git repo url>
      tag: <git tag regex>
```

Stage:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
...
spec:
...
  promotionMechanisms:
    gitTagUpdates:
    - repoURL: <git repo url>
      writeBranch: <branch name>
      readBranch: <branch name>
      value: <tag value name>
      valuesFilePath: <values file path>
```
