### ISSUE TITLE
Infinite loop when promoting image

### ISSUE THREAD

**Issue by stephaneetje** [akuity/kargo#2968]
Hello, 

I've been trying to use kargo to only promote image tags (using helm-image-update) but on all my stages, i get an inifnite loop at the argocd-update step.

Here is my stage:

```
      steps:
        - config:
            checkout:
              - branch: main
                path: ./src
            repoURL: https://github.com/test/test-helm.git
          uses: git-clone
        - as: update-image
          config:
            images:
              - image: europe-docker.pkg.dev/test-001/test/scim
                key: image.tag
                value: Tag
            path: ./src/helm/scim/values-scim-staging-image.yaml
          uses: helm-update-image
        - as: commit
          config:
            messageFromSteps:
              - update-image
            path: ./src
          uses: git-commit
        - config:
            path: ./src
          uses: git-push
        - config:
            apps:
              - name: scim-staging
                sources:
                  - desiredCommitFromStep: commit
                    repoURL: https://github.com/test/test-helm.git
          uses: argocd-update
```

I also tried removing `desiredCommitFromStep` but didn't change anything.
My warehouse is only subscribing an image repository:

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    kargo.akuity.io/color: black
  name: scim-prod
  namespace: scim
spec:
  subscriptions:
  - image:
      imageSelectionStrategy: SemVer
      repoURL: europe-docker.pkg.dev/test-01/test/scim
      discoveryLimit: 10
      allowTags: ^v(\d+\.)?(\d+\.)?(\*|\d+)$
```

You can see in the Argocd app's envents that it is looping
<img width="1188" alt="Capture d’écran 2024-11-20 à 12 38 54" src="https://github.com/user-attachments/assets/53389d9b-ddd1-4ff0-b7b9-e91d6f317fa7">

Discussion has began on [this issue](https://github.com/akuity/kargo/issues/2952), opening another one as asked by @krancour

**Comment by krancour** [comment]
@stephaneetje my apologies, as I seem to have misunderstood the nature of your loop. With the previous discussion having taken place in a thread about `desiredCommit`, I was misled into believing that to have been an actual factor in your problem. If you leave that field alone, as you are currently, AND if there is no commit in your Freight, then when syncing an App, Kargo has no notion of what specific revision that App should observably be synced to once complete.

This means the cause of your loop has nothing to do with a mismatch of the desired revision.

The continuous syncing is _probably_ due to the argocd-update step syncing, then when checking to see if the sync completed, discovering that the most recently completely sync wasn't the one _it_ asked for. It's waiting for its request to complete and seeing _a_ sync completed, but that operation must have been initiated by someone or something else, so it tries again.

Do you happen to have auto-sync enabled on your Apps? It is possible _that_ is what the update step is fighting a losing battle against. We do generally suggest disabling autosync oh Apps when you use Kargo. I will address it in the docs to make that more clear.

If this ends up not being the issue, enabling debug logging on the controller should provide more insight into what conditions are causing the update step to be caught in this sync loop.

**Comment by krancour** [comment]
> I verified and sync is comming from Kargo

Oh. I had no doubt of that.

The mystery is why Kargo is syncing over and over again -- which would usually be because:

1. It initiates a sync operation
2. It follows up on the status of the last operation
3. Finds something unsatisfactory about the status of the last operation
4. Tries again

I'm trying to piece together what's going wrong at step 3 and it was conjecture that something _besides_ Kargo might also be initiating syncs.

I am attempting to replicate this.

**Comment by hiddeco** [comment]
Running a build with #2936 in it should make it much easier to trace the reason without having to try to reproduce it.

**Comment by hiddeco** [comment]
> Running a build with #2936 in it should make it much easier to trace the reason without having to try to reproduce it.

`ghcr.io/hiddeco/kargo:1.0.4-rc.66550612` built from our `release-1.0` branch should log the reason for the infinite loop, if any.

**Comment by hghtwr** [comment]
I have the same problem and this is what I found in the logs: 
```
time="2024-11-20T18:21:15Z" level=debug msg="sync result revisions [0b8559a96d3441da09b2c84f6bd85f8fa06e56d1] do not match desired revisions [62429f4247599ff1746023c29e4514e24dee322e]" freight=d82c676db847dce25b54c3328801ec10fae9592b namespace=kargo-poc-tags promotion=teststable-tags.01jd5cw76w9waj367f69rsk1ek.d82c676 stage=teststable-tags
```

While `0b8559` being the head of the branch (with new manifests in a separate folder) and `62429f` being the commit the freight originated from.

**Comment by stephaneetje** [comment]
@krancour  i just tried with only the name :
```
      - uses: argocd-update
        config:
          apps:
            - name: scim-staging
```

Step passes well, but i end up with the application being synced successfully (not with the latest comit which is kargo one's with the image update), then outofsync (image has not been updated). I have to do another manual sync...
