### ISSUE TITLE
Project level permission

### ISSUE THREAD

**Issue by creeram** [akuity/kargo#3023]
I didn't find an option to grant a user access only to a specific project, and I would love to have this feature implemented in Kargo.

Current feature
```
  oidc:
    enabled: true
    issuerURL:
    clientID
    cliClientID:
    additionalScopes:
    - groups
    admins:
      claims: 
        email:
        - alice@example.com
        - bob@examples.com
        groups:
        - kargo-admin
    viewers:
      claims: 
        email:
        - alice@example.com
        - bob@examples.com
        groups:
        - kargo-viewer

**** Requested feature****

    projectadmin: // lets-say demo-project
      projectname : demo-project
        claims: 
          email:
          - alice@example.com
          - bob@examples.com
          groups:
          - kargo-demo-project-admin
    projectreader: 
      projectname : demo-project
        claims: 
          email:
          - alice@example.com
          - bob@examples.com
          groups:
          - kargo-demo-project-viewer

```
Expected: Current feature + Requested feature.
