### ISSUE TITLE
PR link no longer displayed in the Promotion UI

### ISSUE THREAD

**Issue by simonartige** [akuity/kargo#3024]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

With the new promotion steps, which are indeed more flexible now, it seems that we have lost the link to the opened PR in the promotion view on the Kargo UI.
This feature on the UI was very handy as it allowed to quickly see the pull request opened for the promotion.

Looking at the code, we can see the functionality got removed with this change:
https://github.com/akuity/kargo/pull/2694/files#diff-831008a406138fc2b4e0288bf2dfc2fe4c9ed871de1268ee4c67edaa0f7977f2
Which looks like the intended behavior.

We can still find the PR number by browsing in the new promotion details panel 
<img width="648" alt="image" src="https://github.com/user-attachments/assets/f9842204-aa19-46bd-9f7f-a472ab5b3471">
But this requires more navigation and there is no link available - only the PR number

Are there any future plans to show the list of PRs opened in the promotion steps on the UI?

I logged a bug, but this is a functional regression. But I would understand if this is seen as a feature request as this is a feature from the 0.x Kargo version, that was before the new promotion steps mechanism. With the new system, there could be multiple PRs opened in a single promotion, therefore there may be UX challenges to display them. But I would say it is expected to find these PR links somehow when we see this icon 
<img width="226" alt="image" src="https://github.com/user-attachments/assets/405c21ad-19e2-4091-8367-b621025a620c">

# Screenshots

![image](https://github.com/user-attachments/assets/ae09f78b-b000-492a-8663-1733948ce656)

# Steps to Reproduce

Create a promotion with the following configuration:

```
        - uses: git-commit
          config:
            path: ./app
            messageFromSteps:
              - helm-update-image
        - uses: git-push
          as: push
          config:
            path: ./app
            generateTargetBranch: true
        - uses: git-open-pr
          as: open-pr
          config:
            repoURL: https://github.com/x/y
            provider: github
            sourceBranchFromStep: push
            targetBranch: main
        - uses: git-wait-for-pr
          config:
            repoURL: https://github.com/x/y
            provider: github
            prNumberFromStep: open-pr
```
Promote a freight using that configuration
A PR is opened during the promotion
Looking at the promotion history in the stage details, we don't have the link to the PR anymore (see screenshot)

I don't have a screenshot to the previous UI sorry, but the associated code was https://github.com/akuity/kargo/pull/2694/files#diff-831008a406138fc2b4e0288bf2dfc2fe4c9ed871de1268ee4c67edaa0f7977f2

# Version

v1.0.3

**Comment by simonartige** [comment]
Alternatively, maybe we could include the link to the PR in this area of the new promotion details panel?
![image](https://github.com/user-attachments/assets/014533c2-0b6f-4c26-8460-3a3be52b4c65)

**Comment by Marvin9** [comment]
There is easy fix to this but the thing is any metadata that is related to promotion steps have potential to show up at meaningful place in the UI. The easy fix is [tightly coupled UI code](https://github.com/akuity/kargo/blob/main/ui/src/features/promotion-directives/utils.ts). This might not scale well with third-party promotions. Although this hasn't been discussed yet which way to go but it might become clearer once we progress on [third party promotion](https://github.com/akuity/kargo/issues/2996).

**Comment by krancour** [comment]
Although I hate to say it, this is one of those spots where we're going to have to accept the less-than-ideal, tightly-coupled solution, at least temporarily.

**Comment by jessesuen** [comment]
This is another use case for https://github.com/akuity/kargo/issues/2752

**Comment by blakestoddard** [comment]
This seems to have regressed again, it's not showing in v1.2.2.

**Comment by Marvin9** [comment]
@blakestoddard the location is moved to promotions list (last column) and at right besides individual promotion step (`git-open-pr`). Is it not showing up there as well?

**Comment by Marvin9** [comment]
Right @hiddeco it is already included in the release version 1.2.2

**Comment by blakestoddard** [comment]
I'm not seeing it in either place: 

![Image](https://github.com/user-attachments/assets/08c3f0b9-5d16-45c8-bb87-6fd8abae7c29)

![Image](https://github.com/user-attachments/assets/6b8b2a70-f5bc-4587-9c29-417a8da46092)

**Comment by Marvin9** [comment]
Could you check console when you are on promotion steps modal? There is error dot so there must be some error reported in console

**Comment by blakestoddard** [comment]
Good call out, I do get an error when I go into the modal:
```
Error: URL parsing failed.
```

`repoURL` here is self-hosted GHE, rather than gh-dot-com (in the format of `https://github.x.y.com/org/repo.git`), passed in via variable:
```
    - uses: git-wait-for-pr
      as: wait-for-pr
      config:
        prNumber: ${{ outputs['open-pr'].prNumber }}
        repoURL: ${{ vars.gitRepo }}
```
