### ISSUE TITLE
Promotionsteps don't take current freight into account for generating commit messages

### ISSUE THREAD

**Issue by Sebast1aan** [akuity/kargo#3097]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When using the promotion step `helm-update-image` or `yaml-update` to update more than 1 image, the commit message will always indicate that all images were updated, even if some images remain identical between promotions.
Note that this has no impact on what is deployed, so I consider this as a minor issue. It rather improves the git logs to show only which images really changed between promotions.

# Screenshots

yaml-update:
![image](https://github.com/user-attachments/assets/aa01ec0c-b453-4988-9246-90c1ebeaa443)

helm-update-image:
![image](https://github.com/user-attachments/assets/b43ed665-b397-481d-ac8a-3e5a372ed59b)

# Steps to Reproduce
Create following `Project`:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-test
```
  
Create following `Warehouse`:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-test
  namespace: kargo-test
spec:
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx
      semverConstraint: ^1.26.0
      discoveryLimit: 5
  - image:
      repoURL: public.ecr.aws/docker/library/golang
```

Create following `Stage`:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-test
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-test
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: $GITHUB_REPO_URL
          checkout:
          - branch: main
            path: ./src
      - uses: yaml-update
        as: update-value
        config:
          path: ./src/environments/dev/builds.yaml
          updates:
          - key: global.solution.buildnumber
            value: ${{ imageFrom("public.ecr.aws/nginx/nginx").Tag }}
          - key: global.project.buildnumber
            value: ${{ imageFrom("public.ecr.aws/docker/library/golang").Tag }}
      - uses: git-commit
        as: commit
        config:
          path: ./src
          messageFromSteps:
          - update-value
      - uses: git-push
        config:
          path: ./src
```

Wait for `Freight` to be generated containing the latest images of both containers. Then manually create new `Freight`, but change the image for only one of the 2 containers. When promoting this new piece of `Freight`, you will see that the commit message indicates that both images have been updated.

# Version
Kargo main branch
