### ISSUE TITLE
JSON body in HTTP promotion step causes schema validation failure

### ISSUE THREAD

**Issue by muenchdo** [akuity/kargo#3109]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I'm trying to do a POST request with a JSON body as part of an HTTP promotion step. It fails during the config validation because after evaluating the expressions, the body is no longer a string but a map. 

I've tried things like inlining my JSON body string and multiple YAML multi-line scalars (`>` and `|`), but couldn't get it to work. It might be possible with different quoting, but I'd argue that Kargo should be smart enough to know that an HTTP request body should always be interpreted as a string. This would also preserve readability.

# Screenshots

![CleanShot 2024-12-09 at 19 01 08@2x](https://github.com/user-attachments/assets/2872ad11-35e2-44e1-a2de-70a76752a1d4)

# Steps to Reproduce

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: in-cluster--beta
  namespace: echoserver
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: echoserver
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - uses: http
        config:
          method: POST
          url: https://echo.free.beeceptor.com
          body: |
            {
              "body": {
                "content": [
                  {
                    "content": [
                      {
                        "text": "Kargo triggered a promotion to ${{ ctx.stage }}",
                        "type": "text"
                      }
                    ],
                    "type": "paragraph"
                  }
                ],
                "type": "doc",
                "version": 1
              }
            }
```

# Version

```
Client Version: v0.9.0
Server Version: v1.1.1
```

# Logs

```
time="2024-12-10T02:45:33Z" level=error msg="error executing Promotion" error="step execution failed: step 1 met error threshold of 1: failed to run step \"http\": invalid http config: body: Invalid type. Expected: string, given: object" freight=857d4e7e79ff63801a8b675728aa0d0dce1d4327 namespace=echoserver promotion=in-cluster--beta.01jeq7a9a8m0ds3b22tfhz2gh5.857d4e7 stage=in-cluster--beta
```

**Comment by krancour** [comment]
This is what the `quote()` function is for, although this appears to be an edge case it does not handle well.

https://docs.kargo.io/references/expression-language#quote

With a small fix, which I'm about to PR, your proper config should look like this:

```yaml
- uses: http
  config:
    method: POST
    url: https://echo.free.beeceptor.com
    body: |
      ${{ quote({
        "body": {
          "content": [
            {
              "content": [
                {
                  "text": "Kargo triggered a promotion to " + ctx.stage,
                  "type": "text"
                }
              ],
              "type": "paragraph"
            }
          ],
          "type": "doc",
          "version": 1
        }
      }) }}
```
