### ISSUE TITLE
UI: ArgoCD app link contains expr-lang references instead of real app name 

### ISSUE THREAD

**Issue by dspereira004** [akuity/kargo#3123]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

Starting from version 1.1.0, we can use [expr-lang](https://docs.kargo.io/references/expression-language) in our Stage resources. More specifically, in the "config" section. This works well, including in the `argocd-update` step (Kargo is able to update the ArgoCD application successfully).

Also, for any app we have in `argocd-update`, Kargo is able to display a link that directs us to the ArgoCD application whenever we click on the stage in the UI. The problem is that the link contains the expr-lang references we put in the Stage resources, instead of displaying the final (after processing) link. This prevents us from going to the app, as the link is wrong.

# Screenshots

![image](https://github.com/user-attachments/assets/1ebf6022-9808-4d9a-8bb0-96487f1286bc)

# Steps to Reproduce

Create a Stage which contains an `argocd-update` step with expr-lang references in the name. Example:
```yaml
- uses: argocd-update
  config:
    apps:
      - name: kargo-${{ ctx.stage }}
        sources:
          - repoURL: https://github.com/example/repo
            updateTargetRevision: false

``` 

# Version

```
{
  "Version": "v1.1.1",
  "BuildDate": "2024-12-09T22:05:23Z",
  "GitCommit": "d9932c7379444b0cc885c05fbc735f4495c65463",
  "GitTreeDirty": false,
  "GoVersion": "go1.23.4",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```
