### ISSUE TITLE
Conditional step execution

### ISSUE THREAD

**Issue by muenchdo** [akuity/kargo#3125]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Add the possibility to add conditions for promotion step executions, similar to what is available in [GitHub Actions](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/using-conditions-to-control-job-execution). The expressions added with v1.1 would make this very useful.

# Motivation

Right now the main use case I have in mind is being able to run something like a "finalizer" to send a Slack notification when the promotion fails, but I feel like this would be useful in more cases.

# Suggested Implementation

GitHub Actions seems to be a good inspiration here. 

```yaml
steps:
- uses: foo
  alias: fooStep
  config:
    option1: value1
    option2: value2
- uses: bar
  if: ${{ len(outputs.fooStep.someOutput) > 0 }}
  config:
    option1: value1
    option2: value2
```

For my finalizer use case, we would need some [special expressions](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#status-check-functions) such as `$always()`.

Looking at #3124, it seems there are technical limitations that make this difficult, but I do think this (especially the finalizer use case) is less of an edge case than loops.
