### ISSUE TITLE
Invalid health status of a Argo CD backed stage

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#3155]
# Description

Kargo UI shows that related Argo CD app health is Degraded although it is Healthy.

# Screenshots

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/46bad0c5-246c-4c74-9c94-13015bb9dc9e" />

```yaml
    - type: Healthy
      status: "False"
      observedGeneration: "9"
      lastTransitionTime: 2024-11-26T19:49:14Z
      reason: LastPromotionErrored
      message: Last Promotion did not succeed
    - type: Verified
      status: "True"
      observedGeneration: "9"
      lastTransitionTime: 2024-11-26T19:49:14Z
      reason: Verified
      message: Freight has been verified
```

# Steps to Reproduce

I belive this is happening if most recent promotion failed.

# Version

v1.1.1
