### ISSUE TITLE
yaml-update: function "imageFrom" not defined

### ISSUE THREAD

**Issue by stephaneetje** [akuity/kargo#3216]
Hello, i'm trying to move from `helm-update-image` to `yaml-update`, but i get an error `function "imageFrom" not defined`

Here is my step:

```
      - uses: yaml-update
        as: update-image
        config:
          path: ./src/helm/ii/values-ii-integ-image.yaml
          updates:
          - key: image.tag
            value: ${{ imageFrom(europe-docker.pkg.dev/test1234/r51/ii).Tag }}
          - key: imageLiquibase.tag
            value: ${{ imageFrom(europe-docker.pkg.dev/test1234/r51/ii-liquibase).Tag }}
```

I've been following the documentation, couldn't find what i am missing (i'm deploying with ArgoCD) 
I guess there might be some escaping issues with Argocd
