### ISSUE TITLE
Kargo sets wrong image during some promotions.

### ISSUE THREAD

**Issue by koushyk** [akuity/kargo#3236]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

Kargo sets wrong image during some promotions something wrong with variable types, I'm using gitlab CI_COMMIT_SHORT_SHA as tag.

# Screenshots
<img width="1319" alt="Снимок экрана 2025-01-09 в 13 31 09" src="https://github.com/user-attachments/assets/2781671c-30c9-4036-b636-ac0a0d2be916" />

# Steps to Reproduce

```
  promotionTemplate:
    spec:
      steps:
        - config:
            checkout:
              - fromFreight: true
                path: ./src
              - branch: env/parser-service-dev1
                create: true
                path: ./out
            repoURL: https://gitlab.com/backend/parser-service.git
          uses: git-clone
        - config:
            path: ./out
          uses: git-clear
        - as: update-image
          config:
            images:
              - image: registry.gitlab.com/backend/parser-service
                key: image.tag
                value: Tag
            path: ./src/chart/values.yaml
          uses: helm-update-image
        - config:
            outPath: ./out/chart/all.yaml
            path: ./src/chart
            releaseName: dev1
            valuesFiles:
              - ./src/chart/values.yaml
              - ./src/chart/values-dev1.yaml
          uses: helm-template
        - as: commit
          config:
            messageFromSteps:
              - update-image
            path: ./out/chart
          uses: git-commit
        - as: push
          config:
            path: ./out/chart
            targetBranch: env/parser-service-dev1
          uses: git-push
        - config:
            apps:
              - name: parser-service-dev1
                sources:
                  - desiredCommitFromStep: commit
                    repoURL: https://gitlab.com/backend/parser-service.git
          uses: argocd-update
  requestedFreight:
    - origin:
        kind: Warehouse
        name: parser-service-wh
      sources:
        direct: true
```

# Version

```
{
  "Version": "v1.1.2",
  "BuildDate": "2024-12-23T23:29:34Z",
  "GitCommit": "4deb9ff40f2391b1c7dcaafa488e2cf62b7fe805",
  "GitTreeDirty": false,
  "GoVersion": "go1.23.4",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

# Logs

```
Paste any relevant application logs here.
```
