### ISSUE TITLE
Parse (grep/yq/jq/sed/awk) step to extract file contents

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3240]
# Proposed Feature

It has been requested to extract a portion of a file's contents after cloning, so that the file's contents can be used in a subsequent step. e.g. 

```yaml
- uses: git-clone
  config:
    repoURL: ${{ vars.gitRepo }}
    checkout:
    - commit: ${{ commitFrom(vars.gitRepo, warehouse("base")).ID }}
      path: ./src
- uses: parse-file
  as: app_versions
  config:
    paths:
    - path: config/app1/version.txt
      sed: # some expression to extract output from the file
      output: app1
    - path: config/app2/version.yaml
      yq: ".app2.version"
      output: app2
- uses: yaml-update
  config:
    path: ./src/charts/my-chart/values.yaml
    updates:
    - key: app1.image.tag
      value: ${{ outputs.app_versions.app1 }}
    - key: app2.image.tag
      value: ${{ outputs.app_versions.app2 }}
```

# Motivation

This would allow Kargo to use git repository monitoring feature in a more powerful way. e.g. A user could configure Kargo to watch a single file in for changes, similar to how we watch a OCI/Helm/Git repo for changes, but then act on specific changes to that file, possibly even in a different repo.

We already have a copy step which is close to this and consider this a variation of the`copy` step.

# Suggested Implementation

Implementation will probably be similar to our [`copy`](https://docs.kargo.io/references/promotion-steps/#copy) step, which deals with files on disk.

The big question would be how to extract information from a file. But should be as good as:
* jq
* yq
* grep
* sed
* awk

jq/yq would be great for structured data. but unstructured data may need grep/sed/awk-like syntax.
