### ISSUE TITLE
Helm repo config & cache directory environment variables aren't respected during helm-update-chart

### ISSUE THREAD

**Issue by WZHGAHO** [akuity/kargo#3290]
# Description

During helm-update-chart promotion step, I received the following error:

```shell
step execution failed: step 1 met error threshold of 1: failed to run
    step "helm-update-chart": failed to update chart dependencies: could not
    find : chart rsp-pulsar-function-example not found in
    https://artifacts.example.com/artifactory/api/helm/rsp-helm-host: looks like
    "https://artifacts.example.com/artifactory/api/helm/rsp-helm-host" is not a
    valid chart repository or cannot be reached: open
    /.cache/helm/repository/ahF2zqceBHME9GAXefZb1vqyn5M=-index.yaml: no such
    file or directory'
``` 

I tried to reproduce by exec'ing into kargo-controller pod, and trying to add Helm repo:

```shell
~ $ helm repo add gabor-test https://artifacts.example.com/artifactory/api/helm/rsp-helm-host
Error: mkdir /.config: permission denied
``` 

It seems if repository config directory is not set, then Kargo takes Helm's default, which is $HOME/.config/helm
Since in our case $HOME is set to /, it tried to create directory /.config. 
Kargo runs with the following user, and it has no permission to write to /

```shell
~ $ ps auxf
PID   USER     TIME  COMMAND
    1 10010700  0:00 /sbin/tini -- /usr/local/bin/kargo controller
    7 10010700  0:09 /usr/local/bin/kargo controller
   28 10010700  0:00 sh
45444 10010700  0:00 ps auxf
~ $ id
uid=1001070000(1001070000) gid=0(root) groups=0(root),1001070000
``` 

Then I tried to set repository config directory to a directory where the user has write permission, and then I could reproduce the problem:

```shell
~ $ helm repo add gabor-test https://artifacts.example.com/artifactory/api/helm/rsp-helm-host --repository-config /tmp/foo
Error: looks like "https://artifacts.example.com/artifactory/api/helm/rsp-helm-host" is not a valid chart repository or cannot be reached: open /.cache/helm/repository/gabor-test-index.yaml: no such file or directory
``` 

When I set also the repository cache directory for Helm, repo add worked:

```shell
~ $ helm repo add gabor-test https://artifacts.example.com/artifactory/api/helm/rsp-helm-host --repository-config /tmp/foo --repository-cache /tmp/bar
"gabor-test" has been added to your repositories
``` 

Then to fix permanently the problem, I tried to set environment variable for Kargo controller, by setting the following in values.yaml:

```yaml
  controller:
    env:
      - name: HELM_REPOSITORY_CACHE
        value: /tmp/helm/.cache
      - name: HELM_REPOSITORY_CONFIG
        value: /tmp/helm/.config
``` 

However, it seems the environment variables are not respected by Kargo.

So to overcome the problem, I set the default HOME environment variable to /tmp, then it started to work.

Questions:
* should above Helm environment variables be used by Kargo?
* can it be, that since tini is the process controller, somehow environment variables are lost?

I run Kargo 1.1.2 on OKD cluster.

**Comment by krancour** [comment]
You don't actually need to `helm repo add` for a `helm-update` command to succeed since the dependency's repo's full URL is in the `Chart.yaml` file. So the repo config directory shouldn't be especially relevant. Is it possible that there's something else going on here?

cc @hiddeco

**Comment by hiddeco** [comment]
The `helm-update-chart` step should run in isolation, and a unique directory is created in a temporary location and disposed of once the step finishes. Because of this, none of the Helm environment variables are taken into account (as they would break the isolation model).

You also should not have to add the repository by hand in any case, as this is automatically done for you. Except if the repository requires authentication, in which case you need the credentials for this to your Kargo Project, and they will then be resolved automatically.

Is there any chance that besides rewriting `$HOME` to a non-writable location (which is fairly uncommon, and disadvised for almost any application that tries to do things on the filesystem to perform operations), you also rewrote `$TMPDIR`?

If not, can you show me what is accumulated in your `/tmp/.config` over time when `$HOME` is set to `/tmp`?

**Comment by WZHGAHO** [comment]
Additional information: we made some more tests, and we downgraded to 0.9.0, we did Promotion again with helm-update-chart, and it worked.

Promotion steps we used:

```
  steps:
    - uses: git-clone
      config:
        checkout:
          - branch: main
            path: ./src
        repoURL: https://example.github.com/raiffeisen/example-deployment-manifest.git
    - uses: helm-update-chart
      as: update-chart
      config:
        charts:
          - fromOrigin:
              kind: Warehouse
              name: charon
            name: rsp-operator
            repository: https://artifacts.example.com/artifactory/rsp-helm-host
        path: ./src/charts/rsp-pulsar-topology-operator

``` 

Same promotion steps worked in 0.9.0, and did not work in 1.1.1 and 1.1.2
No changes were done to environment variables (inc. $TMPDIR)  in both tests.

One difference we observed:

In 0.9.0, XDG base directory specification seems to be set, and this can make a difference, because in "helm" command output, we see the following:

Helm stores cache, configuration, and data based on the following configuration order:

- If a HELM_*_HOME environment variable is set, it will be used
**- Otherwise, on systems supporting the XDG base directory specification, the XDG variables will be used**
- When no other location is set a default location will be used based on the operating system

In 0..9.0, this is the env set:

```shell
~ $ env |grep -i tmp
XDG_CACHE_HOME=/tmp/.cache
XDG_CONFIG_HOME=/tmp/.config
XDG_DATA_HOME=/tmp/.local/share
``` 

So it seems in 1.1.1+ we don't see anymore the XDG variables.
