### ISSUE TITLE
`kustomize-build` step should support private OCI `helmCharts`

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3310]
# Proposed Feature

My preferred way of deploying helm charts is via kustomized helm. e.g.:  

```yaml
helmCharts:
- name: guestbook
  releaseName: guestbook
  version: 1.2.3
  repo: oci://us-docker.pkg.dev/example/guestbook/charts
  valuesFile: values.yaml
```

The challenge is if `repo` is a private repo and needs image credentials, the `kustomize build` will fail.

On a workstation it will works if your environment is logged into the private image repo. I believe the `helm` command will know to use credentials from `~/.docker/config.json` in order to talk to the remote registry. We need to make it possible for this to work in promotion.

# Motivation

Kustomize is not fully functional to workstation capabilities.

# Suggested Implementation

For the kustomize build command, we could set the `~/.docker/config.json` so that `helm` will work.
