### ISSUE TITLE
failed to determine if *v1alpha1.Stage is namespaced ... kargo.akuity.io/v1alpha1: Unauthorized

### ISSUE THREAD

**Issue by Tchoupinax** [akuity/kargo#3373]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

Kargo controller does not boot anymore. I tried to come back to version 1.1.0 but there is no change.
The installation of Kargo is pretty the same since 0.4.0, so I do not understand exactly what is happening.

Am I supposed to add additionnal permissions to read kube API manually?

# Steps to Reproduce

Installion with Kubernetes and Helm

```
# Chart.yaml
apiVersion: v2
name: kargo
type: application
version: 1.0.0

dependencies:
- name: kargo
  version: 1.2.1
  repository: oci://ghcr.io/akuity/kargo-charts
```

```
# values.yaml
kargo:
  rbac:
    installClusterRoles: true

  image:
    repository: ghcr.io/akuity/kargo
    # tag: "v1.2.0"

  api:
    enabled: true
    host: kargo.mydomain.com
    tls:
      enabled: false
      selfSignedCert: false

    rollouts:
      integrationEnabled: false

    ingress:
      enabled: true
      ingressClassName: ingress-controller-traefik
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls:
        enabled: false
        selfSignedCert: false

    adminAccount:
      enabled: true
      tokenSigningKey: one-token
      passwordHash: one-hash

  controller:
    logLevel: DEBUG
    rollouts:
      integrationEnabled: false

    globalCredentials:
      namespaces:
      - kargo
    gitClient:
      name: "Kargo"
      email: "kargo-render@akuity.io"
    serviceAccount:
      # Remove this, see release changelog 1.0.0
      clusterWideSecretReadingEnabled: true
``` 

# Version

```
{
  "Version": "v1.2.1",
  "BuildDate": "2025-01-23T19:17:42Z",
  "GitCommit": "29b07904b8c95213bcc495bf5f4ece2253386972",
  "GitTreeDirty": false,
  "GoVersion": "go1.23.4",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

# Logs

```
time="2025-01-26T11:45:14Z" level=info msg="Starting Kargo Controller" GOMAXPROCS=10 GOMEMLIMIT=16371712000 commit=29b07904b8c95213bcc495bf5f4ece2253386972 version=v1.2.1
time="2025-01-26T11:45:14Z" level=debug msg="loading in-cluster REST config"
time="2025-01-26T11:45:14Z" level=error error="error initializing Kargo controller manager: failed to determine if *v1alpha1.Stage is namespaced: failed to get restmapping: failed to get API group resources: unable to retrieve the complete list of server APIs: kargo.akuity.io/v1alpha1: Unauthorized"
```
