### ISSUE TITLE
in the promotionTemplate.steps add a step that can read YAML and JSON file and output there keys and values to other steps.

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#3374]
# Checklist

* [ v ] I've searched the issue queue to verify this is not a duplicate feature request.
* [ v ] I've pasted the output of `kargo version`, if applicable.  > v1.2.0

# Proposed Feature

when building a promotion template pipeline to promote to the stage, I want to have the ability to read the content of YAML or JSON files from the cloned repository, this will also allow the use of configuration that can be found in the git to trigger HTTP requests and update other files and more.

# Motivation

make the pipeline creation more versatile by consuming data from config/values or payload that are committed to git

# Suggested Implementation

add a task that uses `yq` to read keys from a yaml file.
add a task that uses `jq` to read keys from a JSON file.

```yaml
- uses: read-yaml
  as: config
  config:
    keyName: <<Leading key for output, i.e. payload>>  // the prefix key for the file
    path: <<path/to/the/file.yaml >>
```
usage at another step

```yaml
- uses: yaml-update
  config:
    path: <<path/to/other/file.yaml>>
    updates:
      -  key: someKey
         value: ${{ config.payload.keyFromFile}}
```
