### ISSUE TITLE
Unable to authenticate warehouse to Azure Container Registry

### ISSUE THREAD

**Issue by mimartin12** [akuity/kargo#3376]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate bug report.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `kargo version`.
* [X] I've pasted logs, if applicable.

# Description
When setting up a warehouse that subscribes to an image from Azure Container Registry, It is unable to authenticate with [ACR Tokens](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-repository-scoped-permissions). 

# Screenshots

# Steps to Reproduce

1. Create ACR.
2. Create ACR token that has `_repositories_admin` rights.
3. Create image secret.
4. Create a warehouse that subscribes to the ACR.

The resources are defined like so:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-galactica
  namespace: kargo-galactica
spec:
  subscriptions:
  - image:
      repoURL: spaceport.azurecr.io/galactica
      semverConstraint: ^1.0.0
      discoveryLimit: 5
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: kargo-acr-secret
  namespace: kargo-galactica
  labels:
    kargo.akuity.io/cred-type: image
stringData:
  repoURL: spaceport.azurecr.io
  username: galactica
  password: <token-password>
```

# Version

```
Client Version: v1.2.1
Server Version: v1.2.1
```

# Logs

```
status:
  conditions:
    - lastTransitionTime: 2025-01-27T16:32:50Z
      message: Discovering artifacts for 1 subscriptions
      observedGeneration: 1
      reason: ScheduledDiscovery
      status: "True"
      type: Reconciling
    - lastTransitionTime: 2025-01-27T16:32:50Z
      message: 'Artifact discovery failed: error discovering images: error discovering
        latest images "spaceport.azurecr.io/galactica": error discovering newest
        applicable images "spaceport.azurecr.io/galactica": error listing tags:
        error listing tags for repo URL spaceport.azurecr.io/galactica: GET
        https://spaceport.azurecr.io/oauth2/token?scope=repository%3Agalactica%3Apull&service=spaceport.azurecr.io:
        UNAUTHORIZED: authentication required, visit
        https://aka.ms/acr/authorization for more information. CorrelationId:
        9aba79cb-067b-4b97-bae2-61d6298bcb7d'
      observedGeneration: 1
      reason: DiscoveryFailure
      status: "False"
      type: Ready
    - lastTransitionTime: 2025-01-27T16:32:50Z
      message: 'Unable to discover artifacts: error discovering images: error
        discovering latest images "spaceport.azurecr.io/galactica": error
        discovering newest applicable images "spaceport.azurecr.io/galactica":
        error listing tags: error listing tags for repo URL
        spaceport.azurecr.io/galactica: GET
        https://spaceport.azurecr.io/oauth2/token?scope=repository%3Agalactica%3Apull&service=spaceport.azurecr.io:
        UNAUTHORIZED: authentication required, visit
        https://aka.ms/acr/authorization for more information. CorrelationId:
        9aba79cb-067b-4b97-bae2-61d6298bcb7d'
      observedGeneration: 1
      reason: DiscoveryFailed
      status: "False"
      type: Healthy
```
