### ISSUE TITLE
Images subsequently tagged with a semver aren't picked up by kargo

### ISSUE THREAD

**Issue by darkpeak** [akuity/kargo#3412]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description
Our workflow is this:
* Developers create an image that they tag that looks like link-1234
* This is deployed to our link environment by kargo
* Once they are happy with this image, they tag it with a semantic version - e.g. 1.2.3 - to deploy it through the pipeline to subsequent environments
* Kargo doesn't pick this up, unless we remove the link-1234 tag from the image

Is this a bug, are we misunderstanding how kargo works, or  misunderstanding how we should be using it?

As we have to remove the link tag, this leaves us with the original freight with the link tag showing in kargo but not existing in the source image repository any more.

Other customisations to stages we have made that I don't think are relevant are:
* we add an alias to the freight at the start of the link stage to be the tag
* we have a http step at the start of the preprod stage to check if the image tag is a semantic version which will fail and stop if it isn't

# Screenshots

![Image](https://github.com/user-attachments/assets/a74200bc-28c0-4bf4-aa6c-4ea20c875a1e)

# Steps to Reproduce

Our warehouse looks like this:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ecr
  namespace: xxxxx
spec:
  subscriptions:
    - image:
        allowTags: ^(?:\d+\.\d+\.\d+|link-\d+)$
        discoveryLimit: 20
        imageSelectionStrategy: NewestBuild
        repoURL: xxxx
```

# Version
1.2.2

# Logs

```
Paste any relevant application logs here.
```
