### ISSUE TITLE
unknown field "spec.promotionTemplate.spec.steps[0].task.vars"

### ISSUE THREAD

**Issue by mmclane** [akuity/kargo#3433]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description
Reading over the documentation here: https://docs.kargo.io/user-guide/reference-docs/promotion-tasks I should be able to specify the vars in my template two ways, the gloabal vars section and the task step's vars section.  The global section works but when I try to set a tasks step var section (as shown on that page) I get the following error when I try to apply the template:

```
Error from server (BadRequest): error when creating ".../problem.yaml": Stage in version "v1alpha1" cannot be handled as a Stage: strict decoding error: unknown field "spec.promotionTemplate.spec.steps[0].task.vars"
```

# Screenshots

NA

# Steps to Reproduce

This is the content of problem.yaml
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: problem
  namespace: default
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: wh
    sources:
      stages:
      - qa
  promotionTemplate:
    spec:
      steps:
      - task:
          name: release-branch
          kind: ClusterPromotionTask
          vars:
          - name: targetRepo
            value: https://github.com/my/repo.git
```

I have also tried removing "kind: ClusterPromotionTask" to make it just like the example in the documentation but I get the same result.

# Version

```
v1.2.2
```

# Logs

```
Paste any relevant application logs here.
```
