### ISSUE TITLE
ArgoCD Application deploying Kargo will never sync

### ISSUE THREAD

**Issue by maxs-rose** [akuity/kargo#3444]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

When deploying Kargo using the helm chart through ArgoCD the application will never sync as the `divisor` field is created when the manifest is in the cluster however it is not present from the helm install. This means ArgoCD is detecting the application as out of sync and will perpetually try to "correct" this.

Current we can mitigate this with setting the fields to be ignored by ArgoCD but it would be nice if we didnt need to do that

# Screenshots

![Image](https://github.com/user-attachments/assets/fb6b2510-6cb2-472a-ad3b-e976b88c2d92)

# Steps to Reproduce

Application definition:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.2.2
    helm:
      releaseName: kargo
      valuesObject:
        api:
          oidc:
            enabled: true
             # OIDC config goes here
          adminAccount:
            enabled: false
          host: kargo.example.com
          ingress:
            # Ingress setup here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
```

# Version

```
{
  "Version": "v1.2.2",
  "BuildDate": "2025-01-28T00:06:22Z",
  "GitCommit": "f53aa4883f1a59c3ccc781a33ab494cd4ea1dd9d",
  "GitTreeDirty": false,
  "GoVersion": "go1.23.4",
  "Compiler": "gc",
  "Platform": "linux/arm64"
}
```
