### ISSUE TITLE
delete step should be idempotent

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3497]
# Description

If I try to use `delete` against a file/dir that does not exist, I get the following error:

`step execution failed: step 0 met error threshold of 1: failed to run step "delete": failed to delete "./out": lstat out: no such file or directory`

Ideally, `delete` should succeed if the specified path already does not exist.

If we want, we could add a strict option in case there is a use case where the path is expected to be there, but don't have a strong opinion here.

# Screenshots

<img width="777" alt="Image" src="https://github.com/user-attachments/assets/f0f757f3-73ed-4fb0-b5fd-cc1aab7dda04" />

# Steps to Reproduce

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: render-config
  namespace: kargo-rendered-branches
spec:
  steps:
  - uses: delete
    config:
      path: ./out
```

# Version

```
Kargo v1.2.2
```
