### ISSUE TITLE
glob matching does not support files nested in subdirectories

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3499]
# Description

I have the following GitOps directory structure. I would like my Warehouse to create Freight on any changes under `env/*` *including* files in subdirectories.

```
.
├── base
│   ├── guestbook-deploy.yaml
│   ├── guestbook-ns.yaml
│   ├── guestbook-svc.yaml
│   └── kustomization.yaml
├── env
│   ├── dev
│   │   └── kustomization.yaml
│   ├── prod
│   │   ├── increase-replicas.yaml
│   │   └── kustomization.yaml
│   └── staging
│       ├── increase-replicas.yaml
│       └── kustomization.yaml
```

I tried the following in include paths: `glob:env/*`, but it did not detect a change I made to `env/prod/increase-replicas.yaml`, which is in a *subdirectory* of `env`.

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: config
  namespace: kargo-rendered-branches
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/jessesuen/kargo-rendered-branches.git
      branch: main
      includePaths:
      - glob:env/*
```

# Steps to Reproduce

The above Warehouse will not detect changes to `env/xxxxx/modified-file.yaml`

Workaround is to use regex

# Version

```
v1.2.2
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by jessesuen** [comment]
Workaround is to use regex:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: config
  namespace: kargo-rendered-branches
spec:
  subscriptions:
  - git:
      repoURL: https://github.com/jessesuen/kargo-rendered-branches.git
      branch: main
      includePaths:
      - regex:env/.*
```
