### ISSUE TITLE
repeated use of git-clone causes confusion in out path in git-clear

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3500]
# Description

I have a `Stage` that calls a `PromotionTask` and will perform `git-clone` multiple times for the same repo. After the second git-clone, the following `git-clear` step will fail with:

`step execution failed: step 7 met error threshold of 1: failed to run step "git-clear": error loading working tree from ./out: error reading repo dir from config: error executing cmd [/usr/bin/git config kargo.repoDir]: : chdir /tmp/promotion-a81a77c5-5c57-4af0-95c7-057f122628c8/out: no such file or directory`

# Screenshots

<img width="773" alt="Image" src="https://github.com/user-attachments/assets/2df3d0f8-0c39-40a6-891c-4e83cd126d0b" />

<img width="771" alt="Image" src="https://github.com/user-attachments/assets/1a0d00f4-0d74-4910-bc28-68d444cd12be" />

# Steps to Reproduce

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: render-envs
  namespace: kargo-rendered-branches
  annotations:
    kargo.akuity.io/color: grey
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: config
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task: {name: render-config}
        vars: [{name: env, value: dev}]
      - task: {name: render-config}
        vars: [{name: env, value: staging}]
      - task: {name: render-config}
        vars: [{name: env, value: prod}]

----
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: render-config
  namespace: kargo-rendered-branches
spec:
  vars:
  - name: repoURL
    value: https://github.com/jessesuen/kargo-rendered-branches.git
  - name: branch
    value: main
  - name: env
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - commit: ${{ commitFrom(vars.repoURL).ID }}
        path: ./src
      - branch: env/${{ vars.env }}
        path: ./out
        create: true
  - uses: git-clear
    config:
      path: ./out
  - uses: kustomize-build
    config:
      path: ./src/env/${{ vars.env }}
      outPath: ./out
  - uses: git-commit
    as: commit
    config:
      path: ./out
      message: Updated configuration for ${{ vars.env }}
  - uses: git-push
    config:
      path: ./out
  # This is necessary so subsequent invocations of this task
  # have a clean out directory
  - uses: delete
    config:
      path: ./out
```

# Version

```
v1.2.2
```

# Logs

```
Paste any relevant application logs here.
```
