### ISSUE TITLE
when adding a warehouse in a middle stage the connecting lines are broken

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#3517]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate bug report.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `kargo version`.

# Description
In Kargo 1.2.2, I have added a warehouse in the middle of the promotion pipeline

the lines that connect from the new warehouse and it parallel stage are broken as you can see in the picture

# Screenshots

![Image](https://github.com/user-attachments/assets/0d2980bd-9cff-4875-8822-e333caa00cb6)

# Steps to Reproduce

create a new warehouse attach it to a stage that is in the middle of the promotion pipeline and have a parallel stage and a stage that request both stage and warehouse.

```
  requestedFreight:
    - origin:
        kind: Warehouse
        name: candidate-gitlab
      sources:
        stages:
          - candidate-qe
    - origin:
        kind: Warehouse
        name: candidate-qe
      sources:
        direct: true
```

# Version

```
Kargo v1.2.2
```
