### ISSUE TITLE
Garbage collector doesn't clean freight

### ISSUE THREAD

**Issue by semenar-0** [akuity/kargo#3572]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

garbage collector doesn't clean freights. We already have 1029 freights, some of them older than 40 days.
It is breaks the UI.

# Screenshots

# Steps to Reproduce

```yaml
garbageCollector:
  enabled: true
  schedule: "*/5 * * * *"
  workers: 5
  maxRetainedPromotions: 5
  minPromotionDeletionAge: 168h
  maxRetainedFreight: 10
  minFreightDeletionAge: 72h
  logLevel: DEBUG
  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  securityContext: {}
  env: []
  envFrom: []
```

```console
$ kubectl get freight | wc -l
1022
```

```console
$ kubectl get pods
NAME                                           READY   STATUS      RESTARTS   AGE
kargo-api-7b5c879bc6-52n5l                     1/1     Running     0          29d
kargo-controller-5df95df976-bx69x              1/1     Running     0          30d
kargo-garbage-collector-29009465-lg6l7         0/1     Completed   0          13m
kargo-garbage-collector-29009470-lttb4         0/1     Completed   0          8m43s
kargo-garbage-collector-29009475-qbp7d         0/1     Completed   0          3m43s
kargo-management-controller-57db5d4d4b-g8mjd   1/1     Running     0          30d
kargo-webhooks-server-5f9d59b468-pglhc         1/1     Running     0          29d
```

# Version

```
1.2.0
```

# Logs

```
- kargo-garbage-collector-29009470-lttb4 › garbage-collector
kargo-garbage-collector-29009475-qbp7d garbage-collector time="2025-02-26T11:15:00Z" level=info msg="Starting Kargo Garbage Collector" GOMAXPROCS=2 GOMEMLIMIT=134217728 commit=0958769ad8df56d274bc752ce236a257f2920f64 version=v1.2.0
kargo-garbage-collector-29009475-qbp7d garbage-collector time="2025-02-26T11:15:00Z" level=debug msg="loading in-cluster REST config"
kargo-garbage-collector-29009475-qbp7d garbage-collector time="2025-02-26T11:15:01Z" level=debug msg="cleaned Promotions to Stage" project=workflows stage=dev
kargo-garbage-collector-29009475-qbp7d garbage-collector time="2025-02-26T11:15:01Z" level=debug msg="cleaned Promotions to Stage" project=workflows stage=qa
kargo-garbage-collector-29009475-qbp7d garbage-collector time="2025-02-26T11:15:01Z" level=debug msg="cleaned Promotions to Stage" project=workflows stage=uat
kargo-garbage-collector-29009475-qbp7d garbage-collector time="2025-02-26T11:15:01Z" level=debug msg="cleaned Freight from Warehouse" project=workflows warehouse=jobrunner-dev
kargo-garbage-collector-29009475-qbp7d garbage-collector time="2025-02-26T11:15:01Z" level=debug msg="cleaned Freight from Warehouse" project=workflows warehouse=jobrunner-rc
kargo-garbage-collector-29009475-qbp7d garbage-collector time="2025-02-26T11:15:01Z" level=debug msg="cleaned Project" project=workflows
- kargo-garbage-collector-29009475-qbp7d › garbage-collector
```
