### ISSUE TITLE
More Flexible App Selection in argocd-update Step

### ISSUE THREAD

**Issue by wmiller112** [akuity/kargo#3576]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

It would be nice to be able to select applications to be managed by a stage with argocd-update step by more than just a complete name.

# Motivation

We've found as we add and remove applications, whether that be from adding/removing services or adding/removing clusters that existing services then get deployed to (by way of new applications generated by applicationsets), that we need to have some custom way of generating the list of apps a stage should be responsible for. I've handled this using argocd lovely plugin with a preprocessor that basically performs the functions of the argocd applicationset git file generator to create a kustomize patch with all the app names. This is fairly cumbersome and seems like it shouldn't be necessary at least from a security perspective, if we're already granting a particular stage permission to sync the application via the required `kargo.akuity.io/authorized-stage` annotation on the app side.

# Suggested Implementation

Ability to select applications for sync by label or regex of the name.

**Comment by avishayafik** [comment]
any plans for that ? it's very limiting , even supporting a list, or project will be very helpful

**Comment by jessebot** [comment]
yeah, an argocd-update step that supported an `appset` arg would help a lot. Right now, what I did is use an [AnalysisTemplate](https://docs.kargo.io/user-guide/reference-docs/analysis-templates), but its certainly not the most elegant solution since I then need to keep track of a token and I had to add an appset label to the Applications generated by the ApplicationSet, so that I could then grab their metrics using a joined prometheus query and I had to use a job to actually do the sync as well:

<details>
  <summary>example_testing_anaysis_template.yaml</summary>

I'll try to remember to update this example when it's tested and working

```yaml
apiVersion: argoproj.io/v1alpha1
# ref.1: https://docs.kargo.io/user-guide/reference-docs/analysis-templates
# ref.2: https://argo-rollouts.readthedocs.io/en/stable/features/analysis/#clusteranalysistemplates
kind: ClusterAnalysisTemplate
metadata:
  name: argocd-appset-check
  namespace: argo-rollouts
spec:
  args:
    # name of the Argo CD ApplicationSet to check for health
    # and associated Applications' health
    - name: argocd-appset
    # name of the Argo CD Server with the ApplicationSet to check for health
    # do NOT include the protocol (e.g. https) - that breaks everything
    - name: argocd-server
      value: myargoserver.com
    # Secret holding the Argo CD API Token for Kargo
    - name: argocd-token
      valueFrom:
        secretKeyRef:
          name: kargo-argocd-api-token
          key: apiToken

  # ref: https://argo-rollouts.readthedocs.io/en/stable/features/analysis/#measurements-retention
  measurementRetention:
    - metricName: .*
      limit: 5

  metrics:
    # uses the Argo CD CLI to sync all Applications associated with a given ApplicationSet
    - name: argocd-appset-apps-sync
      # time between runs
      interval: 5s
      # how many times to run this metric check - we only need this to run once
      count: 1
      # how many times this can fail before the metric is allowed to be marked as unhealthy
      failureLimit: 1
      # evaluate the output of the metric check
      successCondition: result == "Done"
      provider:
        # ref: https://docs.kargo.io/user-guide/reference-docs/analysis-templates#job
        job:
          spec:
            backoffLimit: 1
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: sync-argocd-apps
                    image: alpine/curl:latest
                    command:
                      - /bin/sh
                      - -c
                      - |
                        # install the argocd binary directly from argo running in the same cluster
                        curl -sSL -o /usr/local/bin/argocd http://argo-cd-argocd-server.namespace.svc/download/argocd-linux-arm64
                        chmod +x /usr/local/bin/argocd

                        # get all argocd apps associated with a given appset
                        export ARGOCD_SERVER={{ args.argocd-server }}
                        export ARGOCD_AUTH_TOKEN={{ args.argocd-token }}
                        export ARGOCD_APPS=$(argocd app list -l argocd-appset={{ args.argocd-appset }} -o name --grpc-web | cut -d '/' -f 2)

                        # sync all argocd appset apps
                        for app in $ARGOCD_APPS; do
                            echo -e "Syncing ${app}..."
                            argocd app sync $app --grpc-web
                            echo -e "Waiting for ${app} health..."
                            argocd app wait --health $app --grpc-web | grep "Healthy"
                            if [ $? -eq 0 ]; then
                              echo "Application ${app} is Healthy :)"
                            else
                              echo "Application ${app} is Unhealthy :O"
                              exit 1
                            fi
                        done
                        echo "Done"

    # checks thanos for if the Argo CD ApplicationSet is healthy
    - name: appset-healthy-metric
      # time between runs - this is set to 11s because the scrape runs every 30s
      # so this means we'll always eventually get the current status of the metric
      interval: 11s
      # how many times to run this metric check
      count: 3
      # how many times this can fail before the metric is allowed to be marked as unhealthy
      failureLimit: 3
      # NOTE: prometheus queries return results in the form of a vector.
      # So it is common to access the index 0 of the returned array to obtain the value
      successCondition: result[0] == 1
      provider:
        # ref: https://argo-rollouts.readthedocs.io/en/stable/analysis/prometheus/
        prometheus:
          address: http://prometheus.namespace.svc:9090/query
          # timeout is expressed in seconds
          timeout: 10
          query: |
            group by(name) (argocd_appset_info{name="{{ args.argocd-appset }}", resource_update_status="ApplicationSetUpToDate"})

    # checks thanos for if the Argo CD ApplicationSet's Applications are healthy
    - name: apps-healthy-metric
      # time between runs - this is set to 11s because the scrape runs every 30s
      # so this means we'll always eventually get the current status of the metric
      interval: 11s
      # how many times to run this metric check
      count: 3
      # how many times this can fail before the metric is allowed to be marked as unhealthy
      failureLimit: 3
      # NOTE: prometheus queries return results in the form of a vector.
      # ref: https://argo-rollouts.readthedocs.io/en/stable/analysis/prometheus/#range-query-and-successconditionfailurecondition
      successCondition: "all(result, # == 1)"
      provider:
        # ref: https://argo-rollouts.readthedocs.io/en/stable/analysis/prometheus/
        prometheus:
          address: http://prometheus.namespace.svc:9090/query
          # timeout is expressed in seconds
          timeout: 10
          query: |
            group by(name) (argocd_app_labels{label_argocd_appset="{{ args.argocd-appset }}"}) * on(name) group_right(argocd_app_info) argocd_app_info{health_status="Healthy"}
```

</details>

Otherwise, even if I got associated apps for an appset via an http step and used them in the next step of a PromotionTemplate, there's no way to range through them to in the current argocd-update step (to my knowledge - please correct me if I'm wrong!).
