### ISSUE TITLE
cannot fetch commitMessage from one step

### ISSUE THREAD

**Issue by wqbbs911** [akuity/kargo#3596]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [ ] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

After upgrade kargo to 1.3.0 , according to release docs: https://github.com/akuity/kargo/releases , i removed messageFromSteps field of the [git-commit](https://docs.kargo.io/user-guide/reference-docs/promotion-steps/git-commit#configuration) , instead of messge, but it still failed:

![Image](https://github.com/user-attachments/assets/a57e9b5d-79dc-4143-bbbc-66f177bd8339)

![Image](https://github.com/user-attachments/assets/961cb416-6188-42f1-a371-0b79b8910681)
YAML error:

![Image](https://github.com/user-attachments/assets/921168bb-fa5d-432a-8dc9-2eaf609e3589)

changed the message, still failure:

![Image](https://github.com/user-attachments/assets/75690f2c-99c5-40f3-b320-6db2f8786f08)

![Image](https://github.com/user-attachments/assets/5724b6b5-fd43-4ba2-8582-21e944d9df74)

# Steps to Reproduce

# Version

```
Client Version: v1.3.0
Server Version: v1.3.0
```

# Logs

```
step execution failed: step 2 met error threshold of 1: failed to get step config: cannot fetch commitMessage from <nil> (1:25) | outputs['yaml-update'].commitMessage | ........................^
```

### BTW , the full config is:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: standard-process
  namespace: ctms-argotest-core-provider-kargo
spec:
  vars:
  - name: gitRepo 
  - name: appName
  - name: imageRepo
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./src
  - uses: yaml-update
    as: yaml-update
    config:
      path: ./src/apps/${{ vars.appName }}/${{ ctx.stage }}/values.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: git-commit
    as: commit
    config:
      path: ./src
      message: ${{ outputs['yaml-update'].commitMessage }}
  - uses: git-push
    config:
      path: ./src
  - uses: argocd-update
    config:
      apps:
      - name: ${{ vars.appName }}-${{ ctx.stage }}
```

**Comment by wqbbs911** [comment]
the full config is:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: standard-process
  namespace: ctms-argotest-core-provider-kargo
spec:
  vars:
  - name: gitRepo
  - name: appName
  - name: imageRepo
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
      - branch: main
        path: ./src
  - uses: yaml-update
    as: yaml-update
    config:
      path: ./src/apps/${{ vars.appName }}/${{ ctx.stage }}/values.yaml
      updates:
      - key: image.tag
        value: ${{ imageFrom(vars.imageRepo).Tag }}
  - uses: git-commit
    as: commit
    config:
      path: ./src
      message: ${{ outputs['yaml-update'].commitMessage }}
  - uses: git-push
    config:
      path: ./src
  - uses: argocd-update
    config:
      apps:
      - name: ${{ vars.appName }}-${{ ctx.stage }}
```
