### ISSUE TITLE
Dex OIDC issues when upgrading to 1.3.0

### ISSUE THREAD

**Issue by shmargum** [akuity/kargo#3599]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When upgrading to 1.3.0 I am no longer able to load projects.  I did first have to add this option `terminatedUpstream: true` to the config as well before getting the error logs below.
It looks like the there is an audience mismatch between `kargo.example.com` and `kargo.example.com-cli`

# Screenshots

N/A

# Steps to Reproduce

Upgrade from 1.2.0 to 1.3.0 when using dex as an oidc provider and upstream tls termination.

# Version

```
v1.3.0
```

# Logs

```
time="2025-03-03T18:28:16Z" level=error msg="finished unary call" connect.code=unauthenticated connect.duration=1m0.001954479s connect.method=ListProjects connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2025-03-03T18:27:16Z" error="unauthenticated: failed to verify signature: fetching keys context canceled\noidc: expected audience \"kargo.example.com-cli\" got [\"kargo.example.com\"]"

```

**Comment by shmargum** [comment]
I am seemingly able to work around this for now by adding the following to the API env
```
env:
    - name: OIDC_CLI_CLIENT_ID
      value: kargo.example.com # no -cli suffix
```

**Comment by krancour** [comment]
>  I did first have to add this option terminatedUpstream: true

As the name implies, it's something you set when something upstream (besides an Ingress) is terminating TLS -- something like a LoadBalancer or an Ingress controller that terminates TLS using its own wildcard cert. Does that apply to you?

Also, this isn't new in v1.3.0. 🤔 

> It looks like the there is an audience mismatch between kargo.example.com and kargo.example.com-cli

We configure Dex to know about two separate clients because the proper callback URL is different between the two.

Neither of these issues you're encountering seem like things that should have have happened by upgrading. I don't believe these things were touched _at all_ between v1.2.0 and now.

How you are installing Kargo exactly? Does it happen to be through some means other than the chart?

**Comment by krancour** [comment]
Ahh.

It's got to be related to this:

https://github.com/akuity/kargo/pull/3441/files#diff-4b56901aa63ff02fd44d953c0e59890716e5e0eb70db0ba521245c52b238f6c5

I'm still working out how that could have led to the audience mismatch issue.

**Comment by krancour** [comment]
@shmargum I tried to replicate. Here are my values overrides. Is your config much different from this?

```yaml
image:
  tag: v1.3.0
api:
  host: kargo.example.com
  tls:
    enabled: false
    terminatedUpstream: true
  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
      enabled: false
  adminAccount:
    enabled: false
  oidc:
    enabled: true
    dex:
      enabled: true
      connectors:
      - id: mock
        name: Example
        type: mockCallback
      probes:
        enabled: false
    admins:
      claims:
        email:
        # This email claim is hard-coded in the Dex mockCallback connector
        - kilgore@kilgore.trout
```

**Comment by shmargum** [comment]
small difference in tls settings
```
    tls:
      enabled: true # i think because i'm using cert manager
      terminatedUpstream: true
```

for oidc/dex
```
    oidc:
      enabled: true
      clientID: kargo
      admins:
        claims:
          groups:
            - my-admin-okta-group
      viewers:
        claims:
          groups:
            - "my-viewer-okta-group"
      dex:
        enabled: true
        connectors:
          - type: oidc
            id: blah
            name: blah
            config:
              ...
```

**Comment by krancour** [comment]
I think you slipped through a tiny crack. 🤭 Then you fixed it... Then idk...

The logic for building the base of _user-facing_ URLs is consolidated to one place in the chart and it looks something like this:

HTTPS if any of the following:

* `api.ingress.enabled: true` AND `api.ingress.tls.enabled: true`

  Because you're using an `Ingress` with TLS enabled. User interactions with Kargo should be over HTTPs.

* `api.ingress.enabled: false` AND `api.tls.enabled: true`

  Because you're NOT using an `Ingress`, so traffic is presumably flowing straight to the `Service`, and Kargo is (natively) using TLS. User interactions with Kargo should be over HTTPs.

* `api.tls.terminatedUpstream: true`

  It's possible that neither of the previous conditions are met, but something upstream (load balancer, reverse proxy, etc.) is terminating TLS. The chart never could have inferred this from any other configuration, so you can set `api.tls.terminatedUpstream: true` to ensure that user interactions with Kargo will be over HTTPs.

And it's HTTP otherwise.

> I did first have to add this option `terminatedUpstream: true`

So _initially_, that was the default of `false`? The third condition wasn't met.

The rest of your (relevant) original config would have been this?

```yaml
tls:
  enabled: true
ingress:
  enabled: true
  tls:
    enabled: false
```

Neither of the other two (first two) conditions are met:

* The first isn't met, because it looks like you're using `Ingress`, but that the `Ingress` doesn't use TLS. This implies user interactions with Kargo should be over HTTP... unless one of the other conditions is met...

* The second isn't met because, again, it looks like you're using `Ingress`, so traffic presumably _isn't_ flowing directly to the `Service`. That means any server-level TLS settings shouldn't dictate whether user interactions with Kargo should be over HTTP or HTTPS.

This is pretty much the exact scenario for which `api.tls.terminatedUpstream` was added to the chart. _You were right to set it to true._ But as I noted, this wasn't new in v1.3.0, so it's a bit perplexing that `v1.2.0` worked for you without have set `api.tls.terminatedUpstream: true`. 🤔 At any rate, you did the right thing.

As for needing to add `OIDC_CLI_CLIENT_ID: kargo.example.com` (no `-cli`) suffix to, I'm not sure what's going on there. It probably wouldn't surprise you to hear that, as the name of the  `OIDC_CLI_CLIENT_ID` env var implies, it only impacts the client ID used by the CLI. Any interaction with Kargo via the UI should have been unaffected by that change.

Bottom line is I believe things should have started working fine the moment you switched `terminatedUpstream` to `true`.

Ultimately, it seems the following _should_ be working for you:

```yaml
api:
  host: kargo.example.com
  tls:
    enabled: false
    terminatedUpstream: true
  ingress:
    enabled: true
    annotations:
      # You probably need to set something here so that your ingress controller knows to use HTTPS for communication with the back end service endpoints.
    ingressClassName: whatever
    tls:
      enabled: false
```

**Comment by krancour** [comment]
> Ahh.
>
> It's got to be related to this:
>
> https://github.com/akuity/kargo/pull/3441/files#diff-4b56901aa63ff02fd44d953c0e59890716e5e0eb70db0ba521245c52b238f6c5

So this changed in v1.2.3. The logic was corrected to handle some edge cases better...

Without `terminatedUpstream: true` set (which it should have been) and you previously having been on v1.2.0, you were dependent on the old (but slighty incorrect) logic.

> I'm still working out how that could have led to the audience mismatch issue.

Things are making more sense now.

> I'm still working out how that could have led to the audience mismatch issue.

Are you sure it wasn't an _issuer_ mismatch?

**Comment by krancour** [comment]
> I guess I was relying on a bug :)

It happens.

> It looks like the API is expecting the cli audience from web UI requests for me for some reason

That's certainly what it sounds like, but I still can't spot how it's possible. I will look some more when time permits.

One thing you could try...

Since Kargo clients (CLI and UI) both use the OIDC Authorization Code Flow _with PKCE_, they interact directly with the identity provider and do not use the Kargo API server as any sort of middle-man. What they _do_ do, however, is interact with an unsecured "public configuration" endpoint _before_ attempting any authentication. This is how they learn the IDP's issuer URL as well as the correct application ID they should be using when initiation the Authorization Code Flow. It's probably no surprise that the UI uses the application ID _without_ the `-cli` suffix and the CLI uses the one _with_ the `-cli` suffix -- or at least that's how it's supposed to work.

If you can interact with that endpoint yourself, you may be able to make a determination as to whether, somehow, it is returning incorrect/unexpected information to the client. It isn't RESTful, however, so you cannot just `curl` it. If you have any desire to do so, you could take the CLI code (or UI code if you prefer, but CLI is probably easier) and add some debug statements or a `spew.Dump()` after that public configuration retrieval to try and see what it looks like.

**Comment by krancour** [comment]
@shmargum checking in... wondering where you currently stand with this.

**Comment by BWagenerGenerali** [comment]
Hey, just chiming in - we are facing the same issue with a new install using 1.4.0. Here's the relevant config we use:

```yaml
api:
  tls:
    enabled: false
    selfSignedCert: true
    terminatedUpstream: true # terminated by openshift-router's edge termination feature
  oidc:
    enabled: true
    additionalScopes:
      - groups
    admins:
      claims:
        groups:
          - some-group
    viewers:
      claims:
        groups:
          - some-other-group
    dex:
      enabled: true
      env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: openshift-dex
              key: token
      tls:
      connectors:
        - id: dex
          type: openshift
          name: OpenShift
          config:
            issuer: https://<k8s-api-server>:6443
            clientID: system:serviceaccount:kargo:openshift-dex
            clientSecret: $CLIENT_SECRET
            redirectURI: https://<kargo-api-host>/dex/callback
            insecureCA: true
```

The workaround mentioned [here](https://github.com/akuity/kargo/issues/3599#issuecomment-2695340181) also works for us to circumvent this issue.

**Comment by krancour** [comment]
I trust that something unexpected is happening here, but I'm not seeing details that would help to research this.

If either of you could please configure this without the workaround, which _shouldn't_ work (although I trust it somehow does), and post environment details from the API server's `Deployment`, `ConfigMap`, and `Secret` (with redactions, obviously), it would be a big help in tracking down why valid-looking `values.yaml` is somehow leading to this audience mismatch issue.

**Comment by BWagenerGenerali** [comment]
I am happy to share the files you requested. I do believe however, that just taking our values.yaml and running `helm template repro oci://ghcr.io/akuity/kargo-charts/kargo --version 1.4.0 -f repro-values.yaml` gives the exact files you are interested in.

This is our entire values.yaml, I have merely replaced URLs and group names

`repro-values.yaml`:
```yaml
api:
  host: kargo.example.com
  env:
    - name: OIDC_CLI_CLIENT_ID
      value: kargo.example.com # no -cli suffix
  tls:
    enabled: false
    terminatedUpstream: true
  adminAccount:
    enabled: false
  argocd:
    urls:
      "smc-argocd": kargo.example.com
  oidc:
    enabled: true
    admins:
      claims:
        groups:
          - some-group
    viewers:
      claims:
        groups:
          - some-group
    dex:
      enabled: true
      env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: openshift-dex
              key: token
      connectors:
        - id: dex
          type: openshift
          name: OpenShift
          config:
            issuer: https://api.example.com:6443 # or 443 if using HCP
            clientID: system:serviceaccount:kargo:openshift-dex
            clientSecret: $CLIENT_SECRET
            redirectURI: https://kargo.example.com/dex/callback
            insecureCA: true
```

**Comment by krancour** [comment]
@BWagenerGenerali here is my own configuration, which is as close as I could come to yours.

I configured my Nginx ingress controller to terminate SSL using _its own_ wildcard cert, so there's no SSL from there to Kargo. I didn't need to use your workaround. This just worked.

```yaml
api:
  host: kargo.example.com
  tls:
    enabled: false
    terminatedUpstream: true
  adminAccount:
    enabled: false
  ingress:
    enabled: true
    ingressClassName: nginx
    tls:
      enabled: false
  oidc:
    enabled: true
    dex:
      enabled: true
      connectors:
      - id: mock
        name: Example
        type: mockCallback
      probes:
        enabled: false
    admins:
      claims:
        email:
        # This email claim is hard-coded in the Dex mockCallback connector
        - kilgore@kilgore.trout
```

> I am happy to share the files you requested.

This may be necessary because there are elements of your configuration that I just cannot replicate:

* I don't have access to OpenShift.
* I don't know what's terminating SSL in your case, but since I used an ingress controller to terminate SSL, it became necessary for me to also use an Ingress, which I see you are not doing.

**Comment by BWagenerGenerali** [comment]
@krancour I hadn't considered where SSL is terminated plays a role here. We use the OpenShift "Route" resource to configure the built-in HAProxy instance. The resource looks like this:

<details>

<summary>route.yaml</summary>

```yaml
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: kargo-server
spec:
  host: kargo.example.com
  to:
    kind: Service
    name: kargo-api
    weight: 100
  port:
    targetPort: "8080"
  tls:
    termination: edge # traffic terminates at the HAProxy, traffic between the LB and kargo is unencrypted
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
```

</details>

It could be possible to replicate this behavior using [OpenShift Local](https://console.redhat.com/openshift/create/local). 

I do wonder, @shmargum are you also experiencing this issue on OpenShift?
