### ISSUE TITLE
Add a Tag modifier for what is appended to GitRepoURL for Image Subscriptions

### ISSUE THREAD

**Issue by lantern-sam** [akuity/kargo#3604]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

I would like to see some modifier / filter when using `GitRepoURL` on Docker Image Subscriptions. 

For example I am currently defining the image subscriptions like so: 

```
kind: Warehouse
..
spec:
  subscriptions:
    - image:
        repoURL: kargodemo.azurecr.io/kargo-demo
        imageSelectionStrategy: Lexical
        gitRepoURL: https://github.com/kargodemo/kargo-demo.git
```

However, when I build my Docker images they are tagged in the following format: `{GITHUB-SHA}-{yyyymmddHHMM}`

I do this as I want to use a `Lexical` selection strategy and have it pick up the latest image based on the date stamp. 

However this means in the Kargo Portal it will show the `Source Repo` as: 

```
https://github.com/kargodemo/platform-kargo-demo/tree/{GH-SHA}-{yyyymmddHHMM}
```

Which is not a valid URL and will show a not found error. 

A workaround currently is I could remove the `-yyyymmddHHMM` and use `NewestBuild` but that is not recommended for performance reasons. (Or I could make a git tag for every commit to main but that sounds not great)

# Suggested Implementation

Ideally an extra option which allows me to filter part of my image tag for what I want to be appended onto the end of the URL. 

For example adding a property such as `gitRepoTagRegex`:

```
kind: Warehouse
..
spec:
  subscriptions:
    - image:
        repoURL: kargodemo.azurecr.io/kargo-demo
        imageSelectionStrategy: Lexical
        gitRepoURL: https://github.com/kargodemo/kargo-demo.git
        gitRepoTagRegex: ^\w+
```

This is a Regex that will apply to the full image tag (e.g. `912d8c89a10ff6ba63a2f6efa1644edfc275f9e5-202503041021`) and take only the string it matches (e.g. `912d8c89a10ff6ba63a2f6efa1644edfc275f9e5`)

That way the resulting URL in the Kargo Platform will be: 

```
https://github.com/kargodemo/platform-kargo-demo/tree/{GH-SHA}
```

Which is a valid URL and will allow people to use Lexical image selection without Tagging.
