### ISSUE TITLE
Mutable tag subscriptions are rejected on apply

### ISSUE THREAD

**Issue by remi-gelinas** [akuity/kargo#3606]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When subscribing to an image repository with mutable tags, the Kargo admission webhook rejects image subscriptions with the `semverConstraint` field containing the mutable tag name (described in the [docs](https://docs.kargo.io/user-guide/how-to-guides/working-with-warehouses#image-selection-strategies)). As far as I can tell, this means v1.3.0 fully breaks support for mutable tag subscriptions.

EDIT: This is also present on v1.2.3

# Steps to Reproduce

Apply a `Warehouse` with an image subscription listening to new digests from a mutable tag:
```
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: image
spec:
  subscriptions:
    - image:
        repoURL: <any valid repo>
        imageSelectionStrategy: Digest
        semverConstraint: main # Any mutable tag
```

It will be rejected by the Kargo admissions webhook because the `semverConstraint` value is not valid:

```
 one or more objects failed to apply, reason: admission webhook "warehouse.kargo.akuity.io" denied the request: Warehouse.kargo.akuity.io "image" is invalid: spec.subscriptions[0].image.semverConstraint: Invalid value: "main"
```

# Version

```
{
  "Version": "v1.3.0",
  "BuildDate": "2025-02-25T20:20:33Z",
  "GitCommit": "f645f54c5cc72efc122ffd602544eec1bdee1656",
  "GitTreeDirty": false,
  "GoVersion": "go1.24.0",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

# Logs

```
Paste any relevant application logs here.
```
