### ISSUE TITLE
[PromotionTask] Unable to Fetch field from Compose-Output

### ISSUE THREAD

**Issue by aarontams** [akuity/kargo#3636]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When executing the `PromotionTask`, the task fails at the step where the field is fetched from the output of the `compose-output` step. 

# Steps to Reproduce

### YAML Configuration:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
. . .
spec:
  steps:
  - uses: compose-output
    as: boo
    config:
      path: 'foo'
  . . .
  - uses: helm-template
    as: renderingToDeployRepo
    config:
      outPath: ${{ task.outputs.boo.path }}
  . . .
```

# Version

```
v1.3.0
```

### Error:
```
step execution failed: step 8 met error threshold of 1: failed to get step config: cannot fetch path from <nil> (1:39) | task.outputs.boo.name | ......................................^
```
