### ISSUE TITLE
display logs for verifications/analyses that take the form of a job

### ISSUE THREAD

**Issue by krancour** [akuity/kargo#3641]
We're not going to get into the business of forwarding and storing logs, but @jessesuen has proposed that we allow operators to specify a URL template that can produce URLs as a function of stage, promotion name, freight name, analysis run name, etc., along with auth headers.

This can be used to enable a new API server endpoint to act as a proxy for logs that are accessible via an https get request.

The UI, and possibly the CLI, can make use of the new endpoint to expose verifications/analyses to users.

Ultimately, this would mean that if you can manage to ship your logs to object storage (for instance), Kargo can display them.

**Comment by blakestoddard** [comment]
I scoop up logs from all pods in a cluster and send them to a central store where they're queryable by pod name (Loki) -- having the name of the job (or the child pod itself) that Argo Rollouts kicks off would be great:

`status.metricResults[...]measurements.metadata.job-name`

```
status:
. . .
  metricResults:
  - consecutiveSuccess: 1
    count: 1
    measurements:
    - finishedAt: "2025-03-11T05:47:26Z"
      metadata:
        job-name: f4a3e538-f183-4d9d-b23f-a5a55ba54bda.integration-test.1
        job-namespace: test-service
. . .
```
