### ISSUE TITLE
`helm-template` outPath creates unexpected nested dirs

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3643]
# Description

When using the `helm-template` with `outPath` specified, the resulting files will unexpectedly nest the rendered yaml into a `guestbook/templates` directory.

According to docs, the `outPath` is:
> Path to the file or directory where rendered manifests are to be written

Here are my steps:

```yaml
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - commit: ${{ commitFrom(vars.repoURL).ID }}
        path: ./src
      - branch: env/${{ vars.env }}
        path: ./out
        create: true
  - uses: git-clear
    config:
      path: ./out
  - uses: helm-template
    config:
      path: ./src/charts/guestbook
      releaseName: guestbook
      valuesFiles:
      - ./src/env/${{ vars.env }}/values-image.yaml
      - ./src/env/${{ vars.env }}/values.yaml
      outPath: ./out
```

But I'm left with this:
```
.
└── guestbook
    └── templates
        ├── deployment.yaml
        ├── namespace.yaml
        └── service.yaml
```

On the other hand, if I use the kustomize-build step, it behaves as expected where everything is at the `outPath`:
```
.
├── guestbook-prod-deployment-guestbook.yaml
├── guestbook-prod-service-guestbook.yaml
└── namespace-guestbook-prod.yaml
```

# Screenshots

<img width="926" alt="Image" src="https://github.com/user-attachments/assets/8dfa8754-5a1a-4fcf-81a5-252cc525be3d" />

# Steps to Reproduce

Use example promo steps above

# Version

```
v1.3.1
```

**Comment by jessesuen** [comment]
Hmmm, I suppose this is because `outPath` is treated the same as `--output-dir` from `helm template`?

**Comment by hiddeco** [comment]
>  I suppose this is because `outPath` is treated the same as `--output-dir` from `helm template`?

That's precisely the reason, as #2619 made it behave exactly like `helm`. One option you have is to make use of `useReleaseName`, which works the same as `--release-name` from `helm template`.

If that's not sufficient, I think this is a feature request for a new flag.

**Comment by jessesuen** [comment]
> One option you have is to make use of useReleaseName,

When I try that, the only thing it does is move it one level deeper into a directory whose name is the `releaseName`, so it doesn't help.

<img width="757" alt="Image" src="https://github.com/user-attachments/assets/74a98914-423d-4cec-a0c2-3bd2c9847da6" />

So `helm-template` should have the option to produce the same flat manifest layout as `kustomize-build`. 

Now, whether this should be the **_default_** behavior is debatable. IMO, my preference would be for the flattened layout because: 
* `outPath` would have consistent behavior amongst all our "templating" steps (kustomize, helm, and future tools...)
*  I think most users would expect/prefer a flat directory instead of the helm nested behavior.

**Comment by krancour** [comment]
> IMO, my preference would be for the flattened layout because:

@jessesuen I agree with your rationale, but working differently than the actual `helm template` command is its own sort of inconsistency. I'm also concerned that as breaking changes go, this one is rather significant.

I'm still not disagreeing with your points. I'm only raising additional considerations.

**Comment by jessesuen** [comment]
Let's start with introducing an option, without changing the default behavior.

I propose we consider making this a more generic feature and introduce an `outPathLayout` field that might exist in other templating steps:

```yaml
  - uses: helm-template
    config:
      path: ./src/charts/guestbook
      outPath: ./out
      outPathLayout: Helm
```

The default of outPathLayout can be to preserve the current behavior (for now). That said, in the docs, I would like to propose we have a warning that `outPathLayout` may change to a preferred default (e.g. `outPathLayout: Flat`), and instruct users to set this explicitly if the nested directory behavior is the desired one.
