### ISSUE TITLE
Expression functions not available in conditionals or vars values passed to tasks

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3646]
# Description

If I try to use `commitFrom` function to pass something to a task, e.g.:

```yaml
      steps:
      - task:
          name: render-branch
        vars:
        - name: commit
          value: ${{ commitFrom("https://github.com/jessesuen/kargo-rendered-branches.git").ID }}
```

I get the following error:

`step execution failed: step 0 met error threshold of 1: failed to get step config: error pre-processing promotion variable "commit": reflect: call of reflect.Value.Call on zero Value (1:2) | commitFrom("https://github.com/jessesuen/kargo-rendered-branches.git").ID | .^`

But the same `commitFrom` will work as a normal step:

```yaml
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/jessesuen/kargo-rendered-branches.git
          checkout:
          - commit: ${{ commitFrom("https://github.com/jessesuen/kargo-rendered-branches.git").ID }}
            path: ./src
```

# Screenshots

<img width="784" alt="Image" src="https://github.com/user-attachments/assets/d22fe755-7975-4aef-bc87-99005f6bf999" />

# Steps to Reproduce

Try to use `commitFrom` in a vars[].value passed to a task.

# Version

```
v1.3.1
```

**Comment by jessesuen** [comment]
Conditionals (`if`) also lack access to functions.

**Comment by krancour** [comment]
@jessesuen assigning to you only because I think you said you were working on it.

If I'm wrong of if you need to hand it off, please feel free to kick it back to me.

**Comment by nghazali** [comment]
Hey @krancour and @jessesuen 
This problem is repeated in verification as well. Based on [Kargo doc](https://docs.kargo.io/user-guide/how-to-guides/verification#:~:text=value%3A%20%24%7B%7B%20commitFrom(%22https%3A//github.com/example/repo.git%22).ID%20%7D%7D) I expect expressions work in verification args. I hope we have this fix in `1.3.2` as well.  

I have this manifest:

```
  verification:
    analysisTemplates:
      - name: operators-stability-check
    analysisRunMetadata:
    args:
      - name: verification-tag
        value: ${{ imageFrom(vars.verificationUrl, warehouse("verification-images")).Tag }}
```
and I get the same error as reported in this issue:

> error building AnalysisRun for Stage "dev-operators" and Freight collection "a01fb65ab8cda5c69e0c294cf7f041ba6714db0f" in namespace "operator-gitops": build spec: build arguments: evaluate argument "verification-tag": cannot fetch verificationUrl from <nil> (1:17) | imageFrom(vars.verificationUrl, warehouse("verification-images")).Tag | ................^


The exact expression works fine in the same stage:
```
      steps:
      ...
        - uses: yaml-update
          config:
            path: ${{ vars.resourceTargetPath }}/dev/control-plane/control.yaml
            updates:
              - key: spec.sources.1.targetRevision
                value: ${{ imageFrom(vars.verificationUrl, warehouse("verification-images")).Tag }}
```
