### ISSUE TITLE
Apply promotion policy to multiple stages

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3670]
# Proposed Feature

It would be useful to set a promotion policy based on a set of labels and/or naming patterns.

Today, a promotion policy is set against explicit names:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: example
spec:
  promotionPolicies:
  - stage: test
    autoPromotionEnabled: true
  - stage: uat
    autoPromotionEnabled: true
```

Instead, we could possibly use selectors:

```yaml
spec:
  promotionPolicies:
  - stageSelector:
      matchLabels:
        autopromote: "true"
      matchExpressions:
        - { key: foo, operator: In, values: [bar] }
        - { key: env, operator: NotIn, values: [prod] }
```

or globs/regex:

```yaml
spec:
  promotionPolicies:
  - autoPromotionEnabled: true
    name: glob:prod-*
```

# Motivation

Currently, all the Stages need to be referened in the Project if you want auto promotion

# Suggested Implementation

NOTE: labels are mutable on resources, but names cannot be changed. It could mean that there is a use case for globs/regex vs. labels. So we might want both.
