### ISSUE TITLE
When Repromoting a Freight into a Stage with a failed promotion, it fails on working tree error

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#3675]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate bug report.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `kargo version`.
* [X] I've pasted logs, if applicable.

# Description

I have a stage when a promotion failed due to some reason and i want to repromote the freight after the issue was fix i get:
```
step execution failed: step 0 met error threshold of 1: failed to run step "git-clone": error adding work tree ./nightly to repo https://gitlab.com/openshift-virtualization/fbc-payloads.git: error adding working tree at "/tmp/promotion-ff209559-788c-440d-aa2a-a292ca5be925/nightly": error executing cmd [/usr/bin/git worktree add /tmp/promotion-ff209559-788c-440d-aa2a-a292ca5be925/nightly 93a2d6c1e9693bdd985037ed80abb8f1109158af]: Preparing worktree (detached HEAD 93a2d6c) fatal: '/tmp/promotion-ff209559-788c-440d-aa2a-a292ca5be925/nightly' already exists
```

# Screenshots

![Image](https://github.com/user-attachments/assets/b8b291ea-fc73-4c59-9c76-9ff4b0178d6a)

# Steps to Reproduce

create a warehouse and 2 following stages.
create a freight in the warehouse and start promoting the freight.
fail the freight due to a config error or even an HTTP request error in the second stage
try to promote the freight again.

# Version

```
1.3.1
```

# Logs

```
time="2025-03-19T10:40:21Z" level=info msg="began promotion" freight=2a12077559b892dc79178aa3027ae401a97b9007 namespace=v4-12 promotion=nightly-prod.01jppzttkrtfbc8m9gs8hq6hex.2a12077 stage=nightly-prod
time="2025-03-19T10:40:44Z" level=error msg="error executing Promotion" error="step execution failed: step 0 met error threshold of 1: failed to run step \"git-clone\": error adding work tree ./nightly to repo https://gitlab.com/openshift-virtualization/fbc-payloads.git: error adding working tree at \"/tmp/promotion-35ea43b0-82c0-4612-9e11-cb5290c036be/nightly\": error executing cmd [/usr/bin/git worktree add /tmp/promotion-35ea43b0-82c0-4612-9e11-cb5290c036be/nightly 8a4abdeceadbe5fa834d9703cbd375173aa95312]: Preparing worktree (detached HEAD 8a4abde)\nfatal: '/tmp/promotion-35ea43b0-82c0-4612-9e11-cb5290c036be/nightly' already exists\n" freight=2a12077559b892dc79178aa3027ae401a97b9007 namespace=v4-12 promotion=nightly-prod.01jppzttkrtfbc8m9gs8hq6hex.2a12077 stage=nightly-prod
time="2025-03-19T10:40:44Z" level=info msg=promotion freight=2a12077559b892dc79178aa3027ae401a97b9007 namespace=v4-12 phase="\"Errored\"" promotion=nightly-prod.01jppzttkrtfbc8m9gs8hq6hex.2a12077 stage=nightly-prod
```

**Comment by krancour** [comment]
We've seen something like this before and I am having trouble finding the relevant issues and PRs.

The screenshot is a big clue as to what is happening.

Almost certainly, you got all the way through the `trigger-pipeline` `http` step then encountered a panic on the second one `check-pipeline-status`. A side effect of the panic is that the behind the scenes bookkeeping that marks the Promotion as having left off on that step didn't occur. This means that on the next reconciliation attempt, the steps were started again from step 0, and this is why `git-clone` has now failed.

To investigate further, seeing details of the `check-pipeline-status` `http` step would be helpful.

**Comment by tal-hason** [comment]
Here is the HTTP step from the Promotion:
```
        - uses: http
          as: check-pipeline-status
          retry:
            timeout: 5m0s
          config:
            method: GET
            url: "${{ vars.notificationURL }}/notifications/notification"
            timeout: 5s
            insecureSkipTLSVerify: true
            successExpression: response.body.type == "info"
            failureExpression: response.body.type == "failure"
            headers:
              - name: Content-Type
                value: application/json
            queryParams:
              - name: ID
                value: ${{ outputs['message'].pipelineID }}
            outputs:
              - name: status
                fromExpression: response.status
              - name: type
                fromExpression: response.body.type
              - name: id
                fromExpression: response.body.NotificationID
```
