### ISSUE TITLE
autoPromotionEnabled does not work when using fanout stages

### ISSUE THREAD

**Issue by dlydiard** [akuity/kargo#3719]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description
When using stages that don’t have promotion steps leading to other stages, autoPromotionEnabled doesn’t appear to function as expected. I would expect that promoting to downstream stages would trigger automatic promotions to all subscribed stages with autoPromotionEnabled enabled.

# Screenshots

![Image](https://github.com/user-attachments/assets/30c24b13-8825-4d43-8751-77360bbd20bd)

# Steps to Reproduce
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-poc
  labels:
    kargo.akuity.io/project: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-100"

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  promotionPolicies:
    - stage: devops-sandbox
      autoPromotionEnabled: true
    - stage: sandbox-1
      autoPromotionEnabled: true
    - stage: sandbox-2
      autoPromotionEnabled: true

    # developer UAT
    - stage: developer-uat
      autoPromotionEnabled: true
    - stage: dev
      autoPromotionEnabled: true
    - stage: staging
      autoPromotionEnabled: true
    - stage: management
      autoPromotionEnabled: true

    # Production release
    - stage: production
      autoPromotionEnabled: false
    - stage: production-us
      autoPromotionEnabled: true
    - stage: production-eu
      autoPromotionEnabled: true
    - stage: production-au
      autoPromotionEnabled: true

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-poc
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/MyOrg/kargo-poc.git
        branch: main

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: devops-sandbox
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        direct: true
  promotionTemplate: # work around for https://github.com/akuity/kargo/issues/3707
    spec:
      steps:
        - task:
            name: validate-kustomize
          as: validate-kustomize-devops-sandbox

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: sandbox-1
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - devops-sandbox
        direct: false
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
        - task:
            name: cluster-promo-process
          vars:
            - name: appsetFile
              value: kargo-poc/cluster-configs-sb1.yaml
          as: sb1-cluster-promo-process

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: sandbox-2
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - devops-sandbox
        direct: false
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
        - task:
            name: cluster-promo-process
          vars:
            - name: appsetFile
              value: kargo-poc/cluster-configs-sb2.yaml
          as: sb2-cluster-promo-process

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: developer-uat
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - sandbox-1
          - sandbox-2
        direct: false
        availabilityStrategy: All
  # promotionTemplate:
  #   spec:
  #     steps:
  #       - task:
  #           name: validate-kustomize
  #         as: validate-kustomize-developer-uat

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - developer-uat
        direct: false
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
        - task:
            name: cluster-promo-process
          vars:
            - name: appsetFile
              value: kargo-poc/cluster-configs-dv1.yaml
          as: dv1-cluster-promo-process

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - developer-uat
        direct: false
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
        - task:
            name: cluster-promo-process
          vars:
            - name: appsetFile
              value: kargo-poc/cluster-configs-st1.yaml
          as: st1-cluster-promo-process

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: management
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - developer-uat
        direct: false
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
        - task:
            name: cluster-promo-process
          vars:
            - name: appsetFile
              value: kargo-poc/cluster-configs-mt1.yaml
          as: mt1-cluster-promo-process

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - dev
          - staging
          - management
        availabilityStrategy: All
        direct: false

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production-us
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - production
        direct: false
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
        - task:
            name: cluster-promo-process
          vars:
            - name: appsetFile
              value: kargo-poc/cluster-configs-pd1.yaml
          as: pd1-cluster-promo-process

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production-uk
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - production
        direct: false
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
        - task:
            name: cluster-promo-process
          vars:
            - name: appsetFile
              value: kargo-poc/cluster-configs-eu.yaml
          as: eu-cluster-promo-process

---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production-au
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - production
        direct: false
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
        - task:
            name: cluster-promo-process
          vars:
            - name: appsetFile
              value: kargo-poc/cluster-configs-au.yaml
          as: au-cluster-promo-process

---

apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: cluster-promo-process
  namespace: kargo-poc
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  vars:
    - name: appsetFile
    - name: gitopsRepo
      value: https://github.com/MyOrg/kargo-poc.git
    - name: gitopsConfigRepo
      value: https://github.com/MyOrg/gitops-configurations.git
  steps:
    - uses: git-clone
      config:
        repoURL: ${{ vars.gitopsConfigRepo }}
        checkout:
          - branch: main
            path: ./out
    - uses: yaml-update
      config:
        path: ./out/${{ vars.appsetFile }}
        updates:
          # yaml-update does not work with arrays. Updating this key isn't technically needed, unless we are working with short-lived branches a warehouse
          # - key: spec.generators[].git.revision
          #   value: ${{ commitFrom(vars.gitopsRepo).ID }}
          - key: spec.template.spec.source.targetRevision
            value: ${{ commitFrom(vars.gitopsRepo).ID }}
    - uses: git-commit
      as: commit
      config:
        path: ./out
        message: "Promote to ${{ ctx.stage }}: ${{ commitFrom(vars.gitopsRepo, warehouse(\"kargo-poc\")).ID }}"
    - uses: git-push
      config:
        path: ./out

---

```

# Version

```
 v1.3.2
```

# Logs

```
Paste any relevant application logs here.
```

**Comment by krancour** [comment]
@dlydiard, I'm unable to reproduce what you're reporting.

I used the following YAML, which is not different from yours in any appreciable way. I modified the Warehouse to subscribe to something public and I modified the promotion process to be as minimal as possible -- a single step.

Within a few seconds of applying this YAML to the cluster, the Freight made it all the way through to prod _except_ for `production-uk`, because there is no promotion policy enabling auto-promotion for that Stage. (You enabled auto-promotion for a non-existent Stage `production-eu`, and I assume that to have been a mistake.)

Could you possibly try this YAML and see if it somehow behaves differently from yours?

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-poc
  labels:
    kargo.akuity.io/project: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-poc
spec:
  promotionPolicies:
  - stage: devops-sandbox
    autoPromotionEnabled: true
  - stage: sandbox-1
    autoPromotionEnabled: true
  - stage: sandbox-2
    autoPromotionEnabled: true
  # developer UAT
  - stage: developer-uat
    autoPromotionEnabled: true
  - stage: dev
    autoPromotionEnabled: true
  - stage: staging
    autoPromotionEnabled: true
  - stage: management
    autoPromotionEnabled: true
  # Production release
  - stage: production
    autoPromotionEnabled: false
  - stage: production-us
    autoPromotionEnabled: true
  - stage: production-eu
    autoPromotionEnabled: true
  - stage: production-au
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-poc
  namespace: kargo-poc
spec:
  subscriptions:
  - image:
      repoURL: public.ecr.aws/nginx/nginx
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promo-process
  namespace: kargo-poc
spec:
  steps:
  - uses: http
    config:
      method: GET
      url: https://www.catfacts.net/api/
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: devops-sandbox
  namespace: kargo-poc
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-poc
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: sandbox-1
  namespace: kargo-poc
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-poc
    sources:
      stages:
        - devops-sandbox
      availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: sandbox-2
  namespace: kargo-poc
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - devops-sandbox
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: developer-uat
  namespace: kargo-poc
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - sandbox-1
          - sandbox-2
        availabilityStrategy: All
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-poc
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - developer-uat
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: kargo-poc
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - developer-uat
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: management
  namespace: kargo-poc
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - developer-uat
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: kargo-poc
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - dev
          - staging
          - management
        availabilityStrategy: All
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production-us
  namespace: kargo-poc
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - production
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production-uk
  namespace: kargo-poc
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - production
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production-au
  namespace: kargo-poc
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-poc
      sources:
        stages:
          - production
        availabilityStrategy: All
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promo-process
```

**Comment by dlydiard** [comment]
@krancour I can confirm the YAML behaves the same as my test case—I had to manually approve each promotion throughout the workflow. This suggests a possible issue with my operator install Helm values?

In this screenshot i manually promoted the `devops-sandbox` stage, and also manually approved the `devops-sandbox` "Promote to downstream Subscribers" step.
![Image](https://github.com/user-attachments/assets/d819f45e-2e6e-4039-9576-855b727ea6c7)

Could this possibly be related to OpenShift?
```yaml
global:
  securityContext: {} # needed for OpenShift

rbac:
  installClusterRoles: true
  installClusterRoleBindings: true

api:
  adminAccount:
    enabled: true # This should remain disabled per security best practices.
  secret:
    name: kargo-admin # Contains ADMIN_ACCOUNT_PASSWORD_HASH and ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
  tls:
    enabled: false
    terminatedUpstream: true
  ingress:
    enabled: false # using custom Ingress+cert manager

crds:
  install: true
  keep: true

controller:
  securityContext: {}
  argocd:
    integrationEnabled: true
    namespace: openshift-gitops # argo cd NS
    watchArgocdNamespaceOnly: false
  logLevel: INFO

managementController:
  logLevel: INFO
  securityContext: {}
```

On a different note, I had to grant the `kargo-management-controller-openshift` `ServiceAccount` delete permissions for Namespaces; otherwise, I encountered a “cannot set an ownerRef on a resource you can’t delete” error on the Project CR.

**Comment by krancour** [comment]
This is strange.

Off the top of my head, I can't think of anything involved in determining whether Freight is available for auto-promotion to a given stage that would be influenced much by either Helm values or by OpenShift.

Can you look at the status of of the Freight and see if it has all the expected verifications?

Aside: Permission issues as related to ownership have cropped up on OpenShift from time to time. It's _probably_ unrelated.

Any chance you could give this a whirl quickly on a kind or k3d cluster (or any other local non-OpenShift cluster) to see if the behavior is different?

**Comment by krancour** [comment]
That certainly looks as if that Freight should have automatically progressed farther than it did.

Out of curiosity, if instead of doing a manual Promotion, you just refresh a Stage that seems not to have gotten it's auto-promotion, does the issue sort itself out?

I've spotted a bug in the logic that that enqueues downstream Stages for immediate reconciliation when Freight is newly verified in a given (upstream) Stage. I don't _think_ this bug is directly impacting your scenario, but I want to rule it out.

Does there happen to be anything interesting in the controller's logs?

**Comment by dlydiard** [comment]
Ah ha! I do see errors in the `kargo-controller` POD

```
time="2025-03-27T23:43:19Z" level=error msg="Reconciler error" Stage="{management kargo-poc}" controller=stage controllerGroup=kargo.akuity.io controllerKind=Stage error="failed to auto-promote Freight: error creating Promotion for Freight \"fb9c8d21a0abb87f852f2a58848b829c13c6f9e4\" in namespace \"kargo-poc\": promotions.kargo.akuity.io \"management.01jqczt89zg5j6f2v6qcekm5ph.fb9c8d2\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" name=management namespace=kargo-poc reconcileID="\"91c129f4-3b2b-48c3-874a-f55207c76301\""
time="2025-03-27T23:51:34Z" level=error msg="Reconciler error" Stage="{devops-sandbox kargo-poc}" controller=stage controllerGroup=kargo.akuity.io controllerKind=Stage error="failed to auto-promote Freight: error creating Promotion for Freight \"bb951a8cee2dab7144ed9c1ffb32ea7f4baf965b\" in namespace \"kargo-poc\": promotions.kargo.akuity.io \"devops-sandbox.01jqd09asvhgqcaw1rf5nfhgj4.bb951a8\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" name=devops-sandbox namespace=kargo-poc reconcileID="\"af62ceba-6303-437f-8123-bdb25740efb3\""
```

This seems similar to the OpenShift RBAC problem I had with Namespaces. I used the following RBAC to get Kargo working on OpenShift:

```yaml
# Give Kargo Management Controller special access to delete Project namespaces to work around ownerReference permission errors
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-management-controller-openshift
rules:
  - verbs:
      - delete
    apiGroups:
      - ''
    resources:
      - namespaces

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-management-controller-openshift
subjects:
  - kind: ServiceAccount
    name: kargo-management-controller
    namespace: kargo-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-management-controller-openshift

---

# Give kargo-controller access to delete promotions to work around ownerReference permission errors
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-controller-openshift
rules:
  - verbs:
      - update
    apiGroups:
      - kargo.akuity.io
    resources:
      - freights/finalizers
      - stages/finalizers

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-controller-openshift
subjects:
  - kind: ServiceAccount
    name: kargo-controller
    namespace: kargo-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-controller-openshift
```
