### ISSUE TITLE
Bug: Can't assemble freight from UI with more than one Helm chart from the same repository

### ISSUE THREAD

**Issue by ggogel** [akuity/kargo#3721]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When we create a Warehouse, which subscribes to two different Helm charts on the repository URL, we're unable to assemble the freight through the UI. The automatic freight assembly and creating a freight through kubectl work without issues.

# Screenshots

See screenshots below.

# Steps to Reproduce

1. Create a project.
2. Inside the project, create a warehouse like this:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: app
spec:
  subscriptions:
  - chart:
      name: app-service-a
      repoURL: https://ar.myorg.com/artifactory/api/helm/helm-myorg-virtual
      discoveryLimit: 10
  - chart:
      name: app-service-b
      repoURL: https://ar.myorg.com/artifactory/api/helm/helm-myorg-virtual
      discoveryLimit: 10
 ```
3. Click on "Assemble freight".
4. Select a version for the first chart. The version is added to "freight contents" at the top. Note that in the left column "charts", the equal repository URLs are displayed, not the chart names.

![Image](https://github.com/user-attachments/assets/ad56154d-74f1-4d9c-b21b-c2e13bf41b3f)

5. Click on the second Helm Chart (1). Select a version (2). The version of the second Helm chart is added to the "freight contents" but the version of the first Helm chart disappears(3).

![Image](https://github.com/user-attachments/assets/780eb5a2-b507-43a4-8409-7ca6f76c506e)

6. Click on "Create". The freight creation fails with a null error, because only the version for the second chart is provided.

```
admission webhook "freight.kargo.akuity.io" denied the request: Freight.kargo.akuity.io "47684d5e602fa87a362d199ff4cf075ea52b3309" is invalid: charts: Invalid value: "null": no artifact found for subscription "https://ar.myorg.com/artifactory/api/helm/helm-myorg-virtual" of Warehouse "app"
```

# Version

```
v1.3.2
```

# Logs

No applicable logs.

**Comment by nghazali** [comment]
Also, there is an [issue #2695](https://github.com/akuity/kargo/issues/2698) regarding the lake of chart name which was supposed to be delivered a while ago, but it is deprioritised.

**Comment by sethgupton-mastery** [comment]
I also ran into this.

**Comment by ggogel** [comment]
The bug still exists in version 1.5.0-rc.3

**Comment by caspar-ds** [comment]
Can confirm that this is also the case in 1.6.1. Cannot assemble freight with the following warehouse:

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: warehouse-test
  namespace: kargo-test
spec:
  interval: 1m0s
  subscriptions:
    - chart:
        repoURL: https://grafana.github.io/helm-charts
        name: grafana
    - chart:
        repoURL: https://grafana.github.io/helm-charts
        name: loki
```
