### ISSUE TITLE
Unable to authenticate from CLI when using SSO without dex

### ISSUE THREAD

**Issue by rafalwolny-apt** [akuity/kargo#3722]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.

# Description

I configured OIDC without dex like this:

**values.yaml:**
```yaml
api:
  enabled: true
  replicas: 1
  host: {{ $host }}
  logLevel: TRACE

  adminAccount:
    enabled: false

  tls:
    enabled: true
    selfSignedCert: true
    terminatedUpstream: true

  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: {{ $host }}
      kubernetes.io/ingress.class: azure/application-gateway
      appgw.ingress.kubernetes.io/backend-protocol: https
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
    tls:
      enabled: true
      selfSignedCert: false
    pathType: ImplementationSpecific

  oidc:
    enabled: true
    issuerURL: https://login.microsoftonline.com/<MY_URL>
    clientID: <ID>
    dex:
      enabled: false
    additionalScopes: []
    admins:
      claims:
        groups:
        - <ID>
```
**Azure app registration:**

<img width="760" alt="Image" src="https://github.com/user-attachments/assets/2d17b6b5-8604-4e50-b5e1-a39d33f6b2aa" />

## HTTPS callback
It's working with UI but I can't authenticate using CLI.
When I execute `kargo login https://<my-kargo-url>.com --sso` I'm getting error:
```
The redirect URI 'http://localhost:58194/auth/callback' specified in the request does not match the redirect URIs configured for the application '<ID>'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.
```
## HTTP callback
If I change redirect URI for CLI to use HTTP instead of HTTPS (described above) I'm getting this screen:

<img width="718" alt="Image" src="https://github.com/user-attachments/assets/cd87ca03-90c0-4888-8361-58db2ce2617f" />

but I see different error in the terminal:
```sh
$ kargo login https://<my-kargo-url>.com --sso
Error: error exchanging auth code for token: oauth2: "invalid_request" Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests. Trace ID: <ID> Correlation ID: <ID> Timestamp: 2025-03-26 11:06:34Z"
```
**Is this even supported without dex? 
Did I configured it wrong or is this a bug?**

# Steps to Reproduce

I believe I described it with enough details to reproduce the issue.

# Version

```
v1.3.1
```
