### ISSUE TITLE
Step Loops

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3728]
# Proposed Feature

We should consider having a loop construct in promo steps in order to repeat certain steps or tasks.

# Motivation

There have been instances where I wanted to invoke a PromotionTask multiple times, with different stage names, and had to resort to doing something like:

```yaml
  promotionTemplate:
    spec:
      steps:
      - task: {name: render-commit}
        vars: [{name: stage, value: dev}]
      - task: {name: render-commit}
        vars: [{name: stage, value: staging}]
      - task: {name: render-commit}
        vars: [{name: stage, value: prod}]
```

Another request was to pass in a list of items as a var, and for the invoked promo-task to repeat a step based on the passed in items. e.g.:

```yaml
  promotionTemplate:
    spec:
      steps:
      - task:
          name: repeat-something
        vars:
        - name: my-items
          value: "[foo, bar, baz]"
```

# Suggested Implementation

Argo Workflows, IMO, had a pretty successful looping construct, which was inspired by ansible. It had `withItems`/`withParam` ([docs](https://argo-workflows.readthedocs.io/en/latest/walk-through/loops/)) as the primary loop constructs.`withItems` was an actual list in the yaml/json, whereas `withParam` was a string that could be interpreted as a list (so that it can be passed around as parameters).

If we were to follow similar approach, but using the advantage of expr, we could introduce a `loopExpression` string field that could be an expr:

```yaml
  promotionTemplate:
    spec:
      steps:
      - loopExpression: "[ 'dev', 'staging', 'prod' ]"
        task:
          name: render-commit
        vars:
        - name: stage
          value: "${item}"
```

**Comment by jessesuen** [comment]
Workflows expanded just in time; it could even take an output from a previous step to generate the loop dynamically.

Just-in-time would be nice, but I would be happy to only support static expansion as a first step.

**Comment by ivansamartino** [comment]
I'd like to share my use case for the proposed loop functionality in Kargo.

Currently, I have a promotion flow that:
1. Clones a GitOps repository
2. Updates YAML files with new container image tags
3. Commits and pushes changes (optionally as a PR)
4. Updates ArgoCD applications

I've already decomposed this into separate PromotionTasks for each logical step (git-operations, yaml-updates, argocd-updates). My specific need is to update multiple container image tags in the same values.yaml file without duplicating the entire promotion workflow for each image.

The proposed loop functionality would be ideal, but I'm specifically interested in passing a map of YAML keys and values rather than just a simple list. For example:

```yml
promotionTemplate:
  spec:
    steps:
    - loopExpression: |
        [
          {
            "yamlKey": "component-a.image.tag",
            "imageName": "component-a"
          },
          {
            "yamlKey": "component-b.image.tag", 
            "imageName": "component-b"
          },
          {
            "yamlKey": "component-c.image.tag", 
            "imageName": "component-c"
          }
        ]
      task:
        name: yaml-update-task
      vars:
      - name: yamlKey
        value: "${item.yamlKey}"
      - name: imageName
        value: "${item.imageName}"
```

Then my yaml-update-task could use these variables like:

```yml
steps:
  - uses: yaml-update
    as: update-image
    config:
      path: <path-to-values>
      updates:
        - key: ${{ vars.yamlKey }}
          value: ${{ imageFrom(vars.imageReg + "/" + vars.imageName, warehouse("my-app")).Tag }}
```

Is this the kind of use case the looping feature is intended to support? Or would you recommend a different approach with Kargo's current and planned features?

I'm particularly interested in whether:
1. The loopExpression will support maps/objects, not just simple lists
2. We'll be able to access object properties with dot notation (item.yamlKey)
3. There are any current workarounds you'd suggest for my use case

Thank you for considering this functionality!

**Comment by jessesuen** [comment]
Update: dynamic, just-in-time expansion for step loops won't be required. So, upfront expansion is what we are looking for. This should simplify things a lot.

**Comment by jessesuen** [comment]
Given that we only want to support upfront expansion (and not just-in-time), there is not a strong reason to evaluate an expression to formulate the loop. This also simplifies the syntax. Here is my revised proposal.

1.  We introduce `loop` at the same level as `task` or `uses`. `loop` has an `items` field which is a YAML list of scalars or objects.
2. In the step definition, a new variable `${{ item }}` will reference the current loop element during expansion; `${{ item.field }}` for object fields.

Example:

```yaml
steps:
  - task:
      name: render-commit
    loop:
      items:
        - dev
        - staging
        - prod
    vars:
      - name: stage
        value: ${{ item }}
```

which would expand to:

```yaml
steps:
  - task:
      name: render-commit
    vars:
      - name: stage
        value: dev
  - task:
      name: render-commit
    vars:
      - name: stage
        value: staging
  - task:
      name: render-commit
    vars:
      - name: stage
        value: prod
```

Loops would support objects as well. And the fields would be accessible from a property under `item`. e.g. `{{ item.xxxx }}`.

```yaml
steps:
  - task:
      name: deploy
    loop:
      items:
        - env: dev
          replicas: 1
        - env: staging
          replicas: 2
        - env: prod
          replicas: 5
    vars:
      - name: stage
        value: ${{ item.env }}
      - name: replicaCount
        value: ${{ item.replicas }}
```

Loops are also supported for inlined steps, and not just tasks:

```yaml
steps:
  - uses: git-clone
    loop:
      items:
        - dev
        - staging
        - prod
    config:
      repoURL: ${{ vars.gitRepo }}
      checkout:
        - branch: ${{ item }}
          path: ./${{ item }}
```

**Comment by jessesuen** [comment]
As a future improvement (not for initial implementation), we may want loops to be defined once but referencable multiple times. Something like:

```yaml
loopVars:
- name: emails
  items:
    - alice@example.com
    - bob@example.com
    - cathy@example.com

steps:
- uses: send-message
  loop:
    fromVar: emails
  config:
    channel:
      name: smtp
...
- uses: do-stuff
- uses: do-stuff
...
- uses: send-message
  loop:
    fromVar: emails
  config:
    channel:
      name: smtp
```

I know emails are a bad example, since multiple can be sent in one send-message, but you get the point.
