### ISSUE TITLE
Reference ConfigMaps for DRY configuration

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3733]
# Proposed Feature

We should support the ability to reference a project level var, or possibly even global/system level.

# Motivation

Stages and/or PromotionTasks often have to repeat definitions like:

```yaml
  vars:
  - name: repoURL
    value: https://github.com/jessesuen/kargo-rendered-branches.git
  - name: image
    value: ghcr.io/jessesuen/guestbook
  - name: branch
    value: main
```

To keep things DRY, it would be nice to define these in one shared place (e.g. a configmap), and reference it in a new expr object.

# Suggested Implementation

We already have an established pattern for referencing secrets. e.g. `secrets.slack.token`. I think we do the same but with ConfigMap:

```yaml
  - uses: git-clone
    config:
      repoURL: ${{ config.myproj.repoURL }}
      checkout:
      - branch: ${{ config.myproj.branch }}
        path: ./main
```
