### ISSUE TITLE
Error with PromotionTask after upgrading to v1.3.2 for new projects

### ISSUE THREAD

**Issue by aarontams** [akuity/kargo#3734]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

After upgrading to v1.3.2 this week, I am encountering the following error when attempting to use PromotionTask for my stage promotion. This issue only occurs with new projects:

`admission webhook "promotion.kargo.akuity.io" denied the request: PromotionTask.kargo.akuity.io "snoopy-demo" not found`

#### Example configuration for Stage and PromotionTask:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: local-promotion
  namespace: my-service
spec:
  promotionTemplate:
    spec:
      steps:
        - task:
            kind: PromotionTask
            name: snoopy-demo
```

```
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: snoopy-demo
  namespace: my-service
```

#### When I switch the PromotionTask to ClusterPromotionTask, it works fine:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: cluster-promotion
  namespace: my-service
spec:
  promotionTemplate:
    spec:
      steps:
        - task:
            kind: ClusterPromotionTask
            name: snoopy-demo
```

```
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: snoopy-demo
```

#### Additional Information:
This issue appears only when using PromotionTask with new projects.
Changing to ClusterPromotionTask resolves the issue.

# Screenshots

<img width="373" alt="Image" src="https://github.com/user-attachments/assets/81a7533e-3dea-4d66-a645-46f327549020" />

# Steps to Reproduce

- Upgrade to v1.3.2.
- Attempt to create a Stage using PromotionTask for a new project.
- Observe the error message: PromotionTask.kargo.akuity.io "snoopy-demo" not found.

# Version

```
v1.3.2
```

# Logs

```
Paste any relevant application logs here.
```
