### ISSUE TITLE
document that when searching for creds repo urls are normalized before attempting pattern match

### ISSUE THREAD

**Issue by shellwhale** [akuity/kargo#3736]
Just like suggested in the [docs](https://docs.kargo.io/user-guide/security/managing-credentials/) I'd like to use `repoURLIsRegex` in or to match my repos at `https://dev.azure.com/MY-ORG/*
`.
> This is useful if, for example, your project accesses many GitHub repositories, all beginning with https://github.com/example-org, and can use the same token for accessing all of them.

Here is the relevant part of my PromotionTask

```
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: demo-promo-process
  namespace: hello-world
spec:
  vars:
    - name: gitopsRepo
  steps:
    - uses: git-clone
      config:
        repoURL: "https://MY-ORG@dev.azure.com/MY-ORG/hello-world/_git/hello-world"
        checkout:
          - branch: main
            path: ./main
          - branch: stage/${{ ctx.stage }}
            create: true
            path: ./out
```

This works
```
apiversion: v1
kind: secret
metadata:
  labels:
    kargo.akuity.io/cred-type: git
  name: test-hello-world-registry-password
  namespace: kargo-global-creds
data:
  password: mypass
  repoURL: "https://MY-ORG@dev.azure.com/my-org/hello-world/_git/hello-world"
  repoURLIsRegex: "false"
  username: azure-user
type: opaque
```

But not this if (using a regex)
```
  repoURL: "^https:\/\/MY-ORG@dev\.azure\.com\/MY-ORG.*"
  repoURLIsRegex: "true"
```

This gives the following error :
`
step execution failed: step 0 met error threshold of 1: failed to run step "git-clone": error cloning https://MY-ORG@dev.azure.com/EDU-VD-CH/hello-world/_git/hello-world: error cloning repo "https://MY-ORG@dev.azure.com/MY-ORG/hello-world/_git/hello-world" into "/tmp/promotion-753900cd-e231-4fba-8a2a-de4086adba56/repo-3725121836/repo": error executing cmd [/usr/bin/git clone --bare https://MY-ORG@dev.azure.com/MY-ORG/hello-world/_git/hello-world /tmp/promotion-753900cd-e231-4fba-8a2a-de4086adba56/repo-3725121836/repo]: Cloning into bare repository '/tmp/promotion-753900cd-e231-4fba-8a2a-de4086adba56/repo-3725121836/repo'... fatal: could not read Password for 'https://MY-ORG@dev.azure.com': No such device or address
`
I also tried to remove the MY-ORG@ like so 

```
repoURL: ^https:\/\/dev\.azure\.com\/EDU-VD-CH\/.* # From the Secret
```
```
repoURL: https://dev.azure.com/EDU-VD-CH/hello-world/_git/hello-world # From the PromotionTask
```

But I get the following error:

`
step execution failed: step 0 met error threshold of 1: failed to run step "git-clone": error cloning https://dev.azure.com/MY-ORG/hello-world/_git/hello-world: error cloning repo "https://dev.azure.com/MY-ORG/hello-world/_git/hello-world" into "/tmp/promotion-8c78e61f-9054-43ed-b301-9df5ba51c764/repo-797773650/repo": error executing cmd [/usr/bin/git clone --bare https://dev.azure.com/MY-ORG/hello-world/_git/hello-world /tmp/promotion-8c78e61f-9054-43ed-b301-9df5ba51c764/repo-797773650/repo]: Cloning into bare repository '/tmp/promotion-8c78e61f-9054-43ed-b301-9df5ba51c764/repo-797773650/repo'... fatal: could not read Username for 'https://dev.azure.com': No such device or address
`

I'm clueless about what to try next, I cannot find a proper example on how to use a regex for this.
