### ISSUE TITLE
Image version is interpreted as number instead of string in Kargo 1.3.2

### ISSUE THREAD

**Issue by ToniA** [akuity/kargo#3743]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

If the image version is a number (like '1' or '1.2'), the kustomize-set-image treats it as a number, leading to an error:
```
Promotion Errored
step execution failed: step 2 met error threshold of 1: failed to run step "kustomize-set-image": invalid kustomize-set-image config: images.0.tag: Invalid type. Expected: string, given: number images.1.tag: Invalid type. Expected: string, given: number
```

# Screenshots

# Steps to Reproduce

* Have an image Warehouse with images with tags which are either plain integer numbers, or SemVer with two number fields (like 1.2)
* Attempt to promote a Freight with such images
* Promotion fails, as it tries to update a string field with a number

```
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/apps/application/dev/images-component
          images:
          - image: ${{ vars.imageRepoApi }}
            tag: ${{ imageFrom(vars.imageRepoApi).Tag }}
          - image: ${{ vars.imageRepoSpa }}
            tag: ${{ imageFrom(vars.imageRepoSpa).Tag }}
```

As a workaround, use 'Digest' instead of 'Tag':

```
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/apps/application/dev/images-component
          images:
          - image: ${{ vars.imageRepoApi }}
            digest: "${{ imageFrom(vars.imageRepoApi).Digest}}"
          - image: ${{ vars.imageRepoSpa }}
            digest: "${{ imageFrom(vars.imageRepoSpa).Digest}}"
```

We also tried these, but they didn't work
```
tag: ${{ quote(imageFrom(vars.imageRepoSpa).Tag) }}
tag: "${{ imageFrom(vars.imageRepoSpa).Tag }}"
```

# Version

```
$ kargo version
Client Version: v1.3.2
Server Version: v1.3.2
```

# Logs

**Comment by krancour** [comment]
https://docs.kargo.io/user-guide/reference-docs/expressions#types

**Comment by ToniA** [comment]
We tried the quote function, and got YAML where the image tag was enclosed both in double and single quotes, like `"'42'"`

**Comment by krancour** [comment]
🤔 that's odd. I'm looking into it.

**Comment by krancour** [comment]
@ToniA can you show me what the step looked like when you tried it with the `quote()` function?

**Comment by ToniA** [comment]
We used to have Kargo 1.2.2 with this step
```
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/apps/application/dev/images-component
          images:
          - image: acr.azurecr.io/application/api
          - image: acr.azurecr.io/application/spa
```
In Kargo 1.3.2 we tried this, after we figured out that numbers need to be converted to strings
```
  promotionTemplate:
    spec:
      vars:
      - name: imageRepoApi
        value: acr.azurecr.io/application/api
      - name: imageRepoSpa
        value: acr.azurecr.io/application/spa
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/apps/application/dev/images-component
          images:
          - image: ${{ vars.imageRepoApi }}
            tag: ${{ quote(imageFrom(vars.imageRepoApi).Tag) }}
          - image: ${{ vars.imageRepoSpa }}
            tag: ${{ quote(imageFrom(vars.imageRepoSpa).Tag) }}
```
The result was a commit, which looked like this (previous state was from Kargo 1.2.2):
```
 - name: acr.azurecr.io/application/api
-  newTag: "1.4261"
+  newTag: '"1.4262"'
 - name: acr.azurecr.io/application/spa
-  newTag: "1.6988"
+  newTag: '"1.6988"'
```
We finally ended up with this. The digest is always a string, as it starts with `sha256:`. The downside is that it makes the manifest repo, deployments and pods harder to read, as image references are no longer tags.
```
      - uses: kustomize-set-image
        as: update-image
        config:
          path: ./src/apps/application/dev/images-component
          images:
          - image: ${{ vars.imageRepoApi }}
            digest: "${{ imageFrom(vars.imageRepoApi).Digest}}"
          - image: ${{ vars.imageRepoSpa }}
            digest: "${{ imageFrom(vars.imageRepoSpa).Digest}}"
```
