### ISSUE TITLE
OpenShift RBAC requirements for Kargo auto-promotion and resource ownership

### ISSUE THREAD

**Issue by dlydiard** [akuity/kargo#3746]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description
While testing Kargo on OpenShift, I encountered issues where auto-promotion failed due to permission errors around resource ownership and finalizers. These did not surface in the Stage CR status or UI, and were only visible via the `kargo-controller` pod logs.

This issue tracks the specific RBAC adjustments necessary for Kargo to function correctly on OpenShift, particularly for scenarios involving:
	•	Auto-promotion
	•	Finalizer management
	•	OwnerReferences

The following RBAC adjustments allows Kargo to run correctly in OpenShift
```yaml
# Give Kargo Management Controller special access to delete Project namespaces to work around ownerReference permission errors
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-management-controller-openshift
rules:
  - verbs:
      - delete
    apiGroups:
      - ''
    resources:
      - namespaces

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-management-controller-openshift
subjects:
  - kind: ServiceAccount
    name: kargo-management-controller
    namespace: kargo-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-management-controller-openshift

---

# Give kargo-controller finalizer access to perform auto-promotions - to work around ownerReference/blockOwnerDeletion permission errors
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-controller-openshift
rules:
  - verbs:
      - update
    apiGroups:
      - kargo.akuity.io
    resources:
      - freights/finalizers
      - stages/finalizers

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-controller-openshift
subjects:
  - kind: ServiceAccount
    name: kargo-controller
    namespace: kargo-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-controller-openshift
```

# Screenshots

See discussion in https://github.com/akuity/kargo/issues/3719

# Steps to Reproduce

See comment in https://github.com/akuity/kargo/issues/3719#issuecomment-2754423551 for test case yaml.

# Version

```
v1.3.2
```

# Logs

```
time="2025-03-27T23:43:19Z" level=error msg="Reconciler error" Stage="{management kargo-poc}" controller=stage controllerGroup=kargo.akuity.io controllerKind=Stage error="failed to auto-promote Freight: error creating Promotion for Freight \"fb9c8d21a0abb87f852f2a58848b829c13c6f9e4\" in namespace \"kargo-poc\": promotions.kargo.akuity.io \"management.01jqczt89zg5j6f2v6qcekm5ph.fb9c8d2\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" name=management namespace=kargo-poc reconcileID="\"91c129f4-3b2b-48c3-874a-f55207c76301\""
time="2025-03-27T23:51:34Z" level=error msg="Reconciler error" Stage="{devops-sandbox kargo-poc}" controller=stage controllerGroup=kargo.akuity.io controllerKind=Stage error="failed to auto-promote Freight: error creating Promotion for Freight \"bb951a8cee2dab7144ed9c1ffb32ea7f4baf965b\" in namespace \"kargo-poc\": promotions.kargo.akuity.io \"devops-sandbox.01jqd09asvhgqcaw1rf5nfhgj4.bb951a8\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" name=devops-sandbox namespace=kargo-poc reconcileID="\"af62ceba-6303-437f-8123-bdb25740efb3\""
```
