### ISSUE TITLE
Kargo Dex - Document or add direct support for OpenShift SSO

### ISSUE THREAD

**Issue by dlydiard** [akuity/kargo#3747]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Add documentation and/or a Helm values that show how to configure Kargo’s built-in Dex instance to use OpenShift OAuth, similar to how OpenShift GitOps supports it in the [`ArgoCD` CR](https://docs.redhat.com/en/documentation/openshift_container_platform/4.8/html/cicd/gitops#gitops-creating-a-new-client-in-dex_configuring-sso-for-argo-cd-using-dex):

```yaml
dex:
  enabled: true
  openShiftOAuth: true
```

# Motivation
Kargo already supports Dex and has flexible Helm chart options for custom connectors. However, it’s unclear how to properly configure Dex for OpenShift OAuth specifically.

Other Red Hat-integrated tools like OpenShift GitOps (Argo CD) allow you to enable Dex with `openShiftOAuth: true`, which simplifies SSO by leveraging the platform’s built-in identity provider.

I’d like to use the built-in Dex service in Kargo with OpenShift OAuth, but I’m unsure of the correct configuration.

# Suggested Implementation
This could be resolved with a docs update that includes:
+ An example of a working dex.connectors block for OpenShift OAuth.
+ Any special RBAC, ServiceAccount, or OAuthClient setup needed in OpenShift.
+ Alternatively, could a Helm value like `openShiftOAuth: true` be introduced to simplify configuration for OpenShift environments?

**Comment by dlydiard** [comment]
I'm trying to set up Dex with OpenShift OAuth using a ServiceAccount as the OAuth client, as recommended here: https://dexidp.io/docs/connectors/openshift/

I assume the `kargo-dex-server` ServiceAccount needs the annotation, but the Kargo Helm chart doesn't support adding annotations to it:  
https://github.com/akuity/kargo/blob/da4dadd09f1ac095f424943870df7c9289f6104b/charts/kargo/templates/dex-server/service-account.yaml#L5

Also, what should the annotation value be?  
Something like this?  
`serviceaccounts.openshift.io/oauth-redirecturi.dex: 'https://kargo-dex-server.kargo-operator.svc.cluster.local/auth/callback'`

For OpenShift setups using Dex with a ServiceAccount as the OAuth client, it seems like the Helm chart could also generate a `Secret` annotated with `kubernetes.io/service-account.name`. This would allow the token to be injected into the Dex container via environment variables.

In other words, it feels like the Kargo Helm chart could support OpenShift Dex integration with a one-liner toggle. That would eliminate the need for users to manually annotate the ServiceAccount or figure out what configuration values are actually needed — tasks that are error-prone and not widely understood. It could make Dex + OpenShift "just work" out of the box.

Would appreciate any guidance from folks with OpenShift experience.

**Comment by krancour** [comment]
> I assume the kargo-dex-server ServiceAccount needs the annotation

That _might_ work, but I cannot guarantee it. In a normal k8s cluster, ever since k8s 1.24, a token is _not_ automatically created for every service account. So unless _OpenShift_ still does so, the Dex server's ServiceAccount doesn't have a token. I'm not really experienced with OpenShift, so I'm not sure.

If it doesn't automatically have a token, you need to create a `Secret` of type `kubernetes.io/service-account-token`. At that point you've crossed the threshold where this is no longer _only_ a matter of adding an annotation.

fwiw, the docs do not suggest to me that you _must_ use Dex's own SA.

> The Client ID for a Service Account representing an OAuth Client takes the form `system:serviceaccount:<namespace>:<service_account_name>`.

Creating your own, dedicated, properly annotated SA _with a token_, could _potentially_ end up being the most expedient path.

As an aside, we're deliberately avoiding building support for specific IDPs. OIDC, with Dex as an optional adapter for IDPs that may not implement OIDC natively, were meant to provide a common interface for the rest of Kargo so that we wouldn't have to build IDP-specific support, but I am amenable to the possibility of more _generic_ enhancements to the chart -- say the capability to add any arbitrary annotations to any of Kargo's SAs (we already have something similar for Deployments, Pods, Services, etc.) or capability to add a token to any of those SAs. But before heading down that road, I think it would be worth it for you to do some further experimentation to see exactly how difficult it is (or isn't) to create your own dedicated SA for this purpose.

**Comment by dlydiard** [comment]
I was able to get OpenShift Dex working using the following GitOps friendly configuration:

Kargo HELM values:
```yaml
api:
  host: kargo-api.my-cluster.private.ingress.com

  oidc:
    enabled: true
    admins: # For demo purposes
      claims:
        groups:
          - MyAdminGroup
    viewers:
      claims:
        groups:
          - SomeOtherGroup
    dex:
      enabled: true
      env:
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: openshift-dex
              key: token
      connectors:
        - id: dex 
          type: openshift
          name: OpenShift
          config:
            issuer: https://api.my-cluster.xxxx.xx.openshiftapps.com:6443 # or 443 if using HCP
            clientID: system:serviceaccount:kargo-operator:openshift-dex
            clientSecret: $CLIENT_SECRET
            redirectURI: https://kargo-api.my-cluster.private.ingress.com/dex/callback
            insecureCA: false
````

Dex ServiceAccount and Secret
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-dex
  namespace: kargo-operator
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.dex: https://kargo-api.my-cluster.private.ingress.com/dex/callback 

---

kind: Secret
apiVersion: v1
type: kubernetes.io/service-account-token
metadata:
  name: openshift-dex
  namespace: kargo-operator
  annotations:
    kubernetes.io/service-account.name: openshift-dex
```

Totally understand the need to keep the product agnostic to Kubernetes distributions. Just leaving this here for future reference—maybe the Kargo docs could eventually include examples. Closing this for now; hopefully it’s enough for OpenShift users to get started with OIDC service accounts and Dex integration. Having gone through it myself, the setup wasn’t exactly straightforward.
