### ISSUE TITLE
[Feature] Support Passing Dynamic Key-Value Pairs in helm-template Step

### ISSUE THREAD

**Issue by aarontams** [akuity/kargo#3753]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Enable passing dynamic variables directly through Kargo's helm-template step, similar to the --set flag in Helm. This would allow users to override or set specific key-value pairs during rendering without modifying the values.yaml files.

# Motivation

Currently, when using Kargo's helm-template step, values must be provided through valuesFiles. However, in many cases, it's convenient to pass dynamic values or override specific keys without modifying the values.yaml files or maintaining multiple environment-specific files.

Helm's --set flag allows users to set values directly in the command line during deployment, which is useful for quick updates and overriding values for specific environments or configurations. Adding similar functionality to the helm-template step in Kargo would enable more flexible and dynamic templating, especially in CI/CD pipelines or automation scripts where certain values may need to be passed in without altering the existing values.yaml files.

# Suggested Implementation

Add support for passing dynamic key-value pairs using a --set-like flag to Kargo's helm-template step. This could be implemented by:

### Adding a New Field to the helm-template Step:
A new optional field setValues can be added to the configuration.

### Rendering with Dynamic Values:
When the helm-template step is executed, Kargo would append the --set values to the Helm helm template command internally, allowing users to override or set values dynamically.

```
- uses: helm-template
  as: renderingToDeployRepo
  config:
    disableHooks: false
    includeCRDs: false
    outPath: ${{ vars.deployRepoDir }}/mop-carrier-ops/environments/dev/us-east-1
    path: ${{ vars.serviceRepoDir }}/kubernetes/helm/mop-carrier-ops
    skipTests: false
    releaseName: ${{ vars.releaseName }}
    useReleaseName: false
    valuesFiles:
      - ${{ vars.serviceRepoDir }}/values.yaml
      - ${{ vars.serviceRepoDir }}/dev-values.yaml
      - ${{ vars.serviceRepoDir }}/dev-us-east-1.yaml
    setValues:
      - key: foo1
         value: bar1
      - key: foo2
         value: bar2
```

**Comment by aarontams** [comment]
Also see related Enhancement that I filed  https://github.com/akuity/kargo/issues/3753

**Comment by BenHesketh21** [comment]
I may be wrong but isn't this solved by the yaml-update promotion step? You can just set whatever value you want in any of your value files if you want to override at the time of render? 

```
- uses: yaml-update
  config:
    path: ./src/charts/my-chart/values.yaml
    updates:
    - key: foo1
      value: bar1
    - key: foo2
      value: bar2
```
