### ISSUE TITLE
ImageSelectionStrategy Digest requires Constraint but Constraint field does not accept non-SemVer

### ISSUE THREAD

**Issue by avo-sepp** [akuity/kargo#3783]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

According to [this documentation](https://docs.kargo.io/user-guide/how-to-guides/working-with-warehouses#image-selection-strategies) a Digest Strategy "**Unintuitively**, the mutable tag name must be specified using the semverConstraint field"

This is true. The Digest Strategy will fail if a semverConstraint is not listed. However, if I try and apply a Warehouse manifest with semverConstraint of `edge` or `latest` I get an error:

```The Warehouse "edge" is invalid: spec.subscriptions[0].image.semverConstraint: Invalid value: "edge"```

# Steps to Reproduce

Try and apply a warehouse with digest and a semverConstraint that is not semver, per the documentation for a digest imageSelectionStrategy

# Version

```
1.3.2
```

# Logs

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: edge
  namespace: example
spec:
  subscriptions:
  - image:
      repoURL: <repo>
      imageSelectionStrategy: Digest
      semverConstraint: edge
      discoveryLimit: 6
```

```
The Warehouse "edge" is invalid: spec.subscriptions[0].image.semverConstraint: Invalid value: "edge"
```

If I do not put a constraint, but try something like `allowTags` instead I get the following error in the Kargo UI

```
Unable to discover artifacts: error discovering images: error discovering latest images "repo": error creating image selector for image "repo": digest selection strategy requires a constraint
```
