### ISSUE TITLE
Introduce stage-level `spec.vars` referenceable from `verifications`

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3787]
# Proposed Feature

Stages have a concept of vars, but they are defined at the `spec.promotionTemplate.spec.vars` level. This means that they are not accessible to areas outside `promotionTemplate`, namely `verification`. 

But verification might also need to access these vars and pass them to an AnalysisTemplate. This proposal is to move `vars` to the `.spec` level, so that they can be referenced by verification.

Example:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
...
spec:
  vars:
  - name: branch
    value: foo
  promotionTemplate:
    spec:
      steps:
      - uses: git-clone
        config:
          repoURL: https://github.com/example/example.git
          checkout:
          - branch: ${{ vars.branch }}
            path: ./out
  verification:
    analysisTemplates:
    - name: smoke-test
    args:
    - name: branch
      value: ${{ vars.branch }}
```

# Motivation

This part of overall effort to keep things DRY. 
Related issue https://github.com/akuity/kargo/issues/3733.

Combined with https://github.com/akuity/kargo/issues/3733, users would have two ways to keep things DRY:
1. if var is needed across Stages, it would go into a ConfigMap
2. if var needed for single Stage, it would go into the Stage's `spec.vars`

# Suggested Implementation

See above spec proposal. To maintain backward compatibility, we could prefer looking at `spec.vars`, but if those are not defined, then we fall back to `spec.promotionTemplate.vars`

**Comment by krancour** [comment]
Building vars outside the context of a promotion process would remove the possibility of referencing promotion-specific or freight-specific data. i.e. `ctx.promotion` and functions like `imageFrom()` would be unavailable.


This works today, but would no longer:

```yaml
spec:
  vars:
  - name: foo
    value: ${{ "a value that incorporates " + ctx.promotion }}
```

I can very clearly see why one would want to define vars at a higher level, but I think rather than _move_ `spec.promotionTemplate.spec.vars` to `spec.vars`, we should just _add_ `spec.vars` as another, higher scope, so you could define vars at the Stage level if you had the need, then optionally amend or override vars at the promotion process level if Promotion and/or Freight-specific context is required in defining the var's value.
