### ISSUE TITLE
Add allowBranches Option for Warehouse Git Repository Subscription

### ISSUE THREAD

**Issue by aarontams** [akuity/kargo#3798]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

I would like to suggest a new option, **_allowBranches_**, for Kargo Git subscription configurations.

This would allow users to define a regular expression to limit the selection of branches eligible for commits, similar to how **_allowTags_** works for tags. It would give more flexibility to users who need to restrict their subscriptions to specific branches.

# Motivation

Currently, the branch field allows for targeting a single branch, but it doesn't provide flexibility when multiple branches need to be considered based on a pattern. With the allowBranches option, users would be able to specify which branches to include based on a regular expression. This would be especially useful in scenarios where:

Multiple feature branches follow a naming convention (e.g., `feature/*` or `release/*`).
Users want to limit subscriptions to specific branch patterns without having to manually update the branch field.
It allows for more dynamic selection of branches based on naming patterns.

### Benefits
- Increased Flexibility: Users can define branch patterns without hardcoding specific branch names.
- Consistency: This option enables more predictable behavior in environments where branches follow naming conventions.
- Simplified Configuration: Users will not have to manually update their subscription configuration whenever a new branch that fits the pattern is created.

# Suggested Implementation

Add the following field to the Git subscription configuration:

**_allowBranches_** (optional, string): A regular expression that limits the branches eligible for selection. Only branches matching this pattern will be considered for commits.
Example:
```
spec:
  subscriptions:
    - git:
        repoURL: https://github.com/example/repo.git
        allowBranches: "^feature/.*"
```
In this example, only branches that start with feature/ will be eligible for commit selection.

**Comment by aarontams** [comment]
Like the `allowTags` and `ignoreTags` pair.
We should also consider to support `allowBranches` and `ignoreBranches` pair.

**Comment by krancour** [comment]
This was requested once before in https://github.com/akuity/kargo/issues/2907, but we had a hard time understanding how this wasn't more dangerous than useful since it leads to an awful lot of unpredictability in terms of what's being promoted to where and when.

I'd be happy to hear more about your use case in an attempt to either make sense of this or help you find an alternative.

**Comment by aarontams** [comment]
I raised a **WIP PR**, https://github.com/akuity/kargo/pull/3815,  to demonstrate how I plan to use this feature.  The PR is currently blocked because the 
> git fetch origin
> git for-each-ref --format='%(refname)' refs/remotes
doesn't work within Kargo. It work from my Mac terminal.


For example:
```
  subscriptions:
    - git:
        allowTags: .*
        commitSelectionStrategy: NewestBranch
        discoveryLimit: 10
        repoURL: https://github.com/akuity/kargo

  subscriptions:
    - git:
        allowTags: .*
        ignoreTags: ["main", "master"]
        commitSelectionStrategy: NewestBranch
        discoveryLimit: 10
        repoURL: https://github.com/akuity/kargo
```

Ideally, I want to create two separate warehouses:

- One for the main/master branch only, with dev/stage/prod Kargo stages.

- One for all branches (or non-default branches), but with only the dev Kargo stage. This setup should allow promotion with any branch that is newly created or updated.

#### Workaround with Tags
For now, the workaround is to tag a branch and use the `allowTags` and `ignoreTags` options for all the branches. However, I don't think users would want to rely on this workaround. In the Git world, pipelines are typically triggered when a branch is created or changes, much like how Buildkite operates.
