### ISSUE TITLE
Links to commits in git subscriptions

### ISSUE THREAD

**Issue by BenHesketh21** [akuity/kargo#3814]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

This may be a setting I can't find or something but we should be able to click through to the commit on Github/Gitlab for Git subscription types, after using the OCI annotations for container subscriptions (which is super useful) this feels like a nice addition.

# Motivation

It would allow a user to click through and see the commit that the Freight is referring to.

# Suggested Implementation

Build the URL the same way the UI does from the OCI annotations using the RepoURL and commit ID in the freight.
Or for a more future proof way (if/when more git providers come along), add a field to the subscriptions that is like the Github Autolink feature so they would need to add something like:

```
  - git:
      repoURL: https://github.com/some-org/some-repo
      linkPathFormat: /commit/{{ id }}
      strictSemvers: false
      discoveryLimit: 10
```
