### ISSUE TITLE
git-open-pr implementation for GitLab always checks "Delete source branch" option

### ISSUE THREAD

**Issue by BWagenerGenerali** [akuity/kargo#3858]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

We are currently evaluating Kargo and one apparent bug we have observed is that the `git-open-pr` promotion step has unexpected behavior. We can only speak to our experience with the GitLab implementation of this step.

Regardless of the repository configuration, the step always checks the "Delete source branch" option for the opened PR. So despite explicitly disabling this option by default in the GitLab repository configuration, the step will create a PR with this option checked.

# Steps to Reproduce

Use this step in your promotionTemplate

```yaml
    - uses: git-open-pr
      as: open-pr
      config:
        repoURL: "{{ `${{ vars.gitopsRepo }}` }}.git"
        provider: gitlab
        sourceBranch: "{{ `${{ vars.sourceBranch }}` }}"
        targetBranch: "{{ `${{ vars.targetBranch }}` }}"
```

# Version

```
Client Version: v1.4.0
Server Version: v1.4.0
```
