### ISSUE TITLE
step execution failed: step 3 met error threshold of 1: failed to run step "helm-update-chart": failed to update chart dependencies: could not find protocol handler for: alias

### ISSUE THREAD

**Issue by david-curran-90** [akuity/kargo#3894]
# Checklist

* [ *] I've searched the issue queue to verify this is not a duplicate bug report.
* [ *] I've included steps to reproduce the bug.
* [ *] I've pasted the output of `kargo version`.
* [ *] I've pasted logs, if applicable.

# Description

We use aliases in our helm Chart.yaml

```
dependencies:
  - name: my-chart
     version: 1.22.0
     repository: alias:dr
```

In the promotion tasks we are doing this to update the chart

```
  steps:
  - uses: helm-update-chart
    config:
      path: ${{ vars.appGitPath }}/${{ vars.appHelmPath }}
      charts:
      - repository: alias:dr
        name: my-chart
        version: 1.22.0
```

However this causes an issue in Kargo

```
failed to run step "helm-update-chart": failed to update chart dependencies: could not find protocol handler for: alias
```

I have tried using just the alias name `dr` and also escaping `alias\:dr` but these just cause issues with not being able to find any entry for the dependency

```
failed to run step "helm-update-chart": no dependency in Chart.yaml matched update with repository dr and name
```

# Steps to Reproduce

* Use a helm chart with an alias in the dependency
* Use the helm-update-chart step to update the dependency

# Version

```
1.4.0
```
