### ISSUE TITLE
Introduce `kargo-user` ClusterRole

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#3896]
# Proposed Feature

Kargo currently comes with two ClusterRoles out-of-the-box:
* `kargo-admin`
* `kargo-viewer`

The `kargo-viewer` gives privileges to view all objects across all projects. However, this may be considered too broad, since a user can peek into any project and see stages/warehouses/etc...

On the other hand, the Kargo UI is unusable unless you can view all projects. Even if a user has `view` privileges to all resources in a single project, they can't do so without `get` on projects (or at least their own project)

I think we need to create a ~`kargo-project-viewer`~ `kargo-user` ClusterRole that can view all projects (but not resources in all projects), so an end user can at least navigate to their own project from the project list view.

# Motivation

Currently, an admin is forced to give `kargo-viewer` to everyone just for Kargo to be usable. By having a ~`kargo-project-viewer`~ `kargo-user`, the Kargo admin can give everyone just the privilege to list all projects (and system settings), but not see the objects inside every project.

# Suggested Implementation

Add another ClusterRole as part of helm chart.

**Comment by krancour** [comment]
This requires #3888 as well as the redesigned Project list view @rpelczar is working on because the existing Project list view queries for Stages. Once those are both complete, the rest of this is easy.

**Comment by krancour** [comment]
Although there's the question of how to either make Projects unclickable if the user lacks access to resources within it OR gracefully handle it when a Project is selected and the user's lack of permissions within the project make it impossible to construct the Project view.

**Comment by Kavinraja-G** [comment]
@jessesuen @krancour -- I have created a ClusterRole `kargo-project-viewer` which is for users to get pass through the homePage without any issues on listing the projects. 
```
─❯ k get rolebinding -n conduit-sbx
NAME                            ROLE                                        AGE
kargo-admin                     Role/kargo-admin                            19h
kargo-controller-read-secrets   ClusterRole/kargo-controller-read-secrets   19h
kargo-project-admin             ClusterRole/kargo-project-admin             19h
kargo-project-viewer            ClusterRole/kargo-project-viewer            3h14m
kargo-viewer                    Role/kargo-viewer                           19h

─❯ k get clusterrole kargo-project-viewer -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-project-viewer
rules:
- apiGroups:
  - kargo.akuity.io
  resources:
  - projects
  verbs:
  - get
  - list
```

I did binded with the namespace SA which is created by Kargo for both `kargo-admin` & `kargo-viewer`
```
╰─❯ k get rolebinding -n conduit-sbx kargo-project-viewer -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-project-viewer
  namespace: conduit-sbx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-project-viewer
subjects:
- kind: ServiceAccount
  name: kargo-admin
  namespace: conduit-sbx
- kind: ServiceAccount
  name: kargo-viewer
  namespace: conduit-sbx
```

But the users is always getting:
`projects.kargo.akuity.io is forbidden: list is not permitted`

And, as an admin when I tried to see the Roles section in the `conduit-sbx` project. I'm getting this below error:

![Image](https://github.com/user-attachments/assets/6e5c3f26-4a80-4fe1-8478-24c09f5cf40e)
