### ISSUE TITLE
yaml-update step fails when referencing indexed keys

### ISSUE THREAD

**Issue by shezaan-hashgraph** [akuity/kargo#3907]
My preferred way of deploying helm charts is via kustomize helm. e.g.:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guestbook

helmCharts:
- name: guestbook
  releaseName: guestbook
  version: 1.2.3
  repo: https://github.com/guestbook/charts
  valuesFile: values.yaml
- name: guestbook
  releaseName: guestbook-2
  version: 1.2.3
  repo: https://github.com/guestbook/charts
  valuesFile: values.yaml
```

I am now trying to use the yaml-update step to update the version in kustomization.yaml like this

```
- uses: yaml-update
  config:
      path: ./src/apps/guestbook/overlays/${{ vars.overlay }}/kustomization.yaml
      updates:
        - key: helmCharts[0].version
          value: ${{ chartFrom("https://guestbook.github.io/xxxxxx/charts", "xxxx", warehouse("xxxxx")).Version }}
```

I get this error

```
step execution failed: step 1 met error threshold of 1: failed to run step "yaml-update": values file update failed: error updating image references in values file "./src/apps/guestbook/overlays/test/kustomization.yaml": error mutating bytes: error finding key helmCharts[0].version: key path not found
```

It seems to work if I try to update the `namespace` key in the kustomization.yaml manifest. So I suspect the issue is with the indexing i.e. `helmCharts[0].version` ?

What am I doing wrong?
