### ISSUE TITLE
Stages in unhealthy state with ArgoCD apps using multiple sources

### ISSUE THREAD

**Issue by d47zm3** [akuity/kargo#3910]
I have quite few apps in my ArgoCD repository, I use same Stage to update two apps on different clusters that should use same image on dev
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: app-api
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: app-api
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: git@ssh.dev.azure.com:v3/Company/DevOps/argocd
        - name: imageRepo
          value: company.azurecr.io/app/app-api
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./out
        - uses: yaml-update
          as: update-image
          config:
            path: ./out/values/myapp1-${{ ctx.stage }}.yaml
            updates:
              - key: image.tag
                value: "${{ quote(imageFrom(vars.imageRepo).Tag) }}"
        - uses: yaml-update
          as: update-image
          config:
            path: ./out/values/myapp2-${{ ctx.stage }}.yaml
            updates:
              - key: image.tag
                value: "${{ quote(imageFrom(vars.imageRepo).Tag) }}"
        - uses: git-commit
          as: commit
          config:
            path: ./out
            messageFromSteps:
              - update-image
        - uses: git-push
          config:
            path: ./out
        - uses: argocd-update
          config:
            apps:
              - name: myapp1-${{ ctx.stage }}
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}
        - uses: argocd-update
          config:
            apps:
              - name: myapp2-${{ ctx.stage }}
                sources:
                  - repoURL: ${{ vars.gitRepo }}
                    desiredRevision: ${{ outputs.commit.commit }}
```

however after some time I see stages are unhealthy
```
 Not all sources of Application "myapp" in namespace "argocd" are synced to the desired revisions. Issues: Source 1 with RepoURL git@ssh.dev.azure.com:v3/Company/DevOps/argocd of Application "myapp" in namespace "argocd" does not match the desired revision "ab80031783b0b27d8ba4a00bfbc16d3aa8567dd1".; Not all sources of Application "myapp" in namespace "argocd" are synced to the desired revisions. Issues: Source 1 with RepoURL git@ssh.dev.azure.com:v3/Company/DevOps/argocd of Application "myapp" in namespace "argocd" does not match the desired revision "ab80031783b0b27d8ba4a00bfbc16d3aa8567dd1".; Not all sources of Application "myapp" in namespace "argocd" are synced to the desired revisions. Issues: Source 1 with RepoURL git@ssh.dev.azure.com:v3/Company/DevOps/argocd of Application "myapp" in namespace "argocd" does not match the desired revision "ab80031783b0b27d8ba4a00bfbc16d3aa8567dd1".
```
which makes sense if more updates are pushed to repository... not sure how can I avoid that unhealthy status?
