### ISSUE TITLE
Extend Promotion Variable context (ctx) to include new resource: "targetFreight"

### ISSUE THREAD

**Issue by johnpekcan** [akuity/kargo#3915]
# Checklist
* [X] I've searched the issue queue to verify this is not a duplicate feature request.
* [X] I've pasted the output of `kargo version`, if applicable.
* [X] I've pasted logs, if applicable.

- Kargo Version: `1.4.2`

Related to comment(s) here:
- https://github.com/akuity/kargo/issues/3225#issuecomment-2590757570
- https://github.com/akuity/kargo/issues/3519

# Proposed Feature
Add an additional object to the [existing ctx structure](https://docs.kargo.io/user-guide/reference-docs/expressions#context-ctx-object-structure) named “targetFreight” that exposes detail on freight ID, alias, warehouse ID, and warehouse name.

```tree
ctx
├── project: string           # The name of the Project
├── stage: string             # The name of the Stage
├── promotion: string         # The name of the Promotion
├── targetFreight: string     # The name of the Freight that initiated this Promotion
└── meta
    └── promotion
        └── actor: string     # The creator of the Promotion
    └── targetFreight
        └── origin:
            └── name: string  # The name of the warehouse that contains the Freight responsible for this Promotion
```

# Motivation
We are looking to give parity for our Helm + Github Actions users to our early adopters in Kargo.

Currently, we have a use case in which:
All commits are autopromoted to dev environment(s)
Tagged (SemVer) releases are automatically deployed to all environments (dev, stage, prod)

To achieve this, we have created (2) warehouses – one warehouse that filters for the allowed tag `^dev`, and another that matches `SemVer` tags.

This allows all commits to automatically go out to our dev environment(s). If/When we are happy with that, we tag a release, which allows our second warehouse to pick up the SemVer and auto promote it everywhere (following the defined stage order via freight origin references).

This is where we hit our problem as the `dev` stage is also a subscriber to our `SemVer` warehouse. When the promotion task executes, it has a statically set warehouse in its PromotionTask:
```yaml
 steps:
   - as: argocd-update
     config:
       apps:
         - name: ${{ vars.argoAppName }}
           namespace: ${{ vars.argoNamespace }}
           sources:
             - desiredRevision: ${{ commitFrom(vars.gitRepo, warehouse("grommet-dev")).ID }}
               helm:
                 images:
                   - key: myChart.imageTag
                     value: ${{ imageFrom(vars.artifactoryRepo, warehouse("grommet-dev")).Tag }}
               repoURL: ${{ vars.gitRepo }}
               updateTargetRevision:  #true
     uses: argocd-update
```
<details>
  <summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/e8286776-fd19-498e-8aaf-a5138c6208d8)

</details>

It appears to have attempted to deploy the tagged release `0.0.4` `jaundiced-ostrict`:
<details>
  <summary>Screenshot</summary>

![Image](https://github.com/user-attachments/assets/ee452f01-7520-4f27-bf79-3cb75f85d0b5)

</details>

But when we go look, our dev stage is still running the tag from the `grommet-dev` warehouse belonging to the `bumptious-buffalo`:
<details>
  <summary>Screenshots</summary>

![Image](https://github.com/user-attachments/assets/8bec8c72-8aa6-403e-895f-6bed577f8791)

![Image](https://github.com/user-attachments/assets/32e64a93-f845-4ecb-9a52-61b5e2d7a0da)

![Image](https://github.com/user-attachments/assets/7abaa713-00c2-45b0-a603-b2d209f28338)
</details>

Omitting the “optional”  `warehouse()` in the promotion task leads to this error:
```
step execution failed: step 0 met error threshold of 0: failed to get step config: multiple requested Freight could potentially provide a commit from repo https://github.com/some-project/app; please update promotion steps to disambiguate (1:2) | commitFrom(vars.gitRepo) | .^
```

# Suggested Implementation

Stages are aware of multiple warehouses, however the PromotionTasks cannot handle cases where two warehouses are used to provide freight from the same sources (image URL, repo URL, etc.) but applying different filtering options.

Providing context of the freight that originates the deploy allows for dynamic warehouse selection:

```yaml
spec:
  steps:
    - as: argocd-update
      config:
        apps:
          - name: ${{ vars.argoAppName }}
            namespace: ${{ vars.argoNamespace }}
            sources:
              - desiredRevision: ${{ commitFrom(vars.gitRepo, warehouse(ctx.targetFreight.origin.name)).ID }}
                helm:
                  images:
                    - key: my-app.imageTag
                      value: ${{ imageFrom(vars.artifactoryRepo, warehouse(ctx.targetFreight.origin.name)).Tag }}
                repoURL: ${{ vars.gitRepo }}
                updateTargetRevision: true
      uses: argocd-update
```

For stages that accept multiple freight, another use-case of this is to send a notice to Slack, etc. on what change caused _this specific_ promotion to start. In [this example pattern](https://docs.kargo.io/user-guide/patterns/#multiple-warehouses), my desire is to send a notice that image X is what changed, rather than a generic deployment notice with all freight (inferred via imageFrom(), etc.)  where a human needs to diff in their head between two messages what changed. Having information on the specific freight would allow me to tailor the information (I’ll be able to know which warehouse in particular to reference in expression calls).
