### ISSUE TITLE
Add untar promotion step

### ISSUE THREAD

**Issue by AlexDouze** [akuity/kargo#3926]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature

A new untar promotion step for extracting tgz.

# Motivation

We heavily use helm charts, with umbrella charts and dependencies. But we want to keep the dependent charts as raw helm templates and not the tgz.
And the `helm dependency update` as no `--untar` flag see https://github.com/helm/helm/issues/8479

So we came with a plan for our promotion steps:
- helm-update-chart
- untar (the dependency)
- delete  (the tgz archive)

But obviously this can be use for any other extracting needs 😄 

# Suggested Implementation

I'll join a pull request for implementation...

**Comment by hiddeco** [comment]
While I do believe a generic untar step may be beneficial in a context outside of Helm.

I do wonder how easy it will be to untar all dependencies, as you would have to be aware of their individual paths.

**Comment by AlexDouze** [comment]
As I put in the PR doc here is the flow i tested:

```yaml
vars:
- name: gitRepo
  value: https://github.com/example/repo.git
- name: chartRepo
  value: https://example.github.io/helm-charts
- name: chartName
  value: myChart
steps:
- uses: git-clone
  config:
    checkout:
      - branch: main
        path: ./target
    repoURL: ${{ vars.gitRepo }}
- uses: helm-update-chart
  config:
    path: ./target/pathToMyUmbrellaChart
    charts:
    - repository: ${{ vars.chartRepo }}
      name: ${{ vars.chartName }}
      version: ${{ chartFrom(vars.chartRepo, vars.chartName).Version }}
- as: deleteFormerChart
  uses: delete
  config:
    path: ./target/pathToMyUmbrellaChart/charts/${{ vars.chartName }}
- as: untar
  uses: untar
  config:
    filePath: ./target/pathToMyUmbrellaChart/charts/${{ vars.chartName }}-${{ chartFrom(vars.chartRepo, "kube-prometheus-stack").Version }}.tgz
    outPath: ./target/pathToMyUmbrellaChart/charts/${{ vars.chartName }}
- as: deleteTgz
  uses: delete
  config:
    path: ./target/pathToMyUmbrellaChart/charts/${{ vars.chartName }}-${{ chartFrom(vars.chartRepo, "kube-prometheus-stack").Version }}.tgz
# Then commit, push ...
```

But indeed, you'll have to run this 4 steps:
- helm-update-chart
- delete
- untar
- delete

For each of the dependencies in the umbrella chart, not optimal for sure but it does the job 😄
