### ISSUE TITLE
Step argocd-update takes very long to complete when used inside a (Cluster)PromotionTask

### ISSUE THREAD

**Issue by ggogel** [akuity/kargo#3951]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

We started developing ClusterPromotionTasks in our Kargo environment to standardize the most common promotion processes. In one of our ClusterPromotionTasks we're using the step `argocd-update`. We noticed that it always takes exactly 300 seconds to complete when used inside a ClusterPromotionTask, while it completes within seconds when used without a ClusterPromotionTask.

# Steps to Reproduce

1. Create a simple ClusterPromotionTask using the step `argocd-update`:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: argocd-update-task
spec:
  vars:
    - name: argocdAppName
      value: "${{ ctx.project }}-${{ ctx.stage }}"
  steps:
    - uses: argocd-update
      config:
        apps:
          - name: "${{ vars.argocdAppName }}"
```
2. Reference this ClusterPromotionTask inside a Stage:
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: test-app
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: argocd-update-task
            kind: ClusterPromotionTask
```
3. Run a promotion. Notice that the step `argocd-update` takes 300s to complete.

# Version
```
v1.4.2
```

# Logs
I'm not sure which logs are relevant here.
