### ISSUE TITLE
Outputs don't work properly from cluster promotion tasks

### ISSUE THREAD

**Issue by JessicaLight** [akuity/kargo#3959]
# Checklist

* [X ] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When using cluster promotion tasks using tasks.outputs... does not work at all, you get an error saying tasks do not exist. and if you use outputs['step_name'].output then it says it is nil. 

We tested this with a simple http step, the following works in a promotion task

    - uses: http
      as: gettime
      config:
        method: GET
        url: 'https://microsoft.com'
        outputs:
          - name: timestamp
            fromExpression: response.headers['Date'][0]

      - uses: compose-output
         as: timestamp
         config:
            timestamp: ${{ outputs['gettime'].timestamp }} 

However this just won't work in a cluster promotion task, have tried  ${{ outputs['gettime'].timestamp }}  ${{ task.outputs['gettime'].timestamp }} (which fails to kubectl apply because a task doesn't exist at this level) 
  

# Screenshots

![Image](https://github.com/user-attachments/assets/513ec383-6a38-4df6-9b15-ba369bca0f16)

# Steps to Reproduce

Run this is a cluster promotion task

    - uses: http
      as: gettime
      config:
        method: GET
        url: 'https://microsoft.com'
        outputs:
          - name: timestamp
            fromExpression: response.headers['Date'][0]

      - uses: compose-output
         as: timestamp
         config:
            timestamp: ${{ outputs['gettime'].timestamp }} 

# Version

```
v.1.4.3
```

# Logs

```

```

**Comment by hiddeco** [comment]
As both `PromotionTask` and `ClusterPromotionTask` resources are "inflated" (i.e., copied over) into the `Promotion` that is created, there should be no difference between defining steps in the `PromotionTask` or `ClusterPromotionTask`.

I also just tested the following, and did not run into any issues:

```yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: get-time
spec:
  steps:
  - uses: http
    as: gettime
    config:
      method: GET
      url: https://google.com
      outputs:
      - name: timestamp
        fromExpression: response.headers['Date'][0]
  - uses: compose-output
    config:
      timestamp: ${{ task.outputs['gettime'].timestamp }}
```

<img width="821" alt="Image" src="https://github.com/user-attachments/assets/7efd3229-9f24-44f8-bc8b-8b916b9c54a2" />
