### ISSUE TITLE
Project Roles are not supporting `ClusterRoles` in RBAC

### ISSUE THREAD

**Issue by Kavinraja-G** [akuity/kargo#3977]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I have created a ClusterRole `kargo-project-viewer` which is for users to get pass through the homePage without any issues on listing the projects. To solve exactly the below problem like mentioned in #3896 
> Currently, an admin is forced to give kargo-viewer to everyone just for Kargo to be usable. By having a kargo-project-viewer, the Kargo admin can give everyone just the privilege to list all projects, but not see the objects inside every project.

```
─❯ k get rolebinding -n conduit-sbx
NAME                            ROLE                                        AGE
kargo-admin                     Role/kargo-admin                            19h
kargo-controller-read-secrets   ClusterRole/kargo-controller-read-secrets   19h
kargo-project-admin             ClusterRole/kargo-project-admin             19h
kargo-project-viewer            ClusterRole/kargo-project-viewer            3h14m
kargo-viewer                    Role/kargo-viewer                           19h

─❯ k get clusterrole kargo-project-viewer -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-project-viewer
rules:
- apiGroups:
  - kargo.akuity.io
  resources:
  - projects
  verbs:
  - get
  - list
```

I did binded with the namespace SA which is created by Kargo for both `kargo-admin` & `kargo-viewer`
```
╰─❯ k get rolebinding -n conduit-sbx kargo-project-viewer -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kargo-project-viewer
  namespace: conduit-sbx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-project-viewer
subjects:
- kind: ServiceAccount
  name: kargo-admin
  namespace: conduit-sbx
- kind: ServiceAccount
  name: kargo-viewer
  namespace: conduit-sbx
```

But the users are always getting:
`projects.kargo.akuity.io is forbidden: list is not permitted`

And, as an admin when I tried to see the Roles section in the `conduit-sbx` project. I'm getting the error attached in the screenshot

# Screenshots
Not sure if this is a bug, it's searching for `Role` instead of `ClusterRole` here:
![Image](https://github.com/user-attachments/assets/6e5c3f26-4a80-4fe1-8478-24c09f5cf40e)

# Steps to Reproduce

# Version
```
latest
```

# Logs

```
kargo-api-68576c45b-vw96c api time="2025-05-02T13:14:03Z" level=error msg="finished unary call" connect.code=not_found connect.duration=267.028917ms connect.method=ListRoles connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2025-05-02T13:14:03Z" error="not_found: Role.rbac.authorization.k8s.io \"kargo-project-viewer\" not found"
```

**Comment by krancour** [comment]
@Kavinraja-G it's not entirely clear what you thought this would accomplish.

You have created a `kargo-project-viewer` `RoleBinding` in the `conduit-sbx` Project namespace. You haven't shown the definition of that `RoleBinding`, but presumably, it is binding a SA in the `conduit-sbx` namespace to the `kargo-project-viewer` `ClusterRole`... stop me if I have misunderstood.

When a `RoleBinding` (not a `ClusterRoleBinding`) associates a `ClusterRole` with a SA, the SA gets the permissions defined by the `ClusterRole`, _but only within the namespace the `RoleBinding` lives in. This is documented here: 

https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding

> A RoleBinding can also reference a ClusterRole to grant the permissions defined in that ClusterRole to resources inside the RoleBinding's namespace. This kind of reference lets you define a set of common roles across your cluster, then reuse them within multiple namespaces.

So, in effect, what you have said is, "Users of this SA can get and list Projects in the `conduit-sbx` namespace." The problem with this is that "Projects in the `conduit-sbx` namespace" is an empty set because Project's are cluster-scoped resources. Thus, what you have configured as no effect at all.

Perhaps let's back up and attempt to understand what your intentions were and then we'll go from there.

**Comment by krancour** [comment]
> Yeah I did shared them above

My apologies. Juggling a lot of things. It was right there. 🤦‍♂ 

> Yeah I know that Projects were ClusterScoped, that's why I had to use ClusterRole. My intention was to provide the List/Get access to all Projects for the conduit-sbx SA

But that's not accomplished by referencing a `ClusterRole` from a namespaced `RoleBinding`. Granting access to cluster-scoped resources can only be done using a `ClusterRoleBinding`.

Refer to the link I posted earlier: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#rolebinding-and-clusterrolebinding

**Comment by Kavinraja-G** [comment]
@krancour  -- I see, my apologies. Maybe I got confused from the [previous issue](https://github.com/akuity/kargo/issues/3896). Thanks for clarifying!

So I have now modified to `ClusterRoleBinding`
```
╰─❯ k get clusterrolebinding kargo-project-viewer-conduit-sbx -oyaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-project-viewer-conduit-sbx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-project-viewer
subjects:
- kind: ServiceAccount
  name: kargo-admin
  namespace: conduit-sbx
- kind: ServiceAccount
  name: kargo-viewer
  namespace: conduit-sbx
```

With the same `ClusterRole` & `ServiceAccounts` that I shared earlier. Is this recommended approach here to make the Kargo UI usable without assigning to any other default Roles?
