### ISSUE TITLE
argocd-update step causes infinite sync loop with multi-source applications when revisions do not match

### ISSUE THREAD

**Issue by ivansamartino** [akuity/kargo#4020]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When trying to promote a multi-source application using the `argocd-update` step in a PromotionTask, I'm encountering a continuous cycle of failures with the error message:

`"sync result revisions [6dc721e8ddd9b1e25d62bc887f71bad49ceb04bc d7124931bccce3677568cdd23f967e9831e38ed6[] do not match desired revisions [v2.0.1 HEAD]"`

This happens even though both revisions (a specific tag for the main application repo and HEAD for the GitOps values repo) should be valid and accessible. The promotion keeps failing because the sync result revisions don't match the desired revisions.

What's particularly problematic is that this causes an infinite sync process in Argo CD. Kargo keeps attempting to update the application revisions repeatedly until it eventually times out. During this time, the application is in a continuous sync state, which can lead to application instability and unnecessary load on the system. The logs show that Kargo makes repeated attempts to patch the Argo CD application, but each time encounters the same revision mismatch error.

> **Note**
> 
> I initially tried configuring the PromotionTask to update only the desired revision of `vars.repoURL` (the application repository), without explicitly handling the GitOps repository. However, I noticed that the log messages from Kargo were returning an array with 2 elements in the revision mismatch error. This led me to modify my approach by explicitly adding both sources to the `argocd-update` step - the application repo with its dynamic tag, and the GitOps repo with a hardcoded value of `HEAD`. Despite this change, the issue persists with the same revision mismatch error.

# Screenshots

N/A

# Steps to Reproduce

1. Set up a multi-source Argo CD Application (via ApplicationSet) with two sources:
   - Main application source with a tag-based revision
   - GitOps/values repository with HEAD as revision

2. Create a Kargo Warehouse, Stage, and PromotionTask for promoting the application

3. Configure a PromotionTask with the `argocd-update` step targeting both sources:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote-chart
  namespace: my-namespace
spec:
  vars:
    - name: repoURL
      value: https://github.com/myorg/my-application-repo
    - name: gitOpsRepo
      value: https://github.com/myorg/my-gitops-repo
  steps:
    - uses: argocd-update
      retry:
        timeout: 5m0s
      config:
        apps:
          - name: ${{ ctx.project }}-${{ ctx.stage }}
            sources:
              - repoURL: ${{ vars.repoURL }}
                desiredRevision: ${{ commitFrom( vars.repoURL ).Tag }}
                updateTargetRevision: true
              - repoURL: ${{ vars.gitOpsRepo }}
                desiredRevision: HEAD
                updateTargetRevision: true
```

4. Configure a Stage to use the PromotionTask:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: my-namespace
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: my-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - task:
            name: promote-chart
```

5. Configure ApplicationSet with multiple sources and ignoreApplicationDifferences section:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-application
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - region: region-1
            client: client1
            account: dev
            env: dev
            repoURL: "https://github.com/myorg/my-application-repo"
  template:
    metadata:
      name: my-application-{{account}}
      annotations:
        kargo.akuity.io/authorized-stage: "my-namespace:{{account}}"
    spec:
      project: my-project
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
      sources:
        - repoURL: "{{repoURL}}"
          targetRevision: placeholder
          path: "helm"
          helm:
            valueFiles:
              - $values/{{account}}/values.yaml
        - repoURL: "https://github.com/myorg/my-gitops-repo"
          targetRevision: HEAD
          ref: values
      destination:
        name: "{{account}}-cluster"
        namespace: my-application-{{env}}
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.sources[].targetRevision
```

6. Trigger promotion through Kargo

# Version

```
Client Version: 1.3.2
Server Version: v1.4.3
```

# Logs

```
time="2025-05-08T07:31:41Z" level=debug msg="executing argocd-update promotion step" freight=edc1dffa2137a6ec12f36d2cc3fa150241082304 namespace=my-namespace promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff stage=dev
time="2025-05-08T07:31:41Z" level=debug msg="patched Argo CD Application" app=my-application-dev freight=edc1dffa2137a6ec12f36d2cc3fa150241082304 namespace=my-namespace promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff stage=dev
time="2025-05-08T07:31:41Z" level=debug msg="done executing argocd-update promotion step" freight=edc1dffa2137a6ec12f36d2cc3fa150241082304 namespace=my-namespace promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff stage=dev
time="2025-05-08T07:31:41Z" level=debug msg=promotion freight=edc1dffa2137a6ec12f36d2cc3fa150241082304 namespace=my-namespace phase="\"Running\"" promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff stage=dev targetFreight=edc1dffa2137a6ec12f36d2cc3fa150241082304
time="2025-05-08T07:31:44Z" level=debug msg="enqueued Promotion for reconciliation" app=my-application-dev namespace=my-namespace promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff
time="2025-05-08T07:31:44Z" level=debug msg="reconciling Promotion" namespace=my-namespace promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff
time="2025-05-08T07:31:44Z" level=debug msg="continuing Promotion" freight=edc1dffa2137a6ec12f36d2cc3fa150241082304 namespace=my-namespace promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff stage=dev
time="2025-05-08T07:31:44Z" level=debug msg="executing argocd-update promotion step" freight=edc1dffa2137a6ec12f36d2cc3fa150241082304 namespace=my-namespace promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff stage=dev
time="2025-05-08T07:31:44Z" level=debug msg="sync result revisions [6dc721e8ddd9b1e25d62bc887f71bad49ceb04bc d7124931bccce3677568cdd23f967e9831e38ed6[] do not match desired revisions [v2.0.1 HEAD]" freight=edc1dffa2137a6ec12f36d2cc3fa150241082304 namespace=my-namespace promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff stage=dev
time="2025-05-08T07:31:44Z" level=debug msg="patched Argo CD Application" app=my-application-dev freight=edc1dffa2137a6ec12f36d2cc3fa150241082304 namespace=my-namespace promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff stage=dev
time="2025-05-08T07:31:44Z" level=debug msg="done executing argocd-update promotion step" freight=edc1dffa2137a6ec12f36d2cc3fa150241082304 namespace=my-namespace promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff stage=dev
time="2025-05-08T07:31:44Z" level=debug msg=promotion freight=edc1dffa2137a6ec12f36d2cc3fa150241082304 namespace=my-namespace phase="\"Running\"" promotion=dev.01jtqcxa76gwg05se73ew0bhxd.edc1dff stage=dev targetFreight=edc1dffa2137a6ec12f36d2cc3fa150241082304
```

This issue appears to be related to multi-source applications and how Kargo processes the revisions. Despite the `ignoreApplicationDifferences` section being set correctly, Kargo keeps attempting to update the revisions but cannot reconcile the desired revisions with the actual revisions in the repositories.
