### ISSUE TITLE
[unimplemented] AnalysisRun log streaming is not configured

### ISSUE THREAD

**Issue by shellwhale** [akuity/kargo#4022]
Hello,

I've setup an AnalysisTemplate and it's working but the logs are not showing up.

Here is my code

```yaml
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: integration-test
  namespace: hello-world
spec:
  args:
  - name: image
    value: contoso.azurecr.io/hello-world
  - name: tag
    value: "{{ imageFrom('contoso.azurecr.io/hello-world').Tag }}"
  metrics:
    - name: pytest
      provider:
        job:
          spec:
            backoffLimit: 0
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: pytest
                    image: "{{ args.image }}:{{ args.tag }}"
                    command:
                      - sh
                      - -c
                      - |
                        pytest test_utils.py
```

This error shows up in the UI (Kargo v1.4.3)

![Image](https://github.com/user-attachments/assets/b40181e9-4a26-4752-9d2b-10d2e6a4e5c1)
