### ISSUE TITLE
Pre-defined secrets object isn't populated in Promotion Task

### ISSUE THREAD

**Issue by cerealsnow** [akuity/kargo#4045]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

When running the `http` promotion step as part of a promotion task, the pre-defined secrets object is not populated even though secrets in the project namespace exist.

I was able to replicate my issue by following the Kargo [docs](https://docs.kargo.io/user-guide/reference-docs/promotion-steps/http#posting-to-slack) and creating the example for the Slack post.

# Screenshots

![Image](https://github.com/user-attachments/assets/b1c1916a-0ebd-4489-a972-a783ea1f72d2)

![Image](https://github.com/user-attachments/assets/1040f0fa-3f94-4227-853e-41d24f6ca269)

# Steps to Reproduce

The following manifests are applied in the Kubernetes-Cluster:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-poc
---

apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: helm-chart
  namespace: kargo-poc
... omitted ...
---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gitlab
  namespace: kargo-poc
data:
  token: <TOKEN>
---

apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: kargo-poc
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: helm-chart
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
        ... omitted ....
---

apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: kargo-poc
spec:
  vars:
  ... omitted ...

  steps:
  - uses: compose-output
    config:
      secrets: ${{ secrets }} # for demonstration purposes
  - uses: http
    config:
      method: POST
      url: <GITLAB_URL_VAR>/api/v4/projects/<TARGET_PROJECT_ID_VAR>/repository/tags?tag_name=test&ref=main
      headers:
      - name: PRIVATE-TOKEN
        value: ${{ secrets.gitlab.token }}

```

The role binding for the kargo-controller exists:
```bash
# k describe rolebinding -n kargo-poc kargo-controller-read-secrets
Name:         kargo-controller-read-secrets
Labels:       <none>
Annotations:  <none>
Role:
  Kind:  ClusterRole
  Name:  kargo-controller-read-secrets
Subjects:
  Kind            Name              Namespace
  ----            ----              ---------
  ServiceAccount  kargo-controller  kargo
```

The secrets for the Git repository and Helm OCI registry in the namespace `kargo-poc` are working as expected.

# Version

```
Client Version: v1.0.3
Server Version: v1.4.4
```

# Logs

none
