### ISSUE TITLE
Kargo does not support a RoleBinding with a reference to a ClusterRole

### ISSUE THREAD

**Issue by zigaSRC** [akuity/kargo#4046]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

Kargo does not support a RoleBinding with a reference to a ClusterRole. With such a RoleBinding defined it is impossile to use Kargo RBAC. 

With such a role is defined in the project namespace you get the following error:
Role.rbac.authorization.k8s.io "<cluster-role>" not found

The issue appears to be that Kargo looks only for Role objects when a RoleBinding is used and not for a ClusterRole even if it is referenced in the RB.

The role binding in question in our cluster has nothing to do with Kargo, but is a default rolebinding getting created with the namespace. Because of this other rolebinding, RBAC definitons are not being applied in Kargo nor is it possible to view them via UI or CLI.

# Screenshots

![Image](https://github.com/user-attachments/assets/7355921a-e3e2-48e1-804f-151061cf5e69)

# Steps to Reproduce

Create a Rolebinding with a reference to a ClusterRole in a project namespace. 
Try to open the Roles tab in the kargo UI. 

# Version

```
1.4.4
```

# Logs

```
Role.rbac.authorization.k8s.io "<cluster-role>" not found
```

# Suggestions

- Kargo should check the roleRef.kind field and search for the appropriate object (role or clusterRole) 
- Optionaly kargo should only load serviceAccounts/role/rolebindigs that are marked with a custom annotation or label (to avoid loading irrelevant objects)

**Comment by zigaSRC** [comment]
It was my assumption that this error is the cause of permissions not applying as well. 

I have created something like this (in the project namespace): 
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: group-a
  namespace: project
  annotations:
    rbac.kargo.akuity.io/claim.groups: XXXXXXXXXXX
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-user
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kargo.akuity.io
    resources:
      - clusterpromotiontasks
      - projects
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - clusteranalysistemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-user
subjects:
- kind: ServiceAccount
  name: group-a
  namespace: project
```

So from rereading the docs, is my understanding correct that Kargo only supports Roles/Rolebindings and not ClusterRoles/ClusterRoleBindings?
