### ISSUE TITLE
RBAC for access by a specific group to a specific project not working

### ISSUE THREAD

**Issue by shezaan-hashgraph** [akuity/kargo#4082]
Hi @krancour I'm having similar issues with RBAC as opened here: https://github.com/akuity/kargo/issues/3977. 
I have configured Okta and the users can log in without issue. However, upon login they get this error `projects.kargo.akuity.io is forbidden: list is not permitted`. I think I have overdone the RBAC but I could be missing something that is still causing the error.
As an aside, I added the group `ArgoCD-HashIO` directly via the UI to the `kargo-admin` and `kargo-viewer` roles in the namespace where this project is running i.e. `hashio-pipeline` but neither of them seem to have the `get` or `list` verbs on the `projects` resource since its a Cluster scoped resource I guess.
Please note that in Okta the groups attribute is set to `group` (without the "s"). So I'm not sure if the annotation on the SA needs to be `rbac.kargo.akuity.io/claim.groups: ArgoCD-HashIO` or `rbac.kargo.akuity.io/claim.group: ArgoCD-HashIO`?

As always, thanks in advance for your guidance! Kargo is a phenomenal project and it seems to get better with every release.

Version used 1.4.4

Here is my RBAC in its entirety:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: hashio-pipeline
  annotations:
    rbac.kargo.akuity.io/claim.groups: ArgoCD-HashIO --------------------> group or groups?
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: hashio-pipeline
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - secrets
      - serviceaccounts
  - verbs:
      - '*'
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
  - verbs:
      - '*'
    apiGroups:
      - kargo.akuity.io
    resources:
      - freights
      - stages
      - warehouses
  - verbs:
      - promote
    apiGroups:
      - kargo.akuity.io
    resources:
      - stages
  - verbs:
      - create
      - delete
      - get
      - list
      - watch
    apiGroups:
      - kargo.akuity.io
    resources:
      - promotions
  - verbs:
      - patch
    apiGroups:
      - kargo.akuity.io
    resources:
      - freights/status
  - verbs:
      - delete
      - get
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - analysisruns
  - verbs:
      - '*'
    apiGroups:
      - argoproj.io
    resources:
      - analysistemplates
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kargo.akuity.io
    resources:
      - projects
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer
  namespace: hashio-pipeline
subjects:
  - kind: ServiceAccount
    name: developer
    namespace: hashio-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-viewer
  namespace: hashio-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kargo-viewer
subjects:
- kind: ServiceAccount
  name: developer
  namespace: hashio-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-project-lister
rules:
- apiGroups:
  - kargo.akuity.io
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hashio-project-list
subjects:
- kind: ServiceAccount
  name: developer
  namespace: hashio-pipeline
- kind: ServiceAccount
  name: kargo-admin
  namespace: hashio-pipeline
- kind: ServiceAccount
  name: kargo-viewer
  namespace: hashio-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-project-lister
```
