### ISSUE TITLE
yaml-update step isn't correctly quoting number like fields

### ISSUE THREAD

**Issue by dbason** [akuity/kargo#4099]
# Checklist

* [ ] I've searched the issue queue to verify this is not a duplicate bug report.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description
When passing through a number that is quoted it doesn't end up quoted in the yaml output

# Steps to Reproduce
Create a pipeline with a step similar to:
```yaml
steps:
    - uses: yaml-update
      as: update-image
      vars:
      - name: testValue
        value: main-123456
      config:
        path: values.yaml
        updates:
        - key: version
          value: ${{ vars.TestValue | split("-") | last() | quote() }}
      - uses: helm-template
        config:
          path: ./src/helm
          releaseName: test
          outPath: ./out/manifests.yaml
          valuesFiles:
          - values.yaml
```
If you have a helm chart using the version key it will be expressed in scientific notation indicating the value is unquoted when it is put in the yaml file, even though it is quoted in the value.

# Version
Kargo version 1.4.2

# Logs

```
Paste any relevant application logs here.
```
