### ISSUE TITLE
git-clone step should have an `commit` output

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#4112]
# Proposed Feature

When doing a git-clone, I would like to know the commit hash that was cloned, in order to use it in a subsequent step. We should make the commit hash an output of the step. Either that, or we have a `git-metadata` step that can return all information about a git repo at a certain directory.

# Motivation

```yaml
  - uses: git-clone
    as: clone
    config:
      repoURL: https://github.com/example/repo
      checkout:
      - branch: main
        path: ./main
      - branch: my-rendered-branch
        path: ./rendered
        create: true

  # Render the contents of main to the env-specific branch.
  - uses: git-clear
    config:
      path: ./rendered
  - uses: kustomize-build
    config:
      path: ./main/my-dir
      outPath: ./rendered
  - uses: git-commit
    as: commit
    config:
      path: ./rendered
      message: ${{ 'Render output from ' + tasks.outputs['clone'].commit }}
  - uses: git-push
    config:
      path: ./rendered
```
