### ISSUE TITLE
Can't apply existing Kargo Project configs to Kubernetes after upgrading to 1.5.0

### ISSUE THREAD

**Issue by ThreePinkApples** [akuity/kargo#4122]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

After upgrading to 1.5.0, our existing projects that and does not have a `ProjectConfig` fails to apply (sync through ArgoCD). We have our projects defined in yaml files in a git repository, synced through ArgoCD. We do not use the Kargo UI to do any configurations other than promotions.

```
error when patching "/dev/shm/4234176703": admission webhook "project.kargo.akuity.io" denied the request: Project.kargo.akuity.io "examplename" is invalid: spec: Forbidden: deprecated field: create a ProjectConfig named "examplename" with the config instead
```

# Steps to reproduce
Try to apply a Kargo Project yaml directly to kubernetes that uses the old `spec` directly on the Project and not in a ProjectConfig

# Version

```
{
  "Version": "v1.5.0",
  "BuildDate": "2025-05-15T22:29:42Z",
  "GitCommit": "61a1c24b7971bb19fcb430c737ca48e28912200c",
  "GitTreeDirty": false,
  "GoVersion": "go1.24.3",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

**Comment by jessesuen** [comment]
In v1.5, Project configuration was moved from `spec` to a new separate namespace resource, `ProjectConfig` (See https://github.com/akuity/kargo/issues/3669). So you would gitops a resource, like:


```
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
   name: example
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: example
  namespace: example
spec:
  promotionPolicies:
  - stageSelector:
      name: test
    autoPromotionEnabled: true
  - stageSelector:
      name: uat
    autoPromotionEnabled: true
```
