### ISSUE TITLE
Stage spec.vars not referenceable  from verifications

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#4124]
# Description

In v1.5 we added Stage spec level vars, so that verifications could reference them. However, when I try to reference it and pass it to an AnalysisTemplate, I get error:

`error building AnalysisRun for Stage "vars" and Freight collection "3cf57b82db812e4abedfdedf3393676225a6b2d0" in namespace "kargo-demo-18": build spec: build arguments: evaluate argument "pokemon": cannot fetch pokemon_1 from <nil> (1:7) | vars.pokemon_1 | ......^`

# Screenshots

<img width="452" alt="Image" src="https://github.com/user-attachments/assets/b4d65a5c-cba2-4039-bf65-49721ccea790" />

# Steps to Reproduce

Run example here:
https://github.com/akuity/kargo-examples/pull/3/files

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: vars
  namespace: kargo-demo-18
spec:
  vars:
  - name: pokemon_1
    value: pikachu
  requestedFreight:
  - origin:
      kind: Warehouse
      name: vars
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: pokemon_2
        value: charmander
      steps:
      - task:
          name: promo-process
        vars:
        - name: pokemon_3
          value: bulbasaur
  verification:
    analysisTemplates:
    - name: pokemon-query
    args:
    - name: pokemon
      value: ${{ vars.pokemon_1 }}
```

# Version

```
v1.5.0
```
