### ISSUE TITLE
git-commit with new message style, getting null when passing update-chart commitMessage

### ISSUE THREAD

**Issue by lknite** [akuity/kargo#4136]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

```
      - uses: helm-update-chart
        as: update-chart
        config:
          path: ./src/apps/sealed-secrets/stages/uxo
          charts:
          - repository: oci://registry-1.docker.io/bitnamicharts
            name: sealed-secrets
            version: ${{ chartFrom("oci://registry-1.docker.io/bitnamicharts/sealed-secrets").Version }}
      - uses: git-commit
        as: commit
        config:
          path: ./src
          message: ${{ outputs['update-chart'].commitMessage }}
```
```
step "commit" met error threshold of 1: error running step "commit": invalid git-commit config: message: Invalid type. Expected: string, given: null
```

# Version

```
1.5.0
```

**Comment by krancour** [comment]
> also tried task outputs, maybe i don't fully understand how they work

The config snippet doesn't reveal... are these steps directly part of a Stage's promotionTemplate? Or are these steps part of a reusable PromotionTask (or ClusterPromotionTask)?

**Comment by lknite** [comment]
updated snippit with full stage yaml

**Comment by krancour** [comment]
@lknite out of the two things you tried, `outputs` was correct; not `task.outputs`. The second is specifically outputs "local" to previous steps in a PromotionTask. Since your steps are all directly part of your Stage's promotionTemplate, that is not applicable.

I will look into why `outputs['update-chart'].commitMessage` may not have worked.

**Comment by lknite** [comment]
were you able to verify it is a bug?

**Comment by krancour** [comment]
It's not something I've gotten around to yet.

cc @hiddeco because I have a vague recollection of you working on a fix recently that _might_ have been related to this. I very well may be mistaken.

**Comment by atanev** [comment]
facing the same issue on version 1.5.3

**Comment by hiddeco** [comment]
I suspect your `helm-chart-update` step did not yield any changes, in which case no commit message will be generated. You should make use of [nil coalescing](https://expr-lang.org/docs/language-definition#nil-coalescing), and e.g. configure the following:

```
      - uses: git-commit
        as: commit
        config:
          path: ./src
          message: ${{ task.outputs['update-chart'].commitMessage ?? "No chart updates" }}
```

However, as there are likely no changes to commit, I suspect you might be better off making the `git-commit` step as a whole [conditional](https://docs.kargo.io/user-guide/reference-docs/promotion-templates#conditional-steps). As even with a commit message, an empty commit would not succeed.

**Comment by atanev** [comment]
this is not the situation in my case, I have a sub chart updated and for the moment my workaround is to compose a commit message myself as per the docs: https://docs.kargo.io/user-guide/reference-docs/promotion-steps/git-commit#composed-commit-message
```
message: |
  Promoted ${{ vars.chartName}} to version ${{ chartFrom(vars.chartRepo, vars.chartName).Version }}
```
The above provides a valid commit message and the following `git-push` and `argocd-update` steps are working as expected.
In the repo the `Chart.yaml` and `requirements.lock` files are updated as expected based on my promotion logic.

**Comment by lknite** [comment]
no changes?  i'm trying to understand, for sure a helm chart version was updated and committed to git; maybe the same as atanev, i tend to update a chart with the 'dependencies:' section of a chart that argocd points to
```
$ ls ~/g/k-argocd-addons/apps/sealed-secrets/stages/uxo/
Chart.lock  charts  Chart.yaml  templates  values.yaml

$ tail -n 10 ~/g/k-argocd-addons/apps/sealed-secrets/stages/uxo/Chart.yaml 

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1.0"

dependencies:
- name: sealed-secrets
  version: 2.5.12
  repository: oci://registry-1.docker.io/bitnamicharts
```

**Comment by hiddeco** [comment]
@lknite does the commit that is created update both the `Chart.yaml` and `Chart.lock` file?

**Comment by lknite** [comment]
I don't know the inner workings of kargo, what would I need to look for and I'll check for you.  Does this answer the question?
(this is from a month ago)

![Image](https://github.com/user-attachments/assets/26964312-11ac-4bf0-9677-b2208c1b2e75)

**Comment by lknite** [comment]
![Image](https://github.com/user-attachments/assets/592105f7-3961-4dc2-9e1c-e63b6ec3cc5a)

**Comment by hiddeco** [comment]
Thanks for providing those files; that's sufficient to give me an idea of what the internals should do.

Based on your examples, I have been trying to reproduce this, and I have at least found one variation where some odd behavior occurs (but not _exactly_ what you describe). I will debug this, and hopefully have a PR ready soon (or address it in #4245 — which refactors quite a bit of the internals).

**Comment by lknite** [comment]
I replicate the same technique and all my addons and apps that I have deployed via kargo are broken; at my job they just put in a fake message for all the addons rather than be down until there's a fix; I hope the one you found fixes it, if not we can go into more detail.

**Comment by hiddeco** [comment]
The issue I ran into yesterday was unrelated, and I have been unable to reproduce what you describe thus far using the latest `1.5.x` release. To test it, I utilized the following basic `Chart.yaml`:

```yaml
apiVersion: v2
name: test-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: sealed-secrets
  version: 2.5.0
  repository: oci://registry-1.docker.io/bitnamicharts
```

I then created the following `ClusterPromotionTask`:

```yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: update-chart
spec:
  vars:
  - name: repoURL
  - name: sourceBranch
    value: main
  - name: chartPath
  - name: chartRepository
  - name: chartName
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.sourceBranch }}
        path: ./src
  - uses: helm-update-chart
    as: update-chart
    config:
      path: ./src/${{ vars.chartPath }}
      charts:
      - repository: ${{ vars.chartRepository }}
        name: ${{ vars.chartName }}
        version: ${{ chartFrom(vars.chartRepository + "/" + vars.chartName).Version }}
  - uses: git-commit
    config:
      path: ./src
      message: ${{ task.outputs['update-chart'].commitMessage }}
  - uses: git-push
    config:
      path: ./src
```

and utilized this as follows:

```yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: test-chart-update
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: git-credentials
  namespace: test-chart-update
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/<snip>
  username: hiddeco
  password: <pat>
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: chart
  namespace: test-chart-update
spec:
  subscriptions:
  - chart:
      repoURL: oci://registry-1.docker.io/bitnamicharts/sealed-secrets
      semverConstraint: ^2.0.0
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: update
  namespace: test-chart-update
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: chart
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: update-chart
          kind: ClusterPromotionTask
        vars:
        - name: repoURL
          value: https://github.com/<snip>
        - name: chartPath
          value: charts/test-chart
        - name: chartRepository
          value: oci://registry-1.docker.io/bitnamicharts
        - name: chartName
          value: sealed-secrets
```

With this, no matter how I try to perform the update (with `Chart.lock` file present, without, jumping versions, etc.), I always consistently get a commit message.
