### ISSUE TITLE
git-clone doesnt' support standard github emails

### ISSUE THREAD

**Issue by Gitopolis** [akuity/kargo#4151]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description
```yaml
<...>
  steps:
    - as: clone
      config:
        author:
          email: 211742711+kargo-promote[bot]@users.noreply.github.com
          name: Kargo Promote
        checkout:
          - branch: main
            path: ${{ vars.srcPath }}
        repoURL: ${{ vars.gitopsRepo }}
      uses: git-clone
<...>
```
``` 
invalid git-clone config: author.email: Does not match format 'email'
```

The `[ID+USERNAME@users.noreply.github.com](mailto:ID+USERNAME@users.noreply.github.com)` is a standard gitbub email. Kargo should support it

# Screenshots

<img width="1197" alt="Image" src="https://github.com/user-attachments/assets/364c4e51-9ad3-4e03-9f9e-7dcf1665e9b7" />

# Steps to Reproduce

# Version

```
kargo  version
Client Version: v1.4.4
Server Version: v1.5.0-rc.2
```
