### ISSUE TITLE
Warehouse holding multiple charts

### ISSUE THREAD

**Issue by shezaan-hashgraph** [akuity/kargo#4162]
Hi, I've run into a problem which might be a potential duplicate of https://github.com/akuity/kargo/issues/3721. It seems that warehouses cannot house multiple charts. Is this because the chart repo urls are the same, but have different names and refer to a different chart as shown in the below snippet or does it occur even with different repo URLs?

```yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: all-charts-relay
  namespace: hashio-pipeline
spec:
  subscriptions:
  - chart:
      repoURL: https://hiero-ledger.github.io/hiero-json-rpc-relay/charts
      name: hedera-json-rpc-relay
      discoveryLimit: 20
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: all-charts-websocket
  namespace: hashio-pipeline
spec:
  subscriptions:
  - chart:
      repoURL: https://hiero-ledger.github.io/hiero-json-rpc-relay/charts
      name: hedera-json-rpc-relay-websocket
      discoveryLimit: 20
```
