### ISSUE TITLE
Freight load failure

### ISSUE THREAD

**Issue by shezaan-hashgraph** [akuity/kargo#4165]
I have an entire pipeline that looks like this

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: hashio-pipeline
spec:
  promotionPolicies:
  - stage: previewnet
    autoPromotionEnabled: true
  - stage: testnet
    autoPromotionEnabled: true
  - stage: mainnet
    autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: all-charts-relay
  namespace: hashio-pipeline
spec:
  subscriptions:
  - chart:
      repoURL: https://hiero-ledger.github.io/hiero-json-rpc-relay/charts
      name: hedera-json-rpc-relay
      discoveryLimit: 20
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: all-charts-websocket
  namespace: hashio-pipeline
spec:
  subscriptions:
  - chart:
      repoURL: https://hiero-ledger.github.io/hiero-json-rpc-relay/charts
      name: hedera-json-rpc-relay-websocket
      discoveryLimit: 20
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ga-charts-relay
  namespace: hashio-pipeline
spec:
  subscriptions:
  - chart:
      repoURL: https://hiero-ledger.github.io/hiero-json-rpc-relay/charts
      name: hedera-json-rpc-relay
      semverConstraint: ">=0.0.0"
      discoveryLimit: 20
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ga-charts-websocket
  namespace: hashio-pipeline
spec:
  subscriptions:
  - chart:
      repoURL: https://hiero-ledger.github.io/hiero-json-rpc-relay/charts
      name: hedera-json-rpc-relay-websocket
      semverConstraint: ">=0.0.0"
      discoveryLimit: 20
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: all-images
  namespace: hashio-pipeline
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/hiero-ledger/hiero-json-rpc-relay
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ga-images-only
  namespace: hashio-pipeline
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/hiero-ledger/hiero-json-rpc-relay
      semverConstraint: ">=0.0.0"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: previewnet
  namespace: hashio-pipeline
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: all-charts-relay
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: all-charts-websocket
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: all-images
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: ga-images-only
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: ga-charts-relay
    sources:
      direct: true
  - origin:
      kind: Warehouse
      name: ga-charts-websocket
    sources:
      direct: true
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
          - name: overlay
            value: "previewnet"
          - name: update_type
            value: "chart_and_image"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: testnet
  namespace: hashio-pipeline
  annotations:
    kargo.akuity.io/color: amber
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: ga-charts-relay
    sources:
      stages:
        - previewnet
  - origin:
      kind: Warehouse
      name: ga-charts-websocket
    sources:
      stages:
        - previewnet
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
          - name: overlay
            value: "testnet"
          - name: update_type
            value: "chart"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: mainnet
  namespace: hashio-pipeline
  annotations:
    kargo.akuity.io/color: green
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: ga-charts-relay
    sources:
      stages:
        - testnet
  - origin:
      kind: Warehouse
      name: ga-charts-websocket
    sources:
      stages:
        - testnet
  promotionTemplate:
    spec:
      steps:
      - task:
          name: promote
        vars:
          - name: overlay
            value: "mainnet"
          - name: update_type
            value: "chart"
          - name: openpr
            value: "true"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: hashio-pipeline
spec:
  vars:
  - name: repoURL
    value: https://github.com/swirldslabs/devops-gitops.git
  - name: branch
    value: main
  - name: openpr
    value: "false"
  steps:
  # Clone the Git repository that contains the Kustomize configuration
  # to the ./src directory.
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.branch }}
        path: ./src
  # Use the yaml-update action to update the Kustomization.yaml file
  # with the new version of the Helm chart.
  - uses: yaml-update
    if: ${{ vars.update_type == 'chart_and_image' }}
    as: update-kustomization
    config:
      path: ./src/apps/hashio/overlays/${{ vars.overlay }}/kustomization.yaml
      updates:
        - key: "helmCharts.0.version"
          value: ${{ chartFrom("https://hiero-ledger.github.io/hiero-json-rpc-relay/charts", "hedera-json-rpc-relay", warehouse("all-charts-relay")).Version }}
        - key: "helmCharts.1.version"
          value: ${{ chartFrom("https://hiero-ledger.github.io/hiero-json-rpc-relay/charts", "hedera-json-rpc-relay-websocket", warehouse("all-charts-websocket")).Version }}
        - key: "helmCharts.0.valuesInline.image.tag"
          value: ${{ imageFrom("ghcr.io/hiero-ledger/hiero-json-rpc-relay", warehouse("all-images")).Tag }}
        - key: "helmCharts.1.valuesInline.image.tag"
          value: ${{ imageFrom("ghcr.io/hiero-ledger/hiero-json-rpc-relay", warehouse("all-images")).Tag }}
  - uses: yaml-update
    if: ${{ vars.update_type == 'chart' }}
    as: update-kustomization
    config:
      path: ./src/apps/hashio/overlays/${{ vars.overlay }}/kustomization.yaml
      updates:
        - key: "helmCharts.0.version"
          value: ${{ chartFrom("https://hiero-ledger.github.io/hiero-json-rpc-relay/charts", "hedera-json-rpc-relay", warehouse("ga-charts-relay")).Version }}
        - key: "helmCharts.1.version"
          value: ${{ chartFrom("https://hiero-ledger.github.io/hiero-json-rpc-relay/charts", "hedera-json-rpc-relay-websocket", warehouse("ga-charts-websocket")).Version }}
  # Commit the changes to the Git repository.
  - uses: git-commit
    as: commit
    config:
      path: ./src
      message: |
        ${{ task.outputs['update-kustomization'].commitMessage }}

        Signed-off-by: devops-gitops-bot <devops+saas.kargo@hashgraph.com>
  # Push the changes to the Git repository.
  - uses: git-push
    if: ${{ vars.openpr != 'true' }}
    config:
      path: ./src
  # Push the changes to a newly created branch in the Git repository.
  - uses: git-push
    if: ${{ vars.openpr == 'true' }}
    as: push
    config:
      path: ./src
      generateTargetBranch: true
  # Open a pull request to merge the changes into the main branch.
  - uses: git-open-pr
    if: ${{ vars.openpr == 'true' }}
    as: open-pr
    config:
      repoURL: ${{ vars.repoURL }}
      createTargetBranch: true
      sourceBranch: ${{ task.outputs.push.branch }}
      targetBranch: ${{ vars.branch }}
  # Wait for the pull request to be merged.
  - uses: git-wait-for-pr
    as: wait-for-pr
    if: ${{ vars.openpr == 'true' }}
    config:
      repoURL: ${{ vars.repoURL }}
      prNumber: ${{ task.outputs['open-pr'].prNumber }}
```

I am facing 2 problems.

1. When I `kubectl apply` the entire above yaml I get errors like this and I am not sure why that is happening. The freight line in the UI shows that the freights were detected just fine. So immediately upon deployment I see such errors. Once in a while the pipeline succeeds and so this problem seems intermittent.

```
step execution failed: step 1 met error threshold of 1: failed to get step config: chart "hedera-json-rpc-relay" from repo https://hiero-ledger.github.io/hiero-json-rpc-relay/charts not found in referenced Freight (1:2) | chartFrom("https://hiero-ledger.github.io/hiero-json-rpc-relay/charts", "hedera-json-rpc-relay", warehouse("all-charts-relay")).Version | .^
```

2. Assuming I get past the first stage (`previewnet`) the next stage `testnet` shows a similar error but with warehouse ga-charts-only.

I am unable to decipher what I am doing wrong at this point. Any help would be greatly appreciated. I have posted my kargo.yaml manifest above verbatim as this is an open source project.
