### ISSUE TITLE
SSO doesn't work for some users: no token provided

### ISSUE THREAD

**Issue by PavelPikat** [akuity/kargo#4176]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

We have configurd Dex with Azure Entra ID and specified my team's Entra ID group as admins in the Helm chart.
While it works great for the majority, we have one team member who cannot log in to Kargo UI via SSO

The UI simply redirects the user back to the login page after showing the dashboard for a split second.

In the logs, we can see two events:
- Dex Server says that the login was successful
- API errors with 
```
time="2025-05-21T09:10:58Z" level=error msg="finished unary call" connect.code=unauthenticated connect.duration="17.9µs" connect.method=ListProjects connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2025-05-21T09:10:58Z" error="unauthenticated: no token provided"
```

# Steps to Reproduce

1. Deploy kargo 1.5.0 via Helm with the following config:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kargo
resources:
  - dns.yaml
  - virtual-service.yaml
  - entra-client-secret.yaml
helmCharts:
  - name: kargo
    repo: oci://ghcr.io/akuity/kargo-charts
    namespace: kargo
    version: 1.5.0
    valuesInline:
      global:
        nodeSelector:
          purpose: generic-workload
          kubernetes.io/os: linux
      api:
        host: <domain>
        oidc:
          enabled: true
          dex:
            enabled: true
            connectors:
              - type: microsoft
                id: microsoft
                name: Microsoft
                config:
                  clientID: <redacted>
                  clientSecret: $ENTRA_CLIENT_SECRET
                  redirectURI: https://<domain>/dex/callback
                  tenant: <redacted>
            env:
              - name: ENTRA_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: entra
                    key: clientSecret
          admins:
            claims:
              groups:
                - Platform Engineering
        tls:
          enabled: false
          terminatedUpstream: true
        adminAccount:
          enabled: false
        rollouts:
          integrationEnabled: true
      controller:
        shardName: dev
        rollouts:
          integrationEnabled: false
```
2. Navigate to Kargo URL, click SSO login
3. Observe that the user is briefly redireted to dashboard and then back to the login screen

# Version
1.5.0

# Logs

```
Paste any relevant application logs here.
```
Dex Server:
```
time="2025-05-21T09:12:14Z" level=info msg="login successful: connector \"microsoft\", username=\"xxx\", preferred_username=\"\", email=\"xxx@xxx\", groups=[\"Platform Engineering\"]"
```
API:
```
time="2025-05-21T09:10:58Z" level=error msg="finished unary call" connect.code=unauthenticated connect.duration="17.9µs" connect.method=ListProjects connect.service=akuity.io.kargo.service.v1alpha1.KargoService connect.start_time="2025-05-21T09:10:58Z" error="unauthenticated: no token provided"
```
