### ISSUE TITLE
Hitting Kargo limitations... perhaps

### ISSUE THREAD

**Issue by shezaan-hashgraph** [akuity/kargo#4180]
I have 2 warehouses, one holds all the helm charts including the release candidates and the other uses the same helm repo but has a semverConstraint to only filter the GA releases. Here is an example

```yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: all-charts-relay
  namespace: hashio-pipeline
spec:
  subscriptions:
  - chart:
      repoURL: https://hiero-ledger.github.io/hiero-json-rpc-relay/charts
      name: hedera-json-rpc-relay
      discoveryLimit: 20
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: ga-charts-relay
  namespace: hashio-pipeline
spec:
  subscriptions:
  - chart:
      repoURL: https://hiero-ledger.github.io/hiero-json-rpc-relay/charts
      name: hedera-json-rpc-relay
      semverConstraint: ">=0.0.0"
      discoveryLimit: 20
```

I have previewnet stage that plugs in both warehouses but only uses the all-charts-relay via a promotion task that looks like this

```yaml
  - uses: yaml-update
    if: ${{ vars.update_type == 'chart_and_image' &&  }}
    as: update-kustomization
    config:
      path: ./src/apps/hashio/overlays/${{ vars.overlay }}/kustomization.yaml
      updates:
        - key: "helmCharts.0.version"
          value: ${{ chartFrom("https://hiero-ledger.github.io/hiero-json-rpc-relay/charts", "hedera-json-rpc-relay", warehouse("all-charts-relay")).Version }}
```

I now have another stage `testnet` after the `previewnet` stage that should auto-promote only the GA images which do exist in the `all-charts-relay` warehouse but because I want only GA charts I need to use the `ga-charts-relay` warehouse whose freight while technically is part of the `all-charts-relay` warehouse, hasn't been used in the previewnet stage. As a result, the GA freight can't be auto-promoted to the `testnet` stage. Am I correct in understanding that this won't work? Is there are workaround for this?
