### ISSUE TITLE
git-wait-for-pr step fails

### ISSUE THREAD

**Issue by darius-mccaskey-dd** [akuity/kargo#4183]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate bug report.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `kargo version`.
* [X] I've pasted logs, if applicable.

# Description

The git-wait-for-pr step in my ClusterPromotionTask consistently fails.

# Steps to Reproduce

My ClusterPromotionTask manifest:
```
# Based on https://github.com/akuity/kargo-simple/blob/main/kargo/promotiontask.yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: standard-promotion
  namespace: kargo
spec:
  vars:
  - name: repoURL
  - name: branch
    value: main
  - name: appName
  - name: image
  - name: openpr
    value: "true"
  steps:
  # Clone the Git repository that contains the Kustomize configuration to the ./src directory.
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: ${{ vars.branch }}
        path: ./src
  # Update the image in the Kustomize configuration located at ./env/<stage> in the repository.
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ./src/${{ vars.appName }}/env/${{ ctx.stage }}
      images:
      - image: ${{ vars.image }}
        tag: ${{ imageFrom( vars.image ).Tag }}
  # Commit the changes to the Git repository.
  - uses: git-commit
    as: commit
    config:
      path: ./src
      message: ${{ task.outputs['update-image'].commitMessage }}
  # Push the changes to the Git repository.
  - uses: git-push
    if: ${{ vars.openpr != 'true' }}
    config:
      path: ./src
  # Push the changes to a newly created branch in the Git repository.
  - uses: git-push
    if: ${{ vars.openpr == 'true' }}
    as: push
    config:
      path: ./src
      generateTargetBranch: true
  # Open a pull request to merge the changes into the main branch.
  - uses: git-open-pr
    as: open-pr
    if: ${{ vars.openpr == 'true' }}
    config:
      repoURL: ${{ vars.repoURL }}
      createTargetBranch: true
      sourceBranch: ${{ task.outputs.push.branch }}
      targetBranch: ${{ vars.branch }}
      title: Promote ${{ imageFrom( vars.image ).Tag }} to ${{ vars.appName }} ${{ ctx.stage }}
  # Wait for the pull request to be merged.
  - uses: git-wait-for-pr
    as: wait-for-pr
    if: ${{ vars.openpr == 'true' }}
    config:
      repoURL: ${{ vars.repoURL }}
      provider: github
      prNumber: ${{ outputs['open-pr'].pr.id }}
  # Sync Argo CD Application.
  - uses: argocd-update
    config:
      apps:
      - name: it-ci-ci-${{ vars.appName }}-${{ ctx.stage }}
        sources:
        - repoURL: ${{ vars.repoURL }}
```

My Stage manifest:
```
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: game-2048
  annotations:
    kargo.akuity.io/color: red
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: game-2048
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: repoURL
        value: https://github.com/myorg/myrepo.git
      - name: branch
        value: main
      - name: appName
        value: game-2048
      - name: image
        value: myregistry.example.com/game-2048
      - name: openpr
        value: "true"
      steps:
      - task:
          name: standard-promotion
          kind: ClusterPromotionTask
```

Output of my git-open-pr step:
```
{
 "pr": {
  "id": 123,
  "url": "https://github.com/myorg/myrepo/pull/123"
 },
 "prNumber": 123
}
```

# Version

```
1.5.0
```

# Logs

```
an unrecoverable error occurred: failed to get step config: cannot fetch pr from <nil> (1:21) | outputs['open-pr'].pr.id | ....................^
```
