### ISSUE TITLE
`call of reflect.Value.Field on zero Value` error while evaluating variable

### ISSUE THREAD

**Issue by kamilatwork** [akuity/kargo#4187]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I have ran into an issue where `Stage`'s variable evaluation errors for single step in referenced `PromotionTask`.

I am trying to assign version of an image in `Freight` to `version` variable, it works for all steps *except* `argocd-update`. `vars.version` in `PromotionTask promote` has correct value as steps such as `kustomize-set-image` (and others, omitted here) work well and do what's expected. But when promotion gets to `argocd-update` step I get an error in logs (see below) and step hangs for default 5 minutes before completing successfully.

Am I doing anything wrong or is it a bug? 

# Screenshots

# Steps to Reproduce

Create following promotion template
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionTask
metadata:
  name: promote
  namespace: myproject
spec:
  vars:
  - name: version
  - name: imageRepo
  - name: repoURL
    value: https://github.com/myorg/myrepo
  - name: srcPath
    value: ./src
  steps:
  - uses: git-clone
    config:
      repoURL: ${{ vars.repoURL }}
      checkout:
      - branch: main
        path: ${{ vars.srcPath }}
  - uses: kustomize-set-image
    as: update-image
    config:
      path: ${{ vars.srcPath }}/mypath/${{ ctx.stage }}
      images:
      - image: myimage
        newName: ${{ vars.imageRepo }}
        tag: ${{ vars.version }}
  - uses: git-commit
    config:
      path: ${{ vars.srcPath }}
      message: ${{ task.outputs['update-image'].commitMessage }}
  - uses: git-push
    config:
      path: ${{ vars.srcPath }}

  # works up to here
  # following task errors and hangs

  - uses: argocd-update
    config:
      apps:
      - name: myapp
```

Create following stage:
```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: mystage
  namespace: myproject
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: myproject
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: imageRepo
        value: example.com/images
      - name: version
        value: ${{ quote(imageFrom(vars.imageRepo).Tag) }}
      steps:
      - task:
          name: promote
```

I have tried both with and without `quote()`, same error and behavior in both cases.

# Version

```
Client Version: v1.5.0
Server Version: v1.5.0
```

# Logs

```
failed to extract relevant config from Promotion step 6:ignoring any Argo CD Applications from this step" error="error pre-processing promotion variable \"version\": reflect: call of reflect.Value.Field on zero Value (1:34)\n |  quote(imageFrom(vars.imageRepo).Tag) \n | .................................^"
```

Note: I have removed unrelated steps for brevity so step number above might be incorrect, but there only is single `argocd-update` step.
