### ISSUE TITLE
OIDC with AWS Cognito doesn't seem to work

### ISSUE THREAD

**Issue by AdrianHaley** [akuity/kargo#4191]
Following the guide at: https://docs.kargo.io/operator-guide/security/openid-connect/

I am using AWS Cognito. Which is setup using Single Page Application and no Client Secret. 
My values file looks like below: 

```
api:
  tls:
    enabled: false
    terminatedUpstream: true
  host: "example.example-site.com"
  secret:
    name: kargo-admin-secret
  oidc:
    enabled: true
    issuerURL: <issuer url> ## AWS Cognito issuer, such as (not real) https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_3kme812"
    clientID: <ui client id>
    dex:
      enabled: false
```

I have terminated TLS on the nginx ingress controller using a cert manager certificate from Lets Encrypt. 
The call back URL I am using in AWS Cognito is: `https://example.example-website.com/login`

When I open the browser and navigate to my kargo application at `https://example.example-website.com` I get a box pop up on the bottom right hand corner saying: `OIDC: OIDC config fetch error'
When I check the developer console and under the networking tab, it shows a request to the issuer url + `.well-known/openid-configuration` with an appropriate response. Showing the OAuth/Authorize endpoints and token endpoints. 
When I check the kargo-api config map, it correctly has the OIDC Issuer set. 

When tailing the logs of the Kargo-api pod, it shows on startup that it has enabled OIDC with my issuer and no error logs. 
The `SSO Login` button does nothing and doesn't redirect to a Cognito hosted page. 

If I use postman and I add a callback URL to my cognito App Client for postmans callback url, I am able to receive an Access Token and ID Token.
