### ISSUE TITLE
Digest image selection strategy example in documentation does not work

### ISSUE THREAD

**Issue by WZHGAHO** [akuity/kargo#4240]
# Checklist

* [ ] I've searched the issue queue to verify this is not a duplicate bug report.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description

Digest image selection strategy example in documentation does not work. Adminission webhook blocks creation of Warehouse with spec.subscriptions[].image.semverConstraint: latest

# Screenshots

![Image](https://github.com/user-attachments/assets/c77d99e8-d6a9-49d2-a64e-10d9cc4a1137)

# Steps to Reproduce

Create a WH with the following spec:

```
kind: Warehouse
apiVersion: kargo.akuity.io/v1alpha1
metadata:
  name: example
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  freightCreationPolicy: Manual
  interval: 1m0s
  subscriptions:
    - git:
        branch: main
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 20
        repoURL: https://code.rbi.tech/example/example-repo.git
        strictSemvers: false
    - image:
        repoURL: artifacts.rbi.tech/cmi-testautomation-docker-host/ebics/express-app
        semverConstraint: latest
        imageSelectionStrategy: Digest
```

# Version

```
Kargo v1.4.0
```
