### ISSUE TITLE
File Writer Step

### ISSUE THREAD

**Issue by benduncan-tote** [akuity/kargo#4267]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature

File Writer 

File Writer is a promotion step that writes a to a file.
Proposed step definition:
```yaml
- uses: write
  config:
    outFile: ./out/changelog.json
    contents: |
      ${{ quote({
        "message": vars.message,
      }) }}
```

Using os.WriteFile semantics, this would behave as follows:

> WriteFile writes data to the named file, creating it if necessary. If the file does not exist, WriteFile creates it with permissions perm (before umask); otherwise WriteFile truncates it before writing, without changing permissions. Since WriteFile requires multiple system calls to complete, a failure mid-operation can leave the file in a partially written state.

# Motivation

Currently I have a need to update/write to  a file. I cannot use file copy as the contents must come from elsewhere e.g. a compose output or a http response.

As part of my promotion pipeline, I would greatly benefit from the flexiblity of writing to a file as opposed to using yaml or json update steps. In addition, it would be helpful to be able to use expression syntax to template the contents of the file in this way.
