### ISSUE TITLE
RBAC via OIDC (Dex) not working at all (central-mgmt)

### ISSUE THREAD

**Issue by arsenii-stefanov** [akuity/kargo#4286]
# Checklist

- [x] I've searched the issue queue to verify this is not a duplicate bug report.
- [x] I've included steps to reproduce the bug.
- [x] I've pasted the output of kargo version.
- [x] I've pasted logs, if applicable.

# Description

We're currently in the process of adopting Kargo but we've encountered an issue we can't seem to figure out. I found a number of very similar github issues most of which have already been resolved, however, unfortunately, none of the proposed solutions fixed our issue. Here're the issues I'm referring to: [#3977](https://github.com/akuity/kargo/issues/3977)  [#4082](https://github.com/akuity/kargo/issues/4082) [#3338](https://github.com/akuity/kargo/issues/3338) [#2864](https://github.com/akuity/kargo/issues/2864) [#2717](https://github.com/akuity/kargo/issues/2717) . I would appreciate if someone could take a look at our configuration and share some thoughts as to where the root cause could be.

Here's how our SSO pipeline looks:

`User > Ingress (AWS ALB) > custom-proxy (NGINX + vouch-proxy) > PingID > custom-proxy > kargo-dex > kargo-api`

1. The `custom-proxy` redirects User to a PingID SSO login page where User is supposed to enter credentials.
2. Upon successful authentication, the `custom-proxy` parses PingID's response and splits its contents into the following headers: `X-Vouch-User` (`email`) and `X-Vouch-Groups` (`groups`).
3. From this moment, User's every request that goes through the `custom-proxy` will carry the aforementioned headers and pass them to every backend that's behind the `custom-proxy`, including Kargo.
4. If one opens the USER section at `https://{KARGO_HOSTNAME}/user` , there will be correct groups and email address. My understanding is that this means that Kargo was able to successfully recognise what it was provided with by `dex`, i.e. Kargo was able to parse the claims, distinguish `groups` it the list as well as `email`.
5. At this point, Kargo should find all or at least one ServiceAccount that User is a member of. Apparently, something goes wrong because my user doesn't have access to the home page
```
projects.kargo.akuity.io is forbidden: list is not permitted
```
If I go to the project page directly, `https://{KARGO_HOSTNAME}/project/kargo-my-project`, I get the following errors:
```
namespaces "kargo-my-project" is forbidden: get is not permitted
namespaces "kargo-my-project" is forbidden: get is not permitted
projects.kargo.akuity.io "kargo-my-project" is forbidden: get is not permitted
namespaces "kargo-my-project" is forbidden: get is not permitted
namespaces "kargo-my-project" is forbidden: get is not permitted
projectconfigs.kargo.akuity.io "kargo-my-project" is forbidden: get is not permitted
```
While the `namespaces` and `projects` resources aren't namespaced, the `projectconfigs` is, so it seems that I don't even have access to objects within the project namespace.

`My-Admin-Group` is currently mapped to the `kargo-admin` and `kargo-viewer` ServiceAccounts in the `kargo` namespace as well as to the `dev-team` ServiceAccount in the  `kargo-my-project` namespace.

P.S. The actual names have been redacted, so My-Admin-Group, kargo-my-project, KARGO_HOSTNAME, etc. aren't real names, in case this matters.

# Screenshots

<img width="1159" alt="Image" src="https://github.com/user-attachments/assets/cd8c6a97-df7b-4c21-a383-701264f49965" />

# Configuration

### OIDC config:
```
api:
  oidc:
    enabled: true
    dex:
      enabled: true
      image:
        repository: ghcr.io/dexidp/dex
        tag: v2.43.1
        pullPolicy: IfNotPresent
        pullSecrets:
          - name: dockerhub-cfg
      connectors:
        - type: authproxy
          id: myPingId
          name: PingID
          config:
            # Dex receives these headers from the custom-proxy service 
            userHeader: X-Vouch-User
            groupHeader: X-Vouch-Groups
      env:
        # https://github.com/akuity/kargo/issues/3599
        - name: OIDC_CLI_CLIENT_ID
          value: {KARGO_HOSTNAME}
    globalServiceAccounts:
      namespaces:
        - kargo
    admins:
      claims:
        groups:
          - My-Admin-Group
    viewers:
      claims:
        groups:
          - My-Admin-Group # having this either just in the 'admins' section or in both 'admins' and 'viewers' doesn't change anything for me
          - My-Developer-Group
```
### k8s RBAC resources:
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-team
  namespace: kargo-my-project
  annotations:
    rbac.kargo.akuity.io/claim.groups: My-Admin-Group,My-Developer-Group # I also tried with 'group', 'email' and 'emails'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-team
  namespace: kargo-my-project
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kargo.akuity.io
    resources:
      - freights
      - stages
      - warehouses
  - apiGroups:
    - kargo.akuity.io
    resources:
    - projectconfigs
    verbs:
    - get
    - list
    - watch
  - verbs:
      - create
      - delete
      - get
      - list
      - watch
    apiGroups:
      - kargo.akuity.io
    resources:
      - promotions
      - promotiontasks
  - verbs:
      - patch
    apiGroups:
      - kargo.akuity.io
    resources:
      - freights/status
  - verbs:
      - delete
      - get
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - analysisruns
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - argoproj.io
    resources:
      - analysistemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team
  namespace: kargo-my-project
subjects:
  - kind: ServiceAccount
    name: dev-team
    namespace: kargo-my-project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
```

# Version

**Kargo version**: `v1.5.1`
