### ISSUE TITLE
UI auto-promotion indicator does not work with matchLabels/matchExpressions

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#4288]
# Description

The UI auto-promotion indicator (fixed in https://github.com/akuity/kargo/pull/4117)  only works when stageSelector is by name:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
spec:
  promotionPolicies:
    - autoPromotionEnabled: true
      stageSelector:
        name: prod-us-central
```

But it does not work if we are using matchLabels or matchExpressions. e.g.:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
spec:
  promotionPolicies:
    - autoPromotionEnabled: true
      stageSelector:
        matchLabels:
          autoPromote: "true"
```

This is understandably harder, since the logic of matchLabels or matchExpression would need to be implemented in UI code.

# Version

```
v1.5.1
```
