### ISSUE TITLE
Private GHCR Authentication

### ISSUE THREAD

**Issue by jaydeepappas** [akuity/kargo#4293]
I'm testing out Kargo (v1.5.1) as part of our GitOps setup with Argo and am running into issues authenticating with GHCR. Looking specifically at this part of the docs: https://docs.kargo.io/user-guide/security/managing-credentials#github-authentication-options I feel that it is a bit unclear how to approach this with a _private GHCR repo._

For auth I'm using a classic GitHub PAT that has full repo and read/write package permissions. I can successfully authenticate via:

`docker login ghcr.io/MY_ORG/services -u <username> -p <PAT>`

and pull images manually. 

In Kargo, I have `Repo Credentials` of type `git` which point to the URL of my private repositories, with an empty username and PAT as password. This works fine. However, for GHCR, it is unclear whether to use a `git` or `image` type of `Repo Credential` to authenticate with GHCR, and how that corresponds to the `image` subscription type in my warehouse. That being said, I have tried both combinations of this - I cannot create a `Repo Credential` that allows me to authenticate with GHCR. Nothing seems to work, and I am thrown the error: 

`error listing tags for repo URL ghcr.io/MY_ORG/services: GET https://ghcr.io/token?... DENIED: requested access to the resource is denied`

Here is a simple version of the warehouse I am using:

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: test-ghcr
  namespace: services
spec:
  freightCreationPolicy: Automatic
  interval: 5m
  subscriptions:
    - image:
        repoURL: ghcr.io/MY_ORG/services
        imageSelectionStrategy: SemVer
```

And here is a screenshot of the secret I am configuring (keep in mind I have tried both type `git` and `image`):

<img width="605" alt="Screenshot 2025-05-28 at 4 13 40 PM" src="https://github.com/user-attachments/assets/d897b0fb-8232-4d28-902d-a2f9a64bb204" />

This clearly seems to be a Kargo config issue that I am unable to figure out. Hopefully I am just missing something obvious. Thank you!

**Comment by krancour** [comment]
> However, for GHCR, it is unclear whether to use a git or image type of Repo Credential

It should me `image`. Can you help me understand why that's unclear so docs can be fixed if necessary?

**Comment by jaydeepappas** [comment]
> > However, for GHCR, it is unclear whether to use a git or image type of Repo Credential
> 
> It should me `image`. Can you help me understand why that's unclear so docs can be fixed if necessary?

In the docs, the `Secret` example in the `GitHub App Authentication` section (#2) shows the `kargo.akuity.io/cred-type` as `git`. This is clearly for auth with a repository and works well. But then there are really no mentions of authenticating with a private GHCR registry - I can create a secret with the `cred-type` of image, use the same PAT, but this does not work, so clearly there is something I am missing around private GHCR registries. Is this even possible with a PAT when using Kargo? Am I required to use `username` and `password` auth? The docs clearly lay out how to use GAR, ECR and ACR but nothing around GHCR. So I guess that is more so my issue with the docs.

**Comment by jaydeepappas** [comment]
> GHCR only supports authentication using PATs (and only classic ones, in fact), [as noted in their own docs](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry):

OK, that makes sense, but I am not using GitHub App Authentication - in my post I clearly lay out how I am using a PAT to authenticate with GHCR, but it is not working. 

Again, i can do: 

`docker login ghcr.io/MY_ORG/services -u <username> -p <PAT>`

And auth just fine with my PAT. But I cannot get Kargo to authenticate with my GHCR repository using the same PAT, no matter how hard I try. Can you provide any insight into this?

**Comment by krancour** [comment]
This had made it seem that there was some confusion over how or if GitHub App Authentication was applicable to GHCR...

> In the docs, the Secret example in the GitHub App Authentication section (num. 2) shows the kargo.akuity.io/cred-type as git. This is clearly for auth with a repository and works well. But then there are really no mentions of authenticating with a private GHCR registry

... apologies if I misunderstood.

Your Secret should probably look like this:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: <whatever>
  namespace: services
  labels:
    kargo.akuity.io/cred-type: image
stringData:
  repoURL: ghcr.io/MY_ORG/services
  username: jaydeepappas
  password: <pat>
```

If this is not working, you might consider enabling debug-level logging on the controller, which should give you a lot more information about whether the credentials aren't being found or are simply inadequate.

> with an empty username

That is something I might be suspicious of.
