### ISSUE TITLE
Add Kustomize patch promotion step

### ISSUE THREAD

**Issue by hfoxy** [akuity/kargo#4299]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [x] I've pasted the output of `kargo version`, if applicable.
* [x] I've pasted logs, if applicable.

# Proposed Feature

Add a promotion step type that uses a Kustomize patch for cases when `kustomize-set-image` is not suitable, e.g. when you're updating the image of a helm chart.

Step Definition:
```yaml
- as: patch
  uses: kustomize-patch
  config:
    image:
      image: {repository}
    path: {path to kustomize}
    kind: Application
    labelSelector: kargo.hfox.me/update-target=true
    pathToImage: /spec/source/helm/valuesObject/image/tag
```

Output:
```yaml
patches:
- patch: |
    - op: replace
      path: /spec/source/helm/valuesObject/image/tag
      value: {repository}:{tag}
```

I have implemented a [half-baked](https://github.com/akuity/kargo/compare/main...hfoxy:kargo:main) version of this on a [fork](https://github.com/hfoxy/kargo) for a previous version. I would be happy to update this to the latest version of Kargo and polish it. I have been using it on personal projects and at work for a little while now.

# Motivation

Updating an image that isn't supported by kustomize `images` is not currently possible without a new step type. Without this I am unable to use Kargo effectively at work (without my [fork](https://github.com/hfoxy/kargo)).
