### ISSUE TITLE
ClusterPromotionTask CRD prevents using variables for retry.errorThreshold due to strict integer type

### ISSUE THREAD

**Issue by thodorisit** [akuity/kargo#4306]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

The ClusterPromotionTask CRD does not support using variables (via `${{ vars.* }}` syntax) for the `retry.errorThreshold` field. This is due to the CRD schema enforcing a strict integer (int32) type, which results in validation errors when a string-based variable is configured.

This makes it impossible to configure retry thresholds dynamically using variables, reducing the reusability and flexibility of promotion task templates.

The issue stems from the CRD definition here:
- https://github.com/akuity/kargo/blob/20ee7a2ae6ef5fba4ead0b4321bb6c1992d4eada/charts/kargo/resources/crds/kargo.akuity.io_clusterpromotiontasks.yaml

Excerpt:

```yaml
errorThreshold:
  description: >
    ...
  format: int32
  type: integer
```

This problem is observed due to the same reason in other CRDs such as the PromotionTask, the Stage and the Promotion.

# Steps to Reproduce

With a ClusterPromotionManifest manifest such as the following:

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: ClusterPromotionTask
metadata:
  name: template
spec:
  vars:
[...]
    - name: retryErrorThreshold
      value: 3
    - name: retryTimeout
      value: "0"
  steps:
    - uses: git-clone
      retry:
        errorThreshold: ${{ vars.retryErrorThreshold }}
        timeout: ${{ vars.retryTimeout }}
[...]
```
The resource cannot be created due to the following error:

```text
spec.steps[0].retry.errorThreshold: Invalid value: "string": spec.steps[0].retry.errorThreshold in body must be of type integer: "string", 
```

# Version

```
Client Version: v1.0.3
Server Version: v1.2.0
```
