### ISSUE TITLE
AnalysisRun phase changes don't trigger stage controller reconcile

### ISSUE THREAD

**Issue by AlanLonguet** [akuity/kargo#4312]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

AnalysisRun phase changes doesn't trigger stage controller reconcile. AnalysisRun are shown as "Verifying" until the stage gets requeued automatically by the defaultRequeue of 5min.

# Screenshots

![Image](https://github.com/user-attachments/assets/7e5c1187-fd0c-46d6-9e71-fd0dec0e344a)

# Steps to Reproduce

- Use a sharded kargo controller
- We're using a ClusterAnalysisTemplate based on a metric provider
- Launching through the UI or automated by promotion makes no difference on our side

# Version

Using kargo helm chart without overrides (1.5.1)

# Logs

In the logs the EventSource is started correctly, however we don't see the [handler](https://github.com/akuity/kargo/blob/main/internal/controller/stages/event_handlers.go#L489) getting called at all (with debug logs).

```
time="2025-06-02T15:11:48Z" level=info msg="Starting EventSource" controller=stage controllerGroup=kargo.akuity.io controllerKind=Stage source="kind source: *v1alpha1.AnalysisRun"
```

Our hypothesis revolves around this [predicate](https://github.com/akuity/kargo/blob/main/internal/controller/stages/regular_stages.go#L180) masking the phase status change because the generation didn't change but that might be something else.

**Comment by hiddeco** [comment]
Have been unable to reproduce this, and can see the reconciliation of the Stage getting queued in the logs:

```
time="2025-06-03T10:16:06Z" level=debug msg="enqueued Stage for reconciliation" analysisRun=test.01jwtmh6jvcgsngse8j1r94gcr.1a2e85b namespace=kargo-demo-01 stage=test
```

Could you provide a minimal viable example that I can use to attempt to reproduce it?

**Comment by AlanLonguet** [comment]
Oo, well I'll post the Stage and ClusterAnalysisTemplate we're using below, maybe this is a setup issue on our side, is there anything on argo-rollouts or on kargo (e.g. RBAC) that would not permit the events to be properly received ?

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  annotations:
    kargo.akuity.io/color: '#882255'
  labels:
    argocd.argoproj.io/instance: demo-domain-kargo-promotion
  name: dev-colorapp1
  namespace: demo-domain
spec:
  promotionTemplate:
    spec:
      steps:
        - task:
            kind: ClusterPromotionTask
            name: ecr
          vars:
            - name: environment
              value: dev
            - name: application
              value: colorapp1
            - name: imageURL
              value: XXX
            - name: gitOpsRepoURL
              value: XXX
  requestedFreight:
    - origin:
        kind: Warehouse
        name: colorapp1
      sources:
        direct: true
  shard: dev
  verification:
    analysisTemplates:
      - kind: ClusterAnalysisTemplate
        name: metrics-analysis
    args:
      - name: application
        value: colorapp1
      - name: env
        value: dev
      - name: version
        value: >-
          ${{
          imageFrom('XXX').Tag
          }}
```

```
apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: metrics-analysis
spec:
  args:
  - name: application
  - name: env
  - name: version
  metrics:
  - name: deployment-status
    count: 3
    interval: 20s
    successCondition: result > 0.9
    failureLimit: 3
    provider:
      datadog:
        apiVersion: v2
        interval: 1m
        query: |
          max:kubernetes_state.deployment.condition{status:true,condition:available, env:{{args.env}}, kube_app_name:{{args.application}}, version:{{args.version}}}
```
