### ISSUE TITLE
ArgoCD Update Promotion Step not working for Helm

### ISSUE THREAD

**Issue by sbyrne-teck** [akuity/kargo#4316]
# Checklist

* [ ] I've searched the issue queue to verify this is not a duplicate bug report.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `kargo version`.
* [ ] I've pasted logs, if applicable.

# Description
Not sure if this is a bug but experiencing some issues trying to get a use-case working. 

I am using a kargo pipeline to manage an argo app based on helm. 
This is just an example of a small part of the overall applications using a simple ui/api. 

The goal is that we have kargo listen to a container registry for the 2 docker images and to github releases for the associated helm chart.

For helm changes we want to update the target revision to the new release and for docker changes we want to update the valuesObject with the new imageTags. See examples below - 

Argo App 
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  <removed for brevity >
  annotations:
    kargo.akuity.io/authorized-stage: platform-dev-canary:deva
spec:
  project: platform-testing
  syncPolicy:
   <removed for brevity>
  source:
    repoURL: <git repo url>
    targetRevision: 2.0.0
    path: <helm chart>
    helm:
      releaseName: "1"
      valuesObject:
        api:
          imageTag: 0.5.0
        ui:
          imageTag: 0.5.0
```

Kargo Promotion Steps
```
steps:
  - uses: git-clone
    config:
      <removed for brevity>
  - uses: yaml-update
    as: update-image
    config:
      <removed for brevity>
  - uses: git-commit
    as: commit
    config:
      <removed for brevity>
  - uses: git-push
    config:
      path: ./out
  - uses: argocd-update
    config:
      apps:
      - name: ${{ vars.argocdApp }}
```

We want the argocd update step to just trigger argo to do a refresh of source and sync so that we can then run our analysis templates. 
It seems the argocd update works but it doesn't notice any changes for these values because we are changing the argo application manifest itself. A hard refresh seems required to solve this based on this issue - https://github.com/argoproj/argo-cd/issues/9214

As a result we have been trying several different permutations of the argocd-update but we don't want to implement any pseudo-gitops. 

When we attempted to specify the desired revision we got into an infinite sync loop which we solved by referencing the commit ID. 
When we pass in the helm values directly they are set as parameter overrides which are overriding the git source so are not desired.

We are able to trigger an update of the parent app of this app and that allows it to refresh but this also has a problem wherein an app can only have one kargo authorized stage and the parent has multiple child apps that it would need to sync. 

Do you have some recommendation to solve this concern? 

# Screenshots

None. 

# Steps to Reproduce

Not required in this case. 

# Version

1.5.1

# Logs

Not required
