### ISSUE TITLE
webhook receivers permissions regression

### ISSUE THREAD

**Issue by fuskovic** [akuity/kargo#4393]
# Description

```
time="2025-06-13T18:15:17Z" level=error msg="Failed to watch" error="failed to list *v1.Secret: secrets is forbidden: User \"system:serviceaccount:kargo:kargo-external-webhooks-server\" cannot list resource \"secrets\" in API group \"\" at the cluster scope" logger=controller-runtime.cache.UnhandledError reflector="pkg/mod/k8s.io/client-go@v0.33.1/tools/cache/reflector.go:285" type="*v1.Secret"
```

# Steps to Reproduce

### Project Config

```
apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  webhookReceivers: 
      github:
        secretRef:
          name: gh-wh-secret
```

### Warehouse

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: my-warehouse
  namespace: kargo-demo
spec:
  interval: 30m
  subscriptions:
  - git:
      repoURL: https://github.com/fuskovic/wh-test-repo.git
      branch: main
      strictSemvers: false
```

### Secret

```
apiVersion: v1
kind: Secret
metadata:
  name: gh-wh-secret
  namespace: kargo-demo
stringData:
  secret: my-not-so-secret-token
```
