### ISSUE TITLE
ClusterRole of controller has missed secret permission in helm chart

### ISSUE THREAD

**Issue by gn-viet-n** [akuity/kargo#4437]
# Description

ClusterRole of controller (https://github.com/akuity/kargo/blob/main/charts/kargo/templates/controller/cluster-roles.yaml) has missed secret permission in helm chart

FYI I'm using EKS 1.32

# Logs

```
kubectl describe warehouse aiguard-api -n aant
Name:         aiguard-api
Namespace:    aant
Labels:       <none>
Annotations:  argocd.argoproj.io/tracking-id: platform-customization-raw-yaml-production:kargo.akuity.io/Warehouse:aant/aiguard-api
API Version:  kargo.akuity.io/v1alpha1
Kind:         Warehouse
Metadata:
  Creation Timestamp:  2025-06-21T17:40:05Z
  Generation:          1
  Resource Version:    8346651
  UID:                 dd8d05f8-1be3-4097-bfc9-090fc075df73
Spec:
  Freight Creation Policy:  Automatic
  Interval:                 5m0s
  Subscriptions:
    Image:
      Allow Tags:                ^xxx-.*
      Discovery Limit:           10
      Image Selection Strategy:  NewestBuild
      Repo URL:                  xxxx.dkr.ecr.us-west-2.amazonaws.com/xxxx
      Strict Semvers:            false
Status:
  Conditions:
    Last Transition Time:  2025-06-21T17:40:05Z
    Message:               Discovering artifacts for 1 subscriptions
    Observed Generation:   1
    Reason:                ScheduledDiscovery
    Status:                True
    Type:                  Reconciling
    Last Transition Time:  2025-06-21T17:40:05Z
    Message:               Artifact discovery failed: error discovering images: error obtaining credentials for image repo "xxxx.dkr.ecr.us-west-2.amazonaws.com/xxxx": secrets is forbidden: User "system:serviceaccount:kargo:kargo-controller" cannot list resource "secrets" in API group "" in the namespace "aant"
    Observed Generation:   1
    Reason:                DiscoveryFailure
    Status:                False
    Type:                  Ready
    Last Transition Time:  2025-06-21T17:40:05Z
    Message:               Unable to discover artifacts: error discovering images: error obtaining credentials for image repo "xxxx.dkr.ecr.us-west-2.amazonaws.com/xxxx": secrets is forbidden: User "system:serviceaccount:kargo:kargo-controller" cannot list resource "secrets" in API group "" in the namespace "aant"
    Observed Generation:   1
    Reason:                DiscoveryFailed
    Status:                False
    Type:                  Healthy
Events:                    <none>
```

After working around by manually applying : 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-controller-secrets-fix
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kargo-controller-secrets-fix
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-controller-secrets-fix
subjects:
- kind: ServiceAccount
  name: kargo-controller
  namespace: kargo
```

The issue is fixed successfully.

So we need to update in helm chart.
