### ISSUE TITLE
Promote freight leads to "runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by ricoapon** [akuity/kargo#4467]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

I have created a very simple Kargo project. When deploying the first freight to the stages, there is no issues. When deploying the second freight, I get the issue that the status stays "verifying". This means that the freight is unusable, as I cannot promote it to other environments. The logging shows a panic. Other freights result in the same problem.

# Steps to Reproduce

1. Install Kargo from scratch into a namespace.
2. Create an empty project `kargo-demo` using the GUI.
3. Create a warehouse with this configuration:
    ```
    apiVersion: kargo.akuity.io/v1alpha1
    kind: Warehouse
    metadata:
      name: my-warehouse
      namespace: kargo-demo
    spec:
      freightCreationPolicy: Automatic
      interval: 5m0s
      subscriptions:
        - git:
            commitSelectionStrategy: NewestFromBranch
            discoveryLimit: 20
            includePaths:
              - kargo-detect/input
            repoURL: <url to repository>
            strictSemvers: true
    ```
4. Create stage with this configuration:
    ```
    apiVersion: kargo.akuity.io/v1alpha1
    kind: Stage
    metadata:
      name: dev
      namespace: kargo-demo
    spec:
      promotionTemplate:
        spec:
          steps:
            - as: ""
              config:
                author:
                  email: <some email>
                  name: Kargo
                checkout:
                  - branch: master
                    path: ./src
                repoURL: <url to repository>
              continueOnError: false
              if: ""
              uses: git-clone
            - as: ""
              config:
                path: ./src/kargo-detect/dev
              continueOnError: false
              if: ""
              uses: git-clear
            - as: ""
              config:
                inPath: ./src/kargo-detect/input
                outPath: ./src/kargo-detect/dev
              continueOnError: false
              if: ""
              uses: copy
            - as: ""
              config:
                message: Deploy dev
                path: ./src
              continueOnError: false
              if: ""
              uses: git-commit
            - config:
                path: ./src
                targetBranch: master
              uses: git-push
      requestedFreight:
        - origin:
            kind: Warehouse
            name: my-warehouse
          sources:
            direct: true
            stages: []
    ```
5. Create another stage with this configuration (similar, just changed `dev` to `prd`):
    ```
    apiVersion: kargo.akuity.io/v1alpha1
    kind: Stage
    metadata:
      name: prd
      namespace: kargo-demo
    spec:
      promotionTemplate:
        spec:
          steps:
            - as: ""
              config:
                author:
                  email: <some email>
                  name: Kargo
                checkout:
                  - branch: master
                    path: ./src
                repoURL: <url to repository>
              continueOnError: false
              if: ""
              uses: git-clone
            - as: ""
              config:
                path: ./src/kargo-detect/prd
              continueOnError: false
              if: ""
              uses: git-clear
            - as: ""
              config:
                inPath: ./src/kargo-detect/dev
                outPath: ./src/kargo-detect/prd
              continueOnError: false
              if: ""
              uses: copy
            - as: ""
              config:
                message: Deploy prd
                path: ./src
              continueOnError: false
              if: ""
              uses: git-commit
            - config:
                path: ./src
                targetBranch: master
              uses: git-push
      requestedFreight:
        - origin:
            kind: Warehouse
            name: my-warehouse
          sources:
            direct: false
            stages:
              - dev
    ```
6. Create a commit in the repository. Ensure a freight is created based on this commit. Refresh warehouse if needed.
7. Promote the freight to dev.
8. Promote the freight to prd.
9. Create a new commit in the repository that creates a second freight.
10. Deploy the second freight to dev. This should now fail.

# Version

```
~ $ kargo version
{
  "Version": "v1.5.2-rc.1",
  "BuildDate": "2025-06-05T17:08:11Z",
  "GitCommit": "b7f7db33906beee2d24dd6fce6f0bc67bbfa21a1",
  "GitTreeDirty": false,
  "GoVersion": "go1.24.3",
  "Compiler": "gc",
  "Platform": "linux/amd64"
}
```

# Logs

```
time="2025-06-24T08:17:33Z" level=error msg="Observed a panic" Stage="{dev kargo-demo}" controller=stage controllerGroup=kargo.akuity.io controllerKind=Stage error="<nil>" name=dev namespace=kargo-demo panic="runtime error: invalid memory address or nil pointer dereference" panicGoValue="\"invalid memory address or nil pointer dereference\"" reconcileID="\"3a5a8faa-58f7-4e71-ab62-ead73c04b6e0\"" stacktrace="goroutine 343 [running]:\nk8s.io/apimachinery/pkg/util/runtime.logPanic({0x52f2ee0, 0xc000e2e270}, {0x282fd00, 0x6af3540})\n\t/go/pkg/mod/k8s.io/apimachinery@v0.32.3/pkg/util/runtime/runtime.go:107 +0xbc\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:108 +0x112\npanic({0x282fd00?, 0x6af3540?})\n\t/usr/local/go/src/runtime/panic.go:792 +0x132\ngithub.com/akuity/kargo/api/v1alpha1.(*FreightStatus).RemoveCurrentStage(0xc0007bf340, {0xc001145766, 0x3})\n\t/kargo/api/v1alpha1/freight_types.go:194 +0xb6\ngithub.com/akuity/kargo/internal/controller/stages.(*RegularStageReconciler).syncFreight(0xc000a4a1b0, {0x52f2ee0, 0xc000e2e330}, 0xc0007d4000)\n\t/kargo/internal/controller/stages/regular_stages.go:827 +0x245\ngithub.com/akuity/kargo/internal/controller/stages.(*RegularStageReconciler).reconcile.func2()\n\t/kargo/internal/controller/stages/regular_stages.go:411 +0x5b\ngithub.com/akuity/kargo/internal/controller/stages.(*RegularStageReconciler).reconcile(0xc000a4a1b0, {0x52f2ee0, 0xc000e2e330}, 0xc0007d4000, {0xc000e2e210?, 0x296c260?, 0x6b6da00?})\n\t/kargo/internal/controller/stages/regular_stages.go:466 +0x709\ngithub.com/akuity/kargo/internal/controller/stages.(*RegularStageReconciler).Reconcile(0xc000a4a1b0, {0x52f2ee0, 0xc000e2e270}, {{{0xc0009feb60?, 0x30?}, {0xc0009feb5c?, 0xc000600008?}}})\n\t/kargo/internal/controller/stages/regular_stages.go:338 +0x3e5\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc000bc65c0?, {0x52f2ee0?, 0xc000e2e270?}, {{{0xc0009feb60?, 0x0?}, {0xc0009feb5c?, 0x0?}}})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:119 +0xbf\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x53232a0, {0x52f2f18, 0xc00038b900}, {{{0xc0009feb60, 0xa}, {0xc0009feb5c, 0x3}}}, 0x0)\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:334 +0x3ad\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x53232a0, {0x52f2f18, 0xc00038b900})\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294 +0x21b\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255 +0x85\ncreated by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 185\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:251 +0x6b5\n"
time="2025-06-24T08:17:33Z" level=error msg="Reconciler error" Stage="{dev kargo-demo}" controller=stage controllerGroup=kargo.akuity.io controllerKind=Stage error="panic: runtime error: invalid memory address or nil pointer dereference [recovered]" name=dev namespace=kargo-demo reconcileID="\"3a5a8faa-58f7-4e71-ab62-ead73c04b6e0\""
```

A more readable formatting of the error:

```
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x52f2ee0, 0xc000e2e270}, {0x282fd00, 0x6af3540})
	/go/pkg/mod/k8s.io/apimachinery@v0.32.3/pkg/util/runtime/runtime.go:107 +0xbc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:108 +0x112
panic({0x282fd00?, 0x6af3540?})
	/usr/local/go/src/runtime/panic.go:792 +0x132
github.com/akuity/kargo/api/v1alpha1.(*FreightStatus).RemoveCurrentStage(0xc0007bf340, {0xc001145766, 0x3})
	/kargo/api/v1alpha1/freight_types.go:194 +0xb6
github.com/akuity/kargo/internal/controller/stages.(*RegularStageReconciler).syncFreight(0xc000a4a1b0, {0x52f2ee0, 0xc000e2e330}, 0xc0007d4000)
	/kargo/internal/controller/stages/regular_stages.go:827 +0x245
github.com/akuity/kargo/internal/controller/stages.(*RegularStageReconciler).reconcile.func2()
	/kargo/internal/controller/stages/regular_stages.go:411 +0x5b
github.com/akuity/kargo/internal/controller/stages.(*RegularStageReconciler).reconcile(0xc000a4a1b0, {0x52f2ee0, 0xc000e2e330}, 0xc0007d4000, {0xc000e2e210?, 0x296c260?, 0x6b6da00?})
	/kargo/internal/controller/stages/regular_stages.go:466 +0x709
github.com/akuity/kargo/internal/controller/stages.(*RegularStageReconciler).Reconcile(0xc000a4a1b0, {0x52f2ee0, 0xc000e2e270}, {{{0xc0009feb60?, 0x30?}, {0xc0009feb5c?, 0xc000600008?}}})
	/kargo/internal/controller/stages/regular_stages.go:338 +0x3e5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile(0xc000bc65c0?, {0x52f2ee0?, 0xc000e2e270?}, {{{0xc0009feb60?, 0x0?}, {0xc0009feb5c?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:119 +0xbf
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler(0x53232a0, {0x52f2f18, 0xc00038b900}, {{{0xc0009feb60, 0xa}, {0xc0009feb5c, 0x3}}}, 0x0)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:334 +0x3ad
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem(0x53232a0, {0x52f2f18, 0xc00038b900})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294 +0x21b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2 in goroutine 185
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:251 +0x6b5
```
