### ISSUE TITLE
New function to generate a semantic version

### ISSUE THREAD

**Issue by patpicos** [akuity/kargo#4476]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate feature request.
* [X] I've pasted the output of `kargo version`, if applicable.
* [X] I've pasted logs, if applicable.

# Proposed Feature

A new function that allows to generate a semantic version on a string that is a well formed semver
Pseudocode
```
currentVersion := 1.2.3
semver(currentVersion, TYPE_FEATURE) # Returns 1.3.0
semver(currentVersion, TYPE_MAJOR) # Returns 2.0.0
semver(currentVersion, TYPE_PATCH) # Returns 1.2.4
```

# Motivation

I have a warehouse that monitors a set of images. These images are used in a helm chart we maintain. I wish to make the new image versions the updated defaults in the `values.yaml`, then i need to bump the `Chart.yaml` `version`. 
To do so, I would like to use the new semVer function

The sequence would be like
yaml-parse (read the current version)--> generate Semver --> yaml-update --> git-commit --> git-push --> git-open-pr

When the chart is packaged and published to our chart registry, another project will be kicked off to move this freight along.

**Comment by krancour** [comment]
Workflow aside, can you try to better explain the behavior of the proposed function?

```
currentVersion := 1.2.3
semver(currentVersion, TYPE_FEATURE) # Returns 1.3.0
semver(currentVersion, TYPE_MAJOR) # Returns 2.0.0
semver(currentVersion, TYPE_PATCH) # Returns 1.2.4
```

None of the example return values seem like they have any relation to the example input of "1.2.3".

Did you mean to propose something more like this?

```
currentVersion := 1.2.3
semver(currentVersion, TYPE_MAJOR) # Returns 1.0.0
semver(currentVersion, TYPE_FEATURE) # Returns 1.2.0
semver(currentVersion, TYPE_PATCH) # Returns 1.2.3
```

**Comment by patpicos** [comment]
Let me rewrite the example

```
currentVersion := 1.2.3
nextVersion := semver(currentVersion, TYPE_MAJOR)   # Returns Bumping the major version (first component) goes from 1.2.3 --> 2.0.0
nextVersion := semver(currentVersion, TYPE_FEATURE) # Bumping the feature version (middle component) goes from 1.2.3 --> 1.3.0
nextVersion := semver(currentVersion, TYPE_PATCH)    # Bumping the patch version (last component) goes from 1.2.3 --> 1.2.4
```

Here's a dummy implementation
```go
package main

import (
	"fmt"
	"github.com/Masterminds/semver/v3"
)

// Bump the major version: 1.2.3 → 2.0.0
func bumpMajorVersion(v string) (string, error) {
	version, err := semver.NewVersion(v)
	if err != nil {
		return "", err
	}
	newVersion := semver.New(version.Major()+1, 0, 0, "", "")
	return newVersion.String(), nil
}

// Bump the minor version: 1.2.3 → 1.3.0
func bumpMinorVersion(v string) (string, error) {
	version, err := semver.NewVersion(v)
	if err != nil {
		return "", err
	}
	newVersion := semver.New(version.Major(), version.Minor()+1, 0, "", "")
	return newVersion.String(), nil
}

// Bump the patch version: 1.2.3 → 1.2.4
func bumpPatchVersion(v string) (string, error) {
	version, err := semver.NewVersion(v)
	if err != nil {
		return "", err
	}
	newVersion := semver.New(version.Major(), version.Minor(), version.Patch()+1, "", "")
	return newVersion.String(), nil
}

func main() {
	original := "1.2.3"

	major, _ := bumpMajorVersion(original)
	minor, _ := bumpMinorVersion(original)
	patch, _ := bumpPatchVersion(original)

	fmt.Printf("Original: %s\n", original)
	fmt.Printf("Bump major: %s\n", major)
	fmt.Printf("Bump minor: %s\n", minor)
	fmt.Printf("Bump patch: %s\n", patch)
}

```

Unit Tests
```go
package main

import (
	"testing"
)

func TestBumpMajorVersion(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"1.2.3", "2.0.0"},
		{"0.9.1", "1.0.0"},
	}

	for _, test := range tests {
		result, err := bumpMajorVersion(test.input)
		if err != nil {
			t.Errorf("Unexpected error for %s: %v", test.input, err)
		}
		if result != test.expected {
			t.Errorf("bumpMajorVersion(%s) = %s; expected %s", test.input, result, test.expected)
		}
	}
}

func TestBumpMinorVersion(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"1.2.3", "1.3.0"},
		{"1.9.9", "1.10.0"},
	}

	for _, test := range tests {
		result, err := bumpMinorVersion(test.input)
		if err != nil {
			t.Errorf("Unexpected error for %s: %v", test.input, err)
		}
		if result != test.expected {
			t.Errorf("bumpMinorVersion(%s) = %s; expected %s", test.input, result, test.expected)
		}
	}
}

func TestBumpPatchVersion(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"1.2.3", "1.2.4"},
		{"1.0.9", "1.0.10"},
	}

	for _, test := range tests {
		result, err := bumpPatchVersion(test.input)
		if err != nil {
			t.Errorf("Unexpected error for %s: %v", test.input, err)
		}
		if result != test.expected {
			t.Errorf("bumpPatchVersion(%s) = %s; expected %s", test.input, result, test.expected)
		}
	}
}

```

**Comment by krancour** [comment]
I see. Nothing about the function name `semver()` tipped me off that doing the bump was part of its job.

Wouldn't it be more broadly useful to have a function that parses a semver into three integers representing the major, minor, and patch components of the semver? Once you have those, bumping any of them yourself is trivial.

I think we'd get a lot more mileage out of the parsing function than the more bespoke function you initially proposed.

**Comment by patpicos** [comment]
Sorry, i should have written `bumpSemver(currentVersion, BUMP_TYPE)` 

My preference is to have an opinionated that does the whole thing. Doing math in YAML is just horrid :)

**Comment by krancour** [comment]
> My preference is to have an opinionated that does the whole thing.

I'm sure you can appreciate that in attempting to provide the basic, generally useful building blocks for user-defined promotion processes, we're _avoiding_ anything this is too highly opinionated. I'm weighing where this request fits into the big picture and how, or even if, this will be generally useful.

This is the first request I'm aware of along these lines. I can speculate as to why that is. Promotions are really about moving _existing_ artifacts from environment to environment; not creating new ones. Creating new artifacts (e.g. new version of a chart) is more within the realm of CI. This would probably explain why the need for constructing/generating new revision identifiers (e.g. semvers) hasn't been requested until now. That work is generally left to other systems.

That said, I can see the appeal/convenience of using a Warehouse to monitor for new versions of images and update a chart accordingly. That is at least _close_ to the idea of a promotion. You're updating something with references to known/existing artifacts (the images). What you're doing is also essentially the [pre-pipeline pattern](https://docs.kargo.io/user-guide/patterns/#pre-pipelines). This all seems sensible. It's bumping the chart's version number where I think things become questionable.

Taking a step back, I think it's worth asking why the version number in your Chart.yaml needs to be incremented at all. I know that might sound silly at first, _but_...

> When the chart is packaged and published to our chart registry, another project will be kicked off to move this freight along.

So the Git repo isn't the end of the line. You're packaging the chart and publishing it to a proper registry (which I applaud as being superior to consuming the chart directly from the Git repo). Presumably you have some automation closer to your Git repo that is responsible for this. If your Git repo were in GitHub, for instance, you might be using Actions for this. Presumably your automation uses the `helm package` and `helm push` commands.

Given a choice between trying to keep the version number in Chart.yaml up to date or updating your automation to override a placeholder version in the Chart.yaml using the `helm package` command's `--version` flag, the latter is the clear winner.

We do this ourselves and I've seen it done in several other projects as well. I've also seen what a nightmare it can be to try and keep the version number in Chart.yaml up to date. Apart from Kargo updating references to new versions of images, I'm sure you or others also make _other_ changes to the chart periodically. Thinking back to the days of https://github.com/helm/charts, the most frequent feedback on PRs was along the lines of, "You forgot to bump the version number" or, "You need to bump the version number again because PR x got merged before yours."

For reference, this is how we do it:

https://github.com/akuity/kargo/blob/4724da607a7de1880faf84af35ea45cec46b0574/charts/kargo/Chart.yaml#L5

https://github.com/akuity/kargo/blob/4724da607a7de1880faf84af35ea45cec46b0574/.github/workflows/release.yaml#L173

I'm hoping you might find this trick useful. If not, and for whatever reason, using the `--version` flag when you package the chart isn't going to work out for you, I'm willing to leave this issue open to see whether other community members come forward with similar use cases that would be well-served by the feature you're requesting. That may bolster your case.

**Comment by patpicos** [comment]
> I'm sure you can appreciate that in attempting to provide the basic, generally useful building blocks for user-defined promotion processes, we're avoiding anything this is too highly opinionated

Totally understand. I appreciate the deep discourse and evaluation to determine if this would introduce bloat or become a feature that would be used by the masses 

> What you're doing is also essentially the [pre-pipeline pattern](https://docs.kargo.io/user-guide/patterns/#pre-pipelines). This all seems sensible. It's bumping the chart's version number where I think things become questionable.

Correct pre-pipeline with a sprinkle of CI automation as you said.

> Presumably you have some automation closer to your Git repo that is responsible for this. If your Git repo were in GitHub, for instance, you might be using Actions for this. Presumably your automation uses the helm package and helm push commands.

Correct. We are packaging our Crossplane XRDs/compositions. We run a full set of unit tests w/ Chainsaw and if passing, we package a new version of the chart and push it to our registry. We bump the version when changing the default images because it is similar to  upgrading the deps in your Golang application; your dependencies have changed.

Ideally, in our CI, we would use something like `semantic-release` which would DECIDE what version bump to do based on git commit comments from engineers. If I had this, I would basically set the commit message from Kargo to `feat: bump images of crossplane functions and providers` and let `semantic-release` execute the bump in `Chart.yaml`
Unfortunately, my client is not yet at that level of engineering sophistication...so I'm working a bit under the constraints of the team vs. engineering idealism :)

In the interim, I might create myself a small API that accepts a semver and return a payload that I can parse.
```json
{
    "inputSemver" : "2.3.4",
    "versionComponents": {
        "major": 2,
        "minor": 3,
        "patch": 4
    },
    "bumpedSemver": {
        "major": "3.0.0",
        "minor": "2.4.0",
        "patch": "2.3.5"
    }
}
```
```yaml
    outputs:
    - name: newVersion
      fromExpression: response.body.bumpedSemver.minor
```

**Comment by patpicos** [comment]
For readers... i have a working solution w/ a Pod running an http server accepting a `semver=1.1.1` through POST and returns a payload from previous post.

PromotionTask Snippet
```yaml
    # Extract current chart version
    - uses: yaml-parse
      as: chart-version
      config:
        path: ./src/Chart.yaml
        outputs:
          - name: currentVersion
            fromExpression: version
    # Get new chart version
    - uses: http
      as: new-version
      config:
        method: POST
        url: http://function-semver:8080/semver # Requires pod & svc to be running inside kargo namespace
        headers:
          - name: Content-Type
            value: application/x-www-form-urlencoded
        body: "semver=${{ task.outputs['chart-version'].currentVersion }}"
        outputs:
          - name: newVersion
            fromExpression: response.body.bumpedSemver.minor
    # Update chart to new version
    - uses: yaml-update
      as: update-chart-version
      config:
        path: ./src/Chart.yaml
        updates:
          - key: version
            value: ${{ task.outputs['new-version'].newVersion }}
```

<img width="233" alt="Image" src="https://github.com/user-attachments/assets/0ebd13ae-99f0-4e5f-b2ea-bc9099360a08" />

<img width="542" alt="Image" src="https://github.com/user-attachments/assets/a498683f-919a-48d7-b83d-f7da07dc6abd" />

Web API Codebase: https://github.com/patpicos/function-semver

**Comment by krancour** [comment]
Sorry for the delay responding @patpicos.

> semantic-release which would DECIDE what version bump to do based on git commit comments from engineers

I think it wasn't clear to me that you'd wanted this logic included in what you proposed. Doing so makes the proposed function, perhaps even more opinionated since it would require adherence to some particular commit message scheme. Or else, to keep it less opinionated, it would have to be highly configurable. There's a technical dilemma also in that expressions don't have access to all the commit messages between now and some previous point, and what previous point to compare to exactly is also unknown.

I think this is something we can continue to discuss and perhaps come up with something better over time.

In the meanwhile, I see that your current solution isn't actually making the decision of whether the changes constitute a major, minor, or patch release (yet?):

```yaml
outputs:
- name: newVersion
  fromExpression: response.body.bumpedSemver.minor
```

This would accomplish the same thing without the overhead of the custom server:

```
- uses: yaml-parse
  as: chart-version
  config:
    path: ./src/Chart.yaml
    outputs:
    - name: currentVersion
      fromExpression: version
- uses: yaml-update
  as: update-chart-version
  config:
    path: ./src/Chart.yaml
    updates:
    - key: version
      value: ${{ let parts = split(task.outputs[chart-version].currentVersion, "."); parts[0] + "." + string(int(parts[1])+1) + "." + parts[2] }}
```

Not the final solution you're looking for, but perhaps an incremental improvement.
