### ISSUE TITLE
Helm Chart - Accept extraObjects for arbitrary k8s resources creation

### ISSUE THREAD

**Issue by patpicos** [akuity/kargo#4538]
# Checklist

* [X] I've searched the issue queue to verify this is not a duplicate feature request.
* [X] I've pasted the output of `kargo version`, if applicable.
* [X] I've pasted logs, if applicable.

# Proposed Feature

Add a new attribute to the helm chart to allow creation of arbitrary kubernetes resources during the deployment. This is useful when needing to deploy additional manifest through gitops tools like ArgoCD and avoid having an Application for a few resources then one Application driven from Helm Chart
Reference implementation: https://github.com/cloudability/metrics-agent/pull/267
# Motivation

During installation, I see two use cases already:
- ConfigMap creation for the caBundle to be used by the controller
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-ca
  namespace: kargo
data:
  gitlab-ca.crt: |
<omitted>
```
- Deployment of RoleBinding when doing global credentials. However, I would prefer an opinionated approach to this feature on the helm chart, but `extraObjects` would do the trick. For this use case, I would need to create the Namespace, RoleBinding, and perhaps a series of ExternalSecrets resources to source my secrets from AWS Secret Manager
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: kargo-controller-read-secrets
    namespace: kargo-global-creds
subjects:
    - kind: ServiceAccount
      name: kargo-controller
      namespace: kargo
roleRef:
    kind: ClusterRole
    name: kargo-controller-read-secrets
    apiGroup: rbac.authorization.k8s.io
```

**Comment by krancour** [comment]
Given that what you're requesting isn't actually a feature Helm provides, I'm not sure this feels like the right place for this.

I've had this exact need many times myself and my current favorite approach is to leverage Argo CD multi-source applications.

I do this in my own home lab where I install charts using one source, and both the `values.yaml` with the specific configuration for the chart _and_ the additional resources required to make everything work being another source. In my case, most of those other things are Cert or SealedSecret resources.

Would that work for you?

Here's an example of how I do it:

https://github.com/krancovia/lab-gitops/blob/main/apps/traefik.yaml

https://github.com/krancovia/lab-gitops/blob/main/traefik/manifests/cert.yaml

**Comment by patpicos** [comment]
I like having one stop shop to install an app for all its components, especially if it has a helm chart. Did you check the PR i did on the cloudabiilty metrics-server

Here's the appset using that chart and using `extraObjects`

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudability-metrics-agent-aws
  namespace: argocd
spec:
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          sourced.io/cloud-service-provider:  aws
          addons.sourced.io/cloudability: 'true'
  template:
    metadata:
      name: '{{.name}}-cloudability'
    spec:
      project: platform-cluster-bootstrap-prj
      destination:
        server: '{{.server}}'
        namespace: cloudability
      source:
        repoURL: https://gitlab.net/api/v4/projects/461/packages/helm/stable/
        targetRevision: "2.11.30"
        chart: metrics-agent
        helm:
          releaseName: cloudability
          valuesObject:
            # <omitted>
            extraObjects:
            - apiVersion: v1
              kind: ServiceAccount
              metadata:
                name: external-secrets-sa
                namespace: cloudability
                annotations:
                  eks.amazonaws.com/role-arn: '{{ index .metadata.annotations "cloudability.addons.sourced.io/role-arn" }}'
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                  argocd.argoproj.io/sync-wave: "-99"
            - apiVersion: external-secrets.io/v1beta1
              kind: SecretStore
              metadata:
                name: cloudability-store
                namespace: cloudability
                annotations:
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                  argocd.argoproj.io/sync-wave: "-89"
              spec:
                provider:
                  aws:
                    service: SecretsManager
                    region: '{{ index .metadata.labels "sourced.io/region" }}'
                    auth:
                      jwt:
                        serviceAccountRef:
                          name: external-secrets-sa
                          namespace: cloudability
            - apiVersion: external-secrets.io/v1beta1
              kind: ExternalSecret
              metadata:
                name: metrics-agent
                namespace: cloudability
                annotations:
                  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
                  argocd.argoproj.io/sync-wave: "-79"
              spec:
                secretStoreRef:
                  name: cloudability-store
                  kind: SecretStore
                target:
                  name: metrics-agent
                  creationPolicy: Owner
                data:
                  - secretKey: CLOUDABILITY_API_KEY
                    remoteRef:
                      key: 'arn:aws:secretsmanager:omitted'
```
