### ISSUE TITLE
Replace Stage health information with structures checks status

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#570]
UI needs to visualize the current stage state. Right now stage CRD/API provides “health” that includes aggregated status (healthy/unhealthy/unknown) and the list of “issues”.

I think ‘health’ is confusing since there are a lot of checks not related to health. Simplest example: stage which is “unhealthy” because the related Argo CD app is not synced. This is how it looks like in UI:

<img width="289" alt="image" src="https://github.com/akuity/kargo/assets/426437/23b4ea3b-f337-4b5d-beed-05789cd6d5eb">

UI is showing a broken heart, which does not make sense because UI has no idea what health means. 

```yaml
  currentState:
    firstSeen: "2023-08-15T21:41:50Z"
    health:
      issues:
      - Argo CD Application "kargo-demo-test" in namespace "argocd" is not synced
        to revision ""
      status: Unhealthy
    id: 4b94f4bf6adcca4765b9a2c554647b649646784b
```

# Proposal

Replace high-level health information with detailed/structured status of performed checks. Example to illustrate the idea (structure needs to be discussed):

```yaml
  currentState:
    firstSeen: "2023-08-15T21:41:50Z"
    checks:
      argocd:
      - appName: kargo-demo-test
         sync:
            valid: false
            reason: Argo CD Application "kargo-demo-test" in namespace "argocd" is not synced to revision "abc"
    id: 4b94f4bf6adcca4765b9a2c554647b649646784b
```

The predefined structure allows UI to render meaningful information about stage state. E.g. if UI knows status has information about the application sync state it would use appropriate icon and URL that redirects user to Argo CD application.
