### ISSUE TITLE
Kargo should re-apply "promotions" if deviations detected

### ISSUE THREAD

**Issue by alexmt** [akuity/kargo#571]
Once state is "promoted" the Kargo should re-apply promotions change then the deviation is detected:

Lets use `kargo-demo-test` from quick start:

1. Create stage

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
spec:
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-test
      appNamespace: argocd
    gitRepoUpdates:
    - kustomize:
        images:
        - image: nginx
          path: stages/test
      repoURL: https://github.com/alexmt/kargo-demo
      writeBranch: main
  subscriptions:
    repos:
      images:
      - repoURL: nginx
        semverConstraint: ^1.24.0
        updateStrategy: SemVer
```

2. Make sure the is a change and promote it
3. Wait for kargo to push git commit and sync `kargo-demo-test` application
4. Manually sync `kargo-demo-test` application to previous version

Expected functionality:

User should be able to "apply" promotion one more time to fix deviations. Bonus feature: addition setting in Auto-sync policy to auto-reapply  promotions ( aka self heal  )

Current behavior:

Promotion is atomic and Kargo does not do anything to get `test` to desired state.
