### ISSUE TITLE
Kargo redirectURI should omit colon

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#585]
When configuring kargo with my **self-hosted** Dex IdP (not the bundled dex), I had to configure the redirectURI strangely:

```yaml
  staticClients:
  - id: kargo
    name: Kargo
    redirectURIs:
    - https://kargo.demo.akuity.io:/login
    public: true

  web:
    allowedOrigins:
    - https://kargo.demo.akuity.io
```

Notice the `:` in `https://kargo.demo.akuity.io:/login`. 

This is a bit abnormal. Our UI client should use a more canonical URI and remove the `:`.
