### ISSUE TITLE
Use `envFrom.secretRef` instead of `env[].valueFrom.secretKeyRef`

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#597]
I noticed we are repeating a pattern that I regret in Argo CD. That is, we have individual env vars, with `secretKeyRef` to specific keys in the same `kargo-api` secret:

```yaml
            env:
            - name: ADMIN_ACCOUNT_PASSWORD_HASH
              valueFrom:
                secretKeyRef:
                  name: kargo-api
                  key: adminPassword
            - name: ADMIN_ACCOUNT_TOKEN_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: kargo-api
                  key: tokenSigningKey
```

We used the same technique in Argo CD, and I really wish we hadn't because:
1. The key name in the secret, was different than the env var (we would use dot notation like `admin.enabled`). The same is happening here with `tokenSigningKey` and `ADMIN_ACCOUNT_TOKEN_SIGNING_KEY`.
2. It resulted in a ton more YAML than necessary in the Deployment.

I think we should do this instead:

```yaml
          envFrom:
          - configMapRef:
              name: kargo-api
          - secretRef:
              name: kargo-api
```

And the Secret/ConfigMap itself would have env vars as the keys. e.g.:

```yaml
data:
  ADMIN_ACCOUNT_PASSWORD_HASH: xxxxx
  ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: yyyyy
```

The benefits I see are:
* There is only one well-known documented "key" to adjust. Not both `tokenSigningKey` and `ADMIN_ACCOUNT_TOKEN_SIGNING_KEY` and making sure `tokenSigningKey` is properly declared and referenced from the Deployment.
* It reduces the amount of YAML necessary in the Deployment.
