### ISSUE TITLE
Kargo evaluated a Freight to be Unhealthy when app was still Progressing

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#672]
I promoted a git commit via Kargo. Kargo initiated the Argo CD app sync operation. The sync completed, but the app took some time to fully roll out and was progressing for some time. But Kargo assessed the Freight as `Unhealthy` during stage Reconciliation because `Argo CD Application "guestbook-dev" in namespace "argocd" has health state "Progressing"`:

<img width="230" alt="image" src="https://github.com/akuity/kargo/assets/12677113/79914383-b2aa-42c3-9c97-c8ec812aa88d">

```yaml
  history:
  - commits:
    - branch: main
      healthCheckCommit: 10d7fd861e94dd57a63c95b05dc21ad885b0703e
      id: 5c7d29985412024a39dff4b0286bf9eb3f2a0450
      repoURL: https://github.com/jessesuen/guestbook-deploy.git
    firstSeen: "2023-09-07T22:48:07Z"
    health:
      issues:
      - Argo CD Application "guestbook-dev" in namespace "argocd" has health state
        "Progressing"
      status: Unhealthy
    id: 4e1f65309798525de29191ea734ea4f980f07b43
    images:
    - gitRepoURL: https://github.com/jessesuen/guestbook/tree/v0.0.6
      repoURL: ghcr.io/jessesuen/guestbook
      tag: v0.0.6
```
