### ISSUE TITLE
`Error fetching metadata` when using `ghcr.io` for image subscription

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo#694]
Stage spec:
```
spec:
  promotionMechanisms:
    argoCDAppUpdates:
      - appName: morey-tech-demo-app-dev
        appNamespace: argocd
    gitRepoUpdates:
      - kustomize:
          images:
            - image: ghcr.io/morey-tech/demo-app
              path: env/dev
        readBranch: ''
        repoURL: 'https://github.com/morey-tech/demo-app-deploy'
        writeBranch: main
  subscriptions:
    repos:
      images:
        - repoURL: ghcr.io/morey-tech/demo-app
          updateStrategy: Latest
```

Error in status:
```
status:
  error: >-
    error syncing image repo subscriptions: error getting latest suitable tag
    for image "ghcr.io/morey-tech/demo-app": found no suitable version of image
    "ghcr.io/morey-tech/demo-app"
```

Error in controller logs:
```
time="2023-09-08T20:10:17Z" level=error msg="Error fetching metadata for morey-tech/demo-app:d5f4dd376524d10a7e0ca4b2b52c6426399c7749 - neither V1 or V2 or OCI manifest returned by registry: manifest unknown: OCI index found, but Accept header does not support OCI indexes"
```

Tested the same image pushed to Dockerhub and it works.
```
spec:
  subscriptions:
    repos:
      images:
      - repoURL: docker.io/moreytech/demo-app
        updateStrategy: Latest
status:
  availableFreight:
    - firstSeen: '2023-09-08T20:56:20Z'
      id: 315ebae132f84ff09d8e030aa4ed8ac6ef1cc145
      images:
        - repoURL: docker.io/moreytech/demo-app
          tag: 2bc20dfbfd6df6be278b9fd7bc187832839486ec
```
