### ISSUE TITLE
Return native kube API types instead of a proto conversion

### ISSUE THREAD

**Issue by jessesuen** [akuity/kargo#708]
In Kargo API, we convert from kubernetes types, to a different type which is returned in our gRPC/Connect server. And so we have conversion code like the following:

```golang
func ToPromotionProto(p kargoapi.Promotion) *v1alpha1.Promotion {
	metadata := p.ObjectMeta.DeepCopy()
	metadata.SetManagedFields(nil)

	return &v1alpha1.Promotion{
		ApiVersion: p.APIVersion,
		Kind:       p.Kind,
		Metadata:   typesmetav1.ToObjectMetaProto(*metadata),
		Spec: &v1alpha1.PromotionSpec{
			Stage:   p.Spec.Stage,
			Freight: p.Spec.Freight,
		},
		Status: &v1alpha1.PromotionStatus{
			Phase: string(p.Status.Phase),
			Error: p.Status.Error,
		},
	}
}
```

This is undesirable for many reasons:
* it must be manually updated
* it is error prone (e.g. we forgot to add apiVersion and kind at one point)
* omitempty semantics are inconsistent from native kubernetes type, and so our API ends up returning fields set to be empty strings as opposed to omitted strings.
* We face limitations such as: https://github.com/akuity/kargo/issues/707

Instead of converting and maintaining two different identical types, we should generate proto files from [go-to-protobuf](https://github.com/kubernetes/code-generator/tree/master/cmd/go-to-protobuf) and return the native type from our API.

**Comment by jessesuen** [comment]
Kube has moved off of gogoproto. They now maintain:

https://github.com/kubernetes/gengo

which is used in:

https://github.com/kubernetes/code-generator/tree/master/cmd/go-to-protobuf

**Comment by jessesuen** [comment]
Ah. I mistakenly thought Kube moved off of gogoproto, but I see they [have not](https://github.com/kubernetes/code-generator/blob/71364b5549ac6cce68b84a760fdd05174f6073da/go.mod#L8).

Hmmm, I agree we should not re-introduce gogoproto. Unfortunately, I'm at a loss on how to deal with the inconsistency that 
 is currently caused by redefining our types in our API. For example the omitempty inconsistency and the [enum problem](https://github.com/akuity/kargo/issues/707):

```yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  generateName: ""     ####  native type would not return this because omitempty works properly
```

**Comment by jessesuen** [comment]
@devholic does `EmitUnpopulated` do what we expect? I see this in UI:

<img width="578" alt="image" src="https://github.com/akuity/kargo/assets/12677113/6cc4faa5-d1e6-414e-bc59-503f1b06dab2">

But this from kubectl:

```yaml
  health:
    argoCDApps:
    - healthStatus:
        status: Healthy
      name: guestbook-prod-euw1
      namespace: argocd
      syncStatus:
        revision: d3083b73a25f1f606118d4ba40ef5c4ffd277c5e
        status: Synced
    status: Healthy
```
