### ISSUE TITLE
Include example Argo CD `Application` for installing `kargo` Helm Chart

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo#794]
Many Kargo users will likely install it using an Argo CD `Application`. We can provide an example for installing the `kargo` Helm chart in this way. Potentially even update the quickstart guide to use it instead.

**Comment by krancour** [comment]
> Potentially even update the quickstart guide to use it instead.

Quickstart setup is more scripted now than before, so I wouldn't bother changing that, but in general, I agree this would be nice thing to have documented somewhere, perhaps under the installation section of the docs.

I just tested this and it worked nicely:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.11.5
    helm:
      parameters:
      - name: installCRDs
        value: 'true'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
spec:
  project: default
  source:
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 0.1.0 
    helm:
      parameters:
      - name: api.service.type
        value: NodePort
      - name: api.service.nodePort
        value: '31444'
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kargo
```

**Comment by morey-tech** [comment]
> Quickstart setup is more scripted now than before, so I wouldn't bother changing that
An advantage to using it in the quickstart is that the Kargo components will be visible in Argo CD, which would help users (particularly cluster admins responsible for maintaining it) understand Kargo.

**Comment by tal-hason** [comment]
Here is my Argo App with values.yaml detached from the Chart using sources

```YAML
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: openshift-gitops
spec:
  destination:
    namespace: kargo
    server: 'https://kubernetes.default.svc'
  project: kargo
  sources:
    - chart: kargo
      helm:
        valueFiles:
          - $values/kargo-values.yaml
      repoURL: ghcr.io/akuity/kargo-charts
      targetRevision: 0.1.0
    - ref: values
      repoURL: 'https://github.com/tal-hason/kargo.git'
      targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
