### ISSUE TITLE
Running Kargo on top Openshift 4.13 - getting can't set finalizers on

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#811]
Hi,

trying to run Kargo On top of Openshift 4.13 all is running well with the helm chart and installation.

when trying to create the promotion stage I get:
  error: "error creating Promotion of Stage \"test\" in namespace \"kargo-demo\"
    to Freight \"14c12986571908126c554297243b177858c5a87b\":
    promotions.kargo.akuity.io \"test.01hat93ddrhf231x4qe6xyh9ng.14c1298\" is
    forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a
    resource you can't set finalizers on: , <nil>"

![image](https://github.com/akuity/kargo/assets/97454240/6548ee2d-e300-495c-8b16-f2257d6ca845)

I have all the configs and manifest that I used to deploy in this repo:
https://github.com/tal-hason/kargo.git

**Comment by tal-hason** [comment]
i found out that i didnt use the kargo cli,once i used it i got the 3 steps pipeline,
but when i run the following command:
kargo stage promote kargo-demo test --freight $FREIGHT_ID

i get the same error:
`Error: promote stage: internal: promotions.kargo.akuity.io "test.01havnvrcghara87ksp3m85hvh.b73f9d1" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>`

**Comment by tal-hason** [comment]
After more inverstigation, when creating a promotions from a yaml file i.e:

`
apiVersion: kargo.akuity.io/v1alpha1
kind: Promotion
metadata:
  name: test-1234
  namespace: kargo-demo
spec:
  stage: test
  freight: b73f9d1afaca87254b64e64e5439557e86dcba79
`
it starting to promote

looks like the CLI command can't create the promotion CRD and failed

**Comment by krancour** [comment]
I haven't used OpenShift, but as far as I can tell from a quick search, OpenShift (by default?) enables a variety of options and admission controllers that either don't exist in plain k8s or aren't typically enabled in k8s.

In the case of the Kargo CLI, it's the Kargo API server that doesn't have sufficient permission to do this and I can and will look at whether it's reasonable for us to expand its permission slightly to cover this case.

If you're using `kubectl` (seems like this is where you started -- which is fine, btw), it's _you_ that doesn't have sufficient permissions to do this. I can look at the small handful of pre-defined Roles and ClusterRoles we ship with (are you using those?) and see if they require similar adjustments to their permissions, but ultimately, you being bound to Roles or ClusterRoles that allow you to do this is beyond our control.

**Comment by tal-hason** [comment]
Hi @krancour ,

Thanks for the answer.

I have gave cluster-admin to the controller sa and to the api sa, with no success.

When applying the promotion yaml all work fine.

**Comment by krancour** [comment]
> When applying the promotion yaml all work fine.

Oh. That is interesting...

I thought it should be failing either way...

👀

**Comment by krancour** [comment]
Found the secondary issue... owner references are set programmatically, but not in a webhook where they probably should be. This means the owner references aren't set when you create your promos using `kubectl`.

I'm opening a separate issue for _this_.

Will still explore the permissions issue here, which is the primary issue.

**Comment by krancour** [comment]
Opened #815

**Comment by krancour** [comment]
@tal-hason does your original issue resolve if you edit the `kargo-api` `ClusterRole` to allow update and/or patch on the `stages/finalizers` subresource?

**Comment by tal-hason** [comment]
From what I remember nothing help, I will be later in front of my PC and will send you my CRB and RC for kargo sa's

**Comment by tal-hason** [comment]
```YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promoters
  namespace: kargo-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-promoter-finilazier
subjects:
- kind: Group
  name: system:masters
```

```YAML
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-promoter-finilazier
rules:
  - verbs:
      - "*"
    apiGroups:
      - kargo.akuity.io
    resources:
      - "*"
```

```YAML
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-controller-demo-c-admin
subjects:
  - kind: ServiceAccount
    name: kargo-controller
    namespace: kargo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```

```YAML
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-api
subjects:
  - kind: ServiceAccount
    name: kargo-api
    namespace: kargo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kargo-api
```

```YAML
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kargo-api
rules:
  - verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
      - delete
    apiGroups:
      - ''
    resources:
      - namespaces
  - verbs:
      - '*'
    apiGroups:
      - kargo.akuity.io
    resources:
      - promotionpolicies
      - stages
  - verbs:
      - create
      - get
      - list
      - watch
    apiGroups:
      - kargo.akuity.io
    resources:
      - promotions
```

**Comment by tal-hason** [comment]
OK, Just added Cluster-admin role cluster wide to the kargo-api, and it looks like it's promoting from the UI.

and the kargo CLI also working without any issue

**Comment by tal-hason** [comment]
small script that makes promotion easier

./promote.sh kargo-demo prod

>promote.sh

```Bash
#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 PROJECT STAGE"
    exit 1
fi

PROJECT="$1"
STAGE="$2"

export NEW_FREIGHT=$(kargo get stages -p "$PROJECT" "$STAGE" -o yaml | yq eval '.status.availableFreight[0].id')

kargo stage promote "$PROJECT" "$STAGE" --freight ${NEW_FREIGHT}
```

**Comment by krancour** [comment]
> OK, Just added Cluster-admin role cluster wide to the kargo-api, and it looks like it's promoting from the UI.

This seems heavy-handed and could be dangerous. The API server is directly user-facing (and sometimes open to ingress from 0.0.0.0/0 for some) which makes it inherently more vulnerable to attack than, say, the controller.

If your API server is compromised, it can do _anything_ in your cluster.

I'm really curious whether update and patch on the stages/finalizers subresource may be enough.

I don't have OpenShift currently available to me to test.

**Comment by tal-hason** [comment]
It's an isolated instance and not something that can be exposed to the www. So for testing wise it ok.

About testing with openshift, you can send me the CRB and I will test and report.

Or you can download Openshift Local from cloud.redhat.com, it free :-)

**Comment by tal-hason** [comment]
@krancour , i edited the kargo-api role to:

```YAML
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kargo-api
  labels:
    {{- include "kargo.labels" . | nindent 4 }}
    {{- include "kargo.api.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - namespaces
      - finalizers
    verbs:
      - create
      - get
      - list
      - watch
      - patch
      - update
      - delete
  - apiGroups:
      - kargo.akuity.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - kargo.akuity.io
    resources:
      - promotions
      - promotion
    verbs:
      - '*'
```

and it also solved the issue

check it in my repo: https://github.com/tal-hason/kargo
the helm chart is under: kargo-0.1.0/kargo
