### ISSUE TITLE
Add GenerateName Support to Promotion

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#813]
When working with promotion yaml's

a new name is needed for every promote, please add support of generateName: so the same manifest can be used without being needed to change it name.

**Comment by morey-tech** [comment]
@tal-hason, thanks for the suggestion! The first challenge I see with this is how you could use the same manifest if either the `spec.stage` or `spec.freight` would also need to change to trigger a new promotion. Creating a new `Promotion` with a new name but the same `stage` and `freight` won't result in a promotion. If these values are changing, why not change the name in the same fashion?
```
apiVersion: kargo.akuity.io/v1alpha1
kind: Promotion
metadata:
  name: prod-to-${FREIGHT_ID}
  namespace: kargo-demo
spec:
  stage: prod
  freight: ${FREIGHT_ID}
```
