### ISSUE TITLE
Stage Git subscriptions should support specifying paths

### ISSUE THREAD

**Issue by morey-tech** [akuity/kargo#814]
Currently, a `Stage` subscribed to a Git repo will generate a new freight for any change to the subscribed branch. It's common for GitOps repos to have configurations for many applications, resulting in many unnecessary freights that contain no changes relevant to the application the `Stage` is for.

For example:
```yaml
  subscriptions:
    repos:
      git:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          branch: main
```
- The `morey-tech/kargo-demo` contains the Kustomization for the demo app, along with `Application` files for Argo CD. Each time an `Application` is updated, the `Stage` generates a new freight despite no change to the artifacts that affect that `Stage`.

I'd propose the addition of `subscriptions.repos.git[x].paths`, which limits the creation of a freight to if a file changes in that folder. For example:
```yaml
  subscriptions:
    repos:
      git:
        - repoURL: https://github.com/morey-tech/kargo-demo/
          branch: main
          paths: base/,stages/test
```
This should also support globbing.
