### ISSUE TITLE
RegEx not working for `allowTags`

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#820]
Using `allowTags` for images doesn't seem to provide a freight

```yaml
spec:
  subscriptions:
    repos:
      images:
      - repoURL: quay.io/christianh814/kargo-demo-app
        updateStrategy: Latest
        allowTags: '^[0-9a-f]{6}$'
```

This gives the following error...

```
error syncing image repo subscriptions: error getting latest suitable
      tag for image "quay.io/christianh814/kargo-demo-app": found no suitable version
      of image "quay.io/christianh814/kargo-demo-app"
```

Moving it to `ignoreTags` returns the right tags

```yaml
spec:
  subscriptions:
    repos:
      images:
      - repoURL: quay.io/christianh814/kargo-demo-app
        updateStrategy: Latest
        #allowTags: '^[0-9a-f]{6}$'
        ignoreTags:
          - latest
```

This might be an Image Updater issue
