### ISSUE TITLE
Stage with helm chart from a Git repo

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#867]
I want to create a stage, that in the "promotionMechanisms" I have a helm chart from a git repo.

and the path to the values file in the git repo
and the name of the values to update (i.e image.name & image.tag)

is there a sample stage yaml that I can look?!

**Comment by tal-hason** [comment]
Found it!!

  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/<username>/kargo-demo-gitops.git
      writeBranch: stage/test # Writing to stage-specific branch prevents the formation of a loop
      helm:
        images:
        - image: nginx
          valuesFilePath: charts/kargo-demo/stages/test/values.yaml
          key: image.name # Update this key to reference the new image version
          value: Image
    argoCDAppUpdates:
    - appName: kargo-demo-test

**Comment by tal-hason** [comment]
I have created this monster stage:

```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: develop
  namespace: gotham-kargo
  annotations:
    kargo.akuity.io/color: blue
spec:
  subscriptions:
    repos:
      images:
      - repoURL: quay.io/gotham/batman
        updateStrategy: Latest
      - repoURL: quay.io/gotham/joker
        updateStrategy: Latest
      - repoURL: quay.io/gotham/robin
        updateStrategy: Latest
      - repoURL: quay.io/gotham/riddler
        updateStrategy: Latest
      - repoURL: quay.io/gotham/gotham
        updateStrategy: Latest
      git:
      - repoURL: https://gitea-http.gitea.svc/gotham/gotham-cd.git
        branch: main # Watch this branch for new commits
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://gitea-http.gitea.svc/gotham/gotham-cd.git
      writeBranch: main # Writing to stage-specific branch prevents the formation of a loop
      helm:
        images:
        - image: quay.io/gotham/batman
          valuesFilePath: Application/gotham/develop/values-batman.yaml
          key: image.tag # Update this key to reference the new image version
          value: Image
        - image: quay.io/gotham/joker
          valuesFilePath: Application/gotham/develop/values-joker.yaml
          key: image.tag # Update this key to reference the new image version
          value: Image
        - image: quay.io/gotham/robin
          valuesFilePath: Application/gotham/develop/values-robin.yaml
          key: image.tag # Update this key to reference the new image version
          value: Image
        - image: quay.io/gotham/riddler
          valuesFilePath: Application/gotham/develop/values-riddler.yaml
          key: image.tag # Update this key to reference the new image version
          value: Image
        - image: quay.io/gotham/gotham
          valuesFilePath: Application/gotham/develop/values-gotham.yaml
          key: image.tag # Update this key to reference the new image version
          value: Image
    argoCDAppUpdates:
    - appName: gotham-batman-develop
      appNamespace: openshift-gitops
    - appName: gotham-joker-develop
      appNamespace: openshift-gitops
    - appName: gotham-robin-develop
      appNamespace: openshift-gitops
    - appName: gotham-riddler-develop
      appNamespace: openshift-gitops
    - appName: gotham-gotham-develop
      appNamespace: openshift-gitops
```

when I deploy it to the cluster I get the following error:


one or more objects failed to apply, reason: Stage.kargo.akuity.io "develop" is invalid: [spec.promotionMechanisms.gitRepoUpdates[0].repoURL: Invalid value: "https://gitea-http.gitea.svc/gotham/gotham-cd": spec.promotionMechanisms.gitRepoUpdates[0].repoURL in body should match '^((https?://)|([\w-]+@))([\w\d\.]+)(:[\d]+)?/(.*)$', spec.subscriptions.repos.git[0].repoURL: Invalid value: "https://gitea-http.gitea.svc/gotham/gotham-cd.git": spec.subscriptions.repos.git[0].repoURL in body should match '^((https?://)|([\w-]+@))([\w\d\.]+)(:[\d]+)?/(.*)$'].

**Comment by tal-hason** [comment]
@krancour any idea why it not accepting my private git repo?

when updated it with GitHub repo it worked fine

**Comment by krancour** [comment]
Looks like a regex that needs to be relaxed. I'll open a separate issue when I get to my desk.

btw... I notice you're trying to write changes to the same branch you're subscribed to. That can cause problems and because of that, it will be detected at promotion time and will fail.

**Comment by tal-hason** [comment]
So to skip the subscription for the git repo

**Comment by krancour** [comment]
> So to skip the subscription for the git repo

Not sure if that was a question...

You don't _need_ a subscription to your git repo unless you want Kargo to play a role in moving changes that you make to that repo through your stages.

If you skip that subscription, the payload of each piece of freight is just a list of images, and stage by stage, those images would be updated in the stage-specific values file in main branch of the repo.

If your Apps subscribe to the main branch of that repo, you're all good.

The thing you don't get in that scenario is if you make a change to your base values.yaml file or chart template or something, all your Apps will see it right away due to Kargo not being involved in progressing the change.

**Comment by krancour** [comment]
btw... love the image names.

**Comment by krancour** [comment]
Created #870 

@tal-hason is there anything else to be addressed in this issue?

**Comment by tal-hason** [comment]
Having an issue with the push to the repo, I created a repo secret in argoCD with the annotation but it looks like it not catching it,I will try to create a dedicated secret in the project repo and will report

**Comment by tal-hason** [comment]
Also add support for http / insecure git repo?!

**Comment by krancour** [comment]
>  I created a repo secret in argoCD with the annotation but it looks like it not catching it,I will try to create a dedicated secret in the project repo and will report

iirc, "borrowing" secrets from Argo CD is opt-in configuration.

> Also add support for http / insecure git repo?!

Will open a separate issue for that.

**Comment by krancour** [comment]
Opened #872

**Comment by tal-hason** [comment]
> > I created a repo secret in argoCD with the annotation but it looks like it not catching it,I will try to create a dedicated secret in the project repo and will report
> 
> iirc, "borrowing" secrets from Argo CD is opt-in configuration.
> 
> > Also add support for http / insecure git repo?!
> 
> Will open a separate issue for that.

after adding a git secret in the project name, it started working, but it is interesting why it didn't pickup the repo from argo

**Comment by krancour** [comment]
> but it is interesting why it didn't pickup the repo from argo

Was "credential borrowing" enabled?

**Comment by tal-hason** [comment]
> > but it is interesting why it didn't pickup the repo from argo
> 
> Was "credential borrowing" enabled?

you mean the annotation in the argo repo secret?!

```YAML
kind: Secret
apiVersion: v1
metadata:
  name: repo-1071875666
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    kargo.akuity.io/authorized-projects: gotham-demo
    managed-by: argocd.argoproj.io
```

like this?!

in the demo secret, it worked without any issues

**Comment by krancour** [comment]
It also needs to be enabled globally when you install the chart. It's a security consideration. Many people won't want this behavior enabled.

**Comment by tal-hason** [comment]
From my values.yaml

```YAML
  ## All settings relating to the Argo CD control plane this controller will
  ## integrate with.
  argocd:
    ## @param controller.argocd.namespace The namespace into which Argo CD is installed.
    namespace: openshift-gitops
    ## @param controller.argocd.watchArgocdNamespaceOnly Specifies whether the reconciler that watches Argo CD Applications for the sake of forcing related Stages to reconcile should only watch Argo CD Application resources residing in Argo CD's own namespace. Note: Older versions of Argo CD only supported Argo CD Application resources in Argo CD's own namespace, but newer versions support Argo CD Application resources in any namespace. This should usually be left as `false`.
    watchArgocdNamespaceOnly: false
    ## @param controller.argocd.enableCredentialBorrowing Specifies whether Kargo may borrow repository credentials (specially formatted and specially annotated Secrets) from Argo CD.
    enableCredentialBorrowing: true
```

it's enabled
