### ISSUE TITLE
working with private image registry

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#868]
i have a private image registry.

when creating a stage with a subscription to a private repo, I get:

  error: 'error syncing image repo subscriptions: error getting latest suitable
    tag for image "quay.io/gotham/batman": error fetching tags for image
    "quay.io/gotham/batman": unauthorized: access to the requested resource is
    not authorized'

I have created a type: kubernetes.io/dockerconfigjson secret and added it to both API and controller SA, but the error presist

I am using the same secret to push images to the repo without any issues.

any solutions?

**Comment by krancour** [comment]
Hey @tal-hason. I know our docs are sparse still, but fortunately this is one topic that's well addressed:

https://kargo.akuity.io/how-to-guides/managing-credentials

Short answer is you need to provide a specially formatted secret... it doesn't resemble an image pull secret. Rather, it looks more like the secrets Argo CD and Kargo both use for private git and chart repos.

**Comment by tal-hason** [comment]
Hi @krancour ,thanks

i will test and update

**Comment by tal-hason** [comment]
@krancour created the following secret, but still getting the :
error syncing image repo subscriptions: error getting latest suitable
    tag for image "quay.io/gotham/batman": error fetching tags for image
    "quay.io/gotham/batman": unauthorized: access to the requested resource is
    not authorized'


```YAML
kind: Secret
apiVersion: v1
metadata:
  name: elfred-quay-kargo
  namespace: kargo
  labels:
    kargo.akuity.io/secret-type: repo-creds
data:
  password: {My-Token}
  type: image
  url: quay.io
  username: {Robot-User}
type: Opaque
```

**Comment by krancour** [comment]
Wrong namespace... try the project namespace.

**Comment by tal-hason** [comment]
```YAML
kind: Secret
apiVersion: v1
metadata:
  name: elfred-quay-kargo
  namespace: gotham-kargo
```

added it to the project NS

without any different results
