### ISSUE TITLE
Kargo doesn't instruct Argo CD to create namespace when option is set on the Application

### ISSUE THREAD

**Issue by christianh814** [akuity/kargo#874]
I have a `Stage` that has auto promotion enabled in it's `PromotionPolicy`. So when I first deploy the Stage it tries to sync the Argo CD Application

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: dev-app
  project: default
  source:
    path: app
    repoURL: https://github.com/christianh814/kargo-demo-deploy
    targetRevision: env/dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```

However it FAILS

![image](https://github.com/akuity/kargo/assets/10502863/e685e147-c69d-4f6a-aadf-930f7f112215)

The error from Argo CD is "namespace not found"

![image](https://github.com/akuity/kargo/assets/10502863/0a6f4a88-cf13-40ee-b7ee-2042aef381af)

When I use this app with "Vanilla" Argo CD, it works as expected.
