### ISSUE TITLE
When Kargo Updates Helm Values ,is not seting quote on the tag value

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#876]
when Kargo updates helm chart values (i.e image.tag)

it does not set quotes on the values, if as part of the build the tag is fully composed out of numbers helm thinks that it is an integer and it breaks the deployment 

> Error: values don't meet the specifications of the schema(s) in the following chart(s): app: - image.tag: Invalid type. Expected: > string, given: integer

after Kargo updated the git
```YAML
image:
  ## Name of the image you want to build/deploy
  ## Defaults to the release name
  name: quay.io/gotham/batman
  ## Tag that you want to build/deploy
  tag: 3108617
```

How it should set it
```YAML
image:
  ## Name of the image you want to build/deploy
  ## Defaults to the release name
  name: quay.io/gotham/batman
  ## Tag that you want to build/deploy
  tag: '3108617'
```
