### ISSUE TITLE
add a match/placeholder support for helm values file

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#879]
```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: branch-deploy
  namespace: gotham-kargo
  annotations:
    kargo.akuity.io/color: purple
spec:
  subscriptions:
    repos:
      images:
      - repoURL: quay.io/gotham/batman
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/gotham-demo/gotham-cd.git 
      writeBranch: main 
      helm:
        images:
        - image: quay.io/gotham/batman
          valuesFilePath: Application/gotham-demo/develop/branch/values-*.yaml
          key: image.tag
          value: 'Tag'
```

when allowing to use wild card the controller will get the image name last value (i.e. quay.io/gotham/batman , so it will be batman)

and will try to update the values-batman.yaml file with the new image tag.

**Comment by krancour** [comment]
May need more details here...

Wildcards are generally for _selecting multiple somethings_. Example: ls *.txt

In your example, * seems to be more of a _placeholder  for one specific something_. 

If you _know_ * is holding the place of the word "batman," why not just use the word "batman" in the file path?

**Comment by tal-hason** [comment]
@krancour Just like with applicationSets in Argo, let's say that I will drop a value file in a folder after a new branch has been created in the source repo.

now the controller knows that there is a new file check if it listens to the pattern and creates a freight.

but after having a good night's sleep, there is an issue with the Argo application that needs to be set beforehand 🤦

just trying to apply a current process that I have that I am creating an argo application for each source repo branch.

and hoping that I can leverage Kargo For it, but the machinisem isn't there yet

**Comment by tal-hason** [comment]
Even further after giving it some more thought, the stage holds a lot of connections and several types of data.

but the same as with the ArgoCD application, although the argo app is a bit simpler.

I think of a Stage Generator. (substage generator 🤔)

that can be given a pattern such as a git file/folder/image repo and from it to generate stages or maybe to introduce substages

to have a more granular control of the promotion of specific images in a stage.

**Comment by krancour** [comment]
Ya... I expect there will eventually be a way of defining an entire pipeline more succinctly than you do today by applying a common pattern to a list of stage names.

We'll get there. For now, we're still trying to nail down the fundamentals. Applications were around a long time before ApplicationSets arrived.

I think this is a different thing from what's described in the initial post... probably deserving of its own issue. 😉

**Comment by tal-hason** [comment]
Maybe adding in the stage argo section applicationset option and then it can populate all the argo application that the applicationSet generated...

Me just thinking outloud

**Comment by tal-hason** [comment]
> Ya... I expect there will eventually be a way of defining an entire pipeline more succinctly than you do today by applying a common pattern to a list of stage names.
> 
> We'll get there. For now, we're still trying to nail down the fundamentals. Applications were around a long time before ApplicationSets arrived.
> 
> I think this is a different thing from what's described in the initial post... probably deserving of its own issue. 😉

To generate multiple stages from a single yaml will be complected and will require some inhumane pattern understanding, but if stage will be dynamic and will be consuming patterns from git, images and applicationsets , it can be more dynamic

**Comment by krancour** [comment]
> To generate multiple stages from a single yaml will be complicated and will require some inhumane pattern understanding, but if stage will be dynamic and will be consuming patterns from git, images, and applicationsets , it can be more dynamic.

I think we're saying the same thing in different words. Often the only differences between two stages in the same pipeline are branches, paths, and App names -- all of which could often be inferred from a pattern + stage name, but I don't want to get too far off topic. However we _eventually_ deal with creating multiple related stages (with something like a hypothetical "StageSet"), I think that's different from the original topic of this thread, which involves _patterns within a single Stage_.

I lifted this other example of yours from #884:

```
gitRepoUpdates:
- repoURL: https://github.com/gotham-demo/gotham-cd.git 
  writeBranch: main
  helm:
    images:
    - image: # This is not necessary anymore cause the controller will follow a pattern from the subscription
      valuesFilePath: Application/gotham-demo/develop/values-{{subscription.image.name}}.yaml #a wild card pattern that will be populated from the subscription
      key: image.tag # Update this key to reference the new image version
      value: 'Tag'
```

What's different here from your original example in this thread is that you're not specifying an image and that seems to indicate that you want to _iterate over all the images in the freight_. The `{{subscription.image.name}}` placeholder is also far less ambiguous than the splat was.

I get it now. 👍 

I still think there are a lot of details to unpack and carefully consider here. In no particular order (numbers only for reference):

1. Making `image` an optional field and inferring, when it is undefined, that the user's intent is to iterate over all images seems like it will lead to surprising results for users who _accidentally_ left that field blank. I think that could be addressed by adding an `imagePattern` field and making it mutually exclusive with `image`. The new field would support regex and capture groups.

1. The interpretation of `{{subscription.image.name}}` seems arbitrarily tailored to your use case. You've proposed splitting on `/` and substituting the last token for `{{subscription.image.name}}`. What if my images are named like `krancour/demo-batman`, `krancour/demo-robin`, etc. and I want to incorporate `batman` and `robin` into my paths instead of `demo-batman` and `demo-robin`? What if the `krancour` part of the image name were somehow meaningful and I wanted to incorporate _that_? The regex/capture group idea above would address this issue as well. "Iterate over the images that match this regex and assign the capture groups to `$1`, `$2`, etc."

1. Although I can infer what you _mean_ by `{{subscription.image.name}}`, I'm not sure how universally understood this syntax would be. It _looks_ like it's a JSON path, but that path doesn't actually reflect the structure of either the Stage or the Freight. Again, the regex/capture group idea could take care of this. I think `{{$1}}`, `{{$2}}`, etc. would be obvious references to the regex/capture groups right there in the same block of configuration.

1. Unconditionally iterating over _all_ the images in the freight would require that the `key` is valid for _all_ the values files in question. Outside of a demo, is that expectation of uniformity in your charts realistic? Again, the regex/capture group could take care of this because you could be more selective about what you iterate over.

So, I think something that looks like this would address most of my concerns:

```
gitRepoUpdates:
- repoURL: https://github.com/gotham-demo/gotham-cd.git 
  writeBranch: main
  helm:
    images:
    - imageTemplate: marvel/(\w+)
      valuesFilePath: comic-demo/dev/values-{{$1}}.yaml
      key: image.tag
      value: 'Tag'
    - imageTemplate: dc/(\w+)
      valuesFilePath: comic-demo/dev/values-{{$1}}.yaml
      key: image
      value: 'Image'
```

I'll add that the usefulness of this is probably not limited to Helm. It could work for Kustomize also.

I'm curious to know how this resonates with you.

**Comment by tal-hason** [comment]
that sounds AWESOME, I just had a vague idea to make stages a bit more agile.

when I think about big systems with 10-20 deployments/applications the stage starts to become long and repetitive with small changes

i.e:
```YAML
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/gotham-demo/gotham-cd.git #https://gitea-http.gitea.svc/gotham/gotham-cd.git
      writeBranch: main # Writing to stage-specific branch prevents the formation of a loop
      helm:
        images:
        - image: quay.io/gotham/batman
          valuesFilePath: Application/gotham-demo/develop/values-batman.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
        - image: quay.io/gotham/joker
          valuesFilePath: Application/gotham-demo/develop/values-joker.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
        - image: quay.io/gotham/robin
          valuesFilePath: Application/gotham-demo/develop/values-robin.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
        - image: quay.io/gotham/riddler
          valuesFilePath: Application/gotham-demo/develop/values-riddler.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
        - image: quay.io/gotham/gotham
          valuesFilePath: Application/gotham-demo/develop/values-gotham.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
    argoCDAppUpdates:
    - appName: gotham-batman-gh-develop
      appNamespace: openshift-gitops
    - appName: gotham-joker-gh-develop
      appNamespace: openshift-gitops
    - appName: gotham-robin-gh-develop
      appNamespace: openshift-gitops
    - appName: gotham-riddler-gh-develop
      appNamespace: openshift-gitops
    - appName: gotham-gotham-gh-develop
      appNamespace: openshift-gitops
```

and this has only 5 applications, a service-based application can have many more moving parts.

so I think that your understanding is on point and of course it is just us talking and fantasizing about it until it is met with reality and then we will need to drill much deeper. but I like your interpretation.
