### ISSUE TITLE
add promo mech that can update or sync multiple apps managed by a single appset

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#884]
when configuring stage we have 3 type of connection points , subscription, promotionMechanisms and argoCDAppUpdates.

```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: develop
  namespace: gotham-kargo
  annotations:
    kargo.akuity.io/color: blue
spec:
  subscriptions:
    repos:
      images:
      - repoURL: quay.io/gotham/batman
        updateStrategy: Latest
      - repoURL: quay.io/gotham/joker
        updateStrategy: Latest
      - repoURL: quay.io/gotham/robin
        updateStrategy: Latest
      - repoURL: quay.io/gotham/riddler
        updateStrategy: Latest
      - repoURL: quay.io/gotham/gotham
        updateStrategy: Latest
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/gotham-demo/gotham-cd.git #https://gitea-http.gitea.svc/gotham/gotham-cd.git
      writeBranch: main # Writing to stage-specific branch prevents the formation of a loop
      helm:
        images:
        - image: quay.io/gotham/batman
          valuesFilePath: Application/gotham-demo/develop/values-batman.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
        - image: quay.io/gotham/joker
          valuesFilePath: Application/gotham-demo/develop/values-joker.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
        - image: quay.io/gotham/robin
          valuesFilePath: Application/gotham-demo/develop/values-robin.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
        - image: quay.io/gotham/riddler
          valuesFilePath: Application/gotham-demo/develop/values-riddler.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
        - image: quay.io/gotham/gotham
          valuesFilePath: Application/gotham-demo/develop/values-gotham.yaml
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
    argoCDAppUpdates:
    - appName: gotham-batman-gh-develop
      appNamespace: openshift-gitops
    - appName: gotham-joker-gh-develop
      appNamespace: openshift-gitops
    - appName: gotham-robin-gh-develop
      appNamespace: openshift-gitops
    - appName: gotham-riddler-gh-develop
      appNamespace: openshift-gitops
    - appName: gotham-gotham-gh-develop
      appNamespace: openshift-gitops
```

as we can see there is a pattern here cause this set of applications is managed and deployed with an argo applicationSet
so if we know that this specific stage is deployed in a pattern.

```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: develop
  namespace: gotham-kargo
  annotations:
    kargo.akuity.io/color: blue
spec:
  subscriptionSet:
    repos:
      images:
      - repoURL: quay.io/gotham/* # will query all the images in the registry and will populate a list of image names that will be later used to fill promotionMechanisms
        updateStrategy: Latest
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/gotham-demo/gotham-cd.git 
      writeBranch: main
      helm:
        images:
        - image: # This is not necessary anymore cause the controller will follow a pattern from the subscription
          valuesFilePath: Application/gotham-demo/develop/values-{{subscription.image.name}}.yaml #a wild card pattern that will be populated from the subscription
          key: image.tag # Update this key to reference the new image version
          value: 'Tag'
    argoCDAppUpdates:
    - appSetName: gotham-applicationSet #the name of the argo applicationSet
      appNamespace: openshift-gitops

```

Idea that generated in #879

**Comment by krancour** [comment]
```
promotionMechanisms:
  gitRepoUpdates:
  - repoURL: https://github.com/gotham-demo/gotham-cd.git 
    writeBranch: main
    helm:
      images:
      - image: # This is not necessary anymore cause the controller will follow a pattern from the subscription
        valuesFilePath: Application/gotham-demo/develop/values-{{subscription.image.name}}.yaml #a wild card pattern that will be populated from the subscription
        key: image.tag # Update this key to reference the new image version
        value: 'Tag'
  argoCDAppUpdates:
  - appSetName: gotham-applicationSet #the name of the argo applicationSet
    appNamespace: openshift-gitops
```

There are two separate things going on in this example that aren't intrinsically related to one another:

1. Update multiple values files
1. Force sync of multiple Applications by specifying an ApplicationSet.

The reason I say these are separate issues is that it's easy to imagine a scenario where a _single_ Application deploys _all_ your new images. In that case, you need the pattern part, but not the ApplicationSet part.

The opposite it also true. It's easy to imagine a scenario where you update only _one_ values file, but you need to sync multiple Applications. In that case, you need the ApplicationSet part, but not the pattern part.

So I want to focus this issue on a single topic. I think #879, which was initially framed as "wildcard" support is driving in the direction of the _pattern_ support you're talking about here, so let's handle pattern stuff in that thread and keep this thread focused on just the ApplicationSet support part.
