### ISSUE TITLE
PromotionPolicy list/array support

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#894]
# Summary

the current promotion policy only supports a single stage, i.e.:

```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: promote-gothem-image
stage: gothem-image
enableAutoPromotion: true
```

if have several stages that needs auto promoting I need to create multiple files, instead, use _stages:_  and get a list of stages, i.e.:

```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: auto-promotion-for-stages
stages:
  - gothem-image
  - batman-image
  - robin-image
  - riddler-image
  - gotham-image
enableAutoPromotion: true
```

# Motivation

less YAML?!

# Proposal

How do you think this should be implemented?

```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: auto-promotion-for-stages
stages:
  - gothem-image
  - batman-image
  - robin-image
  - riddler-image
  - gotham-image
enableAutoPromotion: true
```
