### ISSUE TITLE
PromotionPolicy Not works in stage frieght is N\A

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#895]
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://kargo.akuity.io/.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.

**Describe the bug**

when having a stage with freight ID, N\A and this stage have promtionPolicy set to auto, the stage isn't promoting, only after manually promoting the stage to freight ID once, then it start to roll promotion automatically 

**To Reproduce**

create a stage with image subscription, check that the fright ID is N\A
wait for a freight ID will be created, but not promote
create a PromtionPolicy with auto set to true.

the freight will not be promoted.

**Expected behavior**

when a stage have a promotion policy each available new freight should be promoted even if the current freight is N\A

**Screenshots**

**Version**

```shell
 kargo version
I0929 23:22:30.382607  415537 request.go:601] Waited for 1.04297698s due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/operators.coreos.com/v1?timeout=32s
Client Version: v0.1.0
Server Version: v0.1.0
```

**Logs**

```
Paste any relevant application logs here.
```

**Comment by krancour** [comment]
Can you enabled debugging on the controller and try to get some logs?

**Comment by tal-hason** [comment]
yes , i will delete everything and try it again 🫣

**Comment by tal-hason** [comment]
Okay, that's weird, I deleted all the stages and promotion and promotion policy from the namespace.

when I reapplied them, it returned to the last state with 2 freights in the list, not with only one.

I think I need to delete the namespace to

**Comment by tal-hason** [comment]
this is the state:
![image](https://github.com/akuity/kargo/assets/97454240/c2d8d20e-4084-42ef-a7e6-9573f0515ab4)

this is the stage:
```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: get-a-new-freight
  namespace: gotham-kargo
  annotations:
    kargo.akuity.io/color: green
spec:
  subscriptions:
    repos:
      images:
      - repoURL: quay.io/gotham/batman
        updateStrategy: Latest
      - repoURL: quay.io/gotham/robin
        updateStrategy: Latest
      - repoURL: quay.io/gotham/joker
        updateStrategy: Latest
      - repoURL: quay.io/gotham/riddler
        updateStrategy: Latest
      - repoURL: quay.io/gotham/gotham
        updateStrategy: Latest
```

the promotionPolicy:
```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: get-a-new-freight
  namespace: gotham-kargo
stage: get-a-new-freight
enableAutoPromotion: true
```

logs from the controller:
[kargo-controller-6f8c88f657-r2xmv-controller.log](https://github.com/akuity/kargo/files/12774342/kargo-controller-6f8c88f657-r2xmv-controller.log)

it looks like it is processing it but sees it as not new
