### ISSUE TITLE
subscriptions and stages need to seperated in to two kinds

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#896]
# Summary

when creating a stage a subscription is part of it, but in fact, a subscription is a different identity that needs to be its own kind.

![image](https://github.com/akuity/kargo/assets/97454240/1eba12ee-b9a8-4f3e-9fca-f67e42fb0f31)

so the stage can register to a subscription, making the flow much more visible and manageable.

# Motivation

make the source of the repo/chart/image a subscription that stages can then be registered to, and then stages can also register to other upstream stages.

# Proposal

freight then should be a stage registered to a subscription, a stage without a subscription, will be able only to consume freights, not generate them, this will assist with more agility in designing the pipeline into different scenarios.

stage should look like:

```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  upstreamStages:
    - name: <<name of the stage>>
  registerTo:
    subscriptions:
      - name: <<name of the subscription>>
  promotionMechanisms:
    argoCDAppUpdates:
    - appName: kargo-demo-test
      sourceUpdates:
      - repoURL: https://github.com/<username>/kargo-demo-gitops.git
        helm:
          images:
          - image: nginx
            key: image.name
            value: Image # Update Application to reference the new image version
```

Subscription should look like this:

```YAML
apiVersion: kargo.akuity.io/v1alpha1
kind:  Subscriptions
metadata:
  name:   subscriptions
  namespace: kargo-demo
spec:
  repos:  #atleast one type of repo is required for a subscription
      images: 
      - repoURL: nginx
        semverConstraint: ^1.24.0
      charts:
      - registryURL: https://charts.bitnami.com/bitnami
        name: nginx 
        semverConstraint: ^14.1.0
      git:
      - repoURL: https://github.com/<username>/kargo-demo-gitops.git
        branch: helm # Watch this branch for new commits
```
