### ISSUE TITLE
Running Multiple instances of kargo on the same server aka. multitenancy 

### ISSUE THREAD

**Issue by tal-hason** [akuity/kargo#897]
# Summary

sometimes a cluster is shared between several development teams and multiple instances of Kargo will be necessary, 
the current state is that if I have multiple instances they all see all the projects in the cluster

# Motivation

to enable multitenancy  and limit noisy neighbors of a shared instance 

# Proposal

the straightforward is to add another label to the namespace:

```YAML
apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
  labels:
    kargo.akuity.io/project: "true"
    kargo.akuity.io/managed-by: kargo #the namespace where the controlling kargo instance is running
```

also if the way is helm chart deployment a suffix needs to be added to all the named resources to support multi-instance installation

it will also will pave the way if a operator is somewhere in the future.
