### ISSUE TITLE
Stage does not validate whether correct image was deployed

### ISSUE THREAD

**Issue by moensch** [akuity/kargo#935]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate bug report.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `kargo version`.
* [x] I've pasted logs, if applicable.

# Description

The Stage reports as "Healthy" when the Argo CD application in `argoCDAppUpdates` is healthy, even if it didn't actually do anyhing.

I was torn between bug/feature on this one. I intentionally misconfigured my argocd `Application` to see how Kargo would behave.

# Screenshots

# Steps to Reproduce

I have the following promotion mechanism configured:
```yaml
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: https://github.com/mycompany/myapp.git
      readBranch: initial
      writeBranch: stage/dev
      helm:
        images:
        - image: myimage
          valuesFilePath: chart/values-dev.yaml
          key: image.tag
          value: Tag
```

But I configured this here in my `Application.spec.source`:
```yaml
  source:
    helm:
      parameters:
      - name: fullnameOverride
        value: podinfo
    path: chart/
    repoURL: https://github.com/mycompany/myapp.git
    targetRevision: stage/dev
```

Notice how I am **not** referencing `values-dev.yaml` in my `Application`.

When promoting in Kargo, it does exactly as told. It takes the contents of my `initial` branch, overrides `image.tag` in `values-dev.yaml`, and pushes it to the `stage/dev` branch.
It then triggers an Argo CD sync, the sync comes back healthy, but nothing was actually deployed because the Argo CD application isn't even looking at this values file.

Kargo then reports back a "Healthy" status for that stage, but the image in question was never deployed.

# Version

Dirty build off `6168ac58662e6eb253bf2b9fe601c4392701c7d1` (HEAD of main as of time of this issue).

# Logs

Nothing noteworthy in the logs - Kargo did exactly as expected.

# Ideas

In theory, Kargo **could** query `.status.summary.images` of the `Application` resource, but that might further entrench it with Argo CD?
Is validating the correct image is deploy even Kargo's job? Or is its job done when it pushed to git?

In this test scenario, I was just thinking about a user that might have a given stage misconfigured. And in a potential future where users are spending more time in the Kargo UI than in the Argo CD UI, they might not catch this error?
