### ISSUE TITLE
Support ArgoCD updates in remote cluster

### ISSUE THREAD

**Issue by akselleirv** [akuity/kargo#964]
# Checklist

* [x] I've searched the issue queue to verify this is not a duplicate feature request.
* [ ] I've pasted the output of `kargo version`, if applicable.
* [ ] I've pasted logs, if applicable.

# Proposed Feature

ArgoCD updates are currently limited to targeting ArgoCD instances running in-cluster. I would like support for doing updates to out of cluster running ArgoCD instances.

I'm running Kargo in my production management cluster and it's able to target the ArgoCD instances running there. However, it is not possible to choose ArgoCD instances running the test management cluster.

For example:

```
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  subscriptions:
    repos:
      images:
      - repoURL: nginx
        semverConstraint: ^1.24.0
  promotionMechanisms:
    gitRepoUpdates:
    - repoURL: ${GITOPS_REPO_URL}
      writeBranch: stage/test
      kustomize:
        images:
        - image: nginx
          path: stages/test
    argoCDAppUpdates:
    - appName: kargo-demo-test
      appNamespace: argocd
      cluster: test-management # <--- Add this entry to target out of cluster update
```

# Motivation

I want to refresh and check health of ArgoCD applications running in a different cluster then Kargo is located.

# Suggested Implementation

Implement it similar to how ArgoCD has done it:

```
apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    kargo.akuity.io/secret-type: cluster
type: Opaque
stringData:
  name: test-management
  server: https://mycluster.com
  config: |
    {
      "bearerToken": "<authentication token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate>"
      }
    }
```
